### ISSUE TITLE
Official Syncthing client

### ISSUE THREAD

**Issue by jkaberg** [canton7/SyncTrayzor#10]
It _seems_ like @calmh might be looking for an official Syncthing wrapper on Windows, perhaps you might fancy applying SyncTrayzor @canton7 ?

Refering to this post: https://discourse.syncthing.net/t/syncthing-windows-installer/2009/3

IMHO SyncTrayzor is a lot more mature than SynchingTray and therfor better fitting then SyncthingTray (no offence to the SyncthingTray author)

**Comment by calmh** [comment]
Spontaneously I like this, I heard of it the first time this evening. :)

**Comment by canton7** [comment]
Heh, to be honest, SyncthingTray inspired me to make SyncTrayzor. I'd been using SyncthingTray for an hour when it decided it wanted to be a fork bomb and spawned a hundred copies of itself (complete with 100 tray icons, to its credit) before I managed to stop it. That's the point at which I decided it was worth doing better...

It's complete coincidence that the first version of SyncTrayzor I deemed ready for general consumption - v1.0.5 - was ready within the same hour that the windows installer project was announced: the posts ended up next to each other on the forums! Such is life.

Thanks for you vote of confidence in SyncTrayzor! From my point of view it's a hobby project: I use it myself on 4 machines, and will respond to bug reports and reasonable community requests. I didn't write it with the intention of having it be made "official" / promoting it / etc. If other people decide that the community would benefit most by such action, then great: you've got my blessing, and I'll do what I can to help. But it isn't my personal mission to make that happen, if that makes sense?

**Comment by canton7** [comment]
FAO anyone browsing issues: https://discourse.syncthing.net/t/windows-autostart-service-or-start-on-login-comments-please/2042

**Comment by Rewt0r** [comment]
i already suggested this after posting the Windows Installer, but I do feel the name needs changing. Possibly to just Syncthing, Syncthing Viewer, STui, Syncthing for Windows etc...

**Comment by canton7** [comment]
I'm not opposed to renaming the project, but I would recomment not calling it just 'Syncthing'. If nothing else, that's a sure-fire way to get me lumbered with Syncthing issues, and Syncthing lumbered with my issues ;)

**Comment by jkaberg** [comment]
Name:
![image](https://cloud.githubusercontent.com/assets/613363/6670069/03e69968-cbfd-11e4-8091-ce34d7621b93.png)


:laughing:

**Comment by canton7** [comment]
Hah! It's a mouthful but at least it's clear!

I'll only go ahead with renaming if the Syncthing devs do want to sort out something "official". Renaming the project's going to be a pain: transferring all users from here to another repo is going to be the trickest part. I'd hate to do then, only to transfer them all to a repo under the 'syncthing' organization a few weeks later!

**Comment by canton7** [comment]
Here's another idea:

If you go to syncthing.net, you get a big promenant button to download Syncthing directly, all good. There are big buttons for the android app, a smaller link for syncthing-gtk, and a tiny link to a list of 'Other Contributions': if you scroll halfway down that wiki page, you read the other GUI clients.

How about taking an approach similar to git-scm.com, and having a list of officially-sanctioned third-party clients? Two buttons for 'Download Syncthing' and 'Download a GUI' have equal prominence. Download a GUI links to a nice list of GUIs, ordered by platform, with screenshots for each.

Syncthing don't need to take responsibility for any of the GUIs, but we make them all a lot more accessible to newbies. It also won't favour SyncTrayzor over, say, syncthing-gtk, and will leave the field open for Syncthing to include an official native UI at some point in the future,

**Comment by jkaberg** [comment]
Good idea @canton7, what do you think @calmh ?

**Comment by princejosuah** [comment]
I second this. Personally, I think it would help democratize Syncthing out
of its "geeky" boundaries and make it accessible to less tech-savvies.
Let's not forget that the UI wrapper played a important role in
widespreading BTSync.

**Comment by Rewt0r** [comment]
I think that's a good idea, could someone possibly do a mock-up / PR?

**Comment by jaredthirsk** [comment]
+1 
I hope the masses on Windows aren't skipping over or missing out on SyncThing because the nice Windows wrapper is buried as a text link half way down an 'Other Contributions' text link.  @canton7's idea sounds good.  Another idea: in addition to the big Android buttons it could be nice to have an equally big buttons to take people to a section where they can download Windows / iOS / Linux / Mac GUI clients.

**Comment by AudriusButkevicius** [comment]
Feel free to make a PR to github.com/syncthing/website giving more attention to your project if you wish, and given others feel that's the right thing.

**Comment by canton7** [comment]
Just to be clear: I'm not trying to favour this project over any other third-rate contribution, just make it clearer to newcomers that such offerings are available. 

I'll try and put together a PR over the next week, unless someone else with a better eye for design beats me to it!

**Comment by fti7** [comment]
i would like to see an "offical" "Syncthing for Windows" Client too
This is much easier to understand for non Tech Users (And for this Users, the GUI/Client represents the Quality of the whole Software!)
SyncthingTrayzor ist one of the best Clients out there! Keep up the good work

**Comment by HyperCriSiS** [comment]
I wonder why this did not already happen. I also like this idea!
This could make Syncthing much more popular.
I was so happy finding this project, it is just awesome. :)

**Comment by canton7** [comment]
We're listed on the homepage now. Is that official enough? 😝

**Comment by calmh** [comment]
There's nothing officialer than that. :)

**Comment by canton7** [comment]
Good enough for me to close this! 

I still think of a name change from time to time, but it gets harder and harder as time goes on.

**Comment by AudriusButkevicius** [comment]
We should also move repos

**Comment by canton7** [comment]
To where, to discuss what?

**Comment by canton7** [comment]
Oh, you mean bring it into the Synching organisation?

**Comment by AudriusButkevicius** [comment]
yeah I guess, for more visibility

**Comment by canton7** [comment]
Sure, if you guys think there would be a strong benefit to doing so. That said, I wonder how many people browse organisations on github.

**Comment by AudriusButkevicius** [comment]
Well I'd think so. @calmh ?
Still, it's under the same umbrella, hence better ;)

**Comment by calmh** [comment]
Honestly I'm unconvinced of the value of that nowadays. Lets discuss offline.
