### ISSUE TITLE
Duplicated and confused info in file transfer progress

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#101]
If pc is put to sleep in the middle of file transfer, after resume Syncthing restarts and in file transfer progress bubble there is ``File: Starting...`` in Downloading and ``Same File: Just now/XY ago`` in Recently Updated. After index exchange is completed, ``File`` resume downloading which leads to ``File: Downloading 7GB/8GB (2MB/s)`` in Downloading and ``Same File: ago`` (there is really only "ago") in Recently Updated. When ``File`` finish downloading, there are 2 lines ``File: ago`` (also only "ago") in Recently Updated. I will come back today later and test more.

**Comment by canton7** [comment]
Ah, sounds like fun. We do assume that Syncthing gives us events in a semi-reasonable order... Let me create a Dev build with some better logging in this area: that will let us see exactly what's going on. 

I've also seen an issue where, if many (thousands) of files are downloaded in quick succession, some will get stuck on "starting"

**Comment by canton7** [comment]
Righty that's built. You can grab a build from here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.22.36/artifacts

I'm going to be on holiday for a week, but I'll be very interested in seeing any relevant logs when I get back!

**Comment by canton7** [comment]
Have you seen this re-appear with the build I linked to? I also fixed a race condition in that build, and so far it's been behaving itself for me...

**Comment by canton7** [comment]
Should be fixed in 1.0.23
