### ISSUE TITLE
Open folder from UI

### ISSUE THREAD

**Issue by dodekeract** [canton7/SyncTrayzor#102]
Is it possible to add an "open folder" button to every folder in the GUI? BTSync had that, and it was really handy.

**Comment by canton7** [comment]
That should already exist - next to edit and rescan. There's also an option if you right click the tray icon.

**Comment by dodekeract** [comment]
Ah, didn't see it, because I didn't expect it to be there.
It would be quite hard to implement it in the "real (web)UI", wouldn't it?

**Comment by canton7** [comment]
How does the differ from the button that's already there in the real Web app, next to edit and rescan?

**Comment by dodekeract** [comment]
Omg, sorry. I don't know what happened.
