### ISSUE TITLE
Use already running Syncthing

### ISSUE THREAD

**Issue by kiler4747** [canton7/SyncTrayzor#103]
My laptop is using by 2 users and I want syncing my data always. If I set startup on both users latest sign in user have error; If laptop have been shutdowned and I set sturtup only for first user syncing also won't be running if sign in second user.

**Comment by canton7** [comment]
What error does syncthing give you when you try and start it for the second user? It should be displayed in the console.

**Comment by canton7** [comment]
My suspicion is that Syncthing is failing to bind to the gui port, since it's already in use. If this is the case, open File - > Settings, find where it says `localhost:8384` and change it to another port, eg `localhost:8385` (obviously each user on your computer will need a different port). 

I should probably add something to SyncTrayzor to search for a free port if 8384 is in use...

**Comment by kiler4747** [comment]
I haven't written precisely. It would be handy to have ability start syncthing like service and to attach this GUI from any user. Or something like that. It can make life better when you don't need turn on laptop before go out. I know about syncthingTray, but this application can't watch out folders.

**Comment by kiler4747** [comment]
thank you that you are adding ability to auto adjust port

**Comment by canton7** [comment]
What you're asking for will never, and should never, be implemented. It would mean that Syncthing would have to run as a user which can access all users' files (which is a huge security hole) and there would be no concept of different users having separate configuration, or sharing different folders: everything would be the same for everyone. This is not how Syncthing should be used: every user should share their own folders, and their syncthing instance should run as them. 

What you're stating is an "xy problem".  You've seen problem X, and think that it is best solved by solution Y, so ask for Y to be implemented. I've explained why Y is a bad idea, so let's go back to the actual problem, X. You can have two syncthing instances running simultaneously for different users by giving them different GUI listen ports (configured in SyncTrayzor) and different protocol listen ports (configured in Syncthing's GUI). Alternatively I can make Syncthing "pause" whenever you switch user.

**Comment by kiler4747** [comment]
It's Ok. I didn't thought about security.

**Comment by canton7** [comment]
Would you be interested in having Syncthing "pause" whenever you switch user? I can see that being useful...

**Comment by kiler4747** [comment]
May be for someone else, but not for me.

**Comment by canton7** [comment]
Fair enough!
