### ISSUE TITLE
GUI has strange mirroring issue 

### ISSUE THREAD

**Issue by jjerome00** [canton7/SyncTrayzor#104]
My server has this weird problem with SyncTrayzor.  The GUI is mirroring diagonally across the window.  There's no better way to describe it than with a screenshot.  

For what it's worth, I opened Syncthing in my browser (Firefox), and everything appears fine.  I'm going to guess this might be an issue with the integrated browser you are using?  I've tried uninstalling/re-installing, double-checking dotnet stuff, etc.

The server is a Lenovo thinkpad, running Win7 x64, 4GB RAM.  Nothing seems taxed on it whatsoever.  I've been able to work around it, but it does get a little annoying.

![synctrayzor_mirring_issue](https://cloud.githubusercontent.com/assets/3046029/8038292/7a44ad7e-0db7-11e5-9745-ef4167d30816.png)

**Comment by dodekeract** [comment]
I'm guessing that this has something to do with the two triangles that might make up the browser rectangle, when it's rendered. Seems like one half of the texture gets mapped twice to both triangles. I don't think it will help, but as this might be related to graphics drivers you might want to check if you can up- or downgrade your drivers.

**Comment by canton7** [comment]
Just when you think you've seen it all...

I'll put together a build which allows you to turn off hardware rendering, see if that helps...

**Comment by canton7** [comment]
Builds will be available at https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.22.38/artifacts when they've been built (will take about 15 minutes). There's an option in Settings to disable hardware rendering (you'll need to restart SyncTrayzor after changing this). Let me know whether that helps!

**Comment by jjerome00** [comment]
I downloaded and installed, and I no longer have the mirroring issue!  Thank you!  It was getting rather annoying trying to interpret some of the screens.

**Comment by canton7** [comment]
Cool, so it was some weird hardware rendering issue with the embedded browser component - nice one @dodekeract! The "real" solution likely lies in some graphics driver updates, or perhaps a fix to the embedded browser, but disabling hardware rendering is good enough :-P

**Comment by canton7** [comment]
1.0.23 is out with this workaround in place
