### ISSUE TITLE
Restore work after exception

### ISSUE THREAD

**Issue by kiler4747** [canton7/SyncTrayzor#105]
When occure fatal exception syncTrayzor close, after restarting syncTrayzor it say that syncthing is stoped but in background in internal brouser show current running instance of syncthing.

**Comment by canton7** [comment]
Not a lot I can do here: a fatal exception occurred. Something went very badly wrong. SyncTrayzor lost control of the Syncthing process. You can kill it with the menu item Syncthing -> Kill all Syncthing processes

**Comment by canton7** [comment]
If you're seeing fatal exceptions, please report them. You should never see one, ever.
