### ISSUE TITLE
Syntrayzor tray icon shows transfers starting when they are completed

### ISSUE THREAD

**Issue by progers885** [canton7/SyncTrayzor#106]
Syntrayzor tray icon shows transfers starting when they are completed,

SyncTrayzor v 1.0.22
Syncthing v 0.11.8
![synctrayzornotifyissue](https://cloud.githubusercontent.com/assets/12861245/8143913/58e3e6be-11bc-11e5-9e74-c9a6cce71bd4.png)
![synctrayzornotifyissue](https://cloud.githubusercontent.com/assets/12861245/8143915/75bf9738-11bc-11e5-8807-b58f463ed02d.png)

This came to light when I was testing syncthing before putting into production, I am using syncthing portable between two laptops (one 32 bit windows 8.1 and the other 64bit) and have reproduced the problem on both systems.

to reproduce:-
1)  exit synctrayzor 
2) delete the database folder
3) restart synctrayzor

After the the database has completed and the status shows up to date 8 files are still showing in the tray notification area as starting.

exit synctrayor and restarting clears the notification area

screen dump attached apologies for the double screendump could not find where to delete the duplicate

Regards

Paul

**Comment by canton7** [comment]
I think this dupes #101. Can you try the build linked to in that issue and see if it fixes the problem?

**Comment by progers885** [comment]
Hi,
That was quick :)
there is not as many with release 1.0.22.36 but still shows one starting:-

![1 0 22 36](https://cloud.githubusercontent.com/assets/12861245/8143981/bec26fb6-11bf-11e5-949c-be091d0ec808.png)

**Comment by canton7** [comment]
Can you send me the relevant section of your log file? You'll find it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs\SyncTrayzor.log`. I'm interested in the time period between when synchronization started and when your screenshot was taken.

**Comment by progers885** [comment]
Hi,

 

Log attached as its portable the logs are within the folder I have not restarted synctrayzor yet and the .picasa.ini file is still showing as starting time now 11:40

**Comment by canton7** [comment]
Unfortunately github doesn't show email attachments. Can you either paste it inline, or put it on a pastebin (e.g. http://gist.github.com) and link to it?

**Comment by canton7** [comment]
(or email it to me directly - my email is on http://github.com/canton7)

**Comment by progers885** [comment]
Hi
sent direct

**Comment by canton7** [comment]
Righty, I think this is because Syncthing tells us that that file starts downloading, but doesn't tell us that it's finished. This is because, if too many things happen too quickly, Syncthing forgets to tell us about some of them. I'll get a workaround in.

**Comment by progers885** [comment]
Thanks for the update,

**Comment by canton7** [comment]
Righty, I've put a fix in place. There will be a build available at https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.22.41/artifacts in about 15 minutes. Mind checking that it solves you issue?

**Comment by progers885** [comment]
Hi,

on my 64bit laptop worked but on my 32 bit laptop didn't?

**Comment by canton7** [comment]
Interesting. Can you send me the log from the 32-bit laptop please?

**Comment by progers885** [comment]
sent direct

**Comment by canton7** [comment]
Can you remember the name of the file on the 32-bit laptop which was marked as constantly starting to synchronize?

**Comment by progers885** [comment]
![one](https://cloud.githubusercontent.com/assets/12861245/8144484/a13ef6a8-11d8-11e5-9822-2e842704206a.png)
![two](https://cloud.githubusercontent.com/assets/12861245/8144485/a80156f2-11d8-11e5-9a33-17d10335dbce.png)

**Comment by canton7** [comment]
Are you absolutely sure that the 32-bit laptop is running the custom version 1.0.22.41 linked to above? The log messages suggest that it's the latest format release

**Comment by progers885** [comment]
yes but to be sure give me a filename and I will tell you the md5

**Comment by canton7** [comment]
`D:\StandAlone\SyncTrayzorPortable-x86\SyncTrayzor.exe` should have the MD5 1ec14470de24e38a4364e32766567ee0

**Comment by progers885** [comment]
hi,
the md5 was different so I must have screwed up somewhere, downloaded again and reran test on 32 bit machine and it worked.

apologies for the extra work.

your product not only provides a tray but an easy method of relocating the Database and appears to incorporate a form of syncthing-inotify 

Great work, many thanks

**Comment by canton7** [comment]
No worries: it happens. That's why I have lots and lots of logging :smile: 

Yeah, SyncTrayzor also provides everything that syncthing-inotify provides (in theory at least!)

**Comment by progers885** [comment]
I mentioned this on the syncthing forum when I was asking some questions one of them being how to relocate the database.
https://forum.syncthing.net/t/windows-backup-image-recovery-to-c-drive-with-sync-folders-on-d-drive/3005

probably a known issue but if you change the web gui from localhost to hostname it sends firefox into apoplexy opening multitudes of windows untill you restart synctrayzor

**Comment by canton7** [comment]
How interesting: that's not a know issue!

**Comment by canton7** [comment]
Should be fixed in 1.0.23
