### ISSUE TITLE
Sync Overview - Error: 2

### ISSUE THREAD

**Issue by Rewt0r** [canton7/SyncTrayzor#109]
![untitled](https://cloud.githubusercontent.com/assets/2598704/8156786/61be13f4-1347-11e5-99ce-a94dc670a09f.png)

**Comment by canton7** [comment]
What syncthing version? This used to be a problem a few versions back, but Syncthing should have fixed it

**Comment by canton7** [comment]
Reference: https://github.com/syncthing/syncthing/pull/1880

**Comment by Rewt0r** [comment]
v0.11.9

**Comment by Rewt0r** [comment]
It hasn't popped back up since so I will keep monitoring, didn't realise it outputs the error reported from Syncthing...

**Comment by canton7** [comment]
Can you correlate it with an entry from Syncthing's log? Either in the console, or `syncthing.log`?

**Comment by canton7** [comment]
Any more input on this?

**Comment by Rewt0r** [comment]
I'm waiting for it to appear again, at the moment it hasn't or I have missed it due to other commitments. I will monitor today and report back at the end of the day.

**Comment by canton7** [comment]
It should be fairly easy to reproduce:

1. Create folder, wait for it to sync
2. Add ignore rule for *.testtmp
3. Create folder\Something.testtmp
4. From another device, delete folder
5. Watch as Syncthing fails to delete the folder

**Comment by Rewt0r** [comment]
I haven't seen this come back so I no longer think this is an issue.

**Comment by canton7** [comment]
Cool - I've seen it work properly with new versions of Syncthing in the meantime.

I'll close this off, feel free to re-open if you see it with a new Syncthing version
