### ISSUE TITLE
Include higher resolutions in icon

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#11]
See https://discourse.syncthing.net/t/synctrayzor-windows-host-for-syncthing-installer-auto-start-built-in-browser-tray-icon-folder-watcher-and-more/2011/4?u=canton7

Have asked d4k0 if he can pass his .ico file my way. Will update if he responds, otherwise roll my own in a few days.

**Comment by d4k0** [comment]
Hi,
I just posted my .ico file on the Syncthing forums. If you want, I can also remove some (unneeded) sizes (or the 8-bit versions) from the .ico file.
