### ISSUE TITLE
File sync status overlay icons (woah.. mouthful!)

### ISSUE THREAD

**Issue by jkaberg** [canton7/SyncTrayzor#111]
I'd love to see this feature in

It would pretty identical with how Dropbox does it with overlay icons on files which are synced, to be synced etc

How it would look like:

![dropbox-sync-complete](https://cloud.githubusercontent.com/assets/613363/8179080/7424f396-1414-11e5-8691-413fdd21edc4.png)

![nbezix](https://cloud.githubusercontent.com/assets/613363/8179084/7ba60ad8-1414-11e5-802b-0c7959303a2a.png)

https://msdn.microsoft.com/en-us/library/windows/desktop/ff521690(v=vs.85).aspx

Thoughts @canton7 ?

**Comment by canton7** [comment]
I was thinking about this the other day. Remember that I can't tell when a file's been uploaded to the cloud (or is being uploaded). I can only tell when a file is being downloaded (currently shown in the tray), or is about to be downloaded (and there's typically only a couple of seconds between this state and the "currently downloading" state).

Also, shell icons take at least a few seconds to update anyway....

So all we would really be able to provide would be some out-of-date information on what's currently downloading :stuck_out_tongue: Does that still sound useful?

**Comment by jkaberg** [comment]
Well yeah sorta, whenever I browse my files it *feels* better if an icon tells me its synced/to be synced/failed :smile: 

Perhaps an upstream patch is necessary? (to tell if an file is synced/to be synced/failure) @calmh @AudriusButkevicius

**Comment by canton7** [comment]
This has come up a few times, and "Synced with the cloud" is a very woolly term: synced with just one device? All devices? All online devices? Any decision is going to mislead *someone*.

**Comment by jkaberg** [comment]
In my mind (seen from the local client) icons would only change whenever the local client is out of sync with the rest of the connected devices/cloud (on a per file basis). Anyhow this information should be available in (and from) Syncthing since it needs to consider it when syncing with connected clients

So IMO you would only need to consider the local file state (is it up-to-date, and if not then its syncing or has failed)

IDK if I'm approaching this the wrong way?

**Comment by canton7** [comment]
Again, it's this definition of "the rest of the connected devices/cloud" that's woolly. Is that a single other device? All connected devices? All other devices, whether connected or not?

**Comment by canton7** [comment]
With Dropbox it's easy, since there's only one other device: the Dropbox server. For us it's a log more hazy...

**Comment by jkaberg** [comment]
IDK if it's really a problem, since Syncthing needs to keep track of if an file is up to date or not. SyncTrayzor could just inherit that, no? (the information would need to be available from Syncthing)

Anyway it would need to consider all connected devices, as we can't get the state from an offline device :smile:

**Comment by canton7** [comment]
Syncthing keeps track of whether its local files are up-to-date with the "global" state. It does *not* keep track of whether the global state is up-to-date with its local files. That is, it only cares that it has the latest version of a file: it doesn't care whether anything else has the latest version of a local file.

**Comment by jkaberg** [comment]
Yeah but thats pretty much what need need is it not?

Syncthing keeps track of whether its local files are up-to-date with the "global" state == green checkmark icon

Syncthing keeps track of whether its local files are up-to-date with the "global" state != blue "sync" icon

And obviously a third state for failure

**Comment by canton7** [comment]
I think you're missing my point still:

If we modify a file locally, we do not know whether anyone else has acquired that file. That is not tracked. We have no way of knowing whether a modification made to a local file as been acquired by anyone else.

**Comment by jkaberg** [comment]
Ah right, sorry. Now I get what you mean, slow thinking today :smile_cat: 

But perhaps an feature request is in order then? @ syncthing

I'm willing to submit it if you agreed

**Comment by canton7** [comment]
I've discussed it with Jakob and Audrius before. In essence it's a pretty large change, and a shift in the current model. You can ask again by all means, but don't stack your hopes on it for the short or medium term :smile:

**Comment by jkaberg** [comment]
Thats to bad, it's a nice little feature to have as it gives "instant" feedback on a files state makes it quite handy

Anyhow, if you already tried then I obviously wont waste anymore of your (or thires) time on this subject 

Thanks for takeing your time tho :-)

**Comment by canton7** [comment]
Yeah, it's a pain, but I can understand why it is the way it is.

SyncTrayzor rotates its tray icon when data is being transferred, and that's really the best I can do.

**Comment by entonio** [comment]
I'm sorry for bumping in, but - aren't we able to know when a file is being uploaded? I haven't delved into how i's implemented, but at some point the data has it be uploaded, or not?
I understand that it may be impossible to know if someone else has a completely up-to-date copy of our file, but don't we know whether we have at least communicated all the data to the 'web'?

Thank you for a very nice program. I'm in the process of setting up a syncthing-based solution again, after having been held back by an unusable internet connection.

**Comment by entonio** [comment]
At least it would be great if the synced folder had an overlay icon, maybe:
- orange: there are no other nodes connected
- blue: data is being transferred to all connected nodes
- half green / half blue: at least one connected node is idle and at least another is exchanging data
- green: all other connected nodes are idle for this folder

I think this would be useful and eye-candy - just so we know there is something going on. But maybe it's too much work for little gain?

**Comment by canton7** [comment]
> I'm sorry for bumping in, but - aren't we able to know when a file is being uploaded?

This comes up again and again: no, there's no concept of a "file being uploaded" in Syncthing. When a Syncthing device downloads a file, it will fetch bits of that file from multiple other devices, and potentially re-use bits of *different* files, on other devices.

**Comment by entonio** [comment]
I get that. I do. But don't we know when we're providing bits over the network to some other node? That's what I meant, not 'we decided to upload this file on our own'.
The UI does show other nodes and whether they're receiving data from us and/or sending it. My proposal above was to have a per sync folder colour indicator of that same data.

**Comment by canton7** [comment]
No. If someone requests a block with hash abc123, Syncthing doesn't report that to us, and it certainly doesn't report which file it decided to grab that block from.

Folder overlays are a lot of work, never mind the fact that they are [no longer recommended](https://devblogs.microsoft.com/oldnewthing/?p=15723), so the likelihood of this being implemented without a contribution by you, a user, is very low I'm afraid.
