### ISSUE TITLE
Crash when is adding larg folder

### ISSUE THREAD

**Issue by kiler4747** [canton7/SyncTrayzor#112]
When I added folder, it started pulling data from other device and SyncTrayzor has crashed. Here log:
```
Received 6 events 
2015-06-16 12:20:31.2385 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <ItemStarted ID=13718 Time=16.06.2015 12:20:31 Item=Project\FrameSync_dll\FrameSync_dll\frame.h Folder=Programming Type=file Action=update> 
2015-06-16 12:20:31.2385 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <ItemStarted ID=13719 Time=16.06.2015 12:20:31 Item=Teseract\tesseractdotnet_v301_r590\Source\ABOUT-NLS Folder=Programming Type=file Action=update> 
2015-06-16 12:21:23.5034 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <ItemFinished ID=13720 Time=16.06.2015 12:20:31 Item=C++\console_test\test_3\My Amplifier Results\r000cc\dicer-db\dd_grouper_hist_dd_thread_global_data7.ddb Folder=Programming Error=> 
2015-06-16 12:21:23.5044 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <ItemFinished ID=13721 Time=16.06.2015 12:20:31 Item=C++\Test_MFC_03\Test_MFC_03\Test_MFC_03.cpp Folder=Programming Error=> 
2015-06-16 12:21:23.5044 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <ItemFinished ID=13722 Time=16.06.2015 12:20:31 Item=Project\SyncFiles\SyncFiles\stdafx.cpp Folder=Programming Error=> 
2015-06-16 12:21:23.5044 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <ItemStarted ID=13723 Time=16.06.2015 12:20:31 Item=test\testphone\testphone\testphone.Windows\Package.appxmanifest Folder=Programming Type=file Action=update> 
2015-06-16 12:21:23.5924 [Warn] SyncTrayzor.Services.DirectoryWatcher: Path E:\programming\MinskTrans\.git\objects\7c\~syncthing~ffc26135f2f16081e79093b42b7423e1917f16.tmp changed, but it doesn't exist any more System.IO.FileNotFoundException File E:\programming\MinskTrans\.git\objects\7c\~syncthing~ffc26135f2f16081e79093b42b7423e1917f16.tmp not found System.String GetLongPathName(System.String)    в SyncTrayzor.Utils.PathEx.GetLongPathName(String shortPath) в c:\projects\synctrayzor\src\SyncTrayzor\Utils\PathEx.cs:строка 41
   в SyncTrayzor.Services.DirectoryWatcher.GetLongPathName(String path) в c:\projects\synctrayzor\src\SyncTrayzor\Services\DirectoryWatcher.cs:строка 184 System.IO.FileNotFoundException: File E:\programming\MinskTrans\.git\objects\7c\~syncthing~ffc26135f2f16081e79093b42b7423e1917f16.tmp not found
   в SyncTrayzor.Utils.PathEx.GetLongPathName(String shortPath) в c:\projects\synctrayzor\src\SyncTrayzor\Utils\PathEx.cs:строка 41
   в SyncTrayzor.Services.DirectoryWatcher.GetLongPathName(String path) в c:\projects\synctrayzor\src\SyncTrayzor\Services\DirectoryWatcher.cs:строка 184
2015-06-16 12:21:23.6834 [Warn] SyncTrayzor.Services.DirectoryWatcher: Path E:\programming\Project\SyncFiles - v3.1\SyncFiles1\My Amplifier Results\r002hs\dicer-db\~syncthing~dd_sw_event_class_base.ddb.tmp changed, but it doesn't exist any more System.IO.FileNotFoundException File E:\programming\Project\SyncFiles - v3.1\SyncFiles1\My Amplifier Results\r002hs\dicer-db\~syncthing~dd_sw_event_class_base.ddb.tmp not found System.String GetLongPathName(System.String)    в SyncTrayzor.Utils.PathEx.GetLongPathName(String shortPath) в c:\projects\synctrayzor\src\SyncTrayzor\Utils\PathEx.cs:строка 41
   в SyncTrayzor.Services.DirectoryWatcher.GetLongPathName(String path) в c:\projects\synctrayzor\src\SyncTrayzor\Services\DirectoryWatcher.cs:строка 184 System.IO.FileNotFoundException: File E:\programming\Project\SyncFiles - v3.1\SyncFiles1\My Amplifier Results\r002hs\dicer-db\~syncthing~dd_sw_event_class_base.ddb.tmp not found
   в SyncTrayzor.Utils.PathEx.GetLongPathName(String shortPath) в c:\projects\synctrayzor\src\SyncTrayzor\Utils\PathEx.cs:строка 41
   в SyncTrayzor.Services.DirectoryWatcher.GetLongPathName(String path) в c:\projects\synctrayzor\src\SyncTrayzor\Services\DirectoryWatcher.cs:строка 184
```

**Comment by canton7** [comment]
What's the crash log? The contents of the window that SyncTrayzor showed you when it crashed.

**Comment by canton7** [comment]
You've posted a snippet from SyncTrayzor's log file, but it doesn't actually document the crash - those are just warnings. When it crashes, it shows a window containing a full error message, and asks you to post it here.

**Comment by kiler4747** [comment]
No, I found it at %appdata%\synctrayzor

**Comment by kiler4747** [comment]
No, It don't show any error. Windows say that app stoped and promt to find solution in internet or close app or debug it

**Comment by canton7** [comment]
Ah fun. If an exception occurs on a filesystem notification, that's not handled nicely unfortunately.

Can you open your event log? Go to Start Menu -> Event Viewer -> Windows Log -> Application. You should find two 'Error' entries for the time of the crash. Could you post the information in both of them, please?

**Comment by kiler4747** [comment]
Имя журнала:   Application
Источник:      .NET Runtime
Дата:          16.06.2015 12:20:29
Код события:   1026
Категория задачи:Отсутствует
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     NAS-PC
Описание:
Приложение: SyncTrayzor.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.ArgumentNullException
Стек:
   в Pri.LongPath.Path.Combine(System.String, System.String)
   в SyncTrayzor.Services.DirectoryWatcher.OnRenamed(System.Object, System.IO.RenamedEventArgs)
   в System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   в System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-16T09:20:29.000000000Z" />
    <EventRecordID>30280</EventRecordID>
    <Channel>Application</Channel>
    <Computer>NAS-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Приложение: SyncTrayzor.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.ArgumentNullException
Стек:
   в Pri.LongPath.Path.Combine(System.String, System.String)
   в SyncTrayzor.Services.DirectoryWatcher.OnRenamed(System.Object, System.IO.RenamedEventArgs)
   в System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   в System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
</Data>
  </EventData>
</Event>

**Comment by kiler4747** [comment]
Имя журнала:   Application
Источник:      Application Error
Дата:          16.06.2015 12:20:31
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     NAS-PC
Описание:
Имя сбойного приложения: SyncTrayzor.exe, версия: 1.0.22.33, метка времени: 0x55705e26
Имя сбойного модуля: KERNELBASE.dll, версия: 6.3.9600.17415, метка времени: 0x54505737
Код исключения: 0xe0434352
Смещение ошибки: 0x0000000000008b9c
Идентификатор сбойного процесса: 0x136c
Время запуска сбойного приложения: 0x01d0a5f9dc7d29d2
Путь сбойного приложения: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
Путь сбойного модуля: C:\Windows\system32\KERNELBASE.dll
Идентификатор отчета: eec2a525-1408-11e5-8268-d0509912ace1
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-16T09:20:31.000000000Z" />
    <EventRecordID>30281</EventRecordID>
    <Channel>Application</Channel>
    <Computer>NAS-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>SyncTrayzor.exe</Data>
    <Data>1.0.22.33</Data>
    <Data>55705e26</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.17415</Data>
    <Data>54505737</Data>
    <Data>e0434352</Data>
    <Data>0000000000008b9c</Data>
    <Data>136c</Data>
    <Data>01d0a5f9dc7d29d2</Data>
    <Data>C:\Program Files\SyncTrayzor\SyncTrayzor.exe</Data>
    <Data>C:\Windows\system32\KERNELBASE.dll</Data>
    <Data>eec2a525-1408-11e5-8268-d0509912ace1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by kiler4747** [comment]
Имя журнала:   Application
Источник:      .NET Runtime
Дата:          16.06.2015 12:35:06
Код события:   1026
Категория задачи:Отсутствует
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     NAS-PC
Описание:
Приложение: SyncTrayzor.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: Stylet.Xaml.ActionNotSetException
Стек:
   в Stylet.Xaml.CommandAction.Execute(System.Object)
   в Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(System.Windows.Input.ICommand, System.Object, System.Windows.IInputElement)
   в Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.OnMouseEvent(Hardcodet.Wpf.TaskbarNotification.Interop.MouseEvent)
   в Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.ProcessWindowMessage(UInt32, IntPtr, IntPtr)
   в Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.OnWindowMessageReceived(IntPtr, UInt32, IntPtr, IntPtr)
   в System.Threading.SynchronizationContext.WaitHelper(IntPtr[], Boolean, Int32)
   в System.Windows.Threading.DispatcherSynchronizationContext.Wait(IntPtr[], Boolean, Int32)
   в System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr, IntPtr, IntPtr, Int32)
   в MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(System.Guid ByRef, System.Object, Int32, System.Guid ByRef)
   в MS.Win32.Penimc.UnsafeNativeMethods..cctor()
   в MS.Win32.Penimc.UnsafeNativeMethods.CreateResetEvent(IntPtr ByRef)
   в System.Windows.Input.PenThreadWorker..ctor()
   в System.Windows.Input.PenThreadPool.GetPenThreadForPenContextHelper(System.Windows.Input.PenContext)
   в System.Windows.Input.StylusLogic.get_TabletDevices()
   в System.Windows.Input.StylusLogic.RegisterHwndForInput(System.Windows.Input.InputManager, System.Windows.PresentationSource)
   в System.Windows.Interop.HwndStylusInputProvider..ctor(System.Windows.Interop.HwndSource)
   в System.Windows.Interop.HwndSource.Initialize(System.Windows.Interop.HwndSourceParameters)
   в System.Windows.Interop.HwndSource..ctor(System.Windows.Interop.HwndSourceParameters)
   в System.Windows.Window.CreateSourceWindow(Boolean)
   в System.Windows.Window.ShowHelper(System.Object)
   в Stylet.BootstrapperBase.Start(System.String[])
   в System.Windows.Application.<.ctor>b__1(System.Object)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   в System.Windows.Application.RunInternal(System.Windows.Window)
   в System.Windows.Application.Run()
   в SyncTrayzor.App.Main()

Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-16T09:35:06.000000000Z" />
    <EventRecordID>30284</EventRecordID>
    <Channel>Application</Channel>
    <Computer>NAS-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Приложение: SyncTrayzor.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: Stylet.Xaml.ActionNotSetException
Стек:
   в Stylet.Xaml.CommandAction.Execute(System.Object)
   в Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(System.Windows.Input.ICommand, System.Object, System.Windows.IInputElement)
   в Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.OnMouseEvent(Hardcodet.Wpf.TaskbarNotification.Interop.MouseEvent)
   в Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.ProcessWindowMessage(UInt32, IntPtr, IntPtr)
   в Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.OnWindowMessageReceived(IntPtr, UInt32, IntPtr, IntPtr)
   в System.Threading.SynchronizationContext.WaitHelper(IntPtr[], Boolean, Int32)
   в System.Windows.Threading.DispatcherSynchronizationContext.Wait(IntPtr[], Boolean, Int32)
   в System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr, IntPtr, IntPtr, Int32)
   в MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(System.Guid ByRef, System.Object, Int32, System.Guid ByRef)
   в MS.Win32.Penimc.UnsafeNativeMethods..cctor()
   в MS.Win32.Penimc.UnsafeNativeMethods.CreateResetEvent(IntPtr ByRef)
   в System.Windows.Input.PenThreadWorker..ctor()
   в System.Windows.Input.PenThreadPool.GetPenThreadForPenContextHelper(System.Windows.Input.PenContext)
   в System.Windows.Input.StylusLogic.get_TabletDevices()
   в System.Windows.Input.StylusLogic.RegisterHwndForInput(System.Windows.Input.InputManager, System.Windows.PresentationSource)
   в System.Windows.Interop.HwndStylusInputProvider..ctor(System.Windows.Interop.HwndSource)
   в System.Windows.Interop.HwndSource.Initialize(System.Windows.Interop.HwndSourceParameters)
   в System.Windows.Interop.HwndSource..ctor(System.Windows.Interop.HwndSourceParameters)
   в System.Windows.Window.CreateSourceWindow(Boolean)
   в System.Windows.Window.ShowHelper(System.Object)
   в Stylet.BootstrapperBase.Start(System.String[])
   в System.Windows.Application.&lt;.ctor&gt;b__1(System.Object)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   в System.Windows.Application.RunInternal(System.Windows.Window)
   в System.Windows.Application.Run()
   в SyncTrayzor.App.Main()
</Data>
  </EventData>
</Event>

**Comment by kiler4747** [comment]
Имя журнала:   Application
Источник:      Application Error
Дата:          16.06.2015 12:35:07
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     NAS-PC
Описание:
Имя сбойного приложения: SyncTrayzor.exe, версия: 1.0.22.33, метка времени: 0x55705e26
Имя сбойного модуля: KERNELBASE.dll, версия: 6.3.9600.17415, метка времени: 0x54505737
Код исключения: 0xe0434352
Смещение ошибки: 0x0000000000008b9c
Идентификатор сбойного процесса: 0xef4
Время запуска сбойного приложения: 0x01d0a817b74b7c1c
Путь сбойного приложения: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
Путь сбойного модуля: C:\Windows\system32\KERNELBASE.dll
Идентификатор отчета: f9294774-140a-11e5-8268-d0509912ace1
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-16T09:35:07.000000000Z" />
    <EventRecordID>30285</EventRecordID>
    <Channel>Application</Channel>
    <Computer>NAS-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>SyncTrayzor.exe</Data>
    <Data>1.0.22.33</Data>
    <Data>55705e26</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.17415</Data>
    <Data>54505737</Data>
    <Data>e0434352</Data>
    <Data>0000000000008b9c</Data>
    <Data>ef4</Data>
    <Data>01d0a817b74b7c1c</Data>
    <Data>C:\Program Files\SyncTrayzor\SyncTrayzor.exe</Data>
    <Data>C:\Windows\system32\KERNELBASE.dll</Data>
    <Data>f9294774-140a-11e5-8268-d0509912ace1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by kiler4747** [comment]
Имя журнала:   Application
Источник:      Application Error
Дата:          16.06.2015 12:35:13
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     NAS-PC
Описание:
Имя сбойного приложения: SyncTrayzor.exe, версия: 1.0.22.33, метка времени: 0x55705e26
Имя сбойного модуля: KERNELBASE.dll, версия: 6.3.9600.17415, метка времени: 0x54505737
Код исключения: 0xc000041d
Смещение ошибки: 0x0000000000008b9c
Идентификатор сбойного процесса: 0xef4
Время запуска сбойного приложения: 0x01d0a817b74b7c1c
Путь сбойного приложения: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
Путь сбойного модуля: C:\Windows\system32\KERNELBASE.dll
Идентификатор отчета: fcb2355f-140a-11e5-8268-d0509912ace1
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-16T09:35:13.000000000Z" />
    <EventRecordID>30287</EventRecordID>
    <Channel>Application</Channel>
    <Computer>NAS-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>SyncTrayzor.exe</Data>
    <Data>1.0.22.33</Data>
    <Data>55705e26</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.17415</Data>
    <Data>54505737</Data>
    <Data>c000041d</Data>
    <Data>0000000000008b9c</Data>
    <Data>ef4</Data>
    <Data>01d0a817b74b7c1c</Data>
    <Data>C:\Program Files\SyncTrayzor\SyncTrayzor.exe</Data>
    <Data>C:\Windows\system32\KERNELBASE.dll</Data>
    <Data>fcb2355f-140a-11e5-8268-d0509912ace1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by canton7** [comment]
It looks like there are a number of crashes there: one at 12:20, and another at 12:35. The one at 12:20 I can understand not giving you a "SyncTrayzor has crashed" window. Did the one at 12:35 not give you that window?

**Comment by kiler4747** [comment]
May be I didn't notice, but it's not likely.

**Comment by kiler4747** [comment]
here screenshot
https://www.dropbox.com/s/pp9mgu31a3avdsf/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%282%29.png?dl=0

**Comment by canton7** [comment]
In about 15 minutes, when the build has finished, there'll be a new version to try here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.22.53/artifacts. Mind giving that a shot and seeing it it helps?

**Comment by canton7** [comment]
(It's built now btw)

**Comment by kiler4747** [comment]
I've tried this build, and it work without error

**Comment by canton7** [comment]
Good to hear, thanks for trying it :smile: I'll include that fix in the next release.

**Comment by canton7** [comment]
That fix is in 1.0.23
