### ISSUE TITLE
Exception on Windows Shutdown

### ISSUE THREAD

**Issue by SammyIAm** [canton7/SyncTrayzor#117]
Was shutting down windows and got this error:

> Version: 1.0.23.68; Variant: Installed; Arch: Amd64
> Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at SyncTrayzor.SyncThing.SyncThingManager.<StopAndWaitAsync>d__21.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 215
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at SyncTrayzor.Bootstrapper.<Configure>b__3(Object o, SessionEndingCancelEventArgs e) in c:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 126
>    at System.Windows.Application.OnSessionEnding(SessionEndingCancelEventArgs e)
>    at System.Windows.Application.WmQueryEndSession(IntPtr lParam, IntPtr& refInt)
>    at System.Windows.Application.AppFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
>    at SyncTrayzor.SyncThing.SyncThingManager.<StopAndWaitAsync>d__21.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 215<---
> 
> 

Hope that's a useful stacktrace.  Let me know if there's any more info I can provide.

**Comment by canton7** [comment]
That's one of the things that 1.0.24 should fix. Try upgrading, see if that sorts it.

**Comment by SammyIAm** [comment]
Hm, just upgraded, no luck:

> Version: 1.0.24.79; Variant: Installed; Arch: Amd64
> Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at SyncTrayzor.SyncThing.SyncThingManager.<StopAndWaitAsync>d__21.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 219
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at SyncTrayzor.Bootstrapper.<Configure>b__3(Object o, SessionEndingCancelEventArgs e) in c:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 126
>    at System.Windows.Application.OnSessionEnding(SessionEndingCancelEventArgs e)
>    at System.Windows.Application.WmQueryEndSession(IntPtr lParam, IntPtr& refInt)
>    at System.Windows.Application.AppFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
>    at SyncTrayzor.SyncThing.SyncThingManager.<StopAndWaitAsync>d__21.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 219<---

**Comment by canton7** [comment]
Hmm ok thanks. I should have some time in Sunday to look into this.

**Comment by canton7** [comment]
Right I messed up the fix I attempted to put into 1.0.24. 1.0.25 should contain the actual proper working fix!

**Comment by SammyIAm** [comment]
Updated, and just shutdown my computer without an issue.  Thanks for the
quick fix!
