### ISSUE TITLE
Syncthing popping up in fullscreen opengl/directx environments

### ISSUE THREAD

**Issue by m0ppers** [canton7/SyncTrayzor#118]
this happened to me the second time now and i don't resemble any other application doing it: 
synctryzor will show the upgrade popup above a full screen opengl/directx window.

It is really annoying to have that in your favorite "click as mad to win" game. If there is an easy way to prevent that it would be awesome to implement it :S

Version: 1.0.25 (NOW THAT I LOST THAT GAME :D)

**Comment by canton7** [comment]
Aha, interesting. I'll have a look and see if there's an eat to detect that a fullscreen application is running. In the meantime you can turn off automatic upgrade checking in the settings.

**Comment by canton7** [comment]
Note to self: http://www.richard-banks.org/2007/09/how-to-detect-if-another-application-is.html

**Comment by canton7** [comment]
In about 20 mins (once the build completes) there will be a build available here https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.25.84/artifacts which contains behaviour to not show the 'upgrade available' toast if an application's fullscreen.

Don't forget to re-enable auto updates :wink:

**Comment by m0ppers** [comment]
wow..that was quick...feeling ashamed about my oss speed now :S :+1:

**Comment by canton7** [comment]
:smile:

**Comment by canton7** [comment]
It's in v1.0.26

**Comment by m0ppers** [comment]
:+1: thx
