### ISSUE TITLE
"Pin to Taskbar" launches second instance when Minimize/Close to tray is Enabled

### ISSUE THREAD

**Issue by blakev** [canton7/SyncTrayzor#119]
Trayzor should determine if there's already an instance running before launching a second Syncthing, and if so maximize from tray before instantiating a second application instance.

**Comment by canton7** [comment]
Hmm I'm going to have to think about this. It might make sense for the installed version only, since running multiple portable instances is fine.

**Comment by canton7** [comment]
Did you mean pin to taskbar btw? Or is this some windows 8 thing I'm not aware of?

**Comment by blakev** [comment]
Yeah, pin to taskbar; my bad. This isn't blocking functionality or anything, it would just mimic other applications that run in the tray until activated from the taskbar...like pidgin, evernote, outlook, etc.

**Comment by canton7** [comment]
I don't think it will be too bad to get something in which only disallows running the exact same exe twice, so different installations in different places can run independently. I'll figure something out!

**Comment by canton7** [comment]
That should be in: my (limited) testing seems to indicate it's working fine.

There will be a build available in about 15 minutes here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.25.85/artifacts

**Comment by canton7** [comment]
It's in v1.0.26
