### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by odgeza** [canton7/SyncTrayzor#123]
Version: 1.0.25.82; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration) in c:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 142
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in c:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 87
   at SyncTrayzor.Bootstrapper.Configure() in c:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 88
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Hmm, looks a lot like #120, but the poster there disappeared before I could get any useful information out of him!

So: did yo do anything before starting SyncTrayzor (the first time that it crashed like this)? Did you upgrade it? Shutdown your computer? Anything else that probably isn't relevant, but would be good to mention just in case?

Could you pastebin `C:\Users\<You>\AppData\Roaming\SyncTrayzor\config.xml` somewhere (or paste it in here)? I'm interested in whether the while file's been corrupted, or just the first few bytes, or whether there's nothing else, or....

Once you've saved your corrupted `config.xml` somewhere, you can rename/delete `C:\Users\<You>\AppData\Roaming\SyncTrayzor\config.xml` and start SyncTrayzor again, which should re-generate it. You'll lose data such as what notifications are enabled (the things in `File -> Settings`), but your Synthing configuration (devices, folders, etc) will be fine.

Thanks!

**Comment by odgeza** [comment]
My PC ran out of power today. 

The contents of it is a whole bunch of "NUL" if open it notepad++ 
Any other app show its as blank (notepad.exe or IE etc).

Renaming the file works as you suggeted (I did eventually find the other language version of the error in #120

**Comment by canton7** [comment]
Roughly how many NULs? Are we in the region of 10s, 100s, 1000s, etc?

**Comment by odgeza** [comment]
there are 1927 NULs

On 15 July 2015 at 08:30, Antony Male <notifications@github.com> wrote:

> Roughly how many NULs? Are we in the region of 10s, 100s, 1000s, etc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/canton7/SyncTrayzor/issues/123#issuecomment-121504946>
> .
>



-- 





*Matthew Ogden*

Management

TenacIT





*Strategic IT Consulting *•* Advanced Networking *• *Virtualisation*

*Custom Development *• *Hosting *• *Syspro Support  *• *MS Licensing*

National Tel: 041 10 10 100 | Cell: 084 205 4445 | Email:
matthew@tenacit.net

CT Tel: 021 201 0333 | Skype Name: matthew.ogden | Web:
http://www.tenacit.net

**Comment by canton7** [comment]
Thanks! OK, so it's basically the right length but everything's NULL. Sounds like we opened it and were just about to write to it (so the filesystem helpfully zeroed everything out to avoid security issues) when everything rebooted. We only write to that file pretty rarely (after initial start-up), so you must have got very unlucky!

I'm looking into making this write more robust...

**Comment by odgeza** [comment]
Perhaps having a fallback/rollback file would be more reliable?

**Comment by canton7** [comment]
That's actually [surprisingly hard to get right](http://blogs.msdn.com/b/adioltean/archive/2005/12/28/507866.aspx). Using TxF looks like a better option.

**Comment by odgeza** [comment]
Hi,

I just mean something like, copy the file to rollback version, and try write changes to current version. Once current version checked as "re-readable" again. Delete rollback version. If it fails mid-write, you would be able to rollback to the copied version, and rewrite it to the main version again, and then delete it. 

Assuming here, that when you re-read the file that was just written, its not somehow still showing you cache from what you wrote, but is actually going to re-read the fully written file.

**Comment by canton7** [comment]
It gets more complex than that, and it's an area I don't particularly want to get into. Especially given that Windows has support for atomic file writes anyway, which I might as well just tap in to.

**Comment by canton7** [comment]
Actually, MoveFileEx looks like the recommended approach nowadays

**Comment by canton7** [comment]
This should be fixed in v1.0.27. Let me know if you still see issues.
