### ISSUE TITLE
21:58:04 INFO: Puller (folder "xxxxxxxx", file "yyyyy"): pull: no available source device

### ISSUE THREAD

**Issue by odgeza** [canton7/SyncTrayzor#125]
I get the no available source device on a file sometimes (not on the instance that created the file). 

But the file remains unsynced even after a restart, and a rescan on both sides. Renaming the file, and renaming it back, makes it sync.

Not sure if its syncthing or synctrayzor. let mw know what I should look at to start?

**Comment by canton7** [comment]
That will be a Syncthing issue - please open an issue on their tracker. It will also help if you include a full console log (from the window at the bottom of SyncTrayzor). Thanks!
