### ISSUE TITLE
browser seems to dissappear

### ISSUE THREAD

**Issue by odgeza** [canton7/SyncTrayzor#127]
On servers that I RDP, sometimes the screen is white when I return to the session, except for the console log. If I change the console visible option, the browser info shows again.

**Comment by canton7** [comment]
Tried turning off hardware acceleration? There's an option in SyncTrayzor's settings

**Comment by odgeza** [comment]
will give that a go, will leave closed for now

**Comment by canton7** [comment]
Nah, leave open until you see

**Comment by odgeza** [comment]
Disabling the hardware acceleration does not help

**Comment by canton7** [comment]
Do things like changing the size of the SyncTrayzor window / minimizing/restoring it / etc also work? I wonder if hiding/showing the console "works" simply because it changes the size of the brwoser's area and forces it to redraw, or some such...

**Comment by odgeza** [comment]
as you suspected, all of those things fix it

**Comment by canton7** [comment]
I fear this may be an interaction between the embedded browser component and RDP, so there may not be much I can do about it. I've done an initial issue search and haven't found anything. I'll do a more thorough search when I have some more time.

**Comment by dodekeract** [comment]
You could use a workaround and manually force a redraw 3 seconds after opening the window or something similar. Would not be the ideal solution, but might be the only thing you can do.

**Comment by canton7** [comment]
I'm not hugely sure I'll be able to do even that tbh - it's pretty self-contained. I'll have a look...

**Comment by odgeza** [comment]
I can live it with to be honest. It does seem to happen on all the win 2012 R2 servers I am using though. Havent seen it on my win2008 servers yet

**Comment by canton7** [comment]
Does the 'Syncthing -> Refresh Browser' menu option help?

**Comment by odgeza** [comment]
no, it doesn't seem to help

**Comment by canton7** [comment]
Hrm. So @dodekeract's suggesting of forcing a redraw after opening the window won't help, because opening the window fixes it anyway. The thing that triggers it is simply viewing the application: anything else (maximizing, resizing, etc) will magically "fix" it again. Since I can't tell when you start viewing the application using Remove Desktop, I don't think there's any workaround I can put in place.

Sorry.
