### ISSUE TITLE
Support Touch-Screens

### ISSUE THREAD

**Issue by Schroedingers-Cat** [canton7/SyncTrayzor#129]
When I access Syncthing's GUI via external browser, I can swipe my finger vertically to scroll up and down.However, using SyncTrayzor's GUI, I'm doing a selection when swiping. It would be great if we could change that behaviour on systems with a touch screen connected or if the OS is in "tablet mode".

**Comment by canton7** [comment]
Fair request. I'm not sure exactly what's at fault here: the embedded browser component, or me. I'll investigate (as best I can without a touch screen) and get back to you

**Comment by canton7** [comment]
I think this is cefsharp/CefSharp#975, making it an upstream bug.

**Comment by Schroedingers-Cat** [comment]
Thank you for looking into this. 

Btw, I have the feeling that SyncTrayzor GUI is rendered at like 10-15fps, no matter if I use an Intel HD or an nVidia GTX. Is there a reason for that?

**Comment by canton7** [comment]
What makes you think it's rendered at a particular frame rate? What are you seeing which indicates this?

**Comment by Schroedingers-Cat** [comment]
The WebGUI utilizes certain animations (like expanding, colorizing, moving UI elements ...). These animations run smooth in the webbrowser but look choppy in SyncTrayzor (like a video game at unplayable fps). On top of that, scrolling is a bit laggy.
I observed this on multiple devices: Desktop with GTX770, Laptops with gaming GPUs from 2013 and 2014 and a Windows Tablet.

**Comment by canton7** [comment]
Ah ok, so it's the animations in the web GUI that you're seeing the slowdown on. I haven't seen anything that bad on any of my machines. Can you try disabling hardware rendering (there's an option in Settings) and see if that makes any difference?

**Comment by canton7** [comment]
Looks like upstream has fixed this. I'll look at upgrading CefSharp (a surprisingly painful process) and see if it works.

The issue indicates that it's not well tested, so I might require editing `SyncTrayzor.exe.config` to enable...
