### ISSUE TITLE
Support for web GUI username/password

### ISSUE THREAD

**Issue by jaredthirsk** [canton7/SyncTrayzor#13]
After migrating my NSSM syncthing configuration over to syncthing's user location (appdata/syncthing) for SyncTrayzor, the web GUI in SyncTrayzor shows a "Not Authorized" message because I set a username/password.

I manually deleted the username/password from synthing's config.xml, restarted, and got in.  Then I added a username/password, and did a restart.  The SyncTrazor's web view then stops updating. (I bet it is getting a 500 not authorized, but not replacing what's on the screen.)

I don't know if it is a huge deal, but I'm not sure I want my web gui running (even on a localhost interface) with no security.

An idea to potentially elevate to syncthing itself: allow wrapper apps to log into the web GUI with a username of "APIKEY" and a password of {apikey}, so that wrapper apps like SyncTrayzor don't need to separately store a username/password.

**Comment by canton7** [comment]
The old embedded browser component I used to use handled HTTP basic authentication just fine. Then I switched (the newer embedded browser didn't leak memory all over the place), but it looks like basic authentication doesn't have quite the same level of support.... 

Something definitely needs to be done. I'll raise an issue with Syncthing, see if there's a neat solution. I *could* manually override the password using the REST API, but I have a feeling that would majorly piss some people off ;) Otherwise, prompting for a username/password wouldn't be so bad: it would only happen when the user first restores SyncTrayzor from the tray icon, so it wouldn't be pestering them on every startup.

**Comment by canton7** [comment]
Right, looks like there's a really nice solution.

I'm afraid I'm not going to have time to put it in place before Monday (it's my anniversary and I will have my head bitten off if I spent it programming), but I'll get it in place ASAP!

**Comment by jaredthirsk** [comment]
Great!  Happy anniversary!

**Comment by canton7** [comment]
Turned out to be a 3-line fix. How about that?

Re-opened because I want this to remain visible for any users in a similar situation browsing the issue list. I'll close it once I get a release out, and I'll do that when I've also fixed #12.

**Comment by canton7** [comment]
Oops, bad commit message reference.

**Comment by canton7** [comment]
Fixed in 1.0.7

**Comment by Brenkon** [comment]
I'm not certain the username + password option is fixed. Please forgive me if I haven't read all the discussion points about SyncTrayzor on the main ST forum and missed something relevant. Here's my case:

1. I downloaded 1.0.7 portable for 64 bit windows. I opened 1.0.7 and selected the option to not use a custom location for the config .... assuming the application would use my already existing ST configuration.

2. Original ST configuration was username + password + https. SynctTrayzor opens its internal browser fine, but it never provides SSL cert warning for my self signed certificate .. nor the login request. It just opens an http screen. Is https conflicting with the username prompt?

Thank you.

**Comment by canton7** [comment]
Username/password was fixed. It looks like https wasn't! SyncTrayzor was still configured to reject invalid certificates (both the API client and the web browser component were aborting their connections). Thanks for pointing that out.

I've committed a fix, and it will be in the next release.

**Comment by Finkregh** [comment]
I am running v1.1.11 / v0.14.6 and try to access the GUI from non-localhost; i never get past the HTTP-Auth, is that intended?
Or am i not entering the credentials correctly?

**Comment by canton7** [comment]
Nothing to do with SyncTrayzor - you should be able to access Syncthing from another machine by entering the HTTP auth credentials which you set up.

Bear in mind that, due to browser-related character encoding shenanigans, passwords (or usernames) containing non-ascii characters might not work.
