### ISSUE TITLE
Allow additional Syncthing command-line flags

### ISSUE THREAD

**Issue by dinosore** [canton7/SyncTrayzor#133]
This is a feature request.

Syncthing provides the command line option -logflags= - see http://docs.syncthing.net/users/syncthing.html#cmdoption-logflags.

Please provide a means to be able to configure, in SyncTrayzor, the value for this option when SyncTrayzor starts syncthing.instead of merely taking the default.

My preference for a default value would be 3 (date and time).

Issue raised at the request of @canton7 https://forum.syncthing.net/t/synctrayzor-logging/5508/7

**Comment by canton7** [comment]
I think I'll add something which lets you specify any command-line flag...

**Comment by canton7** [comment]
Righty, the work should be done.

It will be in the next release, or you can download a pre-release which contains it here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.27.128/artifacts

**Comment by dinosore** [comment]
I've tried the pre-release version with -logflags=3 and it worked fine.

Thanks.
