### ISSUE TITLE
Inconsistency with Syncthing GUI listen port

### ISSUE THREAD

**Issue by simplypeachy** [canton7/SyncTrayzor#134]
Using SyncTrayzor 1.0.27 with Syncthing 0.11.23. In Syncthing's GUI -> Advanced Configuration it states the GUI listen address as "127.0.0.1:21245", which is what matches my %localappdata%\Syncthing\config.xml

However, SyncTrayzor overrides this with a command line switch, to localhost:8384, which is what Syncthing is obeying. This caused me some confusion when trying to access Syncthing outside of SyncTrayzor. Syncthing should probably be displaying accurate information (I'll report this), but is there a reason why SyncTrayzor is overriding Syncthing's config in this instance?

**Comment by canton7** [comment]
Yes - SyncTrayzor needs to be able to talk to Syncthing once Syncthing has started. Therefore it needs to control what port Syncthing listens on. 

If you want to change this, go to Settings -> Syncthing in SyncTrayzor, and change the port in 'GUI Listen Address'.

**Comment by canton7** [comment]
(BTW, you can use Syncthing -> Open in external browser in SyncTrayzor)

**Comment by simplypeachy** [comment]
Shouldn't SyncTrayzor talk to Syncthing via Syncthing's config.xml host:port settings?

**Comment by simplypeachy** [comment]
Ah thanks for that tip - I hadn't looked there

**Comment by canton7** [comment]
SyncTrayzor does not know where to find Syncthing's `config.xml`, nor does it presume that it would know how to parse if it it could find it (since the format can change in any way at any time). Indeed, `config.xml` may not even exist. It's far more reliable if we specify the GUI listen address and API key on the command-line.
