### ISSUE TITLE
Firewall Rules

### ISSUE THREAD

**Issue by gijs007** [canton7/SyncTrayzor#138]
Does Sync Trayzor automatically make rules for the Windows Firewall?
If not which executables need to be allowed?

**Comment by gijs007** [comment]
I'm asking because I've added a device, but I'm being told it's disconnected on both ends. (perhaps this is because the folder is still being scanned?)

I read that I need to add it on both sides. How does this work when there is more than two devices? Do I only have to do this for the first device and it's "master", and then it will automatically know of all the other peers connected to the "master"?

**Comment by canton7** [comment]
It does not (although it might not be a bad idea of it did...) . syncthing.exe is the process you need to let through your firewall

**Comment by canton7** [comment]
Have a read of the syncthing docs (docs.syncthing.net)  and the forum (forum.syncthing.net)

**Comment by gijs007** [comment]
Thank you for the fast reply!

I've added both ends in the firewall, restarted them and they've finished synching/indexing the folders but remain disconnected.. I'll have a read on the docs and forums (but they are huge, so I don't know where to start ;) )

**Comment by gijs007** [comment]
Found out why it wasn't working..

Seems like the data is not bound to syncthing.exe, hence why the rule isn't being applied:

The firewall log shows this:

The Windows Filtering Platform has blocked a packet.

Application Information: Process ID: 0 Application Name: -

Network Information: Direction: Inbound Source Address: 23.246.204.13 Source Port: 0 Destination Address: 208.76.248.162 Destination Port: 0 Protocol: 6

Filter Information: Filter Run-Time ID: 74332 Layer Name: Transport Layer Run-Time ID: 13

For more info see: https://forum.syncthing.net/t/hosts-remain-disconnected-cluster-setup/5600/7

**Comment by canton7** [comment]
Interesting! I'm afraid this is a Syncthing issue, not a SyncTrayzor issue. It's listing a process ID of 0 (which is nonsense) and a source/destination port of 0 (which is also nonsense), so I think it's a bit confused...

**Comment by AudriusButkevicius** [comment]
Its more like a windows issue

**Comment by canton7** [comment]
Fair :smile:
