### ISSUE TITLE
Introducer function

### ISSUE THREAD

**Issue by gijs007** [canton7/SyncTrayzor#139]
When having a trusted device as introducer all the other hosts still need to manually approve any new devices that is being introduced to the network and also add the folders which are shared.

This can be a problem with a large cluster that gets new devices added.
Additionally I noticed that the name of the node that is being used isn't the name that what is set on the introducer, which can cause confusion.

**Comment by AudriusButkevicius** [comment]
This is a false statement, you do not need to add devices manually when they are introduced.

**Comment by gijs007** [comment]
Yes I do? I got a popup that tells me to add them, instead of being added automatically.

**Comment by AudriusButkevicius** [comment]
Then you haven't set something up properly.

**Comment by gijs007** [comment]
I have introducing enabled on all the devices (except for the introducer itself)

**Comment by canton7** [comment]
This is a Syncthing issue, not a SyncTrayzor issue.
