### ISSUE TITLE
Tab label not translated

### ISSUE THREAD

**Issue by uok** [canton7/SyncTrayzor#142]
Thanks for making SyncTrayzor!

in settings at the top the tab label "folders" is not translated and missing in Transifex

**Comment by canton7** [comment]
Only being fluent in English, I'm reliant on generous multilingual users contributing translations. If you see something that can be improved, please create an account on Transifex and fix it :smile: You can join the translation team for your language and start submitting translations without needing any permissions. I'll include updated translations in the next release

**Comment by uok** [comment]
No problem, I already have a Transifex account. I looked into "Resources.resx" but it seems that "folders" is not marked for translation so it never ends up as a string ready for translation

**Comment by canton7** [comment]
Aah dammit, looks like you're right. I'll get this fixed up early next week. Thanks!

**Comment by canton7** [comment]
Righty, that label should be available for translation

**Comment by uok** [comment]
Is it possible to sort the strings alphabetically before they are uploaded to Transifex?

**Comment by canton7** [comment]
I'll look into this

**Comment by canton7** [comment]
Done
