### ISSUE TITLE
Never stops scanning

### ISSUE THREAD

**Issue by insurw** [canton7/SyncTrayzor#144]
This seems to be a SyncTrayzor issue and not SyncThing. As it practically never stops scanning so my CPU is constantly at 30-50% making it unusable. It'll start scanning for a few sec, then "out of sync", scanning and on and on. Forever.

The last thing in the SyncThing log is:
[RDV4Q] 10:17:02 INFO: Completed initial scan (ro) of folder XXX

Here's the last lines from the SyncTrayzor log: http://pastebin.com/k1FvsMCx

**Comment by AudriusButkevicius** [comment]
You are syncing app data directory which is constantly changing. I suggest you disable inotify support for that folder and fall back to time based rescans.

**Comment by canton7** [comment]
Looks like you're syncing ` C:\Users\XXX\AppData\Roaming\SyncTrayzor`. This is a bad idea: SyncTrayzor's log is in that path. Whenever anything happens, SyncTrayzor writes to its log. It then notices that a file has changed, and happily tells syncthing to sync SyncTrayzor's log file. That sync causes more stuff to be written to the log file, and the cycle repeats. 

Syncing the whole of AppData is almost certainly a bad idea. While some programs may be fine with you changing their configuration files under their feet, some won't be (SyncTrayzor falls into that category). I suggest using Syncthing's ignores system to ignore the whole of AppData, then explicitly unignore folders within AppData which you do want to sync like, and which you know will sync without problems. 

You *might* still get a cycle where SyncTrayzor sees gets a change notification that it's log file had changed, then logs the fact that that file is ignored, which writes to the log file, etc. You will see that happening by looking in the log file. If that is the case, I'll fix it.

**Comment by insurw** [comment]
I don't know what or were you set inotify, nothing in the SyncTrayzor docs and no way to set it in the GUI. Why can't I just increase rescan interval? Or am I misunderstanding this setting? Shouldn't 900 s make it only scan every 900 s? Maybe selecting folders manually would be a good idea, but doing that would probably just lead to me forgetting adding folders in the future.

**Comment by canton7** [comment]
File - Settings - Folders, untick 'watch' (or whatever it's called) next to the folder. 

This will not change the fact the syncing SyncTrayzor's AppData files *will* cause unforseen problems, and I will not help resolve them :smile:. Likewise with other applications which use AppData: you *will* cause other applications to break in unforseen and unknown ways.

**Comment by insurw** [comment]
Ok thanks.
