### ISSUE TITLE
Read only folder (but prevent writing locally)

### ISSUE THREAD

**Issue by gijs007** [canton7/SyncTrayzor#145]
I know it's possible to make a shared folder master on  a device, this makes it read only and prevents any changes from remote devices.

My suggestion is to share this information to all other devices and locally prevent those devices from editing the folder. (e.g. making it read only on each local devices and only allow changes to come in from the master synchting server or other devices which are in synch with the master)

**Comment by canton7** [comment]
This sounds like a suggestion for Syncthing, not SyncTrayzor. Please start a topic on the syncthing forum, or maybe open an issue on Syncthing's issue tracker. Thanks!

**Comment by gijs007** [comment]
Will do :+1:
