### ISSUE TITLE
Request: folder root Icon, and file folder check mark, and centralised bib in explorer

### ISSUE THREAD

**Issue by DarkMatter26** [canton7/SyncTrayzor#146]
Please :
- Add syncthing icon for the root syncthing folder
- Add check mark for files and folder (gren for sync, and other for another State
- Add a link that can be develop in Explorer (a bit like the other cloud), to the main directory of syncthing.
  in this main directory add the links to other directories synchronized, if they aren't on the inside

**Comment by canton7** [comment]
This is a large chunk of work with lots of complexities: marking for future consideration

**Comment by canton7** [comment]
Can you clarify what you mean by

> Add a link that can be develop in Explorer (a bit like the other cloud), to the main directory of syncthing. in this main directory add the links to other directories synchronized, if they aren't on the inside

please?

**Comment by DarkMatter26** [comment]
screenshot for check mark, link in explorer, and icon for the root folder :)
Thanks for your work 


![capture 2 check](https://cloud.githubusercontent.com/assets/10407234/10188061/d936d59c-675c-11e5-97b5-f24b8bfa4fdd.PNG)
![capture syncthing](https://cloud.githubusercontent.com/assets/10407234/10188062/d93928f6-675c-11e5-9c03-d01662ebf0ac.PNG)
![capture3 add syncthing in same level for dropbox and onedrive](https://cloud.githubusercontent.com/assets/10407234/10188063/d93f3f5c-675c-11e5-8edf-9f2d3230c908.PNG)

**Comment by canton7** [comment]
Ah, I see what you mean (the phrase "like the other cloud" wasn't particularly clear)

**Comment by canton7** [comment]
That's going to be really quite hard to do. It's not *too* bad to create a link to a custom folder there, but we're creating a custom 'virtual' folder, where the stuff 'inside' it doesn't actually exist on disk in the same way. 

For example, if you expand the 'Dropbox' item, you get a list of folders which are actually in a folder called 'Dropbox' on your PC. If you expand the 'Syncthing' item you'll get a list of shared folders, but there's no folder called 'Syncthing' on your PC which contains those folders.

Notes to self:

System.IsPinnedToNameSpaceTree custom
http://superuser.com/questions/840790/how-can-i-create-a-new-system-folder-to-show-up-in-this-pc-in-windows-8-1-with

**Comment by PrototypeNM1** [comment]
You might be able to reference the TortoiseGit/SVN/etc. projects for this, I know they do similar sync overlay icons.

**Comment by canton7** [comment]
I have no idea where to even start with the link in Explorer stuff, so closing.
