### ISSUE TITLE
Cannot run multiple (one per-user) SyncTrayzor instances on the same PC

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#148]
Hi, I'm want to run a separate Syncthing instance for each user on the same PC.
Works fine if only one user logged in at a time.

BUT, it doesn't work simultaneously:
1. Log in user A, auto-starting SyncTrayzor
2. Switch user and log in user B, auto-start of SyncTrayzor fails
3. It ran manually, SyncTrayzor process will be terminated immediately.

Only if I kill user A's instance, i will be able to run it under user B.

It there any workaround for it???

(In Settings I unchecked "Use Syncthing's default database location")

**Comment by canton7** [comment]
> It ran manually, SyncTrayzor process will be terminated immediately.

Aah, I bet this is the functionality to ensure that two instances aren't running at the same time under the same user kicking in and messing things up. Bummer.

In about 10 minutes, there'll be a build here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.27.138/artifacts . Mind downloading and testing that?

**Comment by scienmind** [comment]
In the mean time I've tried using two "portable" installations (folders), one for each user.
It seems to be working this way.
(There is an issue with IPv4 local discovery though, but it seem to be [SyncThing's thing](https://forum.syncthing.net/t/syncthing-multi-user-and-local-discovery/2082/2), and not Trayzor's one)

Anyway, I will appreciate a proper fix, so i'll being able to run a normal install with auto-updates, etc.
Thanks for the quick response, downloading the test build right now...

**Comment by scienmind** [comment]
OK. Using the test build's installer now I can launch the SyncTrayzor for both users simultaneously.

However, SyncThing refuses to initialize. It seems like SyncTrayzor defines the same directories for storing it's DB (in the portable mode due to separate storage of /data, there was no such error)
Here is the error message:
![STError](https://cloud.githubusercontent.com/assets/11633330/10282788/43b7bc2a-6b85-11e5-8264-ee0c2282e3e0.PNG)

**Comment by canton7** [comment]
Most likely Syncthing is trying to use the same listen port for both instances? The output from the Console will clear that up.

In Syncthing's GUI, go to settings, and change the Sync Protocol Listen Address for one of the users.

**Comment by scienmind** [comment]
Yes, your assumption is correct:
`FATAL: listen (BEP): listen tcp 0.0.0.0:22000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.`

Changing the port fixes it. 
Is it safe to just manually change the "Sync Protocol Listen Addresses" in SyncThing's settings? Or should I make more changes elsewhere in this client/other clients to avoid impairing the functionality?

**Comment by canton7** [comment]
"Normal" discovery and local discovery should both handle the port change fine. If you've set up any devices with a manual address (Edit Device -> Addresses, if one of those is of the form `x.x.x.x:22000`), that will need changing.

**Comment by scienmind** [comment]
OK, I mostly use `dynamic` addresses, so it should be fine.

Will you push an official update for SyncTrayzor, or are there any corners to test before?

**Comment by canton7** [comment]
I'm planning to push an update later this week, once I've got something else in.

In the meantime, feel free to use that dev build. It will automatically upgrade once the next release is out.

**Comment by scienmind** [comment]
Cool, nice to know the project is live and kicking btw.

And just as a side note on multi-user options: 
Adding an ability to run at startup per user (as service, separately for each user, w/o login) seems to be potentially very useful. But that's another story...

Thanks a lot!

**Comment by canton7** [comment]
Yeah, I took some time off to go improve some other projects, as this reached a point where people had stopped breaking stuff and asking for new stuff... Issues are starting to pile up again though, so it's time to get stuck back in.

As I've expanded in other issues, turning this into a service is going to be a very long road indeed. Never mind the fact that I'm then tied into maintaining and testing two stacks (service and non-service) in order to keep the portable users happy.

Services are generally only useful in a central server situation, where most of the features that SyncTrayzor offers are of very limited use anyway!

**Comment by scienmind** [comment]
I understand, the most important thing is to have a solid stable software than can be easily maintained alongside Syncthing's updates. So nothing is urgent.

On another use case - do you have any suggestions on the way to run a single, shared SyncTrayzor instance on multi-user machine, that'll start on startup (before login)? Or is the "service" approach is the only option here?

**Comment by canton7** [comment]
"Shared" meaning...? All users use the same installation, or the same running instance?

**Comment by scienmind** [comment]
"shared" - same instance (can be same installation too)

I have another cluster of PC's, with several users each, that have folders I want to be synced, regardless of users logged in. Just let the data flow (kinda-server functionality).

After digging a bit more, seems like the "bare syncthing" + NSSM setup to run it as a service is the way to go for this use case...
(Unfortunately it means no SyncTrazor's fancy stuff - no icons, no notifications, etc.)

**Comment by canton7** [comment]
Be **very** careful with permissions in a setup like this. If you're running Syncthing as a service with permissions to access any users' files, then that opens you up to attack: anyone who can talk to Syncthing can access any file on the filesystem, no matter who it's owned by. This covers both users accessing each others' files, but also an external attacker using that mechanism to gain administrator rights.

Also, if Syncthing (running as a local admin) is syncing user A's files,then any files written by Syncthing may be owned by the local admin, and won't be accessible to user A. So user A suddenly can't access their own files.

Gotchas like those - which can and will directly affect the security of someone's computer - is another of the reasons I don't want to introduce services (and is why I referred to the need to have a separate service per user).

**Comment by scienmind** [comment]
I intended to run this setup with global discovery off, and with a strong web-ui password.
But the file ownership issue you mentioned may be a big problem. Thanks for pointing that out.

I'm think about the following workaround:
Using NSSM set up several syncthing instances (one for each user), to run as a service, but as each user, not system.
It'll add configuration complexity, but this way they all will start before the login (what i need), each instance will run under the appropriate user's restrictions, and fix the file ownership problem.
I'll be glad to hear your opinion on this.

Another question - is there a way to do something similar, but launch SyncTrayzor instead of plain syncthing? 
I tried simply doing the same as i did with syncthing.exe but defining synctrayzor.exe to start via NSSM instead. In a nutshell it worked, but i got no UI/tray icons once logged in, which is a bummer. Hopefully I can still take advantage of filesystem watcher this way. 


P.S.: I know this discussion got far away from the original topic. If you prefer to hold such discussion elsewhere, let me know.

**Comment by scienmind** [comment]
(sorry about close-reopen... my bad...)

**Comment by canton7** [comment]
The strong password is the critical thing. Make sure you have "Use HTTPS for GUI" checked as well.

Running separate services is the way to go, although you will suffer increased system resources when all of those syncthing instances start scanning together! Is there any reason you need to run all of them before login?

I would be very surprised if SyncTrayzor ran correctly under NSSM - it's certainly not intended to do any of the things that a service should do, and assumes it has a desktop, somewhere to put a tray icon, etc. Running it as a service will also make it somewhat tricky to change the settings... There's no way to get it to show a tray icon on login without a separate process which starts on login.

I hope you're starting to see why I want to avoid all of this complexity if at all possible...

**Comment by canton7** [comment]
Closing to indicate that the original issue has been fixed, and that that fix has been release.

Feel free to continue the services discussion in here.

**Comment by scienmind** [comment]
The cluster in question consists of few PCs used by several users. Each user have an account on every PC. The idea is to have each user's "Working Folders" (Documents, and some more) synchronized. Seem trivial so far.

The problem is that same user is rarely logged in on more than one machine at a time and machines turned off/restarted often.
For example:
* User A working on machine 1. User B working on machine 2.
* User A and B leave and turn all the machines off.
* User B start working on machine 1. (User A is not logged in here) 
* User A start working on machine 2. (User B is not logged in here)

Now in the simple "run on login" approach, user A's files from machine 1 will not be synced to the machine 2, and same for User B.
Using "run as service" approach will ensure synchronization regardless of who logged in where.

The above sounds as a classic use for server with few terminals, or remote desktops, or centralized network storage, etc. But due to equipment limitations and the required SW, those options are not suitable.
So seems to me that running Syncthing(s) as per-user services will do the trick just right. 
Regarding security measures: https for GUI is surely enforced in settings, I'm using 32+ characters random passwords with high entropy. For now UPnP and global discovery are disabled (still unsure, but maybe will be enabled later...)

**Comment by canton7** [comment]
In that situation, I'd go for a star-shaped network. Create a central server, which runs a single Syncthing instance as a service (as an unprivileged user). This Syncthing instance has folders configured for each of yours users. Your users don't have (direct) access to the server, so Syncthing can write all of their files as the same user. Set Syncthing to start on login on each of the development machines, and have it sync with the central server (you may be able to get it syncing with the other development machines easily using the introducer stuff too).

Given free reign, I'd be tempted to set up Roaming Profiles using AD - you get nice guarantees, such as files finish syncing before a user logs in (which means that running programs don't have their config changed underneath them, etc).

**Comment by scienmind** [comment]
Now regarding SyncTrayzor. I'm using it "the usual simple way" on another cluster, and quite pleased (:thumbsup:).
It'd be nice to have it's tray/UI functionality on the "service" cluster as well, but if it's technically imposible now, it's not a big deal.

However, according to description, SyncTrayzor incorporates also a more efficient low level "filesystem watcher", allowing for greater folder scanning gaps and improved sync timings.
On your opinion, is it worth to run SyncTrayzor instead of plain Syncthing for the aforementioned "service cluster" scenario for this benefits? Or should I stick to the more "plain" setup there?

(Side-note: I know my use case is probably not a common one, and hence not worth investing your time in "out of the box" support. That's why I'm absolutely fine with doing some "extra" steps in achieving a proper setup for my personal use case)

**Comment by scienmind** [comment]
Yeah, the "star" setup will be much cleaner way, but i don't have the HW for a central server machine right now, and i'm too lazy to learn to use AD....

**Comment by canton7** [comment]
In the star-shaped network I described, there's no need to have a filesystem watcher on the central server.

In your scenario, I don't honestly know whether I'm comfortable running SyncTrayzor as a service - I've never tested it and have no idea what might happen. Syncthing-inotify might be a better bet.

**Comment by canton7** [comment]
You don't need powerful hardware for a central server - an old laptop will do just fine. Heck, and RPi B+ or ODROID-C1 will do a reasonable job.

**Comment by scienmind** [comment]
I plan to upgrade the whole thing by adding a cheap PC/laptop + RAID backed storage (the folders to be synced are quite big, around 1-2TB) and using it as a central server (with more stuff beyond syncthing) but that's not now, that's in the future :-).

For now, considering your recommendations,I think that I'll use SyncTrayzor as it should be where I can, and Syncthing for the cluster setup.

On the "inotify" and filewatchers/scanning in general, how bad is an impact of 60sec rescans of large folders? What is the reasonable interval for ~0.5TB folder? Should I expect it to be a HDD killer in general?

**Comment by canton7** [comment]
> On the "inotify" and filewatchers/scanning in general, how bad is an impact of 60sec rescans of large folders? What is the reasonable interval for ~0.5TB folder? Should I expect it to be a HDD killer in general?

To be honest I'm not the right person to be asking.
