### ISSUE TITLE
Visual Studio 2015 should be recommended, not 2013.

### ISSUE THREAD

**Issue by Zapados** [canton7/SyncTrayzor#153]
https://github.com/canton7/SyncTrayzor#building-from-source

Please recommend VS 2015 instead of VS 2013 as C# 6.0 is required to compile, and I don't think it's officially supported on VS 2013 anymore.

Thank you!

**Comment by canton7** [comment]
Yeah, C# 6 was never supported by VS 2015: I forgot to update the README when I upgraded the project >>

**Comment by canton7** [comment]
Fixed in #155
