### ISSUE TITLE
Issue starting gui?

### ISSUE THREAD

**Issue by dreaddy** [canton7/SyncTrayzor#156]
Ran into this problem today. 

    [GYY73] 08:05:43 INFO: Starting web GUI on https://127.0.0.1:8384/
    [GYY73] 08:05:44 FATAL: Cannot start GUI: listen tcp: too many colons in address       https://localhost:8384/

Setting <gui enabled="false".... bypasses the error, but no gui.

I do not see another service running on that port.

Any suggestions would be appreciated. 

an other may be relevant issues is that the windows gui is always https. No matter the option selected.

**Comment by canton7** [comment]
That's an incompatibility with v0.12 (it would have been useful to state that you were using a beta in the issue!).

See syncthing/syncthing#2371

**Comment by dreaddy** [comment]
Sorry. I did not realize I was using beta.

**Comment by canton7** [comment]
I've confirmed that v0.12-beta4 seems to fix this.
