### ISSUE TITLE
Folder watcher not working

### ISSUE THREAD

**Issue by uok** [canton7/SyncTrayzor#158]
I did my first test with a non-technical user - SyncTrayzor helps a lot :+1: 
:white_check_mark: Installation
:white_check_mark: Syncthing
:white_check_mark: Sync
the only thing that does not seem to work is the folder watcher, so if the user deletes something it is never changed on my side. I only can support this user via phone so where can he look to find out more?

**Comment by canton7** [comment]
OK, let me get clear on who is who...

There's "you", and "the user". Are you both running SyncTrayzor? You say if the user deletes something it is "never changed on my side". Not even after a few minutes? The default rescan interval for Syncthing is 1 minute. This means that, even if the folder watcher is broken in some way, Syncthing will re-scan the folder every minute, will notice the change, and will propagate it.

This implies that the folder watcher is not at fault: you're seeing some Syncthing problem where it's failing to sync any changes from "the user"'s machine. 

Screenshots of both of your Syncthing GUIs (to make sure that all folders are 'Up to Date' and all devices are 'Up to Date') would be the first step. The next would be looking at the contents of Syncthing's console (available in the console window at the bottom of SyncTrayzor) to see whether Syncthing's having any problems.

**Comment by uok** [comment]
User A (me) - Syncthing out of the box, User B (non-technical) - SyncTrayzor

Because SyncTrayzor uses a folder watcher, we set the rescan interval to 86400s (1 day) during installation. Everything is synced fine (changes on A), but the folder watcher on B does not seem to be working, because only if we wait 1 day or restart Syncthing/SyncTrayzor all changes are propagated.

I will try to get the logs/console output from User B

**Comment by canton7** [comment]
I've need to see SyncTrayzor's log file, then. It's in `%APPDATA%\SyncTrayzor\logs\SyncTrayzor.log`. Make sure that it covers a time at which files were changed.

**Comment by uok** [comment]
I finally managed to have the user online and send me the logs, but there is no sign of the file he dropped into the shared folder, so I guess notify is not working at all. Since it's very hard to debug this via phone and a non-tech user I will close this for now and tell him to set rescan intervall back to 60s

**Comment by canton7** [comment]
Can I see the logs? Does he even have the folder watcher enabled for that folder in settings?

**Comment by uok** [comment]
user says it is and I found "Folders=[\<Folder ID=ABCD IsWatched=True NotificationsEnabled=True\>]" which seems to confirm that, if I understand this line correctly. Because of the rather time intensive remote support I will try again in a few weeks when I'm in front of his computer
Thanks for your help!

**Comment by canton7** [comment]
Other thoughts:
 - Maybe the folder is on a network share, or somewhere else that a filesystem watcher won't work
 - SyncTrayzor will ignore file changes which are covered by Syncthing's ignores. Maybe something's going wrong here?
 - The filesystem watcher crashed out earlier
 - For some reason SyncTrayzor thinks the folder doesn't exist, and has given up watching 

A look at the logs would easily confirm/deny any of those, or may highlight things I haven't thought of. I really need to see it, please :smile:
