### ISSUE TITLE
Obsolete info in README

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#160]
README > What will SyncTrayzor do to my system? > Installer
...
If you check "Use custom home directory or Syncthing" in the settings, then SyncTrayzor will tell Syncthing to use C:\Users\<You>\AppData\Local\SyncTrayzor\syncthing for its database. This is useful if you want to keep the copy of Syncthing managed by SyncTrayzor separate from another copy running on your machine.
...

This part no longer apply, since https://github.com/canton7/SyncTrayzor/commit/a49b3a08c6b08ddcbda2ba07f1c2e835dea99ebc I believe.

**Comment by canton7** [comment]
Fair point, thanks!
