### ISSUE TITLE
Syncthing v0.12.0-rc1 vs v0.12.0-rc3 weirdness

### ISSUE THREAD

**Issue by Confuset** [canton7/SyncTrayzor#161]
Hey. i have a very strange problem. iam trying to upgrade to syncthing v0.12.0-rc3. I did that manually by replacing the "syncthing.exe" in the folder C:\Program Files\SyncTrayzor\.

But when starting SyncTrayzor Syncthing reports: 
>[THNMG] 11:34:23 INFO: syncthing v0.12.0-rc1 "Beryllium Bedbug" (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-10-20 07:59:50 UTC

When starting from command line it reports:
>[THNMG] 11:43:44 INFO: syncthing v0.12.0-rc3 "Beryllium Bedbug" (go1.4.-amd64 default) unknown-user@syncthing-builder 2015-10-22 06:35:48 UTC

SyncTrayzor v.1.0.28

This is really strange..I am up for any idea..

**Comment by canton7** [comment]
SyncTrayzor keeps two copies of `syncthing.exe`.

The one that is executed is in `%APPDATA%\SyncTrayzor`. This one is writable by the user, and so can auto-upgrade.

There's a backup in Program Files. This one is copied to `%APPDATA%\SyncTrayzor` if the one in `%APPDATA%\SyncTrayzor` does not exist (SyncTrayzor has never been run before for that user, for example).

If you want to manually upgrade, you should replace the one in `%APPDATA%\SyncTrayzor`.

**Comment by Confuset** [comment]
Yep. Thats it.
Thanks for the help.

I extendend the docu and send pull request ;)

**Comment by canton7** [comment]
I have thoughts around putting in better management of Syncthing executables, which is why I haven't documented any of this yet.

**Comment by Confuset** [comment]
Let me know when you need somebody for playing ping pong on that ;-)

**Comment by canton7** [comment]
Cheers :smile:

**Comment by canton7** [comment]
#154 merged
