### ISSUE TITLE
v1.0.28 does not write to syncthing.log file

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#162]
v1.0.27 does, but after upgrading to v1.0.28 it stops. syncthing.log file has old modification time and content.

Using syncthing v0.12.0-rc4 with both versions

**Comment by canton7** [comment]
I took that out. Syncthing writes to its own log file in `%LOCALAPPDATA%\Syncthing`, so there wasn't any point.

**Comment by chucic** [comment]
Hm, weird, for me it doesn't. Anything in config files of synctrayzor that could prevent my syncthing to write to that file? In gui settings I have no flags set...

**Comment by canton7** [comment]
Hrm, you're right, it's not going it any more for me either. Asking calmh on IRC...

**Comment by canton7** [comment]
Righty, the next version will log Syncthing's output.

**Comment by canton7** [comment]
This is in v1.1.0.
