### ISSUE TITLE
discoveryFailed.join and relaysFailed.join

### ISSUE THREAD

**Issue by fbreve** [canton7/SyncTrayzor#168]
This is happening in 7 machines I've installed Synctrayzor 1.0.29

![391fa132-83e6-11e5-8b45-5e1227b68298 1](https://cloud.githubusercontent.com/assets/7475908/10984912/1bd915fe-8404-11e5-97a5-ba824ff19b44.png)

The issue does not happen if I open the interface on a web browser.

**Comment by canton7** [comment]
Interesting...

I saw it once, then the problem went away permanently and I haven't been able to reproduce it.

If you can reliably reproduce it, can you edit `SyncTrayzor.exe.config`, change `CefRemoteDebuggingPort` from `0` to something else (say `2004`), then open Chrome, go to `localhost:2004`, click the link, open the Console tab. Then in SyncTrazor, go to Syncthing -> Refresh Browser and see if anything pops up in Chrome?

**Comment by fbreve** [comment]
Indeed, it can't be reproduced. Once I restart Synctrayzor to get the new SyncTrayzor.exe.config, the problem is gone. 

Now I notice that in all 7 machines, I didn't try to simply restart Synctrayzor. Sorry about that.

Thank you.

**Comment by canton7** [comment]
It is really weird the way it disappears like that. I wonder whether it's some cached data / local storage that makes the difference? I'll have a play...

**Comment by berrnd** [comment]
That's definitely cacheing ... just upgraded all my machines to Syncthing v0.12 and had this symptom on all of them ... deleted the complete `data\cef\cache` folder and this went away...

Also noticed that Synchting now uses a different font on the web interface and this also wasn't visible after the upgrade. So maybe it would be good to clear the Cef cache on every Syncthing upgrade...

**Comment by canton7** [comment]
Hmm that may be a viable approach.

**Comment by canton7** [comment]
Actually, there's no viable way I can clear the cache I'm afraid. Syncthing can upgrade without a SyncTrayzor restart, and I can only clear CEF's cache on a restart.

CefSharp doesn't yet provide a way of setting just the local storage path (rather than local storage + everything else which can be cached).
