### ISSUE TITLE
Downgrading SyncThing in SyncTrayzor

### ISSUE THREAD

**Issue by tanja84dk** [canton7/SyncTrayzor#169]
I would like to know if its possible to downgrade the SyncThing version in SyncTrayzor.
The reason is that I didn't knew and didn't see a warning that syncthing 0.12 cant sync to syncthing 0.11, and I cant unfortunally upgrade the syncthing on my endpoint at this moment.

The reason I ask is because syncthing is actually the way I'm doing my primary backup as close to real time as posible

**Comment by canton7** [comment]
Resolved on IRC. 

For anyone else seeing this, read https://github.com/canton7/SyncTrayzor#using-syncthing-beta-releases (I know you don't want to use a beta release, but the approach is the same).
