### ISSUE TITLE
FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000

### ISSUE THREAD

**Issue by markyuk** [canton7/SyncTrayzor#170]
Reformatted PC - brand new install of Windows 10.
Took latest syncthing Win64 download and pasted into my Program Files folder.
Run the exe and setup device ID, and a folder to scan.
Shutdown syncthing
Installed SyncTrayzor using latest 64 installer.
Run first time and receive:
**FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000**

I can see some other issue raised about editing xml files, etc but not sure what to do here.
*Thought I'd post this as a separate issue as this is a brand new install.*

**Comment by canton7** [comment]
Right. You ran syncthing v0.12, which created a config file in `%LOCALAPPDATA%\Syncthing\config.xml`. This config file is in a format which v0.12 can read, but v0.11 can't.

You then installed SyncTrayzor. SyncTrayzor currently bundles syncthing v0.11. When you started SyncTrayzor, it ran syncthing v0.11, which looked in `%LOCALAPPDATA%\Syncthing\config.xml` for its config. It found a config file, but that config file can only be read by v0.12, and it fell over.

Take your v0.12 syncthing exe, and put it in `%APPDATA%\SyncTrayzor\syncthing.exe`, replacing the exe that's currently there. Run SyncTrayzor again, and all should be fine.

**Comment by markyuk** [comment]
You star :-)  Thank you so much.   I had read the other issue someone had raised about copying the syncthing over but instead of looking in %APPDATA% I had looked in the LOCAL, rather than ROAMING folder, seen no XML or EXE and stopped there.

That works perfectly!   Amazing stuff.

**Comment by canton7** [comment]
Yeah, I really need to move some stuff from `%APPDATA%` to `%LOCALAPPDATA%`: the split's not really ideal at the moment...
