### ISSUE TITLE
Suggestion: Restore window to size it was minimised and console colour

### ISSUE THREAD

**Issue by markyuk** [canton7/SyncTrayzor#171]
Is it possible that when the app is minimised, it can be restored to the same size and position?

And could I suggest two things for the console -

1. Set a background colour so it's easy to differentiate between the console and browser panel above?  (like dark grey or something).

2. Add a clear console option.

**Comment by markyuk** [comment]
Another suggestion to the console -

3. Allow the user to PAUSE the console - it's shooting past just now and I can't copy/see the messages clearly!

**Comment by canton7** [comment]
It is already restored to the same size and position after being minimized.

I guess more console controls would be nice. In the meantime, you can just ctrl-a, ctrl-c to copy the console, and paste it into a normal text editor for viewing at your leisure.

**Comment by markyuk** [comment]
Hmmm, maybe I wasn't clear - I want to resize and move the window and when I minimise and restore, the new size and position I set is restored.

I've just tried again here and when I minimise to tray, on restore, the window is back to the middle of the screen at a reduced, default size.

**Comment by canton7** [comment]
Yes, that should be the current behaviour. So something's bugged with your setup.

The window size and position are stored in SyncTrayzor's `config.xml`, in `%APPDATA%/SyncTrayzor`. Can you confirm whether or not they're being correctly written here?

**Comment by markyuk** [comment]
Hi there .... just checked this ... I'm afraid there's no WindowPlacement section in my config.xml

**Comment by canton7** [comment]
What the... Can you paste the entire contents of SyncTrayzor's config.xml? Let's make sure we've got the right file...

**Comment by markyuk** [comment]
Hehe, sure!

Here you go -

`<?xml version="1.0"?>
<Configuration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="5">
  <ShowTrayIconOnlyOnClose>false</ShowTrayIconOnlyOnClose>
  <MinimizeToTray>true</MinimizeToTray>
  <CloseToTray>true</CloseToTray>
  <ShowDeviceConnectivityBalloons>true</ShowDeviceConnectivityBalloons>
  <ShowSynchronizedBalloonEvenIfNothingDownloaded>false</ShowSynchronizedBalloonEvenIfNothingDownloaded>
  <SyncthingAddress>localhost:8384</SyncthingAddress>
  <StartSyncthingAutomatically>true</StartSyncthingAutomatically>
  <SyncthingApiKey>YAH0TDQQawYx1rpNBucgv9yi4q5YSsXyyTYxZ9Pj</SyncthingApiKey>
  <SyncthingCommandLineFlags />
  <SyncthingEnvironmentalVariables />
  <SyncthingUseCustomHome>false</SyncthingUseCustomHome>
  <SyncthingDenyUpgrade>false</SyncthingDenyUpgrade>
  <SyncthingPriorityLevel>Normal</SyncthingPriorityLevel>
  <Folders>
    <Folder>
      <ID>LogicSpot</ID>
      <IsWatched>true</IsWatched>
      <NotificationsEnabled>true</NotificationsEnabled>
    </Folder>
    <Folder>
      <ID>default</ID>
      <IsWatched>true</IsWatched>
      <NotificationsEnabled>true</NotificationsEnabled>
    </Folder>
  </Folders>
  <NotifyOfNewVersions>true</NotifyOfNewVersions>
  <ObfuscateDeviceIDs>true</ObfuscateDeviceIDs>
  <UseComputerCulture>true</UseComputerCulture>
  <SyncthingConsoleHeight>336</SyncthingConsoleHeight>
  <SyncthingWebBrowserZoomLevel>-0.4</SyncthingWebBrowserZoomLevel>
  <LastSeenInstallCount>0</LastSeenInstallCount>
  <SyncthingPath>%APPDATA%\SyncTrayzor\syncthing.exe</SyncthingPath>
  <SyncthingCustomHomePath>%LOCALAPPDATA%\SyncTrayzor\syncthing</SyncthingCustomHomePath>
  <DisableHardwareRendering>false</DisableHardwareRendering>
</Configuration>`

**Comment by canton7** [comment]
So, the call to the winapi's `GetWindowPlacement` function is failing in some way, but we're not currently logging this.

Would you be able to download a build from here https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.29.156/artifacts in about 5 minutes, and try again? SyncTrayzor will behave the same, but when minimize it to the tray it should log a message to its log file which looks something like `Call to SetWindowPlacement failed: <stack trace>`. Could you paste that in here?

**Comment by markyuk** [comment]
Hey hey .... hmm, so I downloaded and am running it here (not sure how to tell if it's the build you just gave me but I installed and ran the setup-64 from the artifacts) ....

The log file is up to date/to the second .... but there's no lines as you mention.

**Comment by canton7** [comment]
You can see the version in Help -> About. Are you definitely closing SyncTrayzor to the tray, rather than just minimizing it?

**Comment by markyuk** [comment]
Running 1.0.29

And yes, I am closing to the tray (I've been doing both as I've also got minimise to tray enabled) ... but just done close to tray a few times after resizing - still nothing in the log.

**Comment by canton7** [comment]
Ah, oops, Help -> About shows a truncated version. The full version is shown in the log when SyncTrayzor starts, e.g. `2015-11-12 09:20:33.3346 [Debug] SyncTrayzor.Bootstrapper: SyncTrazor version 1.0.29.156 (Amd64) started at C:\Program Files\SyncTrayzor\SyncTrayzor.exe`.

Right, new version with a ton more logging: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.29.157/artifacts. Please paste everything that appears in the log when you close it to the tray.

**Comment by markyuk** [comment]
OK, installed and lots more info in the log.

Should I send direct to you?  Is there nothing confidential there?

**Comment by canton7** [comment]
Sure, send direct if you want. My email's on my github profile page.

**Comment by canton7** [comment]
Aah bugger. Got it. Thanks for your help!

New build available here shortly: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.29.158/artifacts
