### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by HyperCriSiS** [canton7/SyncTrayzor#179]
Hi,

would it be possible that you integrate an automatic update process for SyncTrazor itself?
That would be really awesome. :)

Regards,
Hyper

**Comment by canton7** [comment]
The installed version has had an automatic upgrade for a long time now. The portable version is still lacking one (see #82), but it's a fair amount of work for a very small share of the userbase, so it has never seemed like the most important thing to work on...

**Comment by canton7** [comment]
Does that answer your question?

**Comment by HyperCriSiS** [comment]
Yes, thank you! So I just have to wait a bit =)
