### ISSUE TITLE
Error FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000

### ISSUE THREAD

**Issue by iav** [canton7/SyncTrayzor#180]
I have an error on start on 2 of my 4 windows computers.
Log:
[YP43D] 03:47:20 INFO: syncthing v0.11.26 "Aluminium Ant" (go1.4.2 windows-386 default) unknown-user@syncthing-builder 2015-10-02 06:08:07 UTC
[YP43D] 03:47:20 INFO: My ID: YP43DLP
[YP43D] 03:47:20 INFO: Archiving a copy of old config file format
[YP43D] 03:47:20 INFO: Database block cache capacity 16380 KiB
[YP43D] 03:47:21 OK: Ready to synchronize scan (read-write)
[YP43D] 03:47:21 INFO: Starting web GUI on https://127.0.0.1:8384/
[YP43D] 03:47:29 INFO: Completed initial scan (rw) of folder scan
[YP43D] 03:47:30 FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000

This is a new clean syncthing install, none methods like "restore old config" not works.
syncthing itself works fine.

**Comment by canton7** [comment]
You've got a config file that was written by Syncthing v0.12, and you're running Syncthing v0.11.

If you want to run Syncthing v0.12 (recommended): 1) Install the latest SyncTrayzor v1.0.31 (if you haven't already). 2) Delete `C:\Users\<You>\AppData\Roaming\SyncTrayzor\syncthing.exe`. 3) Start SyncTrayzor.

If you wan to run Syncthing v0.11 (not recommended), you'll need to restore the `config.xml` in `C:\Users\<You>\AppData\Local\Syncthing` to a version which was written by Syncthin v0.11.

**Comment by iav** [comment]
Wonderful!
Your solution work, my problem is gone!
Thank you!
