### ISSUE TITLE
Import existing syncthing configuration.

### ISSUE THREAD

**Issue by Zone22** [canton7/SyncTrayzor#182]
Expunged

**Comment by canton7** [comment]
The installed version (the one which most people use) will use Syncthing's existing config file and database in its existing location.

The portable version will want to use a location in `data/` by default, but you can change this by going to File -> Settings -> Syncthing  and checking Use Syncthing's default database location.

This is documented at https://github.com/canton7/SyncTrayzor#portable (although it's slightly out of date: the setting is not called "Use custom home directory or Syncthing" any longer)

**Comment by canton7** [comment]
I'm happy to add some more words to the README, but I'm not hugely convinced that anyone would read them :wink:

**Comment by Zone22** [comment]
Yes I am clearly 100% blind! Could you post a braille version? ;) 

I swear I did read it although obviously did not comprehend!

**Comment by canton7** [comment]
Added a few more works to the readme anyway :smile:
