### ISSUE TITLE
Checksum file typo

### ISSUE THREAD

**Issue by viharm** [canton7/SyncTrayzor#186]
Small typo, but thought I should point out.

The file `md5sum.txt.asc` in the release `Version 1.0.32` describes the hash as `SHA1` even though the actual checksums are MD5 and align with the filename.

**Comment by canton7** [comment]
That is added by pgp. It means that the hash used to sign the file is SHA1. It does not indicate that the contents of the file being signed have anything to do with SHA1.

**Comment by viharm** [comment]
Understood. Apologies for the false alarm. Thanks for taking the time respond, much appreciated.

**Comment by canton7** [comment]
No worries! It is confusing :smile:
