### ISSUE TITLE
UI (minor): allow resize+scroll for the "Settings" window

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#190]
The "settings" window size adjusts automatically depending on tab's content, which is great.
However, it is impossible to override this and re-size the window manually. Such behavior won't scale well if large number of folders used (and/or small-res display).

Here is the example of "Folders" tab with ~20 folders:
![image](https://cloud.githubusercontent.com/assets/11633330/12224258/c282c4da-b7f4-11e5-90cb-08e1f0190928.png)

Using many folders or/and just using low-resolution display will make part of the folder list go off screen.

Allowing user to re-size it and adding a scroll bar in such case will make huge number of folders still be accessible for configuration.

**Comment by canton7** [comment]
Oops, that screen *should* have a scroll bar on the folders list, but for someone reason it doesn't look like it's appearing. Maybe because the screen height is unconstrained it never sees the need to add it in...

**Comment by scienmind** [comment]
Actually it's my "oops". I was seeing the size approaching screen height with no option to shrink it, so I opened this issue...

Just tested it with low resolution, and scroll bar *does* appear if the list size is actually bigger then the  display resolution.

My apologies for interruption

**Comment by canton7** [comment]
Phew, glad to hear!
