### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by dionysius** [canton7/SyncTrayzor#196]
Hi

This is the 3rd Windows I set up synctrayzor. It happens on a specific folder "My Documents". I have no issues with "Desktop", "My Pictures" etc. Currently Win7, upgrade to 10 in Progress now.

I've by hand checked if I can detect any difference between in the Security tab of these folder preferences, but no luck, looks same with same permissions.

Synctrayzor crashes with exiting syncthing, on restart same error. Syncthing doesn't report any error in the log, it's just exiting when the error occurs. Able to remove the folder it by hand in the config files so synctrayzor and syncthing works again, but reproducable everytime i try it again.

http://pastebin.com/XArZMVTk

Any tips what's wrong with that folder?

**Comment by canton7** [comment]
Update to v1.1.1 - SyncTrayzor is tripping up because it's unable to search a special folder for conflict files.

**Comment by dionysius** [comment]
Hi canton

Sorry for my late reply. Thank you very much for the fast response. It indeed fixed the issue, but another small one showed up. I'll open another thread.

again, thanks :-*
