### ISSUE TITLE
conflict Resolver - Update/hide "info bar"

### ISSUE THREAD

**Issue by dsvf** [canton7/SyncTrayzor#197]
The yellow resolver bar showed "500 conflicted files". I started deleting some of the conflicts (externally, not with SyncTrayzor), and the number decreases practically real-time. Then, it got stuck at 305. clicking on "Resolve now" opens the Conflict resolver which promptly congratulates me on "No conflicts found".

I cannot dismiss the yellow bar. Rescanning the folder does nothing. Restarting SyncTrayzor does the job. This is no annoyance but worthy of mention.

**Comment by canton7** [comment]
Can you post your SyncTrayzor log file from around the point where you were resolving conflicts (and the bar stopped decrementing) please? 

The bar works by watching the filesystem for changes to files whose names contain `.sync-conflict` (it doesn't currently communicate with the conflict resolution dialog, although it probably should). Somehow it's stopped receiving notifications from the filesystem, and I'm hoping the log will tell us why.

**Comment by canton7** [comment]
Quite a lot of fixing has happened in v1.1.2 - please reopen this if you can still reproduce it in v1.1.2. Thanks!
