### ISSUE TITLE
Icon resolution issues

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#20]
As discussed in https://discourse.syncthing.net/t/synctrayzor-windows-host-for-syncthing-installer-auto-start-built-in-browser-tray-icon-folder-watcher-and-more/2011/49

User sees low resolution icon in taskbar. Turns into high resolution when icon is pinned. Research.

@d4k0 @Rewt0r: ping, in case you're interested.

**Comment by canton7** [comment]
Relevant? https://github.com/bliker/cmder/issues/154

**Comment by canton7** [comment]
Aha! I can repro if I pin and then unpin. Right!

**Comment by Rewt0r** [comment]
Correct, after pinning a simple right-click changes the icon. Stupid Windows ahahaha.

Would just removing the 16x16 icon be sufficient?

**Comment by canton7** [comment]
1) The guy on StackOverflow said that this caused Windows to manually donwsize the 32x32 icon, which looks works.
2) I use 'small icons' on my taskbar, which are 16x16

**Comment by canton7** [comment]
Going to try using another icon, and colouring each resolution differently so I can tell exactly what's being displayed when, if Windows is doing upsizing, etc.

**Comment by canton7** [comment]
Aaaaaah. Got it, I think. What a bugger.

The Assembly Icon had the full resolution set. The indow's (that is, physical window, not the OS) icon had only 16x16. Windows was using the window's icon when unpinned, and the assembly icon when pinnned. Remove the window icon, boom.

**Comment by Rewt0r** [comment]
Haha! Glad you found it

**Comment by d4k0** [comment]
Interesting. So WPF (that's what you are using, aren't you?) can pick the right size of the icon from the .ico file? With Windows Forms this doesn't seem to be possible (at least I haven't found a proper solution while I was working a bit on SyncthingTray), so one has to provide an additional .ico file for the system tray (otherwise Windows, for whatever reason, will pick a higher resolution of the icon which will then be downscaled to 16 x 16).

**Comment by canton7** [comment]
WPF doesn't actually have a native tray icon (one of its shortcomints). You can use the WinForms one, or you can use the third-party [WPF NotifyIcon](http://www.hardcodet.net/wpf-notifyicon), which is what I do.

I'm not sure whether WPF NotifyIcon will handle .ico files correctly. I've got 5 .icos which contain only 16x16, and which I use for the tray - the 4 rotations of the Syncthing icon, used for the 'syncing' animation - and the grey 'syncthing stopped' icon.

The window's Icon property has nothing to do with the tray icon in WPF.

**Comment by d4k0** [comment]
Ah, OK. Thanks for the explanation!
