### ISSUE TITLE
(1.1.1) Blank UI at synctrayzor start, refresh browser / restarting syncthing fixes it.

### ISSUE THREAD

**Issue by Nihim** [canton7/SyncTrayzor#201]
windows 7 64x portable 1.1.1

After I upgraded & started synctrayzor it showed no devices / folders and buttons were unresponsive. Clicking from the menu syncthing restart fixed it. As suggested in IRC, also refresh browser fixes.

Same behaviour happens every time synctrayzor is started.

If I choose open in external browser (firefox) it is unaffected.

Will try portable chrome as asked by canton7.

**Comment by canton7** [comment]
Error from go: `tls: client using inappropriate protocol fallback`. Error from JS: `Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR`.

Fails to load important JS files, and everything goes pear-shaped from there.

**Comment by canton7** [comment]
Suspecting an AV at this point - it's only the first few requests that fail, and only when `cefsharp.browersubprocess.exe` is newly started.

**Comment by Nihim** [comment]
Stopping "active shields" or excluding the synctrayzor directory from any scans doesn't help. As canton7 said on the initial run of synctrayzor it works fine, afterwards TLS warning appears.

AV: Avast 11.1.2245 (2016?)

**Comment by Nihim** [comment]
With 1.1.2 the problem is fixed? and UI is a lot snappier.
Initial run: fast and ok
Close and reopen window: fast and ok
restart synctrayzor and reopen window: fast and ok

Now if you didn't change something to do with the JS / TLS I have a theory though it's a bit ungrounded and far fetched so will tell you in IRC about it if you want :P

**Comment by canton7** [comment]
Nothing's changed in that area since way back in 1.0-land. I'll bug you on IRC :)

**Comment by canton7** [comment]
Turns out to be related to how long the Computer's been running.

Not sure exactly what's causing it, but pretty sure it's nothing I can fix. Closing :smile:

**Comment by canton7** [comment]
For the next release I'm no longer forcing Syncthing to use https, which means it should default to http. That should work around this issue.
