### ISSUE TITLE
Suggestion: Rename "Choose" to "Keep this version"

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#204]
A small suggestion regarding "Conflict Resolver" UI:

Rename "Choose" button to something more descriptive of an action to be performed.
Some people get confused whether "choose" button will select the files to be deleted/sent to recycle bin, or the ones that will be retained.
So renaming it to "Keep this file" or something similar will clarify it.

**Comment by canton7** [comment]
Point taken. I'm not sure the "keep this version" is any more descriptive though: to me it implies that you can keep multiple versions. I'll have a think...

**Comment by scienmind** [comment]
:+1:

**Comment by canton7** [comment]
I'm thinking a line of text in that bottom box saying something like "Please choose the version of the file you want to keep", and leave the buttons saying "Choose" might be best? That way we don't repeat the same thing over and over, the text "Choose" matches up, and they get a proper explanation?

**Comment by scienmind** [comment]
Yes, I think it is good enough.

But I think it's better to put the "please choose.." above the versions:
![image](https://cloud.githubusercontent.com/assets/11633330/12322921/f10d10f8-babf-11e5-9aa3-b876f74392ef.png)

**Comment by canton7** [comment]
Yeah, that's what I was imaginging
