### ISSUE TITLE
FR: User friendly file transfer log

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#205]
Right now we have a very convenient way to see few of "recent transfers" via the tray icon. 

However it would be useful to be able to review the full list of file transactions (and deletes) for a given time frame. (i.e. via a new menu entry, which would display a window with filterable/searchable list)

**Comment by canton7** [comment]
You're talking about completed transfers, as opposed to pending ones? Do you imagine this persisting through restarts of SyncTrayzor?

**Comment by scienmind** [comment]
Yes, I'm talking about "transfer history" (including deletes).

And yes, it should "survive restarts". I think logging transfers to a local file/db and presenting UI table to see it from SyncTrayzon will do the job. 
Ability to sort & filter & search the table can be a nice bonus, same for kind of "show in folder" link for each entry.
(I'm not sure what i think about just keeping it in a log-like txt file (in addition to showing it in UI): good - can be examined by external tools/editors, bad - maybe harder to implement the "bonus stuff")


Log details that I can think of as useful: `filename, modification time, transfer time, size, remote source device/s name`

Few examples on where it is useful:
* Right now, if a file is changed and synced, i can see it via "tray icon click" + "tray notification", but if a huge update occurred, notification pops saying something like "1300 files updated", but there is no (easy) way to quickly review the changes.
* Being able to periodically review sync history on a device. 
Useful in general, and especially for "not frequently operated device", i.e.: a device that is connected to the sync cluster permanently, but is not being operated constantly (kinda "remote file server" that sync to himself lots of stuff, but not constantly operated directly by user).

(no need to be able to access device's A log from device B, just see the A's log on A)

**Comment by canton7** [comment]
That's a pretty hefty chunk of work. I'll put it on the back burner for now.

**Comment by scienmind** [comment]
Sure, it's a "very very nice to have" one, but nothing urgent :)

**Comment by scienmind** [comment]
Maybe in the mean time it will possible/easy to create an option to just log file transfers to the txt file?

**Comment by canton7** [comment]
Yeah, that would be pretty easy to put in.

**Comment by canton7** [comment]
Cool, that's in.

It's in `logs\DownloadLog.csv`.

**Comment by scienmind** [comment]
Cool, looking forward to the new release :-)

**Comment by scienmind** [comment]
Hi
Is it possible to log outgoing file transfers (uploads) as well?

i.e.: system A just updated a file, and clients B+C pulled this update
as of current behavior, it will be logged on clients B and C, but not on source client A
(same goes for tray icon info as well, not just the csv log)

P.S. i can refile it as a new issue if you prefer

**Comment by canton7** [comment]
No: that information isn't provided by Syncthing sadly

**Comment by scienmind** [comment]
Would you find it reasonable to file such issue for syncthing then? Or is there some substantial reason to avoid it?

**Comment by canton7** [comment]
Syncthing simply doesn't know.

There was a mention by calmh recently about something to do with this: can't remember whether it was on the forum or GitHub.
