### ISSUE TITLE
delete: mkdir \\?\E:\GameBackups\.stversions: Access is denied.

### ISSUE THREAD

**Issue by Gibbz** [canton7/SyncTrayzor#206]
Im getting this error since upgrading to 1.1.2
I have delete the .stversions folder and it still giving me this same error....

Any idea how to fix this?

**Comment by canton7** [comment]
That's a Synthing problem - we're just reporting the error.

**Comment by canton7** [comment]
User opened syncthing/syncthing#2714. Closing here
