### ISSUE TITLE
Avast Anti Virus alarm

### ISSUE THREAD

**Issue by theincogtion** [canton7/SyncTrayzor#207]
![image](https://cloud.githubusercontent.com/assets/10852327/12329548/204b733e-bae1-11e5-94fc-3332c44023c6.png)

![image](https://cloud.githubusercontent.com/assets/10852327/12329562/2c5da962-bae1-11e5-80a4-564618f2294d.png)

![image](https://cloud.githubusercontent.com/assets/10852327/12329632/81151b20-bae1-11e5-826c-c26dcfb0d8da.png)

![image](https://cloud.githubusercontent.com/assets/10852327/12329646/8ca84d7c-bae1-11e5-91a1-0ce9beece6a2.png)

Any additional infos required?
OS is Win 8.1 x64

update
I sended the file to the AV Labs as false positive.

**Comment by canton7** [comment]
The full text of that "Fehler!" dialog would be helpful - it's been cut off by the screenshot.

Looks like avast is stopping SyncTrayzor from launching other processes, which is going to screw up anything to do with opening a web browser, opening a file or folder in explorer, and the entirety of the auto-upgrade system. There's nothing I can do: if you want to use these bits of functionality, you'll have to tell Avast to behave.

**Comment by theincogtion** [comment]
Hi canton7 you are right, not your fault, I already send the file to avast and unblocked it. 
This happend then I clicked on "open folder" in the conflict solver.

But after I removed the file from the virus contaoner it still has the same problem:



Version: 1.1.2.247; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Datei nicht finden
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Stylet.Xaml.ActionBase.InvokeTargetMethod(Object[] parameters) in c:\projects\stylet\Stylet\Xaml\ActionBase.cs:Zeile 201.
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Does `C:\Program Files\SyncTrayzor\ProcessRunner.exe` exist, or did Avast delete it?

**Comment by theincogtion** [comment]
Now it is working again, Avast created the file ProcessRunner.exe.old instead of ProcessRunner.exe
I renamed it and everything is fine.

**Comment by canton7** [comment]
Avast used to be good, but it seems to have gotten a lot worse over time...

Issue solved?

**Comment by theincogtion** [comment]
https://www.virustotal.com/de/file/1c531acd5fae22c228eb925929ee94b41954cc9041dce91458617f4e4ec7eda8/analysis/1452788376/

Solved :)

**Comment by canton7** [comment]
Cool!
