### ISSUE TITLE
Request: Ability to disable "File updated"-Notifications

### ISSUE THREAD

**Issue by JaCoB1123** [canton7/SyncTrayzor#209]
Would ideally be configurable per Repository.

Use case:
I have a Repository synced, that is periodically updated via a cronjob. All other computers notify me of the change (added file). For me, this is redundant since I know that this job runs and adds a file each time.

**Comment by canton7** [comment]
There's an option in the settings. 'Folders' tab -> uncheck 'Notifications'.

**Comment by JaCoB1123** [comment]
Damn, how could I not see that.
Thanks. :)

**Comment by canton7** [comment]
Yeah, it's annoying that it's separate from the rest of the notification-related settings (which are on the SyncTrayzor tab), but the settings are per-folder and need to be with the other per-folder stuff... I might add a note to the SyncTrayzor tab saying "more stuff over there -->".

**Comment by JaCoB1123** [comment]
Yepp, that would be helpful.
I disabled the Device-Notifications first and looked for more settings on the same tab.
I actually checked the folders tab as well but didn't bother to read the column-headers :smile:
