### ISSUE TITLE
When installing new update: access denied writing to synctrayzor

### ISSUE THREAD

**Issue by jaredthirsk** [canton7/SyncTrayzor#21]
Running 1.0.6, I followed the prompt to download 1.0.7. I ran the installer but got an "Access is denied" error: Abort Retry Ignore. As I guessed, I tried exiting Synctrayzor from the tray icon and hitting retry, and it worked.  Novice users may be less likely to be flustered if they are presented with an option like  "Synctrayzor must close to continue upgrading.  Do you want to close it now?" -- preferably before the upgrade starts, so there isn't a half-upgraded installation if the user says no.  Or it could automatically close.

**Comment by canton7** [comment]
Fair point. It's annoying that InnoSetup can't automatically close SyncTrayzor - not sure what it's doing wrong. I think convincing InnoSetup to successfully close SyncTrayzor is the best approach: just because the user's visited the release page, doesn't mean they're going to download and run the installer straight away.

**Comment by canton7** [comment]
`taskkill /f /t /im SyncTrayzor.exe` seems to work, even if it's a bit evil

**Comment by kreischweide** [comment]
Not sure if /f should be used in this context. taskkill sends a proper WM_CLOSE event to the GUI application to give it time to close gracefully (same as windows shutdown). Maybe I'm wrong.

**Comment by canton7** [comment]
First attempt: nothing happens

```
C:\Users\ATM1>taskkill /t /im SyncTrayzor.exe
SUCCESS: Sent termination signal to process with PID 12984, child of PID 2828.
ERROR: The process with PID 8792 (child process of PID 2828) could not be termin
ated.
Reason: This process can only be terminated forcefully (with /F option).
ERROR: The process with PID 13812 (child process of PID 2828) could not be termi
nated.
Reason: This process can only be terminated forcefully (with /F option).
ERROR: The process with PID 2828 (child process of PID 6004) could not be termin
ated.
Reason: One or more child processes of this process were still running.
```

Second attempt: SyncTrayzor closes to the tray, and stays there.
```
C:\Users\ATM1>taskkill /im SyncTrayzor.exe
SUCCESS: Sent termination signal to the process "SyncTrayzor.exe" with PID 2828.
```

**Comment by kreischweide** [comment]
The sub-processes seem to prevent a proper shutdown. Killing the syncthing processes leaves only the CefSharp.BrowserSubprocess.exe left. It gets the event forwarded, but chooses not to react on it.

**Comment by canton7** [comment]
Presumably that's also the reason why InnoSetup is failing

**Comment by canton7** [comment]
Right, I've gone with the hacky, nasty approach.
