### ISSUE TITLE
Asked to report after update from 1.1.2 to 1.1.3

### ISSUE THREAD

**Issue by Jelmerro** [canton7/SyncTrayzor#212]
[log.txt](https://github.com/canton7/SyncTrayzor/files/104930/log.txt)
Not sure if it's all that useful

**Comment by canton7** [comment]
Dup of #210.

**Comment by Jelmerro** [comment]
Might want to change the error message in synctrayzor ;)

**Comment by canton7** [comment]
> Might want to change the error message in synctrayzor ;)

Why? Didn't it give you the generic "something bad happened" page with a stack trace?

**Comment by Jelmerro** [comment]
It asked me to open a new issue, which is what I did, but that's not always needed

**Comment by canton7** [comment]
Opening a new issue is fine - I'll mark it as a dup if necessary. I'd rather that than people jumping on a potentially unrelated issue.

Apologies if I sounded a bit terse - trying to get to the bottom of this as well as responding on GitHub :smile:

**Comment by canton7** [comment]
Got it. There will be a build here in about 10 minutes which should fix it. Mind trying it?

https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.3.284/artifacts
