### ISSUE TITLE
Make file history logging optional

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#214]
File log seems to be working fine since 1.1.3 :+1: 

However, while I appreciate this functionality a lot, some users would prefer to keep their file history un-logged, so I think that such detailed file history logging should be optional.
(sorry for not pointing it out in the first place).

Something like that (not sure about the wording):
![image](https://cloud.githubusercontent.com/assets/11633330/12584256/4512d654-c44f-11e5-9761-4cd0e952685a.png)

**Comment by canton7** [comment]
It's already part of the main log, so there isn't a "keep this stuff private" argument here. Is there another argument to not create this log file?

**Comment by scienmind** [comment]
Hmm, I didn't know detailed file info was always logged to SyncTrayzor.log
"keep stuff private" is the only argument.

But I think overall, the default SyncTrayzor log is pretty extensive, and is not necessary for the "average user". 
Maybe it would be a good idea to trim it to a minimum. Leaving an option to enable "extra logging" for debugging purposes, "file transfer logging" for the .csv file, etc. (just as is goes now with syncthing stuff).

**Comment by canton7** [comment]
Yeah - high logging was absolutely vital during SyncTrayzor's early days, as it's necessary to understand what caused a problem when you're interfacing with something as complex and unpredictable as Syncthing. I keep considering toning it down, but then an issue crops up that the detailed logging is required for, so I leave it :stuck_out_tongue_closed_eyes:

**Comment by scienmind** [comment]
Makes sense. 
ST is still in "kinda-alfa-though-stable" phase, introducing breaking changes here and there...

But I think it definitely should be addressed once Syncthing reaches 1.0

**Comment by canton7** [comment]
Yeah, agreed - for the majority of cases we spit out far more than is necessary. Toning it down would require a fairly thorough audit to decide what to log and what not to log as well, which is time I haven't had so far.

**Comment by canton7** [comment]
Closing as this probably won't happen

**Comment by scienmind** [comment]
:cry: 

But seriously - for now it can be closed, but once ST reaches 1.0, it'd be a point to start toning down and making stuff optional both for ST logs and SyncTrayzors too.

**Comment by canton7** [comment]
It probably won't happen because there's no point: we log everything, and so there's nothing to be gained from turning off this particular log.

**Comment by scienmind** [comment]
> there's no point: we log everything, and so there's nothing to be gained from turning off this particular log...

as long as ST logs it as well, I agree. And such cleanup is going to be tedious, for sure...

just that's, in general, there's a difference between the SW being aware about files flying around and having a non-optional file on the disk documenting all this "awareness" (I'm not talking about synctrayzor in particular...)

**Comment by canton7** [comment]
Syncthing is *gaining* a full file operation log...
