### ISSUE TITLE
Upgrade of portable version fails if %TEMP% and destination not on same volume

### ISSUE THREAD

**Issue by capi** [canton7/SyncTrayzor#218]
When auto-updating the portable version, an `IOException` occured: `Source and destination path must have identical roots. Move will not work across volumes.`

![synctrayzor_update_failed](https://cloud.githubusercontent.com/assets/254852/12592142/739821a2-c46b-11e5-9a33-3f1febb207fb.png)

**Comment by canton7** [comment]
Thanks! Grrr .NET...

**Comment by canton7** [comment]
Righty, I've disabled automatic updates for portable users. I don't fancy pushing out another release at such short notice.

`PortableInstaller.exe` is packaged with the downloaded version, so portable users will be able to automatically upgrade to the next version.
