### ISSUE TITLE
Rename SyncThing to Syncthing

### ISSUE THREAD

**Issue by Rewt0r** [canton7/SyncTrayzor#22]
This is more of a pet hate of mine and is very trivial... Could we use the actual casing used by Syncthing rather than SyncThing?

**Comment by canton7** [comment]
I think we caught all of these in the recent internationalization drive - they should already be fixed in the next release.

**Comment by Rewt0r** [comment]
Ta! Shall close this for now then :smile:

**Comment by canton7** [comment]
Let me know if we missed any. I had a grep through the resources file just now and couldn't see any.

**Comment by Rewt0r** [comment]
Well I found one in my fork, I'll submit a PR since I already changed it.

**Comment by canton7** [comment]
Ah oops. Not a resource, so I would have missed it. By all means, I'm happy to change.

**Comment by canton7** [comment]
I would change all the internal SyncThings to Syncthings, but a lot of that means changing just the case of a file, and that is very bad news for windows machines.
