### ISSUE TITLE
While running SyncTrayzor, local HTTP requests to the REST API fail

### ISSUE THREAD

**Issue by fiatjaf** [canton7/SyncTrayzor#222]
I wrote a Node.js script that changes Syncthing config using the REST API, called locally. It works while Syncthing is running without SyncTrayzor, and GET requests always work, but when SyncTrayzor is running the POST requests to `/config` fail with a 403: "CSRF error".

I don't know if this is a SyncTrayzor or Syncthing problem, but there is [this issue](https://github.com/syncthing/syncthing/issues/720) about a CSRF problem with two Syncthing web GUI tabs open.

I'm using SyncTrayzor 1.0.32.

**Comment by canton7** [comment]
Any node.js scripts you use shouldn't be relying on the CSRF stuff: use the header `X-API-Key` and set the value to the API key.

SyncTrayzor overrides Syncthing's API key: ignore the API key in Syncthing's Config screen and instead copy the one from SyncTrayzor's Settings -> Syncthing tab.

Also your SyncTrayzor version is pretty out of date :wink:

**Comment by fiatjaf** [comment]
> SyncTrayzor overrides Syncthing's API key: ignore the API key in Syncthing's Config screen and instead copy the one from SyncTrayzor's Settings -> Syncthing tab.

I'm confused. What do you mean? I should copy that? Does SyncTrayzor modifies how Syncthing works? How?

So anyone using SyncTrayzor must get the key from that screen so they can use the Syncthing API? Why?

**Comment by fiatjaf** [comment]
Also, I'm using [this library](https://github.com/JodusNodus/node-syncthing) which is setting `X-API-Key`. I don't understand why the CSRF error also.

**Comment by canton7** [comment]
What API key is it using? Using the wrong key has the same effect as not using a key at all. 

If you want to use Syncthing's API, you need to provide an API key. The API key is configured in Syncthing's settings, or it can be overridden by passing a command-line flag to Syncthing when you start it. 

SyncTrayzor uses Syncthing's API, and so needs to provide an API key. It does this by choosing a key, and passing it to Syncthing as a command-line flag when it starts Syncthing, thus overriding the API key in Syncthing's settings. 

You can view, and change, the API key which SyncTrayzor uses in SyncTrayzor's settings menu, as I described. 

If you want to let SyncTrayzor start Syncthing, and talk to Syncthing's API, you need to copy the API key in SyncTrayzor's settings, and use it when taking to Syncthing.

**Comment by fiatjaf** [comment]
I get it. Thank you. That is what is happening. SyncTrayzor is overriding Syncthings API key.

Does SyncTrayzor really needs that? I mean, perhaps SyncTrayzor could read the default Syncthing API key from `config.xml` and so it wouldn't break other apps that used the default Syncthing API key. My script, for example, works whenever Syncthing is ran normally, but fails when it is started by SyncTrayzor.

**Comment by canton7** [comment]
SyncTrayzor does not know about the format of `config.xml`, nor should it. It would also be very hard to start Syncthing for the first time: start Syncthing, wait until it creates `config.xml`, read it, then try and talk to Syncthing.

I have a PR in progress to allow Syncthing to accept both the API key from its configuration *and* the API key specified on the command line, if any: syncthing/syncthing#2748.

**Comment by fiatjaf** [comment]
You're right. Thank you for the PR.
