### ISSUE TITLE
Kobo - Cannot start GUI

### ISSUE THREAD

**Issue by cascafico** [canton7/SyncTrayzor#225]
Hello!

I downloaded and copied syncthing-linux-arm-v0.12.16 on Kobo ereader. 
Once launched:

> [monitor] 18:34:22 INFO: Starting syncthing
> [start] 18:34:22 INFO: Generating ECDSA key and certificate for syncthing...
> [KGBNT] 18:34:23 INFO: syncthing v0.12.16 "Beryllium Bedbug" (go1.5.3 linux-arm) unknown-user@build2.syncthing.net 2016-01-24 07:09:28 UTC
> [KGBNT] 18:34:23 INFO: My ID: KGBNT5F-5JKQZIZ-U6V2NCS-HO2I3W4-EUYF6MY-DVYOAXS-J3J2FK3-G6HJAQ5
> [KGBNT] 18:34:24 INFO: Single thread hash performance is ~7.8 MB/s
> [KGBNT] 18:34:24 INFO: Error loading config file; using defaults for now
> [KGBNT] 18:34:24 INFO: Default folder created and/or linked to new config
> [KGBNT] 18:34:24 FATAL: get free port (GUI): listen tcp 127.0.0.1:0: bind: cannot assign requested address
> [monitor] 18:34:24 INFO: Syncthing exited: exit status 1
> 

after other 3 attempts, synching informs: "not retrying further"

**Comment by canton7** [comment]
Does this have anything to do with SyncTrayzor? It looks like you downloaded a linux build of Syncthing. SyncTrayzor is a Windows host for Syncthing, see https://github.com/canton7/SyncTrayzor.

**Comment by cascafico** [comment]
well, I downloaded what's supposed

**Comment by cascafico** [comment]
Well, I downloaded a build [1] supposed for Kobo:

kobo> uname -a
Linux (none) 2.6.35.3-850-gbc67621+ #617 PREEMPT Mon Apr 22 11:07:47 CST 2013 armv7l GNU/Linux

[1] https://github.com/syncthing/syncthing/releases/download/v0.12.16/syncthing-linux-arm-v0.12.16.tar.gz

**Comment by canton7** [comment]
Sorry, but you're opened this issue in the repository for SyncTrayzor. SyncTrayzor is *not* Syncthing: it is a Windows wrapper for Syncthing that has nothing to do with either Linux or Kobo.

Maybe you meant to open an issue in Syncthing's issue tracker? https://github.com/syncthing/syncthing
