### ISSUE TITLE
Crash during large sync

### ISSUE THREAD

**Issue by kylegordon** [canton7/SyncTrayzor#227]
This may be a bit vague, but whilst importing a bunch of large directories with thousands of files on a Linux Syncthing machine, SyncTrayzor repeatedly crashed on a Windows machine that was receiving the data.

Whilst I have VS2015 installed, I'm no programmer. This is what the JIT debugger came out with, if it helps...

System.ArgumentNullException was unhandled
Message: An unhandled exception of type 'System.ArgumentNullException' occurred in Pri.LongPath.dll
Additional information: Value cannot be null.

**Comment by canton7** [comment]
Oh fun!

Mind sending me your log? You'll find it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs\SyncTrayzor.log` for the installed version, or `logs\SyncTrayzor.log` for the portable version.

If there's sensitive info in there, feel free to email it to me: my email's on my GitHub profile page.

**Comment by kylegordon** [comment]
Yup! :-) That's it emailed over to you. SyncThing stays running, doing the job nicely - it's just SyncTrayzor that exits for some reason.

**Comment by canton7** [comment]
Ah. Completely coincidentally, I think you've just encountered a bug I've just fixed.

Can you try this build and see if it fixes your issue? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.6.306/artifacts

Thanks!

**Comment by canton7** [comment]
Ah no, not quite the whole story. I'll look into this over the weekend. Thanks!

**Comment by canton7** [comment]
Turned out one of the libraries I use had changed how it handles some classes of input.

https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.6.307/artifacts should fix it, and will be built in about 10 mins. Mind trying it and seeing if it fixes the issue for you? Thanks!

**Comment by kylegordon** [comment]
Yup, looks good. Seems stable :+1:

**Comment by canton7** [comment]
Thanks for confirming
