### ISSUE TITLE
inotify on remote smb shares?

### ISSUE THREAD

**Issue by entonio** [canton7/SyncTrayzor#229]
I'm sorry if this more of a request for information than an actual issue.
I couldn't find thorough documentation on SyncTrayzor and inotify. That's probably my fault.
What I'd like to know is:
- by 'watching' folders, may/should one reduce the rescan interval to 0?
- is inotify effective when the watched folder is `\\someserver\someshare`?
- if `\\someserver\someshare` temporarily disappears, syncthing deals with that via the next rescan. By setting ti to 0, we'll be stuck with a 'stopped' folder (afaict). Can SyncTrayzor do something about that, automatically?

**Comment by canton7** [comment]
1. I'd tend to reduce it to something infrequent. Filesystem watchers are not guaranteed to pick up file changes: many file changes in a short space of time can result in notifications getting lost, for example.
2. The filesystem watcher ultimately uses [`ReadDirectoryChangesW`](https://msdn.microsoft.com/en-us/library/aa365465.aspx). The docs there claim that various variants of SMB are supported, but I'd test it before relying on it :wink: 
3. SyncTrayzor's handling of absent directories is separate to Syncthing's: SyncTrayzor check to see whether the directory exists every 3 seconds and will re-establish the watcher if it does. In theory, then, a file change after the folder has reappeared will trigger a rescan request to Syncthing, which will rediscover the folder (but I've never tested it). Changes made between the folder disappearing and it reappearing won't cause a rescan.

**Comment by canton7** [comment]
Closing as no response

**Comment by entonio** [comment]
Sorry, I thought I'd replied to this. As per (1) it's not possible to disable rescanning, so the rest of the issues are a bit moot. My experience since has been that:
- for local non-crucial folders, it's reasonable to set the interval to a large value and let the watcher trigger the rescans
- remote locations should probably not rely on the watcher, though it will eventually do its job
- important locations might as well have whatever interval is required and as such may not need a watcher
That's just my opinion.

**Comment by canton7** [comment]
> As per (1) it's not possible to disable rescanning

Sure it's possible. I just wouldn't recommend it :smile:
