### ISSUE TITLE
How should discovery take?

### ISSUE THREAD

**Issue by OIWitteveen** [canton7/SyncTrayzor#23]
Hi, i installed Synctrayzor yesterday and added a device. But neither SyncTrayzor or the new devive shows that a a device is trying to sync a new folder. I tried Host  > Android device and Host > Raspberry Pi.

Both RPi en Android don't notice a difference.

I also tried the other way around adding a the "host" on Android and RPi.

I installed synctrayzor using the windows x64 installer to default location.
I am running Windows 8.1 x64.

**Comment by canton7** [comment]
Hi,

SyncTrayzor is a wrapper around [Syncthing](http://github.com/syncthing/syncthing). Please either [open an issue with Syncthing](http://github.com/syncthing/syncthing/issues) or [post on their forums](https://discourse.syncthing.net/). I'll make this more clear on the README.

Thanks!

**Comment by OIWitteveen** [comment]
Will do!
