### ISSUE TITLE
System.ArgumentNullException (Value cannot be null)

### ISSUE THREAD

**Issue by dsvf** [canton7/SyncTrayzor#230]
2016-02-08 14:21:26.9720 #5872 [Error] SyncTrayzor.Bootstrapper: An unhandled AppDomain exception occurred. Terminating: True System.ArgumentNullException Der Wert darf nicht NULL sein.
    Parametername: path System.String NormalizeLongPath(System.String, System.String)
    bei Pri.LongPath.Path.NormalizeLongPath(String path, String parameterName)
    bei SyncTrayzor.Services.FileWatcher.OnRenamed(Object source, RenamedEventArgs e) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FileWatcher.cs:Zeile 185.
    bei System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
    bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP) System.ArgumentNullException: Der Wert darf nicht NULL sein.
    Parametername: path
    bei Pri.LongPath.Path.NormalizeLongPath(String path, String parameterName)
    bei SyncTrayzor.Services.FileWatcher.OnRenamed(Object source, RenamedEventArgs e) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FileWatcher.cs:Zeile 185.
    bei System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
    bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

SyncTrayzor 1.1.6 x64 portable

After the restart, the update prompt came, so this may be fixed already. Feel free to close/delete this in this case.

**Comment by dsvf** [comment]
Oh, it occurred twice so far, restarting SyncTrayzor (and killing/restarting Syncthing) worked fine.

**Comment by canton7** [comment]
Dup of #227, fixed in v1.1.7 (released earlier today).

**Comment by canton7** [comment]
> Oh, it occurred twice so far

Have you seen it occur in v1.1.7?

**Comment by dsvf** [comment]
No, still need to upgrade.

**Comment by canton7** [comment]
Phew! Was worried I haven't managed to fix it there.

Yep, upgrading should sort it out.
