### ISSUE TITLE
Portable install upgrades not working

### ISSUE THREAD

**Issue by manekineko2** [canton7/SyncTrayzor#232]
When I click Install Now, it pops up what looks like a command prompt window.

The title is the path to my temp directory Temp\SyncTrayzor\PortableInstaller.exe

The content is the following message: "You should not invoke this executable directly. It is used as part of the automatic upgrade process for portable installations."

I'm running Windows 10 x64.

**Comment by canton7** [comment]
It's because you have a space in the path where the portable installation is located. I should be handling this, but something's getting lost along the way... Let me investigate.

**Comment by canton7** [comment]
This will be fixed in the next release (1.1.8), although the upgrade from 1.1.7 to 1.1.8 won't be fixed, only the upgrade from 1.1.8 to 1.1.9 will work.
