### ISSUE TITLE
If auto-updating fails, prompt for manual upgrade

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#236]
The auto-update process is pretty robust, but it can technically fail and will fail silently without alerting the user.

If this happens, prompt the user to manually upgrade: better than nothing.

**Comment by gitmeister** [comment]
Don't know if this is related by I allowed Syncthing to upgrade to 0.12.19 and somehow SyncTrayzor failed every time to start it. If I started Syncthing on it's own it worked fine. Removed SyncTrayzor and re-installed and now it works great with the packaged Syncthing 0.12.17. I guess we should always disable auto-update of Syncthing?

**Comment by canton7** [comment]
> somehow SyncTrayzor failed every time to start it

Details? Please open a new issue, including detail on what exactly happened. Was there a crash? If so, what's the crash message? 

Syncthing 0.12.19 works fine with SyncTrayzor, so something else is going on.

> I guess we should always disable auto-update of Syncthing?

We explicitly allow Syncthing to auto-upgrade - it means I don't have to release every week to match Syncthing's release schedule.

**Comment by canton7** [comment]
Handled by #302, I think, n ow
