### ISSUE TITLE
Settings screen - needs scroll bars

### ISSUE THREAD

**Issue by lsd87** [canton7/SyncTrayzor#238]
Have 1.17 installed on a laptop, screen resolution 1366*768 (Recommended) and when selecting the settings screen I cannot see the lower part of the screen (Start on login options)

Problem maybe due to sometimes I connect the laptop to another screen, this is the primary screen - when this is connected I can see the whole settings window. Its only when the external screen is removed that I don't get the full screen.

Laptop running Windows 7

Screen dump attached
![screen](https://cloud.githubusercontent.com/assets/17533711/13381937/cfb903c2-de68-11e5-807d-a286cc649abd.png)
Leigh

**Comment by canton7** [comment]
Weird, I use the same resolution and there's room to spare. What's your DPI set to? 

I'll see what I can do anyway. I've been putting it off before as it's quite a bit harder than it looks!

**Comment by lsd87** [comment]
Found the problem, got text size set to 125% (Medium) which sets the DPI to 120
Setting back to 100% (Std) with a 96 DPI, the full screen is show.
Enlarging the text, its a small screen on this laptop, there is a warning about some items not fitting - I  set it a long time ago.
Most people this would not be a problem as they would probably leave the text size set at 100%
So not a major problem and a simple temp fix to get around.

Leigh

**Comment by canton7** [comment]
Cool, that explains why it was so large at your resolution.

I'll look at making it scroll anyway.
