### ISSUE TITLE
Synctrayzor crash on Windows 10 Preview 14279.1000

### ISSUE THREAD

**Issue by Photographix** [canton7/SyncTrayzor#240]
Crash after Update to new Winows Build.
[SyncTrayzor.log.txt](https://github.com/canton7/SyncTrayzor/files/160290/SyncTrayzor.log.txt)

**Comment by canton7** [comment]
Looks like a backwards-incompatible change in .NET, perhaps. I'm on holiday at the moment: I'll look into it when I get back.

**Comment by canton7** [comment]
What .NET version are you running? (SyncTrayzor should log that information on startup, but it looks like it's crashing before it gets to that point).

**Comment by Photographix** [comment]
Output Attached.

[NetOut.txt](https://github.com/canton7/SyncTrayzor/files/160511/NetOut.txt)

**Comment by canton7** [comment]
What tool did you use to generate that `NetOut.txt`?

**Comment by canton7** [comment]
Mind trying this build, and seeing what log output it produces? It should log exactly the .NET framework version it's running on. https://ci.appveyor.com/project/canton7/synctrayzor/build/artifacts

**Comment by Photographix** [comment]
Tool from [here](http://hannes-schurig.de/14/06/2010/5-wege-die-installierte-net-framework-version-herauszufinden/). New Build crash bevor display .Net version.
[Uploading SyncTrayzor.log.txt…]()

**Comment by Photographix** [comment]
sorry

**Comment by canton7** [comment]
Can you post the log from that build I linked to anyway, please?

The output from that tool that you posted is confusing - it appears to just be listing some DLLs and their associated versions, rather than .NET versions.

**Comment by Photographix** [comment]
Log (the same) and Screenshot attached. [SyncTrayzor.log.txt](https://github.com/canton7/SyncTrayzor/files/164886/SyncTrayzor.log.txt)
![2016-03-09 10_59_45-synctrayzor crash on windows 10 preview 14279 1000 issue 240 canton7_synctr](https://cloud.githubusercontent.com/assets/16647382/13631655/1f1d601e-e5e6-11e5-9751-a4d37425fb77.png)

**Comment by canton7** [comment]
It did log it:

> 2016-03-09 10:58:26.6185 #10428 [Debug] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.7.321 (Amd64) started at C:\Program Files\SyncTrayzor\SyncTrayzor.exe (.NET version: 4.5.2 or later (460267))

**Comment by Photographix** [comment]
ah ok

**Comment by canton7** [comment]
There are no docs which mention that version, so I'm not sure how to get my hands on it... Looks like I'll have to open a bug with MS.

**Comment by canton7** [comment]
Opened an issue with MS [here](https://connect.microsoft.com/VisualStudio/feedback/details/2455692/system-notsupportedexception-unbekanntes-modifierkeys-element-strg-when-loading-wpf-application-on-net-460267).

**Comment by Photographix** [comment]
thanks

**Comment by Photographix** [comment]
Synctrayzor working again in the current preview build Windows10 - 14295.1000 
no crash
Ticket can close

**Comment by canton7** [comment]
Aha cool, thanks for updating. Someone on the ticket I opened with Microsoft said that running the application in the English locale might also work, which would invoked editing SyncTrayzor's config.xml, but if it's working again then no need!
