### ISSUE TITLE
No interaction possible using touch on Windows 8.1

### ISSUE THREAD

**Issue by dsvf** [canton7/SyncTrayzor#241]
SyncTrayzor on Windows 8.1 Pro on a Windows tablet.

When using the touchscreen, I can not interact with any of the elements of the Syncthing UI (like "Rescan All", "Add Folder" etc..). Scrolling works, as well as all SyncTrayzor options ("File"/"Syncthing"/"View"/"Help") and the Console options ("Pause"/"Clear"/"Settings").
When i touch "Add Folder", the button is highlighted but no action occurs. Toggling HW rendering makes no difference.

Everything works fine when using a mouse. I can control all elements with touch in the external Interface (Firefox and IE11).

**Comment by canton7** [comment]
So it's the embedded browser (Cef / CefSharp) which is giving you issues...

Mind downloading the Windows 64-bit "Test App" for "Branch 2526" from here: https://cefbuilds.com? If that also doesn't work with the touch screen, mind also trying the "trunk"?

**Comment by dsvf** [comment]
OS is 32 bits, so the 64-bit Test App (cefclient.exe) will not run. The 32-bit version works fine with touch (quick googling/redditing).

**Comment by canton7** [comment]
Sure, then use the 32-bit version.

What happens if you view Syncthing's web UI in the Test App? I just want to make sure we absolutely identify which component is at fault.

**Comment by dsvf** [comment]
Yes, Syncthing Web UI works in the Test App.

**Comment by canton7** [comment]
Mind trying this build (when it's finished building, in about 10 mins)? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.7.323/artifacts

I updated to the latest version of the embedded browser, and changed something which may break scrolling on a touch screen, but may also be related to your issue.

**Comment by dsvf** [comment]
Well, it works, I can interact with the UI elements. Scrolling by dragging in the whitespace does not work, however; I need to use the scroll bar. It works in the Test App (Interaction and scrolling).

**Comment by canton7** [comment]
Right, so the stuff to add scrolling broke tapping, by the looks of it.

Let's raise an issue with CefSharp...

**Comment by dsvf** [comment]
Alright, I'm ready to try any test builds.

**Comment by canton7** [comment]
Did you try tapping on the links at the bottom of Syncthing's Web UI ("Home page", "Documentation", etc) with the "old" version of SyncTrayzor (i.e. the version you reported the button-tapping issue in)? It's a slightly different sort of HTML element, and I'm curious to see if that makes a difference.

**Comment by canton7** [comment]
(Opened as https://github.com/cefsharp/CefSharp/issues/1627)

**Comment by dsvf** [comment]
No, it does not work with them, either.

I noticed that when clicking on buttons or these links, that the cursor changes for a very short time to the "hand" cursor.

**Comment by canton7** [comment]
Interesting, maybe it's starting to "click", but turns it into a drag...

**Comment by canton7** [comment]
Looks like this is still an issue upstream. I'll turn off touch scrolling in the next release (making it behave like that intermediate build I gave you to try), and we'll have to edit until touch scrolling is fixed upstream.

**Comment by dsvf** [comment]
Alright, I look forward to that. I do wonder, however, why it works in the Test App.

**Comment by canton7** [comment]
CefSharp is doing a lot of stuff which the Test App isn't. CefSharp can be integrated into other applications (in particular WPF applications, which is the framework which SyncTrayzor uses). CefSharp needs CEF to add some more support for touch scrolling when rendering in the mode required by CefSharp, in order to display inside a WPF application.

**Comment by canton7** [comment]
Feel free to use that intermediate build above for now: it will auto-upgrade when the next release comes out
