### ISSUE TITLE
Pausing device reports "metering network" incorrectly

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#242]
Manually pausing one of the connected devices, results in the following message:
![image](https://cloud.githubusercontent.com/assets/11633330/13735536/95fddbe8-e9b3-11e5-8636-e02dbb661152.png)

I guess its because the same pausing mechanism engaged in both manual pause and pausing due to metered network, but such behavior is incorrect and may confuse users.

(issue is not present on Windows 7, probably due to the lack of "metered network" concept support)

**Comment by canton7** [comment]
Oops, so it does...

**Comment by canton7** [comment]
... Which is annoying, as there's a lot of code to specifically avoid that case. Let me find out what's going wrong..

**Comment by canton7** [comment]
Right, I've got another approach in place which should help. Can't test it at work (it's a Windows 7 PC, so no metered network support), but I'll test it at home in the next couple of days.
