### ISSUE TITLE
[enhancement] Keep WebUI "in memory"/"alive" while minimized to taskbar

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#248]
Right now the behavior is as follows:

0. SyncTrayzor is running in the background, icon in system tray visible, no windows open
1. Open SyncTrayzor window via system tray
2. Window appears, Web UI inside of it initializes (relisting everything, and loading folders data, etc.)
On mid to big nodes (with >10 folders, >5 devices, >1GB total share size) 
This process takes a while (ranging from 10 seconds up to 1 minute, with noticeable CPU consumption)
3. Initialization is complete, finally syncthing's state is accurately represented
4. Minimize the window to taskbar
5. Restore the window back to focus
6. Actual result: Now the whole lengthy UI initialization process starts all over again
    
Expected result: The UI is kept initialized from before, and no extra re-initialization process happens (similar to switching focus to another program and back, without minimizing).

Now my guess would be that Web UI is cleared to save resources, but it makes sense while minimizing to tray. Doing it on every minimization to taskbar is counterproductive and unjustified.

**Comment by canton7** [comment]
Hmm my memory of it was that it didn't unload the browser when simply minimized, but testing it, it seems that that isn't true...

**Comment by canton7** [comment]
Nope, my memory's correct: I don't touch the embedded browser until the window is closed. It's deciding to unload itself, for some reason.

**Comment by scienmind** [comment]
So we have no control over this behavior?

If syncthing is accessed via usual browser, the behavior is as expected, unlike SyncTrayzor's

**Comment by canton7** [comment]
Aah no: we're refreshing it, not unloading it. I wonder why we're doing that.... Easily fixed.

**Comment by canton7** [comment]
Mind giving this a spin (when it's finished building) and seeing if you can break it? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.8.333/artifacts

**Comment by scienmind** [comment]
Cool!
I'll try it later today

**Comment by ProactiveServices** [comment]
I observed the bug here, and the build you linked to solves them problem for me.

**Comment by scienmind** [comment]
I played with it a bit (getting some [#2854](https://github.com/syncthing/syncthing/issues/2854)'s NaN errors along the way...)

Minimize/restore seems to behave correctly :+1:
