### ISSUE TITLE
Native UI?

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#25]
Toying with the idea of writing a native UI for Syncthing, based on the UI proposition that's floating around the forums.

Pros:
 - Slightly slicker
 - Greatly reduced memory footprint

Cons:
 - Cognitive dissonance for people coming from the web UI
 - Always playing catch-up with Syncthing
 - A significant undertaking, at the expensive of other work/features

Does anyone have any thoughts on this?

**Comment by AudriusButkevicius** [comment]
Don't forget you will always have to play a catch-up game with us adding/removing stuff.

**Comment by canton7** [comment]
A good point - one I remembered on the forums but forgot here

**Comment by canton7** [comment]
Actually I think I might go for this. CEF's causing me way too much pain, see #37 for instance, and the Syncthing GUI isn't particularly complex

**Comment by canton7** [comment]
Actually, after mulling this over, I think I'm going to support both. I'll leave an option to switch between a native GUI / CEF

**Comment by chucic** [comment]
How does this look like? Reason I'm asking is I have 2 small issues with current UI, so if there will be both native GUI / CEF I will raise them but I don't want to bother you with them if you're going to drop CEF in month or 2.

**Comment by canton7** [comment]
I'm still undecided. I think I'll have to keep the CEF UI around, if nothing else because Syncthing's web UI is always going to be up to date, and I'm always going to be playing catch-up, so new features may not be available on the native UI.

**Comment by canton7** [comment]
Closing as inactive

**Comment by dodekeract** [comment]
I don't think that's a good idea. If you'd really implement this I would prefer it to be an option, as I personally would prefer to use the "working-solution", the already existent web-ui. Also I don't think, that the lower memory footprint really is that important, as systems get more and more ram over time and something like 4-8 GB is pretty common today. Of course it would be great to have a lower footprint, but I don't think it's worth the effort - especially if it's really implemented as an option.

**Comment by canton7** [comment]
I think I've come to the conclusion that there's not much point in doing anything here until syncthing hits 1.0 - there's too much risk of something breaking
