### ISSUE TITLE
Occasional "connection to syncthing lost"

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#251]
Do you have any idea why this happens?

![image](https://cloud.githubusercontent.com/assets/11633330/14413755/81b12bce-ff8c-11e5-9fe7-cbfe4e89ec6d.png)

It appears if SyncTrayzor's window is left open for a quite a while (30 min's).
Few weeks ago i never had such issues even if STz window left open for the whole day
I see it quite often lately, it is usually solved by refreshing the browser (F5), but sometimes it doesn't, and i need to restart it.
The console output doesn't have any abnormal info there.

Present on both Win10 and Win7

**Comment by canton7** [comment]
Duplicate of #246.

Basically syncthing started properly reporting json serialisation failures, and this means the gui now notices when the NaN issue occurs. A workaround for that issue had now hir master, but not 0.12.

**Comment by scienmind** [comment]
Ok, then I think I'll close this for now
