### ISSUE TITLE
nodes are left behind on 0.12.xx

### ISSUE THREAD

**Issue by icf20** [canton7/SyncTrayzor#254]
I noticed that while other OS got newer version SyncTrayzor still stay on version 0.12, are there any plans to use version 0.13 ?

**Comment by canton7** [comment]
Version 0.13 hasn't been released yet: it's still in beta. 

I will start including it by default when it is actually released. Until then, you can follow the instructions in the README to use the beta if you want.

**Comment by icf20** [comment]
I dont want to use beta y want to sync, so if linux got autoupdated to 0,13 i need to use that on windows in order to sync

**Comment by canton7** [comment]
Not sure what you're asking.

No distribution should have auto-upgraded you to 0.13: 0.13 is still in beta, and is **not stable**. Complain to your distribution's maintainers, and downgrade to 0.12.

If you really want to use Syncthing 0.13 with SyncTrayzor (and you understand that 0.13 is **unstable** software with real bugs and issues which haven't yet been fixed), [read the README](https://github.com/canton7/SyncTrayzor#using-syncthing-beta-releases).

**Comment by icf20** [comment]
the readme is useless for installations done via chocolatey

**Comment by canton7** [comment]
No it is not.

**Comment by icf20** [comment]
i replaced the exe and it say 0.12.22 in SyncTrayzor

**Comment by canton7** [comment]
If you want me to help you, you're going to have to provide more information than that.

*Which* exe did you replace? What did you replace it with? Did you restart SyncTrayzor?

**Comment by icf20** [comment]
downloaded the beta and placed that on the \AppData\Local\SyncTrayzor

**Comment by canton7** [comment]
If you actually did that (and restarted SyncTrayzor) then it would be running the correct version of SyncTrayzor.

**Comment by icf20** [comment]
i did restart and nothing

**Comment by canton7** [comment]
My instructions are correct. If it's "not working" for you, then you need to provide more information.

**Comment by canton7** [comment]
Ack, I take that back: the README is incorrect.

You want to place it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\syncthing.exe`, not Local.
