### ISSUE TITLE
Tray icon animates when nothing important is happening

### ISSUE THREAD

**Issue by bkidwell** [canton7/SyncTrayzor#255]
The tray icon spins when nothing important is happening. I think this happens once per minute when Syncthing does a full scan of your collections.

Animation should only be used when attention is needed. Otherwise it is disruptive to the user's concentration.

**Comment by canton7** [comment]
It animates when data is being transferred, which also catches data being uploaded: there's no other way to tell that something's being uploaded otherwise. This was a feature that was requested in the early days of development.

**Comment by bkidwell** [comment]
I think it would be easier on users' eyes if there was an on/off switch for this behavior. Or have "transferring" state indicated by a static image of a different color instead of a spinning one. I don't recommend removing the existing solution, but there should be other less visually disruptive options.

**Comment by canton7** [comment]
Yeah, I probably should allow the user to control what makes it spin. Yay for micro-customisations!

**Comment by bkidwell** [comment]
Little jumpy things kill my concentration. I literally walk out of Dunkin Donuts and McDonalds in America because their new menus have the item names and prices literally disappear for some of the **video loop** that is the "menu".

Anyway, I can't be the only one who wants only strictly necessary animation on the desktop. I appreciate being heard, however you manage to tweak it.

**Comment by canton7** [comment]
Available here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.8.343/artifacts

**Comment by canton7** [comment]
Fixed in v1.1.9
