### ISSUE TITLE
Folder changes are not being detected

### ISSUE THREAD

**Issue by heymoe** [canton7/SyncTrayzor#26]
Running SyncTrayzor v1.0.8 (64bit) with Syncthing v0.10.27
OS: Windows 7 64bit

I do have the folder being monitored by SyncTrayzor and I have Syncthing's rescan interval on the folder set to 86400.

Unless I'm misunderstanding the feature set of SyncTrayzor, it should monitor synced folders for changes and notify Syncthing to do a sync when it (SyncTrayzor) detects them.

I have a plain text file in the synced folders and it was synced to my other server upon initial setup.

I've noticed that if I make a change to this text file, like adding "test123" to it and save it. Syncthing does not get notified of this change so it's not updated on the other server. 

I've confirmed that my changes (test123) exist in the file on my computer and does not exist int he text file on the other side.

Windows show the file size is different and the modification time has changed using explorer properties on the text file.

Even copying a new file into the synced folder does not trigger a resync of the folder. 

If I manually trigger a folder rescan in Syncthing, everything syncs up just fine.

**Comment by canton7** [comment]
Can you post the contents of `C:\Users\<You>\AppData\Roaming\SyncTrayzor\SyncTrayzor.log`? There should be lots of activity around the point in time that you made the modifications.

**Comment by heymoe** [comment]
Hey Canton7. I re-did my simple text file change and nothing new got logged related to the text file in question.

Looking though the log though, I did see this message for the folder I'm testing in:

2015-03-16 13:51:09.4397 [Warn] SyncTrayzor.Services.DirectoryWatcher: Watcher for \Sync\Locker\ couldn't be created: path doesn't exist 

Now when I added this folder I used the following for the path: "~\Sync\Locker"

Based on the Syncthing add folder screen the "~" is a shortcut to "C:\Users\<USER>". So the full path to my folder is: "C:\Users\<USER>\Sync\Locker".

It would seem that SyncTrayzor isn't converting the "~" shortcut to the full path to the folder correctly thus the Directory Watcher process / thread isn't able to monitor for changes.

**Comment by canton7** [comment]
Aha, it's that. That will be fixed in the next release, coming shortly. As a workaround, you can use a full path in Syncthing's config.

**Comment by canton7** [comment]
And by "shortly" I mean "probably tomorrow"

**Comment by heymoe** [comment]
Works for me.. Thanks!

**Comment by canton7** [comment]
v1.0.9 is out - that should fix it. Let me know if you still have issues!

**Comment by heymoe** [comment]
Looks like it's working great now. Thanks!

**Comment by canton7** [comment]
Sweet, cheers :)
