### ISSUE TITLE
SyncTrayzor silently crashes during "wake from sleep"

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#260]
As was mentioned in ST's issue #3001:

I have had SyncTrayzor & Syncthing silently crashing during "wake from sleep", here are the logs:
SyncTrayzor: https://gist.github.com/anonymous/a52a5158bd4cca9145137fda6092dc2d
Syncthing: https://gist.github.com/anonymous/7134dbcbadf381ff1e83961fb7056c31

Hard to reproduce. Usually it's OK, only few times I noticed that while resuming the PC from sleep SyncTrayzor was closed. I wasn't sure if it was running before entering sleep, so I disregarded it couple of times. But last time I was sure it was running before sleep, checked the logs - and it indeed has crashed.

**Comment by canton7** [comment]
Right, so we resume from sleep, spot that the networks have changed, and try and resume all devices.

However, Syncthing's refusing our requests. Not sure why. I think I'll need to ping this back to Syncthing.

**Comment by canton7** [comment]
Dup of #252, I think
