### ISSUE TITLE
Synctrayzor 1.1.9 corrupted UI after update to v0.13.1

### ISSUE THREAD

**Issue by tonymorello** [canton7/SyncTrayzor#265]
After the update the UI is broken, no folders and no devices are shown although they sync correctly. It works fine in browser window.

![2016-05-19 11_42_01-synctrayzor](https://cloud.githubusercontent.com/assets/7967400/15399738/d95cfce8-1db6-11e6-81f4-32382f64deff.png)

**Comment by canton7** [comment]
Duplicate of part of #262.

The cause is something to do with the browser caching some old JavaScript. As a workaround, delete `C:\Users\<You>\AppData\Local\SyncTrayzor\cef\cache`

**Comment by canton7** [comment]
(Alternatively, it clears itself after a while)

**Comment by tonymorello** [comment]
Sorry for opening an issue that was already opened. It worked BTW, of course!... Thanks.

**Comment by canton7** [comment]
Awesome!

Closing in favour of the other issue, for tracking this down.
