### ISSUE TITLE
Unable to use when offline

### ISSUE THREAD

**Issue by prismacolorgold** [canton7/SyncTrayzor#267]
I am on mobile data, so I set up my a local network for syncthing.
I just realize if I have my mobile hotspot turn on, synctrayzor will work fine.
But if I don't have the internet turn on, it won't load.

Is it a bug or is it designed like that?

**Comment by canton7** [comment]
What exactly do you mean, "it won't load"?

**Comment by canton7** [comment]
Closing as no response
