### ISSUE TITLE
Interface infelicity - which device is syncing?

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [canton7/SyncTrayzor#269]
The attached screenshot shows, I think, that it's not always as clear as it should be which devices is syncing. (The red scribbles in the screenshot are for purposes of redacting personal information.)

![untitled](https://cloud.githubusercontent.com/assets/9998846/15454441/9ac2e3b8-2030-11e6-8fa2-4f3a7b9b855a.png)

**Comment by canton7** [comment]
This is a Syncthing issue, not a SyncTrayzor one. Please open an issue [on the Syncthing issue tracker](https://github.com/syncthing/syncthing/issues).
