### ISSUE TITLE
Misplaced Tray Icon context menu

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#270]
Since one of the recent commits dealing with tray icon, the behavior is as follows:

Do:
Right click SyncTrayzor's Tray Icon

Result: 
The context menu is not expanded near the mouse cursor (as it does with all other applications), but is aligned to the bottom right edge of the screen instead.

Back in 1.1.8 (or 7) the behavior was correct.
OS - Windows 10 x64

**Comment by canton7** [comment]
Screenshot?

This part of the application hasn't changed in a long time, and uses a third-party component anyway, so whatever you're seeing has nothing to do with changes to SyncTrayzor.

**Comment by scienmind** [comment]
Other application:
![capturefb](https://cloud.githubusercontent.com/assets/11633330/15541324/a4c9bde4-2294-11e6-9b79-fa630373ecd3.PNG)

SyncTrayzor:
![capturest](https://cloud.githubusercontent.com/assets/11633330/15541333/ae74ae58-2294-11e6-8bd4-bfb8203644bd.PNG)

In both cases, the mouse pointer is located on the icon itself.

SyncTrayzor's behavior is the same (not correct) with both portable and install versions.

On Windows 7 the behavior is correct though.

**Comment by canton7** [comment]
What version are you running?

**Comment by scienmind** [comment]
An official 1.1.10

**Comment by canton7** [comment]
OK, nothing has changed in that area since before the 1.1.7 days.

**Comment by scienmind** [comment]
You are correct, I just grabbed 1.0.32 (portable) to test this, and it behaves the same as 1.1.10 does (incorrectly).

Probably the correct behavior I remembered in older versions was just pre-win10 and not synctrayzor-related...

**Comment by scienmind** [comment]
Interestingly though, I tested 1.1.10 portable on a win10 VM, and the bug is not present there...

The weird thing is the on the machine which displays the buggy behavior, synctrayzor is the only application with such a behavior, and the bug is persistent for any type of synctrayzor's installation...

**Comment by scienmind** [comment]
OK, so on the affected machine, I went through about 30 programs that can have tray icons, and found one more piece of software that displays the buggy behavior synctrayzor does.

I'm still not sure though who to blame here, maybe synctrayzor and the another program have some legacy piece of code in them that surfaces under certain OS's condition, or maybe its just another bug in the windows 10's UI shell (which is very much not bug-free) that misbehaves...

**Comment by canton7** [comment]
Just tried it on mine, and it works fine...

Just in case, mind trying this build? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.10.368/artifacts . It contains an upgrade to the library which provides the tray icon.

**Comment by scienmind** [comment]
Tested the portable version, seems like it does the trick!

**Comment by canton7** [comment]
Awesome! That was flukey: I noticed there was an update so pulled it in. There's nothing in the changelog to do with your issue either.
