### ISSUE TITLE
Not portable between PCs?

### ISSUE THREAD

**Issue by TheRealMarnes** [canton7/SyncTrayzor#272]
Does synctrayzor by any chance encrypt its data with a unique OS-generated key or something? Like how vivaldi encrypts sensitive browser profile data with such a key to secure it and prevent copying?

Today I clean reinstalled windows, and copied over all my stuff, but synctrayzor (portable version) is now broken: it now loads the default config instead of my old config that I copied over along with it.

Does synctrayzor purposefully prevent itself from just being copied like that, or is the problem likely to be something else, related to my particular setup/data?

**Comment by norgeous** [comment]
When you run SyncTrayzorPortable for the first time a folder called `data` is created in the same folder as the `SyncTrayzor.exe`. I believe this `data` folder contains all the config info (device identitiy, folders, remote devices, etc).

**Comment by TheRealMarnes** [comment]
Yes, but that's not the issue here. The problem is that my portable copy of
synctrayzor doesn't read its existing data when moved to a new windows
installation. The question is, is this by design (I can imagine reasons why
it would be, and other programs do it), or is it almost certainly just me?

**Comment by TheRealMarnes** [comment]
But as you can see further down in that issue, I also fixed the config as you described there. If those 2 paths are the only difference between a portable and installed copy, then my data is fully patched to be portable now.

Those paths also refer to syncthing, not to my data. If they were broken, synctrayzor wouldn't start syncthing. It does start syncthing, it just doesn't load my data anymore.

**Comment by canton7** [comment]
> Does synctrayzor by any chance encrypt its data with a unique OS-generated key or something?

No, it doesn't. The portable version can be moved between machines. Whatever's going on is something else.

>  it now loads the default config instead of my old config that I copied over along with it.

It loads the config that's in the config file. The location of the config file is specified in `SyncTrayzor.exe.config`, in `<ConfigurationFilePath>`. If the config file does not exist, it's created from the defaults.

So this implies that SyncTrayzor wasn't using the config you thought it was. Did you always use the portable version, or has there been some version there? What's the whole story?

**Comment by TheRealMarnes** [comment]
> No, it doesn't. The portable version can be moved between machines. Whatever's going on is something else.

Ok, good

> Did you always use the portable version, or has there been some version there? What's the whole story?

No, I used the installed version first. Then I downloaded the portable version, copied over the data folder, and fixed the 2 mentioned paths in config.xml. Does more need to change to make an installed version's data folder portable?

SyncTrayzor.exe.config
```xml
<PathConfiguration>
        <LogFilePath>%EXEPATH%\logs</LogFilePath>
        <ConfigurationFilePath>%EXEPATH%\data\config.xml</ConfigurationFilePath>
        <ConfigurationFileBackupPath>%EXEPATH%\data\config-backups</ConfigurationFileBackupPath>
        <CefCachePath>%EXEPATH%\data\cef\cache</CefCachePath>
      </PathConfiguration>
```

config.xml
```xml
  <SyncthingPath>%EXEPATH%\data\syncthing.exe</SyncthingPath>
  <SyncthingCustomHomePath>%EXEPATH%\data\syncthing</SyncthingCustomHomePath>
```

I tried to run synctrayzor straight from the external disk to which I had copied it for my windows reinstall. It did the exact same thing: loaded the default config instead of the existing one.

Short of sending you my whole synctrayzor copy with data folder and everything, is there something else I can check? Something else that differs between the data folders of an installed version and a portable version that would cause this?

**Comment by canton7** [comment]
There are two other things you need to check:

 - `<SyncthingUseCustomHome>` should be `true`.
 - You need to copy the contents of `C:\Users\<You>\AppData\Local\Syncthing` into `data\syncthing`.

**Comment by TheRealMarnes** [comment]
I took a fresh copy from my ext disk (which has the fixed paths) and copied my original AppData\Local\Syncthing into its data\syncthing, overwriting what was there: same result :/

**Comment by canton7** [comment]
Right, post `data\config.xml` and `data\syncthing\config.xml`, please.

**Comment by TheRealMarnes** [comment]
Is the SyncthingApiKey in config.xml supposed to be secret? I don't mind posting even a zip of my whole thing here, but I'd rather not just give away free access to my stuff by posting the auth keys and whatnot :)

**Comment by canton7** [comment]
If you want, you can email them: my email's on my profile page.

The API key will only matter if you've told Syncthing to listen on something other than localhost.

**Comment by canton7** [comment]
You need to change `<SyncthingUseCustomHome>false</SyncthingUseCustomHome>` to `<SyncthingUseCustomHome>true</SyncthingUseCustomHome>`, as I [said earlier](https://github.com/canton7/SyncTrayzor/issues/272#issuecomment-222304472).

**Comment by TheRealMarnes** [comment]
Ah, it was in config.xml too? I was looking at that same key but in 
SyncTrayzor.exe.config, where it already was true. Sorry I missed that, 
I didn't think it'd be in 2 places

Just ran it and yes, now it works :) Thanks

Perhaps all these pitfalls could be put onto a wiki page for future 
reference?

**Comment by canton7** [comment]
SyncTrayzor.exe.config just contains the template for the default configuration, and some things which aren't user-editable: you should never edit it yourself (unless you're a network admin setting up default installs for your users).

Converting from Installed -> Portable is not something that's currently supported: it's not documented, and you're (in theory) on your own. 

I'm having a think about what can be done to make it possible for the average user.

**Comment by canton7** [comment]
The next version will support copying the config between the portable and installed version, and the README will have instructions on how to copy Syncthing's config around.

**Comment by TheRealMarnes** [comment]
Awesome, thanks
