### ISSUE TITLE
Global discovery: unsupported scheme announce.syncthing.net

### ISSUE THREAD

**Issue by Gusatomik** [canton7/SyncTrayzor#275]
I got this message when starting SyncTrayzor. In the SyncThing forum they speak about a config file to delete. I don't know if I can do that with SyncTrayzor.

**Comment by canton7** [comment]
Please give full details: where this message appeared, some context (if it's in a log, the log lines around it), etc.

Either way, this is a Syncthing issue. Please [read the README](https://github.com/canton7/SyncTrayzor#what-will-synctrayzor-do-to-my-system) to see where Syncthing's database and configuration are stored.

**Comment by Gusatomik** [comment]
Ii appears in the SyncTrayzor window. At each start. Here a screenshot of the message.
![st](https://cloud.githubusercontent.com/assets/1189415/15668583/6c6edb32-271c-11e6-8019-cf4450cf9ded.png)
I will have a look at the README.
Thank you canton7 for your work and reactivity :)

**Comment by canton7** [comment]
Go to Actions -> Settings inside Syncthing, the "Global Discovery Servers" box should have just the text "default" in it.

**Comment by Gusatomik** [comment]
Well, there is "announce.syncthing.net:22025" inside it. Should I try to replace it by "default" ?

**Comment by canton7** [comment]
yes

**Comment by Gusatomik** [comment]
Alright, there is no message anymore. I think the problem is solved (I wasn't able to reach a node out of my local network). I have to apply the same changes to this node but I'm pretty sure I will do the job (will do it in the afternoon).
Thank you very much canton7 !
