### ISSUE TITLE
Browser display broken since update to syncthing v0.13.4

### ISSUE THREAD

**Issue by oepoemoepoe** [canton7/SyncTrayzor#276]
Hi,

since I updated Syncthing to 0.13.4 (from 0.12.x, don't remember) the display in the browser seems to be corrupted:

![image](https://cloud.githubusercontent.com/assets/14923159/15712607/4f5a2202-2813-11e6-816e-bbc58c0490ac.png)

Thanks for the awesome application btw, appreciate it!

- Klaus

**Comment by canton7** [comment]
Please see #262.
