### ISSUE TITLE
Configuration file capitalization issue

### ISSUE THREAD

**Issue by snpalavan** [canton7/SyncTrayzor#279]
There seems to be some sort of issue with XML compatibility between SyncTrayzor and SyncThing.

I get this error:  [LRKZW] 17:21:17 FATAL: Config: expected element type \<configuration\> but have \<Configuration\>

But if i change the capitalization to <configuration> i get this error:
![image](https://cloud.githubusercontent.com/assets/1146754/15913227/4bf8535a-2d9e-11e6-8f2c-bb8e264c279e.png)

Running SyncTrayzor 1.1.10 and SyncThing 0.13.5

**Comment by canton7** [comment]
That's all sorts of wrong: it should be trying to load `C:\Users\<You>\AppData\Local\SyncTrayzor\config.xml`, but instead it's trying to load a file from within `Program Files`, and it looks like it's trying to load Syncthing's configuration file. 

I'm guessing you tried to convert a portable version to an installed one by copying it to Program Files, and then tried to fix it by editing SyncTrayzor.exe.config? What exactly is the back story here?

**Comment by snpalavan** [comment]
I originally had syncthing installed on its own, with the config folder within the syncthing folder - i.e.:
![image](https://cloud.githubusercontent.com/assets/1146754/15941012/152d9da2-2e44-11e6-95ca-d9d940706682.png)

Then, when i installed SyncTrayzor, i wanted to keep the same config so i wouldnt have to set everything up again.  So i copied the syncthing folder into the SyncTrayzor program files folder:
![image](https://cloud.githubusercontent.com/assets/1146754/15941063/40f32844-2e44-11e6-9646-04fdf7de2a9a.png)

and changed the settings in the config file:
![image](https://cloud.githubusercontent.com/assets/1146754/15941082/545ad79c-2e44-11e6-9b5a-2938319e119e.png)
![image](https://cloud.githubusercontent.com/assets/1146754/15941092/5a77d1ca-2e44-11e6-8b6f-7939a95437e7.png)

And set SyncTrayzor to not use the default folder, which i assume means to use the CustomHomePath:
![image](https://cloud.githubusercontent.com/assets/1146754/15941166/7b0b3396-2e44-11e6-8d4a-514e4ad61c58.png)

The weird thing is, if i run it without a config.xml file, it will work the first time, but not subsequent times.
Also, if i copy the old config.xml (which has lower case \<configuration\>), it will work the first time, but then the config.xml file gets rewritten (and has the capital \<Configuration\>). After the rewrite, the errors in my original post begin to occur.

-Shea

**Comment by snpalavan** [comment]
Just messed around some more, so i just started from scratch with both the use default location checked and unchecked.

If it is checked, all of the files are successfully created in the %LOCALAPPDATA% folder and the config.xml file has the lower case \<configuration\>:
![image](https://cloud.githubusercontent.com/assets/1146754/15941383/7a52eda8-2e45-11e6-93ac-3cc6c5bf0c86.png)
![image](https://cloud.githubusercontent.com/assets/1146754/15941421/a35c12d8-2e45-11e6-9d66-0d57c2945137.png)

With this setup, it works every time.

With the use default location box unchecked, i tried both starting them together and starting syncthing after already running SyncTrayzor:
First is starting SyncTrayzor and syncthing together (i.e. i have SyncTrayzor completely closed and launch it, so both open simultaneously)
In this case, all of the files are created successfully in the CustomHomePath directory (which for me is the SyncTrayzor folder) and the config.xml file shows the capital \<Configuration\>:
![image](https://cloud.githubusercontent.com/assets/1146754/15941606/8e257ec6-2e46-11e6-8080-cb971a2b25b0.png)

With this setup, it works every time.

Second, I left SyncTrayzor running, removed all the files and started syncthing and get the same results.

So, it seems that if everything starts from scratch (no config or other files), everything works.

Next, i said ok, let's try importing the old files in.  I again tried it with and without the box checked.
That's when i get the error when the box is checked.  Very odd.

**Comment by snpalavan** [comment]
OMG i'm dumb. Nevermind LOL

**Comment by canton7** [comment]
If you hadn't figured it out, `<ConfigurationFilePath>` is the path to SyncTrayzor's config file, not Syncthing's config file. You specify the path to Syncthing's home path by giving `<SyncthingCustomHomePath>` and setting `<SyncthingUseCustomHome>` to `True`.

Also, you shouldn't put Syncthing's home folder in `Program Files`: program files isn't writable by random users, so Windows does a lot of magic to make things appear to work most of them time if you try and write there.

**Comment by canton7** [comment]
Also note that users are not supposed to edit `SyncTrayzor.exe.config`: it is replaced on each upgrade.

**Comment by snpalavan** [comment]
Yeah...i figured all of that out and realized I'm just retarded... haha thanks!
