### ISSUE TITLE
'Open Folder' and 'Browse' buttons missing

### ISSUE THREAD

**Issue by norgeous** [canton7/SyncTrayzor#281]
Syncthing: v0.13.7
SyncTrayzor: 1.1.10

Hi @canton7!

I think recent changes may have broken the in-GUI 'Browse' and 'Open Folder' buttons. It would be nice to have these awesome feature returned at some point, so I thought I'd open a bug. Hopefully you see this also...

I'm not sure of the exact cause but I can explain some of the recent changes that may be related if you think it might help?

I had a look in [ViewerViewModel.cs](https://github.com/canton7/SyncTrayzor/blob/master/src/SyncTrayzor/Pages/ViewerViewModel.cs) and the jQuery selects look like they still match. I'm really not sure what's happening because it feels like parts of this injected jQuery run (such as `$('#directory-list').remove();`) but other parts don't (such as the Browse button).

Also, there have been many recent improvements to the `#directory-list` (in `Add Folder` > `Folder Path`) which you are removing... maybe you could consider including this list with the button also? I don't think these two features (button and list) counteract each other.

**Comment by norgeous** [comment]
I just tried with SyncTrayzor Portable and buttons appear fine. I wonder what's happening, maybe its just my setup.

**Comment by scienmind** [comment]
Occasionally the buttons do disappear, and then reappear.
I've never got around to figuring out what an accurate pattern of this behavior is, but what you are describing is definitely familiar.

**Comment by canton7** [comment]
There's something racey where the javascript stuff sometimes doesn't get run. It's pretty rare, and refreshing the browser usually fixes it. 

I haven't tested your new stuff yet. Bear in mind that CEF doesn't support the mechanism by which the old directory browser worked (I can't remember which html tag it used off the top of my head), which is why I removed it. Have you changed how it works fundamentally?

**Comment by norgeous** [comment]
It still uses `<datalist id="directory-list"></datalist>`. It's unfortunate that...
> CEF doesn't support the mechanism

I guess CEF != chrome. [CEF#906](https://bitbucket.org/chromiumembedded/cef/issues/906/cef3-add-html5-datalist-support)

Yep, with refreshing I get a mixture of showing and not...

**Comment by canton7** [comment]
I can't remember when that javascript is run (I'm on mobile). It might be that it's running too early: might need to hook it into some event when the folders load? 

I'm afraid I'm unlikely to get access to a computer for the next week.

**Comment by norgeous** [comment]
It's ok, enjoy your time away! I'll close this for now.

**Comment by canton7** [comment]
Nah leave it open, otherwise I'll forget...
