### ISSUE TITLE
Display folder name instead of id in Settings|Folders

### ISSUE THREAD

**Issue by EchterAgo** [canton7/SyncTrayzor#284]
Syncthing 0.13 moved to separate folder ids and names, the dialog should display the name.

**Comment by canton7** [comment]
Yep, and elsewhere as well, presumably

**Comment by canton7** [comment]
This will be in the next release

**Comment by EchterAgo** [comment]
Thank you. Also, do you have Bitcoin? I'd like to buy you a beer, but can't use Paypal.
