### ISSUE TITLE
Automatic update problem

### ISSUE THREAD

**Issue by tarbib** [canton7/SyncTrayzor#287]
![_20160627172222](https://cloud.githubusercontent.com/assets/2255433/16375003/cd11ee6e-3c8b-11e6-832e-0a29db2c963d.png)

Hi,

First of all thanks a lot for your great work. 
I would like to submit an issue with automatic upgrade. I use SyncTrayzor on my PC Windows 10 64 bits and syncthing on my VPS ubuntu server 14.04.
Please see details in screenshot enclosed.

Do you need more information?

Thanks

**Comment by canton7** [comment]
This is a Syncthing issue. Please open an issue [with the Syncthing repo](https://github.com/syncthing/syncthing/issues/new].

From a cursory look, it looks like your computer's having trouble talking to Amazon's servers, which GitHub uses to host release binaries. Make sure you don't have a firewall in the way.

**Comment by tarbib** [comment]
Thanks a lot.

I just connected through a VPN and it updated.

Thomas

On 27 June 2016 at 17:32, Antony Male <notifications@github.com> wrote:

> This is a Syncthing issue. Please open an issue [with the Syncthing repo](
> https://github.com/syncthing/syncthing/issues/new].
>
> From a cursory look, it looks like your computer's having trouble talking
> to Amazon's servers, which GitHub uses to host release binaries. Make sure
> you don't have a firewall in the way.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/canton7/SyncTrayzor/issues/287#issuecomment-228697295>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACJqSW3Hwsun6VSV3VExww20nB_q4THyks5qP5jFgaJpZM4I-6F->
> .
>



-- 

Thomas Arbib

France : +33 (0)6 30 66 72 25
中国手机 : +86 150 6616 3405

Twitter : @tarbib <http://twitter.com/tarbib>
微信 (WeChat) ID : tarbib

http://about.me/thomasarbib

**Comment by canton7** [comment]
Glad to hear it!
