### ISSUE TITLE
NullReferenceException on version 1.1.2.247

### ISSUE THREAD

**Issue by tdbe** [canton7/SyncTrayzor#288]
After updating SyncTrayzor (win 7 x64) I get a null reference as soon as I start the program (or as soon as it auto-starts on boot)

Here's the error message:
> Version: 1.1.2.247; Variant: Installed; Arch: Amd64
> Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at SyncTrayzor.SyncThing.FolderIgnores..ctor(List`1 ignores, List`1 patterns) in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\Folder.cs:line 28
>    at SyncTrayzor.SyncThing.SyncThingFolderManager.<>c__DisplayClass29_0.<<FetchFoldersAsync>b__2>d.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 180
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SyncTrayzor.SyncThing.SyncThingFolderManager.<FetchFoldersAsync>d__29.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 188
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SyncTrayzor.SyncThing.SyncThingFolderManager.<LoadFoldersAsync>d__27.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 108
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SyncTrayzor.SyncThing.SyncThingManager.<LoadConfigDataAsync>d__138.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 518
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SyncTrayzor.SyncThing.SyncThingManager.<LoadStartupDataAsync>d__137.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 483
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__131.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 381
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__119.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 203
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 17
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SyncTrayzor.Pages.ViewerViewModel.<Start>d__38.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ViewerViewModel.cs:line 200
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
> 

Is there any info on how can you roll back syncTrayzor for when you get a bad/incompatible version? (without wiping the program and losing my folder setup)

**Comment by canton7** [comment]
You're using an incredibly old version, which does not support newer Syncthing versions. Please upgrade.

**Comment by tdbe** [comment]
Wow, okay. How is it possible that I have an incredibly old version after over a year of me doing regular updates as a result of it asking me to update? 
Did it always only update syncthing and never actually warned me about syncTrayzor?

**Comment by canton7** [comment]
Syncthing updates and SyncTrayzor updates are separate and independent. SyncTrayzor should prompt you to upgrade using a tray notification when it notices there's an upgrade available. If there is a problem with this mechanism, it will be logged. Please post your log file (which you'll find in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs\SyncTrayzor.log`)

**Comment by tdbe** [comment]
Oh, I didn't know they update separately. Hadn't paid enough attention... Thought I had the latest of both.

Okay, I attached a SyncTrayzor log. If everything is fine there then it was either repeated bad luck on my end or someone recently restored my windows from an old backup without me knowing.

I also downloaded a new SyncTrayzor kit and installed it and it works now. Sorry for the lack of noticing on my part. Maybe add a "Check for Updates" button in the Help/About section?

[SyncTrayzor_log.pdf](https://github.com/canton7/SyncTrayzor/files/337137/SyncTrayzor_log.pdf)
Sorry it's a pdf. For some reason github won't let me upload .log, .txt or even a .zip with a .txt in it...

**Comment by canton7** [comment]
When you open Help/About, it will check for updates and tell you if one is available. 

http://gist.github.com is useful for pasting files (although a PDF is fine for now - no need to re-post it as a gist).

The logs indicate that it detected that a new version was available, but it didn't try to download it. That could be because you opted to ignore that upgrade previously, but unfortunately 1.1.2 didn't contain enough logging there to confirm that theory.

In your SyncTrayzor config file (at `C:\Users\<You>\AppData\Roaming\SyncTrayzor\config.xml`) you might see a `<LatestNotifiedVersion>someStuff</LatestNotifiedVersion>`. Would you mind checking, and telling me what `someStuff` is if you do?

**Comment by tdbe** [comment]
My latest config.xml is reporting 1.1.10, because I just upgraded and visited help/about.
But my config-backups folder has 3 versions from: 5/11/2015, 7/12/2015, and 11/1/2016.
All of those logged this version:
<LatestNotifiedVersion>1.0.28</LatestNotifiedVersion>

So I wonder how I even got to installing v1.1.2.247 :D

**Comment by canton7** [comment]
Actually, I can see from your log that it was `LatestNotifiedVersion=1.1.10`. 

It is actually mis-named: it should really be called "LastIgnoredVersion". It should be set when you click 'Don't Remind Me Again' on an update prompt. So the most likely reason is that it prompted you about version 1.1.10 at some point, and you clicked 'Don't Remind Me Again'.

**Comment by canton7** [comment]
Closing, as no response.
