### ISSUE TITLE
Spams connected/disconnected when remote device paused

### ISSUE THREAD

**Issue by alex2108** [canton7/SyncTrayzor#289]
Local device tries to connect and remote rejects because it has the local device paused, this leads to notifications every few seconds.

Synctrayzor could maybe delay the notification for a second and wait if a disconnect follows and then do not display anything. (Alternative: report this as bug in syncthing which should not send events in this case?)

**Comment by canton7** [comment]
Interesting... I think I'd prefer to fix this on the Synching side, since a device rapidly connecting and disconnecting is usually a sign of some broken network configuration, which the user should probably know about.

**Comment by canton7** [comment]
Looks like it would require a protocol change for Syncthing, which isn't likely to happen soon (https://github.com/syncthing/syncthing/issues/3379). I'll get a workaround in place on my side in the meantime.
