### ISSUE TITLE
another Error FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000

### ISSUE THREAD

**Issue by john-qin** [canton7/SyncTrayzor#290]
syncthing stopped working. If I typed syncthing in the terminal. I will get "[RN2F3] 19:40:18 FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000"

I googled this error. some ppl sugguested to

> You've got a config file that was written by Syncthing v0.12, and you're running Syncthing v0.11.
> 
> If you want to run Syncthing v0.12 (recommended): 1) Install the latest SyncTrayzor v1.0.31 (if you haven't already). 2) Delete C:\Users\<You>\AppData\Roaming\SyncTrayzor\syncthing.exe. 3) Start SyncTrayzor.
> 
> If you wan to run Syncthing v0.11 (not recommended), you'll need to restore the config.xml in C:\Users\<You>\AppData\Local\Syncthing to a version which was written by Syncthin v0.11.

however, I installed it on my mac using homebrew. I dont even know where this AppData folder is.

btw, how do you restart syncthing web gui in mac?

Just FYI: 

Johns-Mac-Pro:~ qinking126$ syncthing -version
syncthing v0.11.26 "Aluminium Ant" (go1.5.1 darwin-amd64 default) brew@yosemitevm.local 2015-10-02 06:08:07 UTC

**Comment by canton7** [comment]
SyncTrayzor is a Windows wrapper for Syncthing. If you're using mac, then you are not running SyncTrayzor.

Please open a thread [on the Syncthing forum](https://forum.syncthing.net/).
