### ISSUE TITLE
WebUI is sometimes blank

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#292]
Occasionally (after a long syncthrayzor's uptime period), opening main UI shows blank white page.
Waiting a long period does nothing, "Menu->Syncthing->Refresh browser" does nothing, "Menu->Syncthing->Restart syncthing" has no effect.

The only way to restore UI functionality is to close it entirely (menu->file->exit) and relaunch.
So it seems like the wrapper fails to communicate with the ST itself properly.

In the background the actual syncthing seem to be working, syncing occurs properly.

SyncTrayzor log: https://gist.github.com/anonymous/0b8c1f43babccbdcbea2d03eaa7c3243
Syncthing log: https://gist.github.com/anonymous/d4628810f8393f7c476a4f12c5caca36

Note:
I'm not entirely sure if it's synctrayzor's fault, I have never encountered it with standalone syncthing, but then again I access standalone installation much less often then the synctrayzor's ones...

Environment: SyncTrayzor v.1.1.11, Syncthing v.0.13.10, OS: Win10 x64

**Comment by canton7** [comment]
1. Open Chrome
2. Visit localhost:2004
3. Click the link ("DEVICENAME | Syncthing")
4. Click "Elements"
5. See what's there.
6. Click "Console", Syncthing -> Refresh Browser, see what's there
7. Click "Network", Syncthing -> Refresh Browser, see what's there

**Comment by scienmind** [comment]
OK, next time it stuck again, I'll check there and let you know

**Comment by scienmind** [comment]
OK, I noticed that it also (more frequently) happens upon loss of internet connectivity:

1. disable network adapter (wifi/lan)
2. open main synctrayzor window
3. the window is blank, behavior as before, devtools console content:
![image](https://cloud.githubusercontent.com/assets/11633330/16739674/0060e950-47a4-11e6-8270-a2734f2fb914.png)
(elements are basically blank)

Now, the issue I originally complained about was present with valid network connection. 
Maybe network switching causes SyncTrayzor to loose link to ST somehow.

The GUI listen address is set to: "pc-name:port" and is the same both in the ST's setting and SyncTrayzor's. But console window of ST sometimes reports:
`[ID] 13:53:10 INFO: GUI and API listening on "local_ip:port"`
("local_ip" instead of "pc_name")

**Comment by canton7** [comment]
So the errors you posted are an issue, but are probably an effect rather than a cause.

Please give me all of the information I asked for.

**Comment by canton7** [comment]
Changing Syncthing and SyncTrayzor to use the PC's host instead of `localhost` doesn't do anything to replicate this. Disabling all of my network adapters also doesn't replicate the problem.

**Comment by canton7** [comment]
Did you try opening Syncthing's UI in an external browser? I realise that I assumed you had, but that's not true. That's step 1 to try.

> The only way to restore UI functionality is to close it entirely (menu->file->exit) and relaunch.
So it seems like the wrapper fails to communicate with the ST itself properly.

No, that's not true. Syncthing is completely restarted when you click Syncthing -> Restart. Closing/opening SyncTrayzor implies it's an issue with the embedded browser, as *that* isn't completely reloaded until you exit SyncTrayzor and restart it.

Have you seen this issue before 1.1.11?

**Comment by scienmind** [comment]
I had some similar issue before 1.1.11 as well, although I've never really looked into it until now, so I can't say anything definite.

> No, that's not true. Syncthing is completely restarted when you click Syncthing -> Restart.

Evidently that's what happened nonetheless. And as you see from the logs I initially posted here:
Synctrayzor log: 
```
2016-07-11 13:43:32.4519 #3756 [Debug] SyncTrayzor.Syncthing.ApiClient.SyncthingApiClient: Restarting Syncthing 
2016-07-11 13:43:41.7975 #3756 [Debug] SyncTrayzor.Syncthing.ApiClient.SyncthingApiClient: Restarting Syncthing 
```
Syncthing log at the same time:
```
[IDIDIDID] 13:26:53 INFO: Connection to IDIDIDI1 closed: read tcp local_ipv4:54151->remote_ipv4:22067: wsarecv: An existing connection was forcibly closed by the remote host.
[IDIDIDID] 13:43:21 INFO: Connection to IDIDIDI2 closed: read tcp [IPV6%Ethernet]:22000->[IPV6%Ethernet]:52020: wsarecv: An existing connection was forcibly closed by the remote host.
[IDIDIDID] 13:52:29 INFO: syncthing v0.13.10 "Copper Cockroach" (go1.6.2 windows-amd64) WIN-P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ 2016-07-03 11:29:32 UTC
[IDIDIDID] 13:52:29 INFO: My ID: IDIDIDID
[IDIDIDID] 13:52:30 INFO: Single thread hash performance is ~174 MB/s
```

Note: Synctrayzor issued restart request at 13:43, no corresponding action on ST's side until 13:52 (when I manualy exited SyncTrayzor entirely, and opened it again)

**Comment by canton7** [comment]
> Evidently that's what happened nonetheless

I'm saying that your assertion that "So it seems like the wrapper fails to communicate with the ST itself properly" is wrong. 

Information I'm waiting for:

1. Does opening in an external browser work?
2. The contents of the Elements and Network tabs from Chrome
3. The full contents of the Console tab (not just the two messages your screenshotted)

**Comment by scienmind** [comment]
Now, it just happened again, and here's the info:

Elements:
![image](https://cloud.githubusercontent.com/assets/11633330/16766378/76a5b2d2-4842-11e6-834d-c83708b495e8.png)
Console (the two line are all there is...):
![image](https://cloud.githubusercontent.com/assets/11633330/16766465/f7b5f8aa-4842-11e6-82e3-212540c83adb.png)
Network:
![image](https://cloud.githubusercontent.com/assets/11633330/16766394/8a45d5c4-4842-11e6-94c4-f27d38609ea0.png)

Seemingly "nothing is alive" there. 
Though once again the syncing is up and running, files do fly around. 
Build-in inotify/watcher seem not to be active however.
And for whatever worth, here's `http://localhost:8385/debug/pprof/goroutine?debug=2` contents: https://gist.github.com/anonymous/f31e8f71380cd6c9bc090f0d2c0b7a32

Upon trying to access the GUI via external browser, the result turned out to be the same (!). All blank.
Which leads to the following: 

The thing that I didn't think about, is that following the discussion on [restartOnWakeup setting](https://forum.syncthing.net/t/question-about-restartonwakeup-setting/2222/7), I disabled it.
And this issue I'm having is appearing after wake-from-sleep. So, maybe there's an issue with that on the Syncthing's side. Also, here's the original issue regarding restartOnWakeup: https://github.com/syncthing/syncthing/issues/565 .

**Comment by canton7** [comment]
> Upon trying to access the GUI via external browser, the result turned out to be the same (!).

Not a SyncTrayzor problem, then. Please open an issue with Syncthing.

**Comment by scienmind** [comment]
For future info:

The issue was caused by setting "GUI Listen Address" to `pc_name:port`
In that case, it'll bind to a current IP, and in case of network switch/IP change, it'll stay bound to the old IP.
Setting "GUI Listen Address" to `0.0.0.0:port` achieves the same effect of accessibility via other devices by `pc_name:port` while resolving the issue of sticky-binding to old IP addresses.
