### ISSUE TITLE
Folder selection dropbox not working

### ISSUE THREAD

**Issue by ogrfnkl** [canton7/SyncTrayzor#297]
Hello! I have just started using SyncTrayzor, and it's a great tool, but I have discovered an issue with it: the down arrow on the folder path box (in the Add Folder window) does not do anything. I can still type into the box, but I can't browse the folders. The workaround, of course, is to open Syncthing in a browser window, and then it works just fine, but still, I hope this issue can be fixed in SyncTrayzor.

Cheers,
Oleg.

**Comment by canton7** [comment]
Yeah, there's a workaround in place, which removes the drop-down and replaces it with a 'Browse'  button. However, due its rather hacky nature, it doesn't always take effect. I thought I'd finally got it nailed down on 1.1.11, but apparently not... 

Refreshing the browser window usually fixes it.

**Comment by ogrfnkl** [comment]
I just tried refreshing the browser, but the dropdown still didn't work... There is still the other workaround, though --opening the Syncthing console in an external browser-- so all is good. I'll look forward to an update with a fix... Thanks!

**Comment by canton7** [comment]
What version are you running?

**Comment by ogrfnkl** [comment]
v0.14.0 Windows 64-bit

**Comment by canton7** [comment]
What version of SyncTrayzor, I mean.

**Comment by ogrfnkl** [comment]
Sorry, it's 1.1.12.

**Comment by canton7** [comment]
Can you try 1.1.11? I changed how the hack was implemented between those two versions.

**Comment by ogrfnkl** [comment]
Yep, indeed, v1.1.11 has the Browse button working properly. Is this version free of any serious issues, so I can keep using it for now, until a fix is available for the browse bug?

**Comment by canton7** [comment]
I think you misunderstand. Both versions have the same browse button in them, it's just applied in slightly different ways. The way in 1.1.12 was supposed to be more reliable, and it has been in my testing, but presumably not in your case... 

That's the only difference between 1.1.11 and 1.1.12 though, so using 1.1.11 is fine.

**Comment by ogrfnkl** [comment]
Ok, got it, thanks!

**Comment by canton7** [comment]
(Reverted for 1.1.13)

**Comment by canton7** [comment]
(This was fixed a long time ago).
