### ISSUE TITLE
Upgrade Syncthing from 0.12 to 0.13

### ISSUE THREAD

**Issue by urza** [canton7/SyncTrayzor#298]
Hi, I have Synctrayzor version 1.1.11 and Syncthing version 0.12.23

I would like to upgrade syncthing to latest 0.13 (but not 0.14 because my NAS will be stuck with 0.13 for a while)

How can I do that, thanks.

**Comment by canton7** [comment]
Follow the instructions [in the README](https://github.com/canton7/SyncTrayzor/blob/master/README.md#using-syncthing-beta-releases) (although use 0.13 instead of a beta release, of course).

**Comment by urza** [comment]
Sorry to bother you with this, but I still dont know how to upgrade Synctrazor to have the latest version of Syncthing.

I have Synctrazyror full instalation (not portable, not "raw" syncthing). I re-installed SyncTrayzor with latest release, but still the version of Syncthing is stuck at 0.12..
There is no upgrade button in the Syncthing GUI... neither nowehere in Synctrayzor menus..

Please, what can I do?

**Comment by urza** [comment]
Ahh nevermind, my mistake, got it upgraded by your instructions about beta releases. I didnt see that at tha page at first.

But will I have to do this every time? I would like both synctrayzor and syncthing keep auto updating.

**Comment by canton7** [comment]
No, Syncthing version 0.12.23 was buggy, and stopped auto-upgrading after a period of time, hence the need for manual intervention.

**Comment by urza** [comment]
Ah ok thanks
