### ISSUE TITLE
SyncThing version 0.14.0 is out

### ISSUE THREAD

**Issue by StefH** [canton7/SyncTrayzor#299]
Can we just use latest SyncTrayzor, or do you need to create an update?

**Comment by scienmind** [comment]
You can use the latest SyncTrayzon with syncthing 0.14 just fine. 

Just keep in mind:
 - you'll need to move whole cluster to 0.14 since it won't communicate with 0.13
 - all folders will be rescanned after upgrading to 0.14, so for large repositories it may take some time

**Comment by canton7** [comment]
Yep, any version since 1.1.9 supports Syncthing 0.14.
