### ISSUE TITLE
Memory leak when closing to tray / restoring

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#3]
Memory leak when repeatedly closing to tray / restoring.

Caused by the view tree being retained, probably by DependencyPropertyDescriptor.AddValueChanged.

**Comment by jkaberg** [comment]
As you might expect, I'm also seeing this but as you said keeping it minimized helps a lot

**Comment by canton7** [comment]
Right, a combination of removing those DependencyPropertyDescriptor.AddValueChanged's and moving from WPF's WebBrowser (which seems to leak unmanaged memory left, right, and centre) to CefSharp seems to have 1) fixed the problem, and 2) reduced running memory consumption to the region of 90megs, which is quite a nice improvement. I'll get those changes in soon.

**Comment by canton7** [comment]
In develop, will be in the next release
