### ISSUE TITLE
Custom /data location config

### ISSUE THREAD

**Issue by chrisshearing** [canton7/SyncTrayzor#30]
It would be extremely useful if SyncTrayzor exposed the location of the \data folder, instead of the hard coded \appdata or \currentfolder,

Specifying a location outside of \appdata or \currentfolder is useful for enterprise environments which use mandatory profiles, but also wish to keep applications separate from user data.

it would be useful to be able to specify this as either a registry setting, or ideally on the launching command for SyncTrayzor, so different \data directories could be specified for different users.

**Comment by canton7** [comment]
I knew this would pop up sooner or later :smile: 

I think a command-line switch might make the most sense here? That would match what Syncthing does. Although there is some added complexity in that, if you're letting SyncTrayzor maintain its own auto-start registry key, it will want to keep rewriting it, and will remove the flag.

Currently, whether or not force Syncthing to use a custom data directory is handled through SyncTrayzor's config file. Would you also want a command-line flag to override this?

**Comment by chrisshearing** [comment]
looks like you have a PortableMode True/False flag in the SyncTrayzor config file to switch between \appdata and \currentfolder for the data directory?

being able to put a custom value in here would probably be enough - especially if you allow environment variables, for instance in our case we would use a folder such as C:\LocalSettings\%username%_sync

This would give every user on that device their own settings for SyncTrayzor and syncthing with it.

If the config file supports custom path and environment variables, I can't see a need for the command line flag?

Thanks for the quick response! :)

**Comment by canton7** [comment]
If that's generic enough for you, sure. The limitation is that every user will be forced to use the same general pattern for SyncTrayzor's data directory, but env vars will always provide a workaround I guess...

There's no automatic substitution of env vars here, but I can add that in easily enough.

**Comment by chrisshearing** [comment]
That would fit our needs perfectly!  We tend to work from fixed settings, which have variables in, to be manipulated on in user sessions. It saves having to configure applications per user, which often will be in locations users don't have access to write anyway!

Thanks!

**Comment by canton7** [comment]
Cool, suits me. I'll schedule this for the next release.

**Comment by canton7** [comment]
Would you also want the ability to override the default config? For example, the default config will check for new versions and prompt the user to download them, but that's unlikely to be desirable in a corporate setting...

**Comment by chrisshearing** [comment]
Ah yes, updates would fail as we run users as limited, so they wouldn't have access to update, but could cause errors,

I've not moved past the initial investigation yet as we had the data folder location issue,

So an option to disable updates in the .config would be useful

**Comment by canton7** [comment]
I think probably what I'll do is put the default config in `SyncTrayzor.exe.config`, so you can put whatever defaults you like in here. The auto update mechanism just prompts the user to download the latest installer - we won't fall over in any way. Would that suit?

**Comment by chrisshearing** [comment]
That sounds perfectly fine - much better being able to configure defaults in the install directory than having to worry about registry tweaks per user or anything!

**Comment by canton7** [comment]
Righty, v1.0.10 should contain everything you need. Take a look in SyncTrayzor.exe.config, and feel free to shout if you have any more questions.

Be aware that I'm not guaranteeing backwards compatibility in SyncTrayzor.exe.config. Upgrading SyncTrayzor but not updating SyncTrayzor.exe.config may lead to a crash.

**Comment by chrisshearing** [comment]
Working well so far, managed to install into a read-only location for the program files and store config into another folder - able to start testing the rest of the functionality but looks good so far!

Thanks for the fix!

**Comment by canton7** [comment]
Awesome! You've probably figured out that you need to set `SyncthingUseCustomHome` to `true` in the "DefaultUserConfiguration", in order to make Syncthing use `SyncthingCustomHomePath` for its data, but just in case... You probably also want to set `NotifyOfNewVersions` to `false`, and consider `SyncthingRunLowPriority`.

Let me know if you run into any issues, or if there are some more options you'd like to have at your disposal.

**Comment by canton7** [comment]
@chrisshearing heads-up: the format of `SyncTrayzor.exe.config` is changing slightly in v1.1.3. The same information is there, but the path to it is slightly different.
