### ISSUE TITLE
Disable right click or add a proper context menu

### ISSUE THREAD

**Issue by syrys** [canton7/SyncTrayzor#300]
SyncTrayzor is great. I just have One small issue with it. I use this in windows x64, installed few days ago, and i have a habit of just right clicking. To be honest, when you see the folders/devices it feels like right click is a logical thing to do for editing/deleting etc.

Anyway, when you right click within the app, you get a typical windows/browser context menu that shows "back/forward/print/view source". The annoying thing is, this menu doesnt dissapear. No matter how many times i click within the app, away from the app, this menu just sticks at the top like a bug in windows. Only way to get rid of it is to actually click one of the options, and clicking "back" breaks the ui )(obviously).

I feel like this is probably a very quick flag you set somewhere to disable the menu (if its not providing any benefit anyway), is there any chance this can be done?

Cheers.

**Comment by canton7** [comment]
Ok odd, it definitely used to show a custom menu with Cut/Copy/Paste. An upgrade to the embedded browser must have broke that... Let me take a look.

**Comment by syrys** [comment]
@canton7 let me know if you would like a screenshot or anything.

Also, maybe this might be a feature request, but is there any reason why the installer doesnt set this up as a service or auto start with windows? Just did a restart (the PC) for the first time after installing and realised that it didnt start up, and i would probably need to setup the autostart manually if i want it to do that (which i would assume a very common usecase to expect auto start).

**Comment by canton7** [comment]
I can reproduce the issue here, so that's fine.

It does have autostart functionality. The installed version will set itself to start on login in the first time that it's run; the portable version won't set itself up by default. There's a checkbox in File -> Settings -> Automatically start on login.

**Comment by syrys** [comment]
@canton7 Oh yes i see the option. Thanks.

May i suggest making that option ticked by default? TBH, not sure why anyone wouldnt want it to auto start haha :P

**Comment by canton7** [comment]
It is ticket by default in the installed version. The portable version is supposed to be put on portable media and moved between machines: there's not much point in setting up autostart for something which probably won't be plugged in!

**Comment by syrys** [comment]
@canton7 
i can verify that using the latest installer mentioned below, i did not get the auto start ticked by default. I installed it on 3 machines (i havent tried any other clients on 2 of the machines), and fresh download each time, and definitely not the portable download, each with the same problem. Not a big deal for me, as i can easily tick that now i know where the option is, but just pointing it out as its probably worth looking at :)

Installer i used: https://github.com/canton7/SyncTrayzor/releases/tag/v1.1.12
*X64.exe (the windows x64 exe file)
Each of the machines were using Windows 10 X64.

PS. thanks for the advice and help

**Comment by canton7** [comment]
Oops, looks like I broke the automatically enabling autostart... Let me fixed that!

**Comment by canton7** [comment]
If you want a fixed up context menu, try this: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.12.400/artifacts.

**Comment by syrys** [comment]
@canton7 perfect, context menu works.

im curious, this project is pretty much a wrapper for the default UI that syncthing provides right? Meaning that you guys cannot do anything to do with the UI changes to the app (besides the UI of the wrapper like the window's menu and the console etc). Is that correct?

**Comment by canton7** [comment]
Yes and no.

In principle I just display the html which Syncthing's GUI gives me. In reality, I run some very hacky javascript when the page is loaded, which does things like add the 'Browse' button next to the input box for file paths, and the 'Open Folder' buttons on the folders.

**Comment by jaxankey** [comment]
I also just downloaded a fresh copy from this site and the right-click context menu does not disappear. This is on Windows 10 x64

Regarding the browser, I would suggest a preference to specify the default browser we want to use, in case something happens to the Trayzor browser like this.

**Comment by jaxankey** [comment]
I also agree with syrys: This no-thinking packaged version of syncthing is fantastic.

**Comment by canton7** [comment]
> I also just downloaded a fresh copy from this site and the right-click context menu does not disappear. This is on Windows 10 x64

Weird, OK thanks for reporting. That's another data point...

> Regarding the browser, I would suggest a preference to specify the default browser we want to use, in case something happens to the Trayzor browser like this.

It uses Windows' default browser. I don't see the point in overriding this? I just ask Windows to open a URL, and it figures out how best to do that based on your preferences

**Comment by jaxankey** [comment]
I'm confused. When I double-click the tray icon, it brings up the
SyncTrayzor browser, no? I like this (in particular the console at the
bottom), but may want to change it in the future.

**Comment by canton7** [comment]
Right, I didn't get that you wanted a different browser to open *instead of SyncTrayzor*.

Two thoughts:

1. Double-clicking the tray icon hasn't broken for you, has it? Nothing's stopping you from launching and using SyncTrayzor from the tray icon. It's just the convenience shortcuts when you right-click the tray icon which has gone wonky.
2. Not being able to launch SyncTrayzor kinda defeats the entire point of SyncTrayzor. There are plenty of other minimal tray icons which just launch an external browser when clicked. Use one of them.

**Comment by jaxankey** [comment]
You're totally right, though I would argue that synctrayzor does something
much more important: bundling, and lowering the install / config barrier.
Figuring out everything necessary to get syncthing, a nice tray, and a
monitor to work together, and configuring autostart may seem trivial /
worth it to people already comfortable with syncthing, but can be daunting
to those who are not even sure if syncthing is the right system for them.
It is a big deal to migrate data and trust a new system!

If this solves my problems with resilio sync, you and the syncthing crew
can expect some beer money :)

-Jack

Sent from sender's phone with typos. Sender not liable for inflammatory
autocorrects.
