### ISSUE TITLE
Move auto-update script to Github pages

### ISSUE THREAD

**Issue by OliverCole** [canton7/SyncTrayzor#305]
You could move the data/instructions from server_check.php to a separate Github pages repo.

You would need to reimplement the logic in the client, and keep the old server up for a while, but when all done, people would be able to trust the update process a little more.

**Comment by canton7** [comment]
Why? The point of `version_check.php` (not `server_check.php`) is that I can dynamically take the SyncTrayzor version and variant, and recommend a suitable upgrade. The keyword there is "dynamically"  - github.com pages serve static content only, and aren't capable of running a dynamic script. 

I'm not sure I follow the "trust" argument either. Users already trust me. They are running software which I made. Why is a domain and server which I control less trustworthy than github pages? Don't forget that releases are signed also: SyncTrayzor won't install an update which wasn't signed by my private key, so even if someone did compromise the update page, there's no way they could get people to install a malicious update.

**Comment by canton7** [comment]
...  It also means that I'm dependent on github. If github goes down for an extended period, or if I decide to move somewhere else, I can't.

**Comment by OliverCole** [comment]
I agree Github is only static - that's why I said you would need to reimplement some of the logic in the client. If you host a static file, consisting of a list of releases, and their recommended actions/URLs, you can let the client take care of it.

You would be tied to GitHub if you used the github.io hostname - but you could always use a CNAME and move it somewhere else later. (https://help.github.com/articles/using-a-custom-domain-with-github-pages/)

I only thought about this because of the section "Will SyncTrayzor phone home / give away my secrets / etc?" - I figured it was something you were concerned about if you bothered to write that :)

I didn't manage to find the URL, but is it running the latest TLS settings etc? Using something like GitHub would avoid maintaining that. Even if the releases are signed it provides defence in depth.

**Comment by canton7** [comment]
>  If you host a static file, consisting of a list of releases, and their recommended actions/URLs, you can let the client take care of it.

No. The whole point of the system is that the client is not in charge of it. It used to work as you describe - except that I just used the list of releases from the github api - and it was inadequate. The current system lets me do things like forcing a particular upgrade path through the versions, or only recommending a particular upgrade to a particular subset of affected users. 

> I only thought about this because of the section "Will SyncTrayzor phone home / give away my secrets / etc?" - I figured it was something you were concerned about if you bothered to write that :)

Moving to github pages doesn't remove the motivation for that section: it will still say "no". 

>  Using something like GitHub would avoid maintaining that. Even if the releases are signed it provides defence in depth.

My understanding is that you can't use both a custom domain and https on github pages. 
 
I'm afraid this is not going to happen. I'm not going to spend my lunch breaks and evenings removing a powerful feature for no real reason. Sorry.
