### ISSUE TITLE
Conflicts system tray indicator persists after conflict resolved via remote device

### ISSUE THREAD

**Issue by PrototypeNM1** [canton7/SyncTrayzor#307]
When conflicts are resolved on a remote device, the system tray indicator for conflicts - and iirc other conflict indicators in Synctrazor - does not go away until the conflict resolver is opened. While a minor inconvenience, it is a completely unnecessary and distracting action to have to take, especially in conflict prone directories (e.g. Firefox profiles).

**Comment by canton7** [comment]
Bleh, that's a bug. It was ignoring notifications for deleted sync-conflict files. You can grab an intermediate build which contains this fix here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.12.404/artifacts.
