### ISSUE TITLE
Feature Request: Start/Stop Syncthing at Pre-Defined Hours (perhaps using Task Scheduler)

### ISSUE THREAD

**Issue by holyoaked** [canton7/SyncTrayzor#308]
Hey,

I'd like SyncThing to be started at a certain hour, and stopped at a certain hour. Is there a way to do this currently using Windows' Task Scheduler? If not, is such a feature on the roadmap at all?

**Comment by canton7** [comment]
Nothing built in.

It would be possible, but not particularly easy, to support in SyncTrayzor.

**Comment by canton7** [comment]
The work I've just done on #350 should make this possible using the Windows Task Scheduler.

Set it to call `Path\To\SyncTrayzor.exe --start-syncthing` when you want it to start Syncthing, and `Path\To\SyncTrayzor.exe --stop-syncthing` when you want it to stop Syncthing.

**Comment by canton7** [comment]
Fixed in v1.1.15.
