### ISSUE TITLE
Conflict resolver - Choose last modified

### ISSUE THREAD

**Issue by HyperCriSiS** [canton7/SyncTrayzor#309]
Hi,

I actually have over 2000 conflicts. Clicking them one by one is a real pain in the ass.
It would be helpful to have some options for choosing the last modified file automatically. 
Maybe change view to folder tree and so make it possible to choose actions for parent folders. 
Also it shows last modified only from one of the files.

Thanks and regards,
Hyper

**Comment by canton7** [comment]
Hi, sorry for the delay.

Allowing multiple selection of conflicts is possible. I've done a bit of work on it, but it's not going to happen right now.

**Comment by HyperCriSiS** [comment]
An option to choose always newest file would be nice.
I have to make over 2000 clicks now or how can I speed this up?
