### ISSUE TITLE
Running SyncThing as administrator

### ISSUE THREAD

**Issue by xenotech** [canton7/SyncTrayzor#313]
When I launch SyncThing.exe with Run As Administrator, it properly handled symlinks, but I can't seem to make this happen from SyncTrayzor, not even when I launch _it_ as administrator. Is there a solution to this?

**Comment by canton7** [comment]
Oops, sorry, this one slipped past my radar.

If you launch SyncTrayzor as an administrator, it should launch Syncthing as the same user. I don't do anything special to change the user it launches Syncthing as...

**Comment by canton7** [comment]
Closing as no response
