### ISSUE TITLE
Do not support Chinese IME

### ISSUE THREAD

**Issue by ivysrono** [canton7/SyncTrayzor#314]
Could not input Folder name by Win10's Chinese IME.

Win10 x64 Zh-CN
SyncTrayzor 1.1.12 x64

**Comment by canton7** [comment]
Does it work if you open syncthing in a browser?

**Comment by ivysrono** [comment]
@canton7 It is ok if I use syncthing in a browser directly.

**Comment by canton7** [comment]
Weird, must be something to do with the embedded browser I use. I'll search their issue tracker.

**Comment by canton7** [comment]
This is an issue with the embedded browser control, see https://bitbucket.org/chromiumembedded/cef/issues/1019 and https://github.com/cefsharp/CefSharp/issues/1262. 

I've implemented what the CefSharp guys says is a workaround, but I don't have a Chinese IME to test. I'm planning to release later today - mind testing it and letting me know whether it works?

**Comment by ivysrono** [comment]
I will test as soon as possible.

**Comment by canton7** [comment]
Thanks, I'll let you know when the new release is out.

**Comment by ivysrono** [comment]
1.1.13 has fixed this issue.
Thanks.

**Comment by canton7** [comment]
Fantastic, thanks for letting me know!
