### ISSUE TITLE
Folder names instead of IDs in tray tips

### ISSUE THREAD

**Issue by benshep** [canton7/SyncTrayzor#315]
Can we have an option for the tray tips to show folder names instead of IDs? The IDs are usually auto-generated and therefore not very meaningful.

Thanks!

**Comment by canton7** [comment]
What version are you running? This [should have been fixed in v1.1.11](https://github.com/canton7/SyncTrayzor/blob/master/CHANGELOG.md#v1111).

**Comment by benshep** [comment]
Sorry, I didn't look at the changelog. Here's a sample tray tip (I presume it's ok to post IDs?):

![traytip-showing-id](https://cloud.githubusercontent.com/assets/5038790/19268550/f9522d94-8fac-11e6-8780-1830e9e19147.png)

I'm running 1.1.12 on Windows 7 64-bit.

**Comment by canton7** [comment]
Oops, looks like I missed out those ones. I'll get that fixed, thanks for spotting!

**Comment by benshep** [comment]
Thanks for responding so quickly :)

**Comment by canton7** [comment]
Fixed! The fix will be included in the next release, [or you can download an intermediate build which has the changes](https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.12.408/artifacts).
