### ISSUE TITLE
Rename "Restore" option

### ISSUE THREAD

**Issue by JohnVeness** [canton7/SyncTrayzor#320]
I have the settings "Close to tray" and "Start Minimized" ticked, which means that whenever I start my PC, and most of the time in general, SyncTrayzor sits in the system tray. When I right-click on its icon, the top option is "Restore".

Given that many people treat Syncthing as something like a backup application (I realise it is not really), the word "Restore" here is slightly ambiguous, as people might take it to mean something to do with restoring old files.

Also because, with "Start Minimized" ticked, the user isn't conscious of having closed or minimized the window, and because in general users aren't, I believe, very familiar with the terminology of maximizing, minimizing, and restoring windows, this is doubly confusing.

I suggest that top option be renamed to something like "Show user interface". Maybe a little survey of other programs that minimize to the system tray could be carried out to see what they call bringing up the main UI.

**Comment by canton7** [comment]
Fair point. The other apps in my tray all use "Open", so I guess that's probably a better option.
