### ISSUE TITLE
Feature request: Sync only when plugged in

### ISSUE THREAD

**Issue by benshep** [canton7/SyncTrayzor#327]
Syncthing on Android has an option to only sync when the phone is charging. This is really useful since Syncthing is quite CPU-intensive. Can we have this option built into SyncTrayzor as well please, for use on laptops? (I like the option to pause on a metered network - it could work like that.)

**Comment by scienmind** [comment]
Seems like a duplicate of #283

**Comment by canton7** [comment]
Ah yeah, you're right. Closing as a duplicate.

**Comment by benshep** [comment]
Apologies - I did do a quick search but I must have missed it.
