### ISSUE TITLE
Notification services

### ISSUE THREAD

**Issue by Hydro8** [canton7/SyncTrayzor#335]
Hi

I don't know if it's possible but can we have notifications like pushbullet or pushover when a sync is starting ?

My internet is very low here and I would like to have a notification to my android system (with pushover) to know when a file is start sync and when it finish.

**Comment by canton7** [comment]
I'm afraid this has very little relation to what SyncTrayzor does - there's almost no overlap.

I'm sure there's scope for a different application which talks to Syncthing and sends notifications, but I don't see that it fits into SyncTrayzor.
