### ISSUE TITLE
Feature request: Perform action on new files

### ISSUE THREAD

**Issue by benshep** [canton7/SyncTrayzor#337]
Since SyncTrayzor includes a filesystem watcher, it would be nice if I could define actions that would take place when new files were received (or added locally, or modified). The particular use case I have in mind is this:

- Copy files from my camera to my laptop
- Laptop syncs with desktop via Syncthing
- Movie files are automatically processed on desktop using ffmpeg (to convert to H264)
- Processed movies synced back to laptop

I'm picturing an 'Actions' GUI something like this:

![synctrayzor actions gui](https://cloud.githubusercontent.com/assets/5038790/22650470/47397e14-ec77-11e6-8649-281ae9275eb8.png)

**Comment by canton7** [comment]
Bear in mind that the filesystem watcher is going to be removed the minute that syncthing/syncthing#2807 gets merged.

**Comment by canton7** [comment]
There are loads of tools which will do this for you: [here's a list of some graphical ones](https://www.raymond.cc/blog/3-portable-tools-monitor-files-folders-changes/), and there are numerous command-line ones (which people use for things like recompiling web asset files on change).

I think that writing Yet Another one and integrating it into SyncTrayzor is the wrong thing to do, I'm afraid.
