### ISSUE TITLE
Prompt for update to new version on restore from sleep

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#34]
Currently we only check for new versions on startup. If people are like me, and almost never actually shut down their computers, they'll never know!

So prompt on resume, as well (`SystemEvents.PowerModeChanged`). Dismissing notifications for that version is just as little effort as saying "remind me later", so I'm not too worried about pissing people off with regular unstoppable alerts for a version they don't want.

**Comment by jkaberg** [comment]
This one is a big + for me, perhaps also checking on a intervall (once a day?)

My desktop almost never sleeps/is shutdown  so that would help

**Comment by canton7** [comment]
To be honest, once an interval may make more sense than on resume from sleep. People tend to turn their computers on with the intention of doing something **right now**, and annoying little popups that get in the way are just dismissed.

**Comment by canton7** [comment]
OTOH, we currently use a modal dialog to prompt for updates, as we can include the changelog. This is acceptable when logging in / starting up, but probably not at random points throughout the day!

Using the tray icon just feels a bit Java though. I think people arae conditioned to ignore those.

**Comment by canton7** [comment]
Any preferences, @jkaberg? Would a tray notification annoy the hell out of you? :P

**Comment by jkaberg** [comment]
It would, atleast on every login as I tend to do a lot of thoes when I'm at school ;)

But a notification; if for example lets say it schedules to announce at 12.00 and my laptop is shutdown, it could then notify me when I turn on the laptop again and login
