### ISSUE TITLE
Feature request: Manage remote syncthing instances

### ISSUE THREAD

**Issue by cdrfun** [canton7/SyncTrayzor#340]
I'm quite certain that many users of SyncTrayzor have servers lying around they are maintaining to back their syncthing infrastructure.

I imagine a option to add the credentials of these serers in the settings und make them available inside of a tab.

This way adding new folders to the infrastructure would be more easys, because you have your remote servers right at hand and don't need to navigate to them externally.

Minimum Features would be:

- Setting to define multiple remote servers with credentials
- Option to open remote server web gui
- Display remote server web gui in tabs

I can think of more features, too:

- Display syncthing console of remote servers
- Open (configured) remote servers from inside the web gui (maybe this would better be a synthing feature?)
- Automatically add new folders to remote servers based on a default location (maybe this would better be a synthing feature?)

**Comment by canton7** [comment]
So, basically a web browser, but a bit worse? Why not just use a normal web browser?

> Display syncthing console of remote servers

No can do. The console output comes from Syncthing's stdout, and you can only get this if your process started Syncthing.

> Open (configured) remote servers from inside the web gui (maybe this would better be a synthing feature?)

Not sure what this means I'm afraid. "Open" in what sense?

> Automatically add new folders to remote servers based on a default location (maybe this would better be a synthing feature?)

Again not sure what "based on default location" means in practice, but automatically adding folders to Syncthing is not something that I want to do.

I think your request is best served by:

* Open your web browser, and create a bookmark for each Syncthing instance. If you need to add credentials, you can do that by adding a bookmark to `https://username:password@your.syncthing.instance:8384`.
* Put all of the bookmarks in a folder
* Tell your web browser to open all of the bookmarks in that folder as separate tabs (e.g. by right-clicking on the folder).
