### ISSUE TITLE
Feature request: Sync a volume

### ISSUE THREAD

**Issue by canneasucre** [canton7/SyncTrayzor#342]
Hi
Do you think it would be possible to sync a volume like a TrueCrypt volume which never "apparently" change please ?
Thank you for your work.

**Comment by canton7** [comment]
Please ask these sorts of questions on the [Syncthing forum](https://forum.syncthing.net).

[Here's the result of searching for 'truecrypt'](https://forum.syncthing.net/search?q=truecrypt) on those forums, which contains posts explaining how to solve your issue.
