### ISSUE TITLE
cannot parse recent config.xml

### ISSUE THREAD

**Issue by sirber** [canton7/SyncTrayzor#347]
Latest synctrayzor cannot parse config.xml created by syncthing v0.14.24, Windows (64 bit)

**Comment by canton7** [comment]
SyncTrayzor never attempts to parse Syncthing's config.xml.

**Comment by sirber** [comment]
I tryed to move my working syncthing (standalone) to synctrayzor. I ran synctrayzor, closed it and moved my data into ./data , where I saw xonfig.xml. Maybe I used the wrong folder?

**Comment by canton7** [comment]
You're using the portable version, I assume?

There's `data\config.xml`, which is SyncTrayzor's config file. There's also `data\syncthing\config.xml`, which is Syncthing's configuration file.

[As the README says](https://github.com/canton7/SyncTrayzor#migrating-between-raw-syncthing-portable-and-installed-synctrayzor), copy Syncthing's data into `data\syncthing`.

**Comment by sirber** [comment]
thank you!
