### ISSUE TITLE
How to change display language of built-in web browser?

### ISSUE THREAD

**Issue by dmsierra** [canton7/SyncTrayzor#35]
May be it is too easy, or may be it is not possible yet, but I cannot find how to change the language of the built-in web browser to just display in english. It uses my windows language, which I don't want to.

Thanks,
Diego.

**Comment by canton7** [comment]
Not yet possible I'm afraid. I'll put something into the next release.

**Comment by dmsierra** [comment]
On 21/03/2015 13:05, Antony Male wrote:
> Not yet possible I'm afraid. I'll put something into the next release.

Thanks for your prompt reply, Antony!

-- Diego.

**Comment by canton7** [comment]
I'd like to also add a gui option to change SyncTrayzor's language, but it's somewhat complicated by the fact that Syncthing and SyncTrayzor support different languages, and SyncTrayzor's language can't be changed without restarting it...

I'll come up with something! Im tempted to just have a checkbox for "use system language for both Syncthing and SyncTrayzor" and leave it at that.

**Comment by kreischweide** [comment]
Otherwise you could also iterate over `CultureInfo.GetCultures(CultureTypes.SpecificCultures)` to create a dropdown and send the string towards the browser? Tough that would also complicate things

**Comment by canton7** [comment]
Kinda confusing if Syncthing doesn't actually support the language the user selected!

**Comment by canton7** [comment]
Righty, v1.0.10 contains a setting which should do what you want

**Comment by dmsierra** [comment]
Yes it does, and it works, I can have syncthing and SyncTrayzor both in english or on my computer's language.

Thanks!

**Comment by canton7** [comment]
Thanks for letting me know!
