### ISSUE TITLE
Way to pragrammatically start Syncthing under SyncTrayzor

### ISSUE THREAD

**Issue by pyhedgehog** [canton7/SyncTrayzor#350]
It's sometimes required to free up memory for some "heavy" process (be physical model emulation or game). One can send API request (`POST /rest/system/shutdown`) to stop Syncthing. But how to restart it after process is completed (programmatically)? After running "raw" Syncthing SyncTrayzor doesn't catch-up it's status (and obviously can't see logs).
It would be very useful to be able to send some control event to SyncTrayzor.
Possible solutions:
 * **Easiest:** `RegisterWindowMessage`
 * **Best:** When Syncthing is down open same TCP port and accept several REST endpoints (using same API key from config file) and close this port before starting Syncthing itself.
 * **Portable:** Use separate port for API.

**Comment by canton7** [comment]
You could potentially pause all folders / all devices instead. Not sure how much memory that would free..

**Comment by canton7** [comment]
I think listening on Syncthing's port is only going to cause confusion: if something is trying to talk to Syncthing, sometimes it's going to get SyncTrayzor, which is going to behave differently.

Listening on my own port is also complicated. Multiple instances of SyncTrayzor are allowed to run at once, so each will have to look for a different free port. This makes finding the correct port for a particular SyncTrayzor instance more tricky. Granted Syncthing already does this. 

SyncTrayzor already supports some very simple IPC, using named pipes. This is used to bring an already running instance to the foreground if the user tries to run it again. Adding extra functionality to this would be the easiest option, but users need to know SyncTrayzor's PID to find the named pipe (or go searching, of course).

**Comment by canton7** [comment]
Actually, I've got a better idea: Add a new command-line flag to SyncTrayzor, e.g. `-start-syncthing`. If SyncTrayzor wasn't already running, it will start and also start Syncthing. If it was already running, it will tell the running instance to start Syncthing, using the existing IPC mechanism.

**Comment by pyhedgehog** [comment]
Maybe it will even better to publish "existing IPC mechanism"? It's exactly what I'm asking for.

**Comment by canton7** [comment]
My point that I tried to make is that it's not easy to use, since you need a language which can deal with named pipes, and a means to find the PID of the correct running SyncTrayzor instance. Also currently this mechanism only supports bringing the SyncTrayzor window to the foreground, which is not what you need... 

Like I said, a better approach would be to allow you to invoke the SyncTrayzor executable with suitable command line flags, and it will manage finding the PID if the already running instance in the way that islr currently does. The new command line flags and the new messages to communicate over the named pipe would need to be added.

**Comment by pyhedgehog** [comment]
So current workaround - stop SyncTrayzor with Syncthing and start it as on login?

**Comment by canton7** [comment]
Currently, yes

**Comment by canton7** [comment]
Right, I've got something in. It's available in the intermediate build here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.14.441/artifacts

Mind trying it out, see if it works for you?

**Comment by pyhedgehog** [comment]
@canton7 Excellent! Works for me.
