### ISSUE TITLE
different syncthing instances

### ISSUE THREAD

**Issue by dtxl** [canton7/SyncTrayzor#351]
With testing syncthing, I also looked at SyncTrayzor for a more handiness. I recognized that it is possible to run syncthing e.g. from the command line and to additionally start another instance with SyncTrayzor. I've seen that SyncTrayzor has the menu *Kill all Syncthing processes*.
Although this might be by purpose, different running instances can be problematic if not recognized.

Is it possible for SyncTrayzor not just to start a syncthing process, but to recognize already running ones and e.g. tell about it, or e.g. to offer to close it first?

Thank you

**Comment by canton7** [comment]
Not really, no. It's perfectly valid to run multiple Syncthing instances, each having a different database location.

**Comment by dtxl** [comment]
Yes, under the circumstances you mentioned different instances of syncthing are fine, I agree.  But it's also easily possible to make a mistake with that. My question is therefore not to kill running processes, but to inform about it and maybe to offer to close it first (not to do it automatically).

**Comment by canton7** [comment]
It would be a bit annoying, though? If you had set up multiple Syncthing instances correctly, then every time you started SyncTrayzor you'd have to OK this warning.

**Comment by dtxl** [comment]
Yes, this is of course true. The Windows way might be to add a check box of the kind *do not warn me anymore*. But this is then a question of whether the effort to code it at the end pays. I cannot rate that.

**Comment by canton7** [comment]
Yeah, then you get to the trade-off. On the one hand, a bit of work here, and a bit of work for the translators. On the other hand... What's the issue? We already show a sensible error message if Syncthing fails to start because another Syncthing instance is running, and we point the user towards the "Kill all Syncthing instances" button.

In other words, what does this suggestion bring that we don't have already?

**Comment by dtxl** [comment]
Mmh, I tested it again. You are right. If a syncthing instance has been started with SyncTrayzor to start another one as command line gives a warning because the database is already used and it quits. The other way around I get now the same. My mistake. Sorry for the noise.
