### ISSUE TITLE
Chocolatey package update

### ISSUE THREAD

**Issue by tunisiano187** [canton7/SyncTrayzor#352]
Hello,You didn't have updated the chocolatey package.
Can you  do it?
Thank you.

**Comment by canton7** [comment]
Darn, my bad. Done!

It will take a bit of time to make its way through the moderation procedure.

**Comment by canton7** [comment]
Since the Chocolatey package is just a wrapper around the installer, it should have auto-updated fine anyway, I think?

**Comment by tunisiano187** [comment]
Yes but i use your software in my courses ... so my students will install it, it can be better to install the latest version...
Thank you very much.

**Comment by canton7** [comment]
Aha, I see. 

Apparently it's through moderation now, btw.
