### ISSUE TITLE
Graphics driver issues (?) on Windows 10 Creators Update

### ISSUE THREAD

**Issue by TeutonJon78** [canton7/SyncTrayzor#355]
I installed the W10 Creator Update that released today on several computer and SyncTrayzor is now crashing on startup. Syncthing.exe run by itself runs fines. I had also just updated to 1.1.15, so not entirely sure if the issue is just the W10 1703 update or 1.1.15 or both.

It is happening consistently on several computers, but not all.

Windows 10 64-bit (all crashing versions are Home, not sure if that matters)
Intel GPU crashes on a Surface 3 and NUC 5i5, but works on another Atom Z8300 (Chinese) and Z270i + 7700k setup.
Core2Duo with legacy AMD driver is fine (only version running W10 Pro).

The SyncTrayzor log itself shows nothing related to any crash -- it looks like a normal startup.

3 Windows Applications Events are generated in this time order:
1: .NET Runtime
Application: SyncTrayzor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFBA7A0FD0C

2: Application Error
Faulting application name: SyncTrayzor.exe, version: 1.1.15.0, time stamp: 0x58dd61e2
Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416
Exception code: 0xc0000005
Fault offset: 0x000000000000fd0c
Faulting process id: 0x2d44
Faulting application start time: 0x01d2ae79ecc3563b
Faulting application path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: dfbc466f-055b-4f7b-99d5-f3385bc71168
Faulting package full name: 
Faulting package-relative application ID: 

3: (Windows Error Reporting Event)
Fault bucket 120728567036, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: SyncTrayzor.exe
P2: 1.1.15.0
P3: 58dd61e2
P4: d3d9.dll
P5: 10.0.15063.0
P6: 631de416
P7: c0000005
P8: 000000000000fd0c
P9: 
P10:

**Comment by canton7** [comment]
Hi, thanks for reporting!

Would you mind editing `C:\Users\<You>\AppData\Roaming\SyncTrayzor.config.xml`, and changing `<DisableHardwareRendering>false</DisableHardwareRendering>` to `<DisableHardwareRendering>true</DisableHardwareRendering>`?

**Comment by TeutonJon78** [comment]
[On a side note, I had also done a full uninstall and reinstall leaving only the syncthing settings there.]

OK, edited the file. The startup got further -- the SyncTrayzor window popped up with the console at the bottom. Then it crashed again. There is more info in the SyncTrayzor log, but it's still only normal info -- nothing about the crash. It ends up generating the same error events as started in the report.

Rand syncthing.exe alone again, it still works as expected. Then I ran the program again, it got further again (the GUI came up in the SyncTrayzor window), then it crashed. Slightly different info on this second round:

1: .NET Runtime (different address)
Application: SyncTrayzor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFBBD19FD0C

2: Application Error
Faulting application name: SyncTrayzor.exe, version: 1.1.15.0, time stamp: 0x58dd61e2
Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416
Exception code: 0xc0000005
Fault offset: 0x000000000000fd0c
Faulting process id: 0xafc
Faulting application start time: 0x01d2aef43b941858
Faulting application path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: adbbd92a-bc8a-4d9e-bba3-75ae2b8a8c93
Faulting package full name: 
Faulting package-relative application ID: 

and the 3rd WER, but that doesn't really provide anything useful.

**Comment by canton7** [comment]
You're now hitting #355. Please try the suggestion in there, and let's continue this discussion in there.

**Comment by TeutonJon78** [comment]
Uh, this is 355. Did you mean to link another bug?

**Comment by canton7** [comment]
Yeah, I got confused. I then deleted that comment.

**Comment by TeutonJon78** [comment]
Deleted the cef cached uner {user}/AppData/Local/SyncTrayzor

It got further again -- it connected to another syncthing instance and popped up the notification and then crashed. The .NET address was different again, but the Application Error report was identical again.

**Comment by canton7** [comment]
Right, I'm more and more convinced it's the embedded browser.

Can you try this intermediate build (when it finishes building, in about 5 mins)? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.15.460

**Comment by TeutonJon78** [comment]
Installed 64-bit. It has the same crash and same signature. Browser element stated up (although no syncthing interface was actually rendered this time -- it stayed white) and then crashed. Still no trace info in the SyncTrayzor log itself.

To give more info -- it leaves syncthing.exe running in the background since it obviously can't clean up after itself in a crash.

**Comment by canton7** [comment]
OK, I've upgraded to RS2 and can't reproduce it. 

I'll have a think about what else might be affecting it... I'd suspect something's up with your Direct3D installation, since that's what's crashing out.

**Comment by TeutonJon78** [comment]
Seems like other programs are having the same issue with RS2 -- Windows Firewall Control -- https://www.wilderssecurity.com/threads/windows-firewall-control-4.347370/page-120#post-2665703

**Comment by canton7** [comment]
Just for fun, try the 'Sample Application' from here: http://opensource.spotify.com/cefbuilds/index.html. Try starting it both with and without `--multi-threaded-message-loop --off-screen-rendering-enabled`.

**Comment by TeutonJon78** [comment]
Before, I try that one, I reinstalled the latest Intel drivers (which seems to be older than what RS2 tried to install). SyncTrayzor is now seeming to work -- however, with the build you had me install first, the in-app syncthing GUI is still all white. I'll try the new builds.

**Comment by canton7** [comment]
Which is "the build you had me install first" and which is "the new builds", exactly?

**Comment by TeutonJon78** [comment]
1.1.15.460 if the build currently running on the computer. Before and after the graphics card driver installation, it had an empty white square for the syncthing interface, but the browser could still pull the interface up at localhost:8384. It crashed just like 1.1.15 official before the graphics driver reinstall.

The "new" builds I was talking about were the CEF sample applications -- so, not really a new build at all.

It seems more to the point that MS messed up something in the CU update as it relates to some of the intel drivers.

**Comment by canton7** [comment]
Yeah, it's starting to look that way. I'll release a new version soon (before April 11), in case other users have that empty white square issue.

**Comment by TeutonJon78** [comment]
So....it seems to be working on the Surface 3 now (1.1.15). I also put the NUC back to 1.1.15 from 1.1.15.460, and it still works (and the GUI renders again -- so that was confined to 460 with the white box).

I reinstalled 1.1.15 official on the NUC, and it still works, even though Windows updated the Intel driver back to the CU version. So, something either got corrected with the driver reinstall, or Windows CU fixed something in the driver it was pushing out. So.... I don't know what the bug was in the end. :/

**Comment by JLJTGR** [comment]
So, I appear to have this same issue on one of my two Creator Update PCs.

Working: i7-4820K (no internal GPU), AMD R9 270X
Not-working: i7-6700K, Nvidia GTX 1070

My Windows Event Viewer data seems the same as the OP except for the PID, datetime, etc.
Tried using `<DisableHardwareRendering>true</DisableHardwareRendering>`, tried deleting the CEF cache, running the Windows SFC validation.
Tried using v1.1.15.460

Tried running the application as admin... the only change was that it was able to write **debug.log** to the Program Files folder.
```
[0410/133139:ERROR:gpu_child_thread.cc(260)] Exiting GPU process due to errors during initialization
[0410/133139:ERROR:browser_gpu_channel_host_factory.cc(133)] Failed to launch GPU process.
[0410/133139:ERROR:browser_gpu_channel_host_factory.cc(133)] Failed to launch GPU process.
```

For me, I never get as far as getting a user interface... but it usually starts minimized anyways.

I guess I'll try driver reinstalls, though the Intel GPU is unused and the other driver is the one I installed manually.

**Comment by JLJTGR** [comment]
So, here's the interesting part that I've observed.

If you start it normally, it just crashes out because it tries to load the user interface.  If you start it with the `-minimized` flag, it will start hidden, load syncthing.exe and be somewhat happy.  But if you mouse-over the tray icon or anything similar, that's where it crashes.  I assume that the hover-status on the icon uses CEF somehow or something else HW graphical.

I later tracked this down to RivaTuner Statistics Server(comes with MSI Afterburner).  Think FRAPS except its sole purpose is an FPS overlay.  I guess it intercepting the d3d9 calls was causing issues for the first time with the Creator's Update.  Telling it to ignore SyncTrayzor completely stopped the crashing.

Though 1.1.15.460 was giving me a blank screen where SyncThing's web interface should be.  Downgrading to 1.1.15.0 restored the UI.

In the end, my specific run-in with the problem doesn't seem like something you can fix.  It's a weird interaction with d3d hooking and the new Windows update.

**Comment by TeutonJon78** [comment]
I looking around the web at similar issues, I found lots of threads over the years about D9 programs corrupting the stack at runtime. Apparently, a "bad" program can mess it up for future programs that then look like they are crashing in the d3d9.dll stack.

One of the other threads tracked it down to MSI Afterburner as well. For the two computers that were experiencing it and are now working, I don't know the culprit would be -- my guess might be NoMachine or KeePass since those are the only things really running in the background).

And I had the same thing -- it would work as long as you didn't access the interface. On boot/login, it would seem to work till you touched the icon. On manual start it would just crash. But again, I only reinstalled the intel drivers, which autoupdated back to the CU version anyway, and now it's working again.

**Comment by JLJTGR** [comment]
I actually had a similar problem with the previous large Windows 10 update.  A popular way for modders to enhance games was to put a d3d9.dll or similar into the game's folder to get loaded into memory.  The DLL would get loaded, run its initialization and then pass through all d3d calls to the real DirectX.  The previous big update made that method fail because Microsoft modified the real d3d9.dll and so the passthrough failed somehow.

Lots of programs do this sort of injection using one method or another.  The afore mentioned FRAPS, Riva Tuner Statistics Server, Steam Overlay UI, Xbox Gamebar UI.  The ways all of these methods worked never seemed that safe to me, so when Microsoft comes in with big changes...

**Comment by hoerst** [comment]
I had the same problem. After updating RivaTuner (that was installed with MSI Afterburner) to the new 7.0 beta, the problem is gone.

**Comment by canton7** [comment]
Thanks for your input everyone! 😄 @JLJTGR's theory seems pretty plausible, so I'm inclined to say it's not something I have any control over.

Anyone who tried 1.1.15.460, did you also see the issue where the Syncthing area of the screen is white after starting Syncthing? If so, I might roll that upgrade to the embedded browser back...

> On boot/login, it would seem to work till you touched the icon

@TeutonJon78: by "touched the icon" do you mean double-clicking it only, or did single-clicking it also cause a crash?

> But if you mouse-over the tray icon or anything similar, that's where it crashes

@JLJTGR: can you confirm that even mousing over the tray icon causes it to crash? If so that's really weird, as it shouldn't care about mouse-overs.

**Comment by JLJTGR** [comment]
With RivaTunerStatisticsServer 6.6, mousing over the SyncTrayzor tray icon will crash it with no clicking needed.  I don't know if this tells you anything, but SyncTrayzor seems to spawn another copy of itself while it is crashing and then everything but syncthing.exe closes.
![image](https://cloud.githubusercontent.com/assets/5780236/25066523/03220dea-21f6-11e7-8a47-6bdf8ca4c086.png)

1.1.15.460 shows a blank browser on one of my machines and a different machine works fine.

**Comment by TeutonJon78** [comment]
I only tried 1.1.15.460 on one machine, and it always showed the blank browser. So, something is wrong there. Even on that build, opening up the syncthing GUI directly in Chrome (which was on v57, so newer than the CEF to moved too), rendered just fine. And again, reverting to 1.1.15 build worked fine -- so something isn't working right in the upgrade you did.

Regarding the icon, just mousing over the icon (no clicking needed) would cause it to crash. I never did figure out what the problem app was for my setups. One started working after reinstalling the intel driver (which then autoupdated back to what it was anyway), and the Surface 3 just started working. However, MS had pushed out that first update to CU by then, which had some graphical system fixes included (no real mention of what). If the Xbox Gamebar UI uses d3d9.dll, then that could have been the problem, as that is now installed by default in 1703 (so it could have been fixed by a Windows store update).

I agree, it seems like whatever the culprit was, it seems like not SyncTrayzor's fault.

**Comment by canton7** [comment]
>  I don't know if this tells you anything, but SyncTrayzor seems to spawn another copy of itself while it is crashing and then everything but syncthing.exe closes.

That's completely unexpected - SyncTrayzor doesn't know how to spawn extra instances of itself.

> Even on that build, opening up the syncthing GUI directly in Chrome (which was on v57, so newer than the CEF to moved too),

CEF and Chrome aren't particularly closely related, and the fact that Chrome works is by no means an indication that the corresponding version of CEF will not experience issues. On top of that is the wrapper used to make CEF work within WPF, which introduces a raft of other possibilities

**Comment by JLJTGR** [comment]
>> I don't know if this tells you anything, but SyncTrayzor seems to spawn another copy of itself while it is crashing and then everything but syncthing.exe closes.

>That's completely unexpected - SyncTrayzor doesn't know how to spawn extra instances of itself.

Then I guess it's more likely the same behavior that runs WerFault.exe when it crashes tried to restart the crashing process.  Sometimes Windows offers to do that with a dialog box.

**Comment by TeutonJon78** [comment]
I figured out what was causing the trouble for my systems -- being logged into NoMachine on the remote computer. Synctrayzor worked fine with nomachine running on the host, but as soon as I would log into that machine remotely, synctrayzor would crash on mousing over the icon in the system with the D3D9 problem.

If I logged into the machine via TeamViewer, syncthing would stay active.

**Comment by canton7** [comment]
@TeutonJon78 great, thanks for the info! I'm not sure there's anything I can do about that, I'm afraid.

**Comment by TeutonJon78** [comment]
Just to update -- NoMachine dev reproduced the error and are working on a fix. The short term fix is to disable GPU acceleartion on the NoMachine server.

https://www.nomachine.com/forums/topic/logging-in-with-nomachine-causes-d3d9-dll-errors-in-other-programs

So, it seems like this bug can be closed, if you want @canton7, as it's not related to SyncTrayzor directly. I'm not sure if you want the bug open for tracking the other changes you made.

**Comment by canton7** [comment]
Aha, thanks for the update.

I rolled back the update I made to the embedded browser after feedback earlier in this thread, so I don't think there's anything left to track.
