### ISSUE TITLE
(Enhancement) Toast notification support for Windows

### ISSUE THREAD

**Issue by jebeld17** [canton7/SyncTrayzor#356]
It would really be nice to see Synctrayzor use native Windows toast notifications. This will a) match the UI of the OS and b) work seamlessly with the users' current notification settings on Windows 10.
Microsoft literature on toast notifications:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification

Toasts sample:
https://code.msdn.microsoft.com/windowsdesktop/Sending-toast-notifications-71e230a2/sourcecode?fileId=51046&pathId=1435720579

[ToastNotification_PSD&XCF.zip](https://github.com/canton7/SyncTrayzor/files/904092/ToastNotification_PSD.XCF.zip)
![toasttest](https://cloud.githubusercontent.com/assets/9492083/24778352/22df6ad8-1af8-11e7-953c-866e795656bf.png)

**Comment by canton7** [comment]
Interesting suggestion: I wasn't aware these existed.

It looks like they're Windows 8 and up only? I'll have to make sure we do something sensible of Windows 7. The docs you linked are for UWP, but from some quick googling around it looks like it's possible to use them from Desktop applications, if you're prepared to P/Invoke.

**Comment by canton7** [comment]
Ah, although doing the appropriate things if the user clicks 'Accept' are going to be more complex than you think. It's going to involve modifying Syncthing's config and posting it back. I've avoided doing anything which requires posting back a modified config as the config format changes fairly rapidly.

**Comment by jebeld17** [comment]
As an alternative, why not change the theme of the original toast notifications to something more modern that the user sees everyday? Something like my example :)

**Comment by canton7** [comment]
I'm not sure I follow. I use the standard Windows notifications. I ask Windows to show the notification, and it shows it. It looks like every other notification on Windows. How is that not something that the user sees every day?

**Comment by jebeld17** [comment]
I'm sorry, I mean for app updates and left-clicks to the tray icon. I just made that photo as an example

**Comment by canton7** [comment]
I've tried to keep the toast notifications in line with the rest of the SyncTrayzor design - which is the default Windows look and feel. The recent transfers popup looks very similar to the DropBox one, as well.

However, I'm a programmer, not a designer. If you have concrete proposals then I'd be very happy to consider and discuss them. Otherwise, there are more important things to work on.

**Comment by jebeld17** [comment]
@canton7 how would you like designs saved? I can do PSD, AI, XCF, you name it. :-)

**Comment by canton7** [comment]
Anything which can be viewed with freely-available tools 😄

**Comment by jebeld17** [comment]
I had them included in my post.
Here is the link again, though! :-)
**_[Toast Notification PSD and XCF Working Files](https://github.com/canton7/SyncTrayzor/files/904092/ToastNotification_PSD.XCF.zip)_**

**Comment by canton7** [comment]
We were talking about:

> I'm sorry, I mean for app updates and left-clicks to the tray icon.

Your post had a mockup for a hypothetical "accept device" notification.
