### ISSUE TITLE
net framework 4.6.2

### ISSUE THREAD

**Issue by maravento** [canton7/SyncTrayzor#358]
SyncTrayzor does not recognize net framework 4.6.2 (only 4.0x-4.5x)
Windows 7 SP1 x86 x64
Note: If the OS does not have netframework installed and net framework 4.6.2 is installed for the first time, SyncTrayzor does not recognize it and requests that netframework 4.0x need to be installed

**Comment by canton7** [comment]
No, I'm running it on .NET 4.6.2 on my machines and it's fine. .NET 4.6 is an in-place upgrade to 4.5: apps which target 4.5 automatically run on 4.6. SyncTrayzor does not run on 4.0 at all.

Please send a screenshot of "SyncTrayzor does not recognize it and requests that netframework 4.0x need to be installed".

**Comment by maravento** [comment]
You are right. Works with 4.6.2. The problem was Windows, which apparently lacked some essential packages. I did several tests on VMs and all successful. Thank you

**Comment by canton7** [comment]
Cool, thanks for letting me know!
