### ISSUE TITLE
Make "Select Multiple File Conflicts" more discoverable

### ISSUE THREAD

**Issue by hyronx** [canton7/SyncTrayzor#359]
First of all, good work! I'm using SyncTrayzor on Windows and it really increases Syncthing's usability there.

Like the title says, it would be cool if you could add this option which applies this rule to all conflicts (maybe named like the Windows Explorer one but I don't this in English).
I had to choose the newer version around 300 times which got boring after some time. 😆 

Version: 1.1.15
Syncthing: v0.14.26

**Comment by canton7** [comment]
You can select multiple entries with ctrl-A (or there might be a right-click option? Not sure). From there you can select newest for all.

I should make this more discoverable, so I'll leave the issue open.

**Comment by hyronx** [comment]
Okay, haven't seen that.. Thanks!
