### ISSUE TITLE
Launch SyncTrayzor and syncthing as low priority

### ISSUE THREAD

**Issue by PazerOP** [canton7/SyncTrayzor#360]
Every time it refreshes my folders (which contain 50k+ items total), there's a periodic CPU usage spike. I'd like to minimize this spike as much as possible by having SyncTrayzor and syncthing run as low priority. I could write a small utility to keep these two processes at low priority, but I'd prefer something built in.

Although I can't see how this is relevant, this is required info apparently:
SyncTrayzor version: 1.1.15
syncthing version: 0.14.27

**Comment by canton7** [comment]
You can set the priority of the Syncthing process in the SyncTrayzor settings. You can't set the priority of the SyncTrayzor process this way, but it won't be the one creating the CPU usage spike on rescan.

**Comment by PazerOP** [comment]
Ah, my apologies. I wasn't aware there was a separate set of settings for SyncTrayzor.

**Comment by canton7** [comment]
Yeah there is a bit of an awkward split between the two applications, it's true. Not much I can do about it though I'm afraid.
