### ISSUE TITLE
SyncTrayzor doesn't start

### ISSUE THREAD

**Issue by RangerLpm** [canton7/SyncTrayzor#364]
Version: 1.1.15.0; Variant: Installed; Arch: Amd64
Path: P:\SyncTrayzor\SyncTrayzor\SyncTrayzor.exe
System.IO.IOException: Das Zeitlimit für die Semaphore wurde erreicht.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   bei SyncTrayzor.Services.Ipc.IpcCommsClient.SendCommand(String command) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Ipc\IpcCommsClient.cs:Zeile 53.
   bei SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:Zeile 123.
   bei Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:Zeile 81.
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
I have never seen that one before! Interesting... I'll put some handling in for that.

**Comment by RangerLpm** [comment]
Thank you. I'll test a reinstall tomorrow.

**Comment by canton7** [comment]
This intermediate build will fix it: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.15.461/artifacts

I should really release that...

**Comment by RangerLpm** [comment]
Thank you! It works! 😄

**Comment by canton7** [comment]
Fixed in 1.1.16.
