### ISSUE TITLE
Enhancement: Choose Tray Icon

### ISSUE THREAD

**Issue by jebeld17** [canton7/SyncTrayzor#375]
Please add the ability for the user to choose his or her tray icon for Synctrayzor, in replacement of the default.

**Comment by canton7** [comment]
Why? I don't know of any other application that lets you do this. 

In addition, making a correct tray icon is hard. You need 6 different ico files, each one containing specific resolutions, and the lower resolutions done in a specific way so they don't look rubbish. It took me months with the help of various people to get it right: I don't expect that your average user will manage it.

**Comment by ivellios** [comment]
I think this feature would be at really low priority. But I would suggest, that if you - @jebeld17 - want this to happen, you should consider just contributing this feature via PR.

**Comment by canton7** [comment]
There's also the question of branding. We're talking about the Syncthing application, which has its own branding. Should we really give the user the option to remove that branding?

**Comment by ivellios** [comment]
Well, I think some users want to customize their desktop as strong as it is possible. And I would respect that. But still, it should be minor feature with low priority. If someone does that, why not? Unless there are any legal/license issues with that. I think there's none.

**Comment by canton7** [comment]
Do you know of anyone who actually wants this, or are you asking me to spend my time on it on the off-chance that someone out there might want it?

**Comment by jebeld17** [comment]
It is just a small change. I could do it myself, but I was thinking about others' who want a small amount of UI customization like myself - and for myself in future use aspect, when I install this on a different PC. It would make it much easier to have a small piece of the software let me choose a photo to replace the current shell icon.
This isn't a big priority or anything, it was just a small enhancement idea - kudos to @ivellios for stating this! :)

**Comment by canton7** [comment]
> It is just a small change

But that's the whole problem - as an outsider, you're saying "this is a small change, why don't you do it?". In fact, it's actually quite a big change. But you never asked that question - you assumed it was a small change, and went from there.

> I could do it myself

Depends how much free time you have 😄. If you have enough free time, I'd much prefer to spent it helping out with the features which users have requested.

To make this vaguely user-friendly, you'd need to build a UI where the user selects image files for each of the 3 resolutions for each of the 6 icons. You'd need validation - did the user actually select correct solutions with the correct formats. You'd need logic to build up the ico files from there. In reality users are never going to break out an image editor and create 18 new images, just to change a tray icon. So maybe you want to add functionality which takes a base image and rotates it for each of the 4 orientations, then overlays the pause and warning symbols, and attempts to scale it to each of the 3 required resolutions. But the pause and warning symbols are probably going to look horrible unless you can move them around or change them a bit, so you need to be able to tweak what happens there, and before you know if you're well on your way to building a basic image editor application.

**Comment by canton7** [comment]
Closing this as unrealistic. If you want to embed an image editor into SyncTrayzor, contributions welcome.

**Comment by Eucaly** [comment]
This would be useful for [multiple SyncTrayzor instances on the same PC](https://github.com/canton7/SyncTrayzor/issues/148#issuecomment-145544583). I tried that with two portable instances under different folders, and the same Windows user name. Up and running !!

Under such condition, it helps to identify the two (or more) instances by different icons. 
Maybe not totally different icons, but with some tweak as:
* different color
* overlay letter or color dot on some corner

Please consider to re-open this issue.
