### ISSUE TITLE
Feature Request: Sync local folders

### ISSUE THREAD

**Issue by Sirove** [canton7/SyncTrayzor#376]
How about adding a function to sync local folders? I mean if the program can sync files and folders across devices then it should be possible with local folders, right? :)

**Comment by canton7** [comment]
That's a Syncthing issue, not a SyncTrayzor. If you look at the [Syncthing Forum](https://forum.syncthing.net) and [Issue Tracker](https://github.com/syncthing/syncthing/isuses), you'll find plenty of discussions on this.
