### ISSUE TITLE
Does setting a folder to be watched in SyncTrazor override setting Rescan Interval to 0 in Syncthing?

### ISSUE THREAD

**Issue by jdrch** [canton7/SyncTrayzor#38]
Brand new user here. Does setting a folder to be watched in SyncTrazor override setting Rescan Interval to 0 in Syncthing? Reason I'm asking is the default Rescan Interval value (60s) in Syncthing absolutely nails my CPU. Ideally I'd like to disable polling entirely and just have the Watched Folders feature catch changes on demand. Is this doable?

**Comment by jkaberg** [comment]
No, see https://github.com/canton7/SyncTrayzor/issues/9

**Comment by canton7** [comment]
You can edit the rescan interval in Syncthing's UI - click 'Edit' next to the folder, and it's right there.

SyncTrayzor doesn't currently try to override this, as @jkaberg said. I'm toying around with some ideas, but finding something intuitive is tricky (having two places to set the same value is always counter-intuitive).

**Comment by jdrch** [comment]
Yeesh. Welp, I'm trapped between the BitTorrent Sync Android client being broken and Syncthing rendering 2 of my PCs unusable due to CPU (and also seriously slowing my Android device down).

**Comment by canton7** [comment]
Can you post your logfile somewhere? I curious as to what Syncthing is doing...

**Comment by jdrch** [comment]
It's 20 MB. Can I upload it to Google Drive and email it to you?

**Comment by canton7** [comment]
OK, something interesting's hapepning if it's that large :stuck_out_tongue_closed_eyes: 

Sure, or post to gist.github.com and link in here. Whatever you fancy.

**Comment by jdrch** [comment]
I don't think that's a great idea from a privacy perspective ...

**Comment by canton7** [comment]
Do whatever you feel most comfortable with.

**Comment by jdrch** [comment]
I emailed you at antony.male@gmail.com. Thanks and let me know what you think.

**Comment by canton7** [comment]
Got it, thanks. As of around about 2015-03-23 21:08, local scanning has finished, but devices EQ3BGQJ and OZHLA4M are still scanning and indexing (and local files are occasionally updated). The local device was processing index changes from the remote devices at the point the log ended.

Overall, the network is still getting itself in sync. I'd give it a while longer, then I'd expect CPU usage to be down to usual.

**Comment by canton7** [comment]
Closing off, as the user's disappeared, and it's not my problem anyway
