### ISSUE TITLE
SyncTayzor shows an empty window

### ISSUE THREAD

**Issue by basil-lion** [canton7/SyncTrayzor#382]
SyncTayzor 1.1.16
Syncthing 0.14.32-rc.2

Syncthing is working (files being in sync). WebUI is working fine. SyncTayzor shows an empty window.

![image](https://user-images.githubusercontent.com/29046292/27858261-3aca1a14-617d-11e7-85b7-20f875a1431f.png)

**Comment by canton7** [comment]
Did this happen since an upgrade? Has it been working previously?

**Comment by basil-lion** [comment]
It was working fine... and the same version is working fine on other machines. However, on one specific machine this issue occurred, and triggering factor was multiple sequential reboots of this machine. (I did technical reboots 2-3 times due to installing new HW)

**Comment by canton7** [comment]
Weird. I've seen something similar with Syncthing upgrades before.

Try deleting `C:\Users\<you>\AppData\Local\SyncTrayzor\cef\cache`

**Comment by basil-lion** [comment]
I did this 4 days ago (numerous times, without any success)
1. Stopped all services
2. Deleted "C:\Users\<you>\AppData\Local\SyncTrayzor\cef\cache"
3. Started services

Re-tried this + service/system restarts, then dropped attempts to fix it.
Syncing was in fact working, but interface failed to show anything.

Yesterday morning (!) is started to work fine again. I have not done anything.
So for now all is OK. Still have no clue why that happened and what fixed it.

I think this issue may be closed. (unless you want to investigate it)

**Comment by canton7** [comment]
The next step would be to grab some logs from the embedded browser component, but I'd need to give you a special build for that, and if it's started working again then that isn't going to help....

Various people have seen issues where the embedded browser stops working due to interference from another application (#335 being the latest). My guess is that some application of yours updated itself and broke my embedded browser (and the update only kicked in after a reboot), then it fixed itself recently (again, after a restart).

**Comment by basil-lion** [comment]
Yes, that is possible... Windows always updating something. I see whole bunch of updates on 26 Jun, and since I do not reboot my system often - it is possible that something broke with the update in embedded browser.

I recalled another thing which might be relevant - trying to restore browser functionality I disabled WiFi interface, and rebooted my PC with just Ethernet present. In a while browser started to work. I'll test it out and report back if this is the case.

Otherwise I'm going to close this issue.

**Comment by jebeld17** [comment]
Is your computer also running abnormally slow? #412

**Comment by canton7** [comment]
@jebald17 please stop linking to your issues all over the place!

**Comment by jebeld17** [comment]
@canton7 my issues with Synctrayzor include the screen not showing up full when the program is slowing down my unit. I believe this could be linked if the issue @basil-lion reported has other characteristics of my reports.

**Comment by canton7** [comment]
No this is not related. Your issue was that the window stopped responding, because SyncTrayzor crashed, as far as I can tell. This report is about the window responding, but the embedded browser is not displaying content correctly. Please leave linking issues to me: you're not helping.

**Comment by jebeld17** [comment]
Sorry. I should have noted the browser was not always refreshing the page properly in my bug.
