### ISSUE TITLE
Remote device Upload/Download rates are switched or misleading

### ISSUE THREAD

**Issue by cloo** [canton7/SyncTrayzor#383]
I've got only two connected devices, and both show ~1MiB/s upload rate, and both ~20kbps download. 
Makes no sense to me - one device is actually downloading at ~1MiB/s.

**Comment by canton7** [comment]
Is this in the main syncthing UI? If so, that's a syncthing issue.

**Comment by cloo** [comment]
Yes, that is main UI.

**Comment by canton7** [comment]
Post on the syncthing forum, then. SyncTrayzor just shows that UI, I didn't design it.
