### ISSUE TITLE
Eset detection for a variant of Generik.BVNZTSF trojan

### ISSUE THREAD

**Issue by lyndhurst** [canton7/SyncTrayzor#384]
Hi, 
I just got a detection from eset  NOD32 antivirus. And I would like to know if I should notify eset for a false positive, or if the infection is on my PC, and, not related to SyncThing, or SyncTrayzor.

It seems to be related to an upgrade to v0.14.32 .
I currently run Version 1.1.16, SyncThing Version v0.14.28 on windows 10 64 bit.

I had no problem running synctrayzor for the last 6 month or so, and the first detection might have been triggered after an automatic upgrade of SyncTrayzor with no interactions on my end. 

![eset_detect](https://user-images.githubusercontent.com/30077629/28070553-97029f5c-664d-11e7-8d9b-b8ee733f1d6e.PNG)
![sync_upgrade](https://user-images.githubusercontent.com/30077629/28070554-970610d8-664d-11e7-91ac-05441c0c8ac3.PNG)

After letting eset clean the suspicious file, I can restart SyncTrayzor, and, SyncThing seems to be starting correctly, but detection occurs as soon as I start the upgrade manually. 
Also, eset will not let me ignore the detection, and keeps popping up.

Thank you for your time.

This is the full log for eset detection with the path to file slightly edited:

Time;Scanner;Object type;Object;Threat;Action;User;Information;Hash;First seen here
11/07/2017 14:45:36;Startup scanner;file;Operating memory » \SyncTrayzorPortable-x64\data\syncthing.exe;a variant of Generik.BVNZTSF trojan;cleaned by deleting;;;888B473ADD74A445939AF88B6F474DF6525986A6;22/05/2017 14:40:27

**Comment by canton7** [comment]
That's reporting Syncthing, not SyncTrayzor. Look at the Syncthing forum - other people have been reporting similar things. Either way, it's not anything that I can solve - I write SyncTrayzor, not syncthing.
