### ISSUE TITLE
Bug with metered connection and VPN

### ISSUE THREAD

**Issue by jabacz** [canton7/SyncTrayzor#385]
Machine: Windows 10
Synctrazor is able to detect metered connection and pause syncing when network is expensive. This is great feature. But this feature fails when the VPN connection is made over the metered network.
I guess it's due to fact, that VPN cannot be set "as metered". Than synctrayzor detects primary network (VPN) as unlimited and starts syncing. This is bad, actually crippling the pause feature.
Please, can you modify to check all currently active networks and pause "if any is metered"?

best regards
thanks for great product :-)
Jan

**Comment by canton7** [comment]
This is how it works:

1. Your device connects to a remote device
2. I ask Window whether the IP of the remote device is metered
3. Windows says Yes
4. I pause the device

So no, it doesn't do detection of a "primary network" - it gets the cost of the IP of the remote device. What you're seeing is expected behaviour, and is not a bug.

I do not want to change the behaviour to pause all devices if any network is metered. This would users who have multiple connections, some of which are metered, and devices connecting over the unmetered connections.

Whether or not Windows correctly reports the VPN as metered is between you, Windows, and possibly the VPN provider. Another possibility would be to do your own detection of whether any network is metered, and tell SyncTrayzor to stop Syncthing (there are command-line flags for this).

You say:

> This is bad, actually crippling the pause feature.

Please explain what you mean: you should be able to pause/unpause devices in Syncthing just fine, even while SyncTrayzor is pausing devices because of metering. If you have issues around this, please provide details.

**Comment by jabacz** [comment]
Thanks for reply. I did not know how this is implemented. You do it from the central point of view, while I did expect the mobile device perspective.
The explanation is easy: I have few synced points across company network to keep data as much local as possible to the user while providing full data set to all.
There are also few workers with notebooks flying all around, mostly at mobile data. For these we got homebuilt simple utility, which detects active internet connection and fires up the VPN. This enables us to keep mobile workers as "connected to company". Eating mobile data and battery every time the mobile node is waking up is unbearable to mobile persons. They tend to manually copy data making even more mess :-) This is mean by the sentence with "crippling" :-)

I understand fully your perspective. 
Just think about the opposite way: while I'm at expensive data and battery I don't want to be synced. When I get back to convenient place, let's fire the sync up.
Maybe a config switch? Running as central hub _vs_ nomadic node?

I can try to to participate with the battery detection code, which we already have with the VPN restarter, if you find it helpful.

**Comment by canton7** [comment]
It sounds to be like you might not want to let users access the company's Syncthing devices over the VPN?

**Comment by jabacz** [comment]
Not really. When they are at home with fixed line and WiFi, or customers meeting room, or hotel WiFi the sync is welcome and needed. What I need is disable sync when on mobile tether or WiFi paid by volume.
I want to "not-sync" when the VPN runs over metered connection.
eg. my idea was: Check all  active network adapters. If any is metered detected, cease sync.

**Comment by canton7** [comment]
> Check all active network adapters. If any is metered detected, cease sync.

Easier than it sounds - the API in question is badly documented, and it took me a considerable amount of effort to get to the point I'm at now. You're welcome to have a go at figuring out the logic needed yourself.

**Comment by jabacz** [comment]
Sorry for delay in answer. I was to my vacation. 
I have found that API for this desired function is available for "Windows Universal applications" eg. Win8+ (not working with Win7 and older).  
We probably cannot call this API directly from the Synctrayzor, but I have managed a powershell script which returns desired answer. Invoking the powershell is easy task .... You are calling external OS commands anyway to run synthing, so it's not a big deal :-)
To be constructive, I want to ask you for a favor. I'm definitely noob in Github forking and pushing updates. Could you create a version (fork code for download) where you prepare dummy functions returning boolean "ConnectivityIsMetered"?
I will supply the code inside.
You will handle the surrounding like settings checkbox and merge this to pausing syncthing commands.
Can this proposal work for you?

**Comment by canton7** [comment]
I would prefer not to use the UWP APIs. There's already code do calling into the COM version, and it properly handles the API not being available. You'll also have to ask the OS to tell you when the meteredness of the connection changes (although that should be pretty similar to code I already have), and I don't think you can do that in a sensible way though powershell. 

Another complex part is how this interacts with the user manually pausing and unpausing devices. There's work around this in already, but I don't know ow how much it might need to be changed. 

I'm afraid I don't have time to do 80% of the work for you, at least in the short term, sorry. There are other issues on this issue tracker which are either bugs, or have been requested by multiple (very patient) people, which I really should address first.

**Comment by canton7** [comment]
To be honest, if you've got a powershell script working, just make it call SyncTrayzor.exe with command line flags to start or stop Syncthing (see what they are with --help)
