### ISSUE TITLE
custom home path doesnt seems to work

### ISSUE THREAD

**Issue by beerisgood** [canton7/SyncTrayzor#386]
I have my Syncthing unpacked in "E:\X\syncthing-windows-amd64" and use it for many months now, but now i try the switch to this more automatic tool. Thanks for it! 

For me this setting means, the syncthing.exe is used from that folder too, but SyncTrayzor always use "C:\Users\USER\AppData\Roaming\SyncTrayzor\syncthing.exe"
Why? In my config and sure a lot of more users restrict access to AppData and then SyncTrayzor doesnt work.

I get then that error:
![error](https://user-images.githubusercontent.com/9625159/28499854-91eb6faa-6fbf-11e7-8c88-6439b38f39b7.png)

**Comment by canton7** [comment]
There are settings to change where syncthing.exe and the syncthing config and database are stored. Look in the settings window.

**Comment by canton7** [comment]
Also the "Migrating between "raw" Syncthing, Portable, and Installed SyncTrayzor" section in the README, which was written to address your question.

**Comment by beerisgood** [comment]
Yes i found that setting with home path for Syncthing in the settings if you wish (Settings -> Syncthing -> Advanced -> Syncthing Custom Home Path) but sadly SycnTrayzor still try to start "C:\Users\<You>\AppData\Roaming\SyncTrayzor\syncthing.exe" which i dont want.
I also choice the installed version of SyncTrayzor

**Comment by canton7** [comment]
Ah yeah, that particular setting isn't in the user-editable settings.

You can use the portable version of SyncTrayzor. Put it in `E:\X\`. It will put its data, and syncthing.exe, in a `data` subfolder.

**Comment by beerisgood** [comment]
But i want use the windows autostart feature and auto update
Or can i do that with the portable as well?

Or another way is if that would be a user-editable settings in menu for installer version

**Comment by canton7** [comment]
Both of those are available in the portable edition.

beerisgood wrote:

**Comment by beerisgood** [comment]
Alright, then i will switch to the portable version.
Sad that the installed doesnt provide that

**Comment by canton7** [comment]
Contributions welcome!

**Comment by beerisgood** [comment]
Looks fixed cause it works as you told me in this issue: https://github.com/canton7/SyncTrayzor/issues/464

**Comment by canton7** [comment]
Yes, I fixed it on the 28th Feb, as it says above.
