### ISSUE TITLE
The status that SyncTrayzor shows is wrong

### ISSUE THREAD

**Issue by Lighfer** [canton7/SyncTrayzor#387]
What happened: The SyncTrayzor shows wrong status when files in sync, it's should be syncing instead of up to date. 
What expected to happend: The receiver shows same  status with sender(PS: sender 1 and sender 2 are different because of the time gaps I take screenshots.).

Receiver version: v0.14.33, Windows (64 bit) 
Sender 1 version: v0.14.33, Linux (64 bit) 
Sender 2 version: v0.14.33, Windows (64 bit)  

[Receiver screenshot](https://drive.google.com/open?id=0B36UgAsaN323akE4eGRaMk1hZ2c)
[Sender 1 screenshot](https://drive.google.com/open?id=0B36UgAsaN323N21Ednl3eUlJQ1E)
[Sender 2 screenshot](https://drive.google.com/open?id=0B36UgAsaN323dEVoWVNGOWtWY1k)

Syncthing Version: v0.14.33
OS Version: Windows 10 64 bit  / Ubuntu 16.04 64bit
Browser Version: Google Chrome  59.0.3071.115

**Comment by canton7** [comment]
You are looking at the Syncthing UI. This is a Syncthing issue. Please post on the Syncthing forum.
