### ISSUE TITLE
Expand 8.3 paths when notifying syncthing

### ISSUE THREAD

**Issue by AudriusButkevicius** [canton7/SyncTrayzor#388]
I'll look at doing that at Go land, but I guess it's easy to do that from C# too.

**Comment by canton7** [comment]
I already do. At least that's the intention - if you have details on where this isn't working, I'd love to hear them.

Details here: https://github.com/canton7/SyncTrayzor/blob/master/src/SyncTrayzor/Services/FileWatcher.cs#L237

**Comment by canton7** [comment]
Closing as no response.

**Comment by AudriusButkevicius** [comment]
Yeah, it doesn't look like it slipped through your gaps, but it somehow has via ours.
