### ISSUE TITLE
COMMENTS WANTED: Automatic Updates

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#39]
Right, time for a braindump around auto-updates.

The current auto-update stretegy is effectively but fairly crude. On every startup / resume from sleep, we check the Github API to see if there's been a new release. If there has, we show the user the changelog and ask them if they want to upgrade now, later, or never. If they select 'now', we take them to the release page, where they can download the installer and run it. If they select 'later', we'll try again on the next startup / resume from sleep. If they select 'never', we'll skip this version.

Ideally we want something a bit slicker. There are some thoughts:

UAC Prompts
-----------------

Do we want to bring up a UAC prompt? If not, we have two options: either install into AppData, or run an update service (modelled on [Mozilla's Silent Update](https://wiki.mozilla.org/Windows_Service_Silent_Update)).

I'm not a fan of installing into AppData. It:
 - Sidesteps UAC completely, which is a Bad Thing from a security point of view. Something malicious can pretend to by SyncTrayzor.
 - Prevents you from backup up AppData. You have to blacklist all applications which have snuck in there.

However, an update service has some downsides as well:
 - Slightly fiddly to get working
 - I'd want to give people the option to not install this (think of portable users, too), but then we need two upgrade mechanisms....

For most people, a UAC prompt is a simple yes/no checkbox, and for the people for whom it isn't, they're probably either under the control of a sensible Sysadmin (who installed SyncTrayzor, and will be responsible for updating it) or they're paranoid and wouldn't like us "bypassing" it anyway.

Another consideration is that I already have an installer infrastructure in place - Inno Setup - and this gives me a lot of control to tweak/move/do custom stuff on installation. Users also already have stuff installed into `Program Files`, and I'm not keen to duplicate SyncTrayzor around their systems!

Prompt the user?
---------------------

Do we prompt the user before installing an update, assuming we've automatically detected and downloaded it?

On the one hand, silent updates are nice. They force everyone into using the same version with zero effort. On the other hand, SyncTrayzor runs *all the time*. There's no chance for us to sneakily update when starting / stopping (as your browsers do). We could stop ourselves, update, start, and hope the user doesn't notice - but they might, and they'll be confused.

Not prompting the user will require a UAC bypass - users panic if they get a random UAC prompt, as well they should.

Another option is to show a little tray notification (we can show arbitary stuff as toast from the tray) saying "Hey, I've got a update, apply?" with "Yes", "Later", and "No" buttons. The "Yes" button could have that little UAC sheild on it, so the user isn't surprised when they get a UAC prompt. 

This is slick and avoids the "What happened there" factor, but we run the risk of being too similar to Java. Users might be conditioned to ignore update requests from the Tray, because Java does it constantly and annoys everyone. However, we could style it to be sufficiently different and friendly-looking....

What to download?
-----------------------

Any of the approaches described above will require SyncTrayzor to download a new installer from Github. Hower, knowing *which* file to download is actually tricky, and the reason I link to the release announcement rather than the actual file. When moving from 64-bit-only to 64-bit/32-bit I needed to rename the files available for download. I may need to do the same again in the future for another reason. This means I can't simply rely on the download file's name being something pre-determined.

One solution might be to create a little service hosted elsewhere. SyncTrayzor goes "Hey, I'm verison XXX on platform YYY - give me a new download link", and it gets one. That would also allow us to control the upgrade path to a degree. However, it does rely on a bit of extra infrastructure to work, which is something I try and avoid if I can.

Security
----------

In any approach where we automatically download something and effectively promise the user that it's legit, we run the risk of being hijacked, and having some mailicious party abuse the user's trust in SyncTrayzor to sneak something nasty onto their system. This is particularly true for the installation service scenario, but also true if we're prompting the user to accept a UAC prompt.

One solution would be to sign the installer, then SyncTrayzor would verify that the key used to sign it is one that I own. This wouldn't require buying a cert from a root authority (although I'm not sure how Windows behaves if you ask it to install an exe signed with an unverifyable cert, as opposed to not signed at all) - we're verifying that it was signed by *me*, not by anyone trusted by a root authority.

Another approach would be to provide the signature separately to the exe, and download both.

Update frequency
----------------------

I think it makes sense to move from "check on startup" to "check regularly, starting a suitable period after logon". When users turn on the computer, they normally want to do something. Upgrading random tools isn't one of those things. Prompting them when things are a big quieter would make sense.

Of course, this only applies if we do prompt them. If we silently update, this isn't so much of an issue.

Upgrading Syncthing
--------------------------

Syncthing currently auto-updates, which is why it's stored in AppData. I want to keep it auto-updating (I don't want to have to release a new version every week to match Syncthing's update schedule).

However, I am uncomfortable with sticking it in AppData, for the same reasons that I don't want to put SyncTrayzor there. If we run an update service we can use it to silently let Syncthing auto-update as a privileged user, and keep it in `Program Files`. If we go with prompts, we can still prompt users to allow Syncthing to auto-update.

Portable
-----------

The portable users form about 1/4 of installed users, so we can't ignore them. How to handle updates for them? The current system works - we could just keep it.

Summary
-----------

Let me know your thoughts! You're the people using SyncTrayzor, and I'll ultimately do what you want. Ping @jaredthirsk.

**Comment by eyeson** [comment]
My thoughts on this are; a tray notification saying "I need to be updated, yes, no" and like you said yes have the UAC symbol so people aren't surprised if they get a UAC request. For me this is the best, I am swapping from btsync to ST, and one of my complaints with btsync was on my non-techie families machines, they would often have a UAC request and they would always click no, not knowing what it was for, so btsync wouldn't get updated. If they had of seen the tray notification they are more than happy then to click yes. It also gives the opportunity for those that don't want to update for whatever reason to click not now or never etc etc rather than just do a silent update.

**Comment by canton7** [comment]
Thanks for your comments! Did BTSync just fire up a UAC dialog out of the blue? That's pretty poor IMO - I think we can do better than that :)

**Comment by canton7** [comment]
So I don't lose the link: http://stackoverflow.com/questions/24060009/checking-digital-signature-on-exe

**Comment by chucic** [comment]
I like the way it is now. I got tray notification, I could see changelog, there was nice and clean and fast installation and I didn't have to choose anything what I already chose before.

**Comment by rolve** [comment]
I see that this "issue" is already closed, but I thought one more comment cannot hurt too much. I'm using the portable version, so for me it would be a big improvement if SyncTrayzor updated (semi-)automatically. Right now, I have to go to the website, download the zip, shutdown SyncTrayzor, copy the files (making sure not to overwrite the `data` folder), and finally start SyncTrayzor again.

I think having a small notification asking "Update? - Yes - No" would be a good solution for both portable and non-portable versions, given that the UAC prompt would only be shown for non-portable versions. There could also be a setting "Update without prompt", which would arguably make more sense for portable users.

**Comment by canton7** [comment]
Fair request. I've got a couple of thoughts:

 - We currently verify the integrity of the downloaded installer by checking its digital signature. I don't *think* we can do the same for zips, so we'd have to come up with an alternative.
 - We currently handle installed version updates by running the installer in quiet mode. This gives us the scope to script some custom actions if the installation requires it, e.g. migrating some data. We'd have to invent a similar process for portable updates...

I'm imagining something like:

1. Download new zip
2. Verify (somehow)
3. Extract to a temporary location
4. Execute some sort of custom exe inside the newly-extracted archive, passing in the location of the current portable folder. That would copy over your data folder, etc.
5. Manage a swap of locations. Needs thinking about, as renaming a folder inside which a file is executing is somewhat painful. Maybe that custom exe would need to go into another temporary location.

**Comment by rolve** [comment]
I see, a solution that works for the portable version appears to be quite a bit more complex to implement. The approach you described sounds good to me though.

Regarding integrity verification, are you thinking about real security or just protection from random corruption? In general, I would try to follow whatever Syncthing is doing. I see that there are various checksum files, signed with GPG it seems. However, from a quick glance at the code it appears that the update process just checks the syncthing executable against an MD5 hash.

**Comment by canton7** [comment]
I codesign (in the Microsoft sense) the installers. The auto-updates verify the code signature, and check that it was created by my private key. This has the dual affects of ensuring there's no corruption, as well as making sure that no-one's intentionally fiddled around with it.

I could go down the syncthing-esque route of having a separate checksums file, and signing that, but I'd prefer to keep close to the approach I currently have if possible... Hrm. I'll mull this over for a few days.

**Comment by cryptogeek** [comment]
Hi, I'm a portable user. Thank you for taking portable users into account :+1: it would be awesome if the portable version could prompt in tray area when an update is available and then automatically update if user chooses so. I never tried the non-portable version but I think that 100% automatic updates is a necessary option because some users don't bother reading or clicking.

**Comment by canton7** [comment]
Portable users make up about 14% of the total user base, so I'm afraid that portable-specific features are always going to be near the bottom of the priority list :disappointed: 

For your specific case, you could use the installed version, but open by `SyncTrayzor.exe.config` and modify the `PathConfiguration` section to place your SyncTrayzor config and syncthing database inside your secure container. (You'll need to select "Use custom home directory for Syncthing" in the Settings page for

**Comment by canton7** [comment]
... although an upgrade will replace `SyncTrayzor.exe.config`, so that might not actually be the best idea...

**Comment by chucic** [comment]
> although an upgrade will replace SyncTrayzor.exe.config

Yeah, about that: #86
Although I realise that it wouldn't solve cryptogeek's issue.

**Comment by dodekeract** [comment]
I don't think it's the perfect solution, but I'm just leaving this link here, so that you at least know about it: https://chocolatey.org/ . It's like apt-get for windows. MIGHT be an acceptable solution.

**Comment by canton7** [comment]
While I'm not discounting chocolatey, I don't *think* it affects this at all - my understanding is that chocolatey will run SyncTrayzor's installer

**Comment by Rewt0r** [comment]
I'd definitely like a way to automatically download, extract and update the portable version so that I can instruct users to just click the update button rather than me having to remote into each machine and do it myself...

**Comment by canton7** [comment]
@Rewt0r don't you have an application deployment mechanism set up in your corporate environment? SyncTrayzor takes several steps to support such steps.

Also, what's your reason for not using the installed version?

**Comment by Rewt0r** [comment]
@canton7 the setup in this company doesn't use AD or even a domain controller, they all have laptops and log directly onto them. It's only a small company, and I'm implementing better IT processes for them from July/August time including introducing a DC. So there is no way to automate deployments at this time.

I've opted for the portable version to have everything stored under SyncTrayzor's folder rather than `%AppData%`

**Comment by canton7** [comment]
Closing this off: the portable installers are represented by #82
