### ISSUE TITLE
Version: 1.1.16.0; Variant: Portable; Arch: Amd64

### ISSUE THREAD

**Issue by youngfe** [canton7/SyncTrayzor#392]
Version: 1.1.16.0; Variant: Portable; Arch: Amd64
Path: D:\Youngfe\_Softwares\SyncTrayzorPortable-x64\SyncTrayzor.exe
System.UnauthorizedAccessException: 拒绝访问。

```
   在 Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   在 SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to) 位置 C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:行号 51
   在 SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) 位置 C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:行号 130
   在 SyncTrayzor.Bootstrapper.Configure() 位置 C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:行号 139
   在 Stylet.BootstrapperBase.Start(String[] args) 位置 c:\projects\stylet\Stylet\BootstrapperBase.cs:行号 81
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by youngfe** [comment]
Thank you for your response. But it was running very well before this Exception. I didn't change any permission on "Data" folder.

**Comment by youngfe** [comment]
Thank you for your response. But it was running very well before this Exception. I didn't change any permission on "Data" folder.

**Comment by canton7** [comment]
Please post the bit of your log file leading up to that exception.

**Comment by youngfe** [comment]
I renamed the "Data" folder to "Dataa". And after I started SyncTrayzor.exe again, There was a new "Data" folder created. But I still had this same Exception.

**Comment by youngfe** [comment]
2017-08-10 10:08:05.5542 #1644 [Info] SyncTrayzor.Services.ProcessStartProvider: Starting D:\Youngfe\_Softwares\SyncTrayzorPortable-x64\ProcessRunner.exe --shell  -- "https://github.com/canton7/SyncTrayzor/issues"  
2017-08-10 10:08:38.3289 #1644 [Info] SyncTrayzor.Services.ProcessStartProvider: Starting D:\Youngfe\_Softwares\SyncTrayzorPortable-x64\ProcessRunner.exe --shell  -- "explorer.exe" /select, D:\Youngfe\_Softwares\SyncTrayzorPortable-x64\logs\SyncTrayzor.log

**Comment by canton7** [comment]
I need more of the log - that snippet is not relevant.

Can you please email me the entire log file? My email address is on my GitHub profile page.

**Comment by canton7** [comment]
Hi, any response?

**Comment by canton7** [comment]
Closing as no response.
