### ISSUE TITLE
Suggestion to help with conflicts.

### ISSUE THREAD

**Issue by dgnuff** [canton7/SyncTrayzor#395]
I don't know if this would be possible, but is there some way SyncTrayzor could be set up to allow us to specify a difference tool is the settings somewhere, in a similar manner to TortoiseSVN.  You'd specify it as:

"C:\Program Files\MyDiffTool\diff.exe %1 %2"

and then when resolving conflicts we can hit a button on the Conflict Resolver window to execute the command, with %1 and %2 replaced by the two filenames.

**Comment by canton7** [comment]
#296 already tracks this.
