### ISSUE TITLE
Unhandled error: JSON integer x is too large

### ISSUE THREAD

**Issue by jkaberg** [canton7/SyncTrayzor#4]
While syncing my photo albums (120GB) to another computer I get this and SyncTrayzor crashes. When starting it again this is the first thing that comes up, and SyncTrayzor crashes

The sync progress made it roughly to 12% before this happend

![image](https://cloud.githubusercontent.com/assets/613363/6344999/8f877206-bc00-11e4-92a9-0f6750f35ab9.png)

**Comment by canton7** [comment]
That's a large repository to sync! It will have made it to 3.5ish gigs on a 32 bit int. I'll bump that up to 64 bits. 

The plan is to have fixes out for this and #2 by the end of tomorrow.

**Comment by jkaberg** [comment]
Appreciate it @canton7, really enjoying the "built-in" filewatcher :-)

**Comment by canton7** [comment]
Cheers. How did you come across SyncTrayzor btw? It's still pretty immature (as you've seen!) so I haven't mentioned it anywhere yet.

**Comment by jkaberg** [comment]
Was actully looking for a "better" working fork to SyncthingTray when I saw this, which had the features  I wanted ;-)

**Comment by canton7** [comment]
Sweet! Yeah I tried SyncthingTray. It decided it wanted to be a forkbomb and started 100 instances of itself before I stopped it. That's when I decided I could do better :stuck_out_tongue:

**Comment by canton7** [comment]
In develop, will be in the next release.
