### ISSUE TITLE
request: folder paths

### ISSUE THREAD

**Issue by sho-87** [canton7/SyncTrayzor#40]
Looking for an alternative to syncthing gtk and I'm liking synctrayzor so far

a couple of requests that would make useability a bit better (I dont know how possible these are, as it seems syntrayzor simply displays the web gui)

1. It would be awesome if there was a way (when adding folders) to be able to browse the filesystem to select a folder, instead of typing the full path

2. If there was an option to automatically edit the syncthing config.xml when adding folders to enable long file paths in windows: https://github.com/syncthing/syncthing/wiki/Windows-Troubleshooting-Guide

**Comment by canton7** [comment]
Hi!

1. Is not possible for now - Syncthing's in charge of the GUI, and I've got very limited options regarding tweaking what it displays or how it behaves. *However*, I'm working on a native UI at the moment (expect it in a month or so), and I'll be able to do whatever I like for that - including a proper filebrowser.

2. That's certainly do-able, thanks for the idea!

**Comment by canton7** [comment]
Actually, 2 is going to be a lot easier with the native UI.

Changing the user's config requires restarting syncthing, and I don't want to do that without the user's consent...

**Comment by canton7** [comment]
Re 2) It looks like Syncthing 0.11 will support that natively: https://forum.syncthing.net/t/syncthing-v0-11-0-release-notes/2426

1) is definitely on the cards as part of the native GUI work though (which will also happen after 0.11)

**Comment by canton7** [comment]
The native UI is off the cards - there's no point trying to replicate Syncthing's UI when it's changing so fast: users get a far better experience by being given Syncthing's UI.

1) is now duped by #78.
