### ISSUE TITLE
Feature Request: Installer argument to disable Start on Login

### ISSUE THREAD

**Issue by bushelofsilicon** [canton7/SyncTrayzor#402]
I think it might be nice if there was an installer switch that made the config file created with StartSyncthingAutomatically in the config file set to False.

In my deployment I'm setting it so that Syncthing starts automatically for any user who logs into the computer without them having to launch it first to create the Run key value in HKCU.

So this means that my options are.

1. Create the value in HKLM instead and then manage the SyncTrayzor config file in order to keep StartSyncthingAutomatically set to false so that I don't get duplicate values in HKLM and HKCU (which I don't think there would be any ill effects with duplicates, just isn't very clean)

2. Use Active Setup in order to create the key under HKCU. This means I might not have to manage the config file, but I kind of feel like putting the value under HKLM is the simpler solution.

So then I feel the simplest solution would be if I could install SyncTrayzor without it creating a Run value in HKCU and then I create my own Run value in HKLM

**Comment by bushelofsilicon** [comment]
I just realized I could probably use the portable version and then set my own registry values, however my plan was to install from the chocolately repo

**Comment by canton7** [comment]
> I think it might be nice if there was an installer switch that made the config file created with StartSyncthingAutomatically in the config file set to False.

I'm afraid I can't parse that sentence. "config file created with StartSyncthingAutomatically in the config file"?

The installer can't write the config file. The installer run as an administrator, but the config file is created in the AppData folder of every single user which runs SyncTrayzor. You would have to iterate all users on the computer, impersonate each in turn, and create a config file to each. Even the ones which weren't interested in SyncTrayzor.

The default configuration is stored in SyncTrayzor.exe.config. The intention that people doing deployments edit this file to taste, and re-package SyncTrayzor. I guess I could let people specify their own version of this file in an installer parameter: that could work.

**Comment by bushelofsilicon** [comment]
> I guess I could let people specify their own version of this file in an installer parameter: that could work.

Yes! Even better, that would be perfect!

> You would have to iterate all users on the computer, impersonate each in turn, and create a config file to each. Even the ones which weren't interested in SyncTrayzor.

You can imagine what I have to do with the Syncthing config file order to get everyone's Desktop and Documents to sync to a central server automatically without any user intervention 😕

**Comment by canton7** [comment]
This should work: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.16.477/artifacts

**Comment by canton7** [comment]
([Documentation here](https://github.com/canton7/SyncTrayzor/tree/develop#notes-for-system-administrators))
