### ISSUE TITLE
Should Syncthing be closed before installing Synctrayzor?

### ISSUE THREAD

**Issue by Smallous** [canton7/SyncTrayzor#403]
Basic question I know, but I could not find any reference to this in the documentation.

SyncThing: v0.14.37, Windows (64 bit) "Dysprosium Dragonfly"
SyncTrayzor: 1.1.18

**Comment by canton7** [comment]
No. 

If you're upgrading SyncTrayzor, the installer will stop it. If you're installing SyncTrayzor alongside Syncthing, read the README for how to migrate your config etc.
