### ISSUE TITLE
Attach to a running Syncthing process

### ISSUE THREAD

**Issue by igrehs** [canton7/SyncTrayzor#404]
Hi all,

I've started using Syncthing + SyncTrayzor recently, and I would like to start Syncthing on system startup, independently of any users login. I tried using Task Scheduler to start the syncthing.exe for a few user accounts, however, after the such users login, SyncTrayzor does not "attach" to the running Syncthing process of that user. So, I have to kill the syncthing.exe process for that user and start it again with SyncTrayzor.

Is it possible for SyncTrayzor to attach to an already running Syncthing process? 
If not, is such a feature easily implemented or is there another workaround for this issue?

Best regards,
Ismael

**Comment by canton7** [comment]
Not possible, very hard to implement, not on the roadmap. 

A similar issue where a background SyncTrayzor service starts Syncthing is in the issue list, but it's so much work that it's not on the roadmap either.
