### ISSUE TITLE
"Some protected files may be overwritten and cause issues" warning triggered by locating portable SyncTrayzor folder and default "Sync" folder in same Windows user directory.

### ISSUE THREAD

**Issue by Showerrodney** [canton7/SyncTrayzor#405]
Have been using your excellent program for around six months. Updated to 1.1.18 and am now having the above issue.

I run a portable installation of SyncTrayzor (Win 7 64bit in a folder named 'SyncTrayzorPortable-x64') from within my user folder, the same folder in which my initial default "Sync" folder was created. This has caused no issues until the recent update. Now I receive the following warning:

`Some protected files may be overwritten and cause issues
C:\Users\Myusername\SyncTrayzorPortable-x64\data\syncthing\index-v0.14.0.db, C:\Users\Myusername\SyncTrayzorPortable-x64\data\syncthing\config.xml, C:\Users\Myusername\SyncTrayzorPortable-x64\data\syncthing\cert.pem, C:\Users\Myusername\SyncTrayzorPortable-x64\data\syncthing\key.pem`

If I remove then re-add the "Sync" folder with a different name the warning is no longer issued. Removing then renaming the folder back to "Sync" causes the warning to appear once more. I am not syncing my User directory itself, which I understand would usually be the cause of the above warning.

Apologies if this is a Syncthing issue and entirely unrelated to SyncTrayzor; I'm non technical and merely drew the connection due to the issue appearing after I recently updated to 1.1.18.

**Comment by canton7** [comment]
> Now I receive the following warning:

Where does that warning appear?

**Comment by Showerrodney** [comment]
> Where does that warning appear?

In a large, yellow framed box at the top of the SyncTrayzor window, and also in the console output at the bottom.

**Comment by canton7** [comment]
So, inside the Syncthing UI?

**Comment by Showerrodney** [comment]
![shot](https://user-images.githubusercontent.com/31789069/30333545-15c6e808-97d5-11e7-8676-5d652a943ae9.jpg)

Starting to realise this is very likely a Syncthing issue, in which case I apologise for posting the issue here.    An honest mistake by a non tech user!

**Comment by canton7** [comment]
No worries! Yep this is a Syncthing issue, please raise it [on the Syncthing forum](https://forum.syncthing.net).
