### ISSUE TITLE
How Can I Stop Auto-Syncing?

### ISSUE THREAD

**Issue by Camuvingian** [canton7/SyncTrayzor#406]
I would like to _prevent_ auto-sync for the synchronized folders I have. I would like to synchronize on request from either computer. Is there any way of doing this?

**Comment by canton7** [comment]
As this is a Syncthing issue, you'll get better support on the [Syncthing forum](https://forum.syncthing.net).

You can pause the folder from Syncthing's UI.

Another option might be to disable the folder watching in SyncTrayzor (Settings -> Folders -> Uncheck 'Watched'), and set the Rescan Interval to 0 (or a really high number if 0 doesn't work) in Syncthing's folder settings. That will prevent your folder from detecting changes and sending them to other devices, but will not prevent other devices from sending changes to your computer.
