### ISSUE TITLE
help me with this, 

### ISSUE THREAD

**Issue by grecia90** [canton7/SyncTrayzor#409]
I can not enter synctrayzor because I get this message 
![si](https://user-images.githubusercontent.com/32203611/30755870-de6b8498-9f8d-11e7-8881-c41c8bc85def.JPG)

**Comment by grecia90** [comment]
How can I correct it? It's urgent.

**Comment by canton7** [comment]
Something has corrupted the file `C:\Users\Lenovo\AppData\Roaming\SyncTrayzor\config.xml`. If you want a quick fix, delete this file. You will lose all settings which you set inside the SyncTrayzor UI (in the File -> Settings menu, for example) but not any of the Syncthing configuration (which includes your folder and device configuration).
