### ISSUE TITLE
Syncthing failed to start

### ISSUE THREAD

**Issue by Smallous** [canton7/SyncTrayzor#411]
SyncTrayzor v 1.1.18
Syncthing v 0.14.38
Windows 10

Hello,

I am starting to receive this error message regularly on start-up with the window recommending to "Kill all Syncthing processes".

There are two instances of Syncthing.exe running the 1st using 44MB and the 2nd using 0.2MB.

Using SyncTrayzor - Syncthing - Kill all Syncthing processes has no effect.

If I manually stop the 1st instance of Syncthing.exe running it just comes back.

I have to manually stop the 2nd instance first, then I can manually stop the 1st instance.

I am then able to start Syncthing.exe from the link provided inside SyncTrayzor.

This problem seems to be random. I cannot think of any action I do that causes it.

Regards

**Comment by jebeld17** [comment]
See #410

**Comment by canton7** [comment]
> There are two instances of Syncthing.exe running the 1st using 44MB and the 2nd using 0.2MB.

That's normal: Syncthing has a monitor process.

> Using SyncTrayzor - Syncthing - Kill all Syncthing processes has no effect.

That's weird.

> If I manually stop the 1st instance of Syncthing.exe running it just comes back.
> I have to manually stop the 2nd instance first, then I can manually stop the 1st instance.

That's normal. You need to kill the monitor process first.

Make sure that nothing else is starting Syncthing on startup. It's likely that something else is trying to start Syncthing, and there's a race: if SyncTrayzor starts it first, then the other thing silently fails; if the other thing starts it first, SyncTrayzor complains.

One thing to do could be to use Process Explorer to see which process, if any, started syncthing.exe. Another is to use autoruns to check your startup programs.

**Comment by Smallous** [comment]
Will do. Oddly enough I have not encountered this problem on either of my PCs for a couple of days now.

**Comment by Smallous** [comment]
I have found an 'on start-up' scheduled task on both computers pointing to the following: "C:\Program Files\syncthing-windows-amd64-v0.14.6\syncthing.exe". I assume this was created when Syncthing was originally installed (standalone). Both have now been disabled, so hopefully the problem is fixed. I will update the post in a few days time. Thanks very much.
