### ISSUE TITLE
When laptop sleeps and awakes Synctrayzor pauses remote devices saying they are on metered connection

### ISSUE THREAD

**Issue by arqeco** [canton7/SyncTrayzor#413]
Hello,

First of all, thanks for Synctrayzor.

When my Windows 10 laptop sleeps and, later, awakes,  Synctrayzor gives a message saying that the remote devices are on a metered connection, so they were paused.

I have to manually unpause the remote devices every time my laptop sleeps.

I had to disable the option to pause devices when on a metered connection. But this a problem because I often use mobile connections.

What can I do?

Thanks,
Marcio

**Comment by canton7** [comment]
Apologies for the delay - this slipped under my radar.

Can you post a log which corresponds to this happening? File -> Settings -> Logging + STTRACE -> Show SyncTrayzor log file.

**Comment by Hard-Wired** [comment]
I had this issue over the weekend and solved it the same way by disabling the connection's metered status. I'll try to trace the problem when I get more time this week. If I can't I'll post logs as well.

**Comment by canton7** [comment]
Can you post the log I described above?

**Comment by canton7** [comment]
Closing as no response.
