### ISSUE TITLE
Synctrazor windows 32 & 64 bit crash when scanning large 1.5TB folder

### ISSUE THREAD

**Issue by guyht** [canton7/SyncTrayzor#414]
I initially raised this with the main syncthing repo, but turns out this is an issue with Synctrazor as running syncthing directly fixed the issue.  Let me know if I can provide additional details.

Issue details at:
https://github.com/syncthing/syncthing/issues/4412

**Comment by canton7** [comment]
That's a syncthing crash: nothing to do with me

**Comment by canton7** [comment]
I'm guessing syncthing succeeded the 2nd or 3rd time you tried, due to making progress through the folder the previous times.

**Comment by guyht** [comment]
@canton7 no, it reset every time.

It seems likely that the issue was that when I upgraded Synctrazor to the 64 bit version, for some reason it was still launching the 32 bit Syncthing binary.  Probably not a bug, but also not the desired functionality.

**Comment by canton7** [comment]
Yes, I have to maintain the user's previous Syncthing binary. If I don't. I might accidentally downgrade the version of Syncthing the user is using, which can break things.
