### ISSUE TITLE
360 anti virus False positives 

### ISSUE THREAD

**Issue by sutex** [canton7/SyncTrayzor#415]
Just a heads up, Reports Trogan Win 32  Virus.NetTool.b1c in SyncTrayzor 64.exe
360 Stop the installers

**Comment by canton7** [comment]
There's no executable called "SyncTrayzor 64.exe". What's the actual name of the file it doesn't like?

**Comment by sutex** [comment]
https://github.com/canton7/SyncTrayzor/releases/tag/v1.1.18
Ok left out "setup" when I wrote it.... SyncTrayzorSetup-x64.exe

**Comment by canton7** [comment]
Ah, right. It's probably complaining about the copy of syncthing.exe that I package: that tends to set AV programs off.

**Comment by sutex** [comment]
All good , just letting you know , 360 anti virus is beeping ..:)

**Comment by canton7** [comment]
Closing now
