### ISSUE TITLE
Windows Defender Security - Trojan:Win32/Fuery.A!cl - False Positive?

### ISSUE THREAD

**Issue by Hard-Wired** [canton7/SyncTrayzor#416]
![synctrazor_virus_false_positive](https://user-images.githubusercontent.com/33186956/32138919-12fc6dba-bc0a-11e7-8801-507408821d92.png)

SyncTrayzor 1.1.18 (Windows 10 32-bit)

Hoping this is just a false positive, only happened on a 32-bit machine so far, 64-bit versions are not flagging.

**Comment by canton7** [comment]
AV programs always flag Syncthing: you'll find loads of reports on the Syncthing forum.

**Comment by Hard-Wired** [comment]
Blarg!

**Comment by canton7** [comment]
Something about an application which modifies your files when told to by a remote machine doesn't seem to sit well with AV programs, for some reason... They generally stop flagging it after it's reported as a false positive.

It's the first time I've seen Windows defender flag it though, I think.

**Comment by Hard-Wired** [comment]
I can imagine.

BTW, what are the numbered files it flagged? I don't see those show up in the 64-bit installations yet.

**Comment by canton7** [comment]
No idea. Do they actually exist? If they do, it's probably part of Syncthing's auto upgrade: ask on the forum.

**Comment by Hard-Wired** [comment]
Yeah, they were there before I let Windows Defender scrub them. I'll follow up on Syncthing.

**Comment by canton7** [comment]
Closing as this isn't my issue.
