### ISSUE TITLE
File watcher latency is higher than syncthing-inotify

### ISSUE THREAD

**Issue by Toilal** [canton7/SyncTrayzor#417]
For my use case, I need file changes to be detected and synched with the lowest latency as possible.

I did some tests with [syncthing-inotify](https://github.com/syncthing/syncthing-inotify) binary, and when changing a file, changes are propagated with an acceptable latency, around 1 or 2 seconds.

But when using SyncTrayzor with file watcher enabled, file changes are synched with a higher latency, from 4 to 10 seconds. 

After reading sources, it seems that when changing a single file, the whole directory is synched, making the process slower than with syncthing-inotify. Also there are some features in syncthing-inotify, like `-interval="500ms"` to throttle calls to syncthing that are interesting and could be implemented in this project too.

I would like to contribute with a pull request, but when trying to build the project, I have the following errors, could you help me please ?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'Interaction.Behaviors' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactivity'. Line 25 Position 18.	SyncTrayzor	C:\devel\projects\SyncTrayzor\src\SyncTrayzor\NotifyIcon\TaskbarIconResources.xaml	25	
Error		The tag 'Interaction.Behaviors' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactivity'. Line 82 Position 22.	SyncTrayzor	C:\devel\projects\SyncTrayzor\src\SyncTrayzor\Pages\ConflictResolution\ConflictResolutionView.xaml	82	
Error		The tag 'Interaction.Behaviors' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactivity'. Line 31 Position 14.	SyncTrayzor	C:\devel\projects\SyncTrayzor\src\SyncTrayzor\Pages\ConsoleView.xaml	31	
Error		The tag 'Interaction.Behaviors' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactivity'. Line 19 Position 6.	SyncTrayzor	C:\devel\projects\SyncTrayzor\src\SyncTrayzor\Pages\Settings\SettingsView.xaml	19	
Error		The tag 'Interaction.Behaviors' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactivity'. Line 12 Position 6.	SyncTrayzor	C:\devel\projects\SyncTrayzor\src\SyncTrayzor\Pages\ShellView.xaml	12	
Error		The tag 'EventTrigger' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactivity'. Line 90 Position 50.	SyncTrayzor	C:\devel\projects\SyncTrayzor\src\SyncTrayzor\Pages\Tray\FileTransfersTrayView.xaml	90	
Warning		The referenced component 'System.Windows.Interactivity' could not be found.	SyncTrayzor			
Warning		Could not resolve this reference. Could not locate the assembly "System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	SyncTrayzor			
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	SyncTrayzor		1	Active

````

**Comment by canton7** [comment]
You'll need the blend SDK to build. I'll add it to the README.

Syncthing is gaining its own filesystem notification support though (it's in the RC currently as an advanced option) so syncthing-inotify is going to become obsolete and I'm going to remove my filesystem notification support. Therefore making any changes to it at this point is slorettu pointless I'm afraid.

**Comment by Toilal** [comment]
Ho yes, good news, i'll try the RC then, thanks!
