### ISSUE TITLE
Missing guidance related to backup keys before switching computer

### ISSUE THREAD

**Issue by stevebeauge** [canton7/SyncTrayzor#419]
Hello,

I'm planning to reinstall my computer.

I didn't found (or understand) what is to backup before switching to the new computer.
Especially, I guess some keys are involved in the identity of the computer.

If I backup the whole synctrayzor and syncthing directory, I got errors on the new computer because of the missing folders.

I'd like to simply reattach the sync pairs with other computers, without having to setup each ones.

It would be great to have a paragraph explaining the process.

thanks

**Comment by canton7** [comment]
I guess this is a more general question about moving Syncthing between computers, as there's nothing which SyncTrayzor specifically needs. I can add something near the "migrating" section though, sure.
