### ISSUE TITLE
Can't sync network folder

### ISSUE THREAD

**Issue by jarenduan** [canton7/SyncTrayzor#423]
However， pure syncthing can！

It says missing folder path. 

Similarly, I cannot add a folder that locates in network drive, too.

It seems no access to network folders but only the  local ones.

Great job you guys did, and look forward to fixing that problem.

**Comment by canton7** [comment]
I'm afraid I don't understand the issue from your description. Please add some screenshot showing what you mean.

**Comment by canton7** [comment]
Closing as no response.
