### ISSUE TITLE
 SyncTrayzor file downloading status window missing

### ISSUE THREAD

**Issue by jaggeri** [canton7/SyncTrayzor#424]
Hi, my PC does not display the SyncTrayzor file downloading status window as per the GitHub image at https://github.com/canton7/SyncTrayzor.

Is there a setting for this, or is it because I am using it on Windows 10, Ver 1709, 16299.64 

STray ver 1.1.18, with ST 0.14.40,

Thanks
![synctrayzor download window](https://user-images.githubusercontent.com/28880253/33296444-a5b93fc8-d42b-11e7-8a8c-0308df9593a1.JPG)

**Comment by canton7** [comment]
No, that should work. Single click the tray icon while a large file is downloading.

**Comment by jaggeri** [comment]
Hi Antony,


It works !

I think I had  high CPU % and mouse lag and did not wait for the window to pop up after my left mouse click 

Operator error again !  : ) he he

Thank you
