### ISSUE TITLE
Syncthing mysteriously stops

### ISSUE THREAD

**Issue by jebeld17** [canton7/SyncTrayzor#427]
Syncthing has been stopping without my consent or input on my device if I have left it open in the system tray too long. This has only just begun happening.

LOGS:
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/1576619/syncthing.log)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/1576620/SyncTrayzor.log)

**Comment by ProactiveServices** [comment]
Please use the [Syncthing issue tracker](https://github.com/syncthing/syncthing/issues) for Syncthing bugs. I suspect this has been fixed as per Syncthing issue [4605](https://github.com/syncthing/syncthing/issues/4605)

**Comment by canton7** [comment]
This is indeed a Syncthing crash, but please use the **forum** (not the Syncthing issue tracker) to report it.
