### ISSUE TITLE
Crash during installation (Windows 7) SSE2 required ????

### ISSUE THREAD

**Issue by Czerno** [canton7/SyncTrayzor#430]
Version: 1.1.18.0; Variant: Installed; Arch: X86

Windows 7. Installer CRASH on  AMD K7 processor, CAUSE : very certainly because this CPU does not have SSE2.  

Is SSE2 really really REQUIRED (I guess it is not ! I know, tyrany of the default...) 
Would you PLEASE kindly provide executables compiled using the proper switches for public download,
either as standard or as alternative builds for the poor SSE2-less like me ?

I was really thrilled at the perspective of using your great file sync'ing suite, this delay/glitch comes as a great disappointment.  

Regards and TYIA ...

Path: M:\Programs\SyncTrayzor\SyncTrayzor.exe
System.IO.FileLoadException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. Exception from HRESULT: 0xC000001D
File name: 'CefSharp.Core.dll'

**Comment by canton7** [comment]
Was this during installation, as the issue title says, or when it tries to start *after* installation, as the error implies?

**Comment by Czerno** [comment]
Hi Canton7, Sir ! 
You're right, it happened as the installer was trying to autostart  the "Sync Trayzor", as a final step,
so - I guess - technically the installer itself is not at fault, it is the included Sync Trayzor itself.
Checking my Windows Start Menu, it created the "Sync Trayzor" group OK including links to the program itself and to its "uninstall". Trying to launch sync Trayzor manually by clicking the link, unsurprisingly repeats the same error as hinted in the original report.

**Comment by canton7** [comment]
Right, this is a crash in the embedded browser control, which I don't have any control over. You're out of luck I suspect, sorry.

**Comment by canton7** [comment]
One thing you can try is to see whether the CEF Windows x86 Sample Application works: http://opensource.spotify.com/cefbuilds/cef_binary_3.3239.1723.g071d1c1_windows32_client.tar.bz2

**Comment by Czerno** [comment]
The "CEF" client has the same crash : c000001d unfortunately. Google/Chromium stopped caring about pre-SSE2 processors long ago...

Who would be the party responsible  for fixing the "embedded browser control" and how can they be contacted, please  ?

**Comment by Czerno** [comment]
[SOLVED] Success, after replacing Sync Trazor's bundled version of syncthing.exe 
by : syncthing v0.14.42 "Dysprosium Dragonfly" (go1.9.2 window
s-386) teamcity@build.syncthing.net 2017-12-07 09:43:00 UTCSyncthing.exe"

This is the most recent precompiled available AND does not seem to require SSE2 !

Very happy end AFAIAC ! I'm leaving it to You to mark the issue as solved; may I first
suggest you applied the switch so others affected can benefit, too ?  

PS : for some reason been unable to EDIT my previous comment. Maybe I not "old" enough at sourceforge, or whatever...

**Comment by canton7** [comment]
https://bitbucket.org/chromiumembedded/cef and the forum http://www.magpcss.org/ceforum/index.php

**Comment by Czerno** [comment]
Noted ! Not being a developer, and not being their user, think I will pass on this one. Maybe, I don't know, 
you might ask them if they would care to build their thing - the parts you reuse - with the appropriate noSSE2 flag. Meanwhile I think I'll learn for myself and then try to teach my partners how to use the bare 'Syncthing' on Windows...

I'll leave it to You to mark the issue closed at your leisure. Thank you !

**Comment by canton7** [comment]
To be honest, they do one Windows build (for x86) and I doubt you'd be able to convince them to disable SSE2 in it, to the detriment of everyone else using it.

**Comment by canton7** [comment]
Take a look at the other community contributions: https://docs.syncthing.net/users/contrib.html
