### ISSUE TITLE
UnauthorizedAccessException copying file at startup

### ISSUE THREAD

**Issue by jtbr** [canton7/SyncTrayzor#431]
Synctrayzor crashes at startup on a new install under Windows 7 x64.

```
Version: 1.1.18.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Access is denied.

   at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 51
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 127
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 139
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

This appears to be the same trace as in bug #407. Over there I was asked to provide [SyncTrayzor.log] (https://github.com/canton7/SyncTrayzor/files/1624605/SyncTrayzor.log). In the log, you can see all prior runs; there appear to have been prior exceptions, which perhaps may have caused this. At some point (all today) I uninstalled and re-installed, so they may not all be relevant. But it always crashed at startup, before and after reinstalling.

**Comment by canton7** [comment]
It's failing to copy Syncthing to C:\Users\jtbr\AppData\Roaming\SyncTrayzor\syncthing.exe. Can you confirm that your user has the right to add files to this folder?

**Comment by jtbr** [comment]
Interesting. It appears that I am specifically blocked from writing executables to this directory (even with administrator access). I'm working to determine what it is that blocks this. It's possible to write non-executables (non - .exe), to the same location however.

**Comment by canton7** [comment]
There's a group policy which controls this IIRC -- executables in AppData *are* a security risk.

**Comment by jtbr** [comment]
I'm still checking into this. I noticed online that it seems common to disallow %AppData%\*.exe and %AppData%\*\*.exe as group policies. I wasn't able to find that in the group policy editor, but I may simply not have access to see corporate policies.

Nonetheless, I found that I _could_ write an executable to %AppData%\SyncTrayzor\test\exename.exe. In other words, putting it in a subdirectory worked (as a normal user). But that may be particular to my organization.

As an aside, I have trouble understanding why an exe in the appdata folder is more dangerous than one on the desktop or anywhere else a user can write. Some organizations prevent installation and usage of any non-approved apps by users. But that's not my case.

**Comment by canton7** [comment]
I don't see that I can do anything to help here -- can I close this issue?

**Comment by jtbr** [comment]
Yes, it appears to be my organization that has created this policy and they are so far not responding to me. I just realized too that running synctrayzor as a portable install might work for me. Thanks for your help.

**Comment by canton7** [comment]
There is a new setting in v1.1.20 (well, the setting was always there but it's exposed in the UI now) to let you change where the syncthing binary is located.

**Comment by martinwk** [comment]
Can you tell me where to find this setting and how to set it? I have exactly the same problem as jtbr.

**Comment by canton7** [comment]
File -> Settings -> Syncthing -> Advanced -> Syncthing Custom Path. Set it to the full path you want `syncthing.exe` to be located.

**Comment by canton7** [comment]
Closing as ancient
