### ISSUE TITLE
Error on system reboot

### ISSUE THREAD

**Issue by harrison-matt** [canton7/SyncTrayzor#432]
![image](https://user-images.githubusercontent.com/7608119/34917375-82378c6e-f913-11e7-8462-90d72d4945b8.png)

cx_Freeze: Python error in main script (traceback unavailable).

This error pops up at system start. Otherwise, there seem to be no other issues that I see.

Let me know if I can provide any more information.

Thanks,
Matt

**Comment by canton7** [comment]
Are you sure this is caused by SyncTrayzor? I don't use Python in any way.

**Comment by harrison-matt** [comment]
![image](https://user-images.githubusercontent.com/7608119/34919012-0711db62-f92b-11e7-9397-d2409803941e.png)
You're absolutely right. My apologies. It looks like GTK is still installed on my system.
