### ISSUE TITLE
Crash on PC wakeup (System.Net.Http.HttpRequestException)

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#435]
Upon waking up the PC from sleep SyncTrayzor crashed (showing it's own crash info screen, overlayed with windows' "the program has crashed dialog"). The setup is very unremarkable on this PC.
Syncthing seem to still be alive after the crash.

SyncTrayzor Log: (first err at line 35) https://gist.github.com/anonymous/8194d418661cbb56a15f8c8ce4538502

SyncTrayzor v.1.1.18
Syncthing v.0.14.43
OS: Win10x64

**Comment by canton7** [comment]
Can I see a bit more of the log? It should retry the connection to Syncthing multiple times before giving up, and I want to see what's going on there.

Line 35 is a red herring: ignore it.

**Comment by scienmind** [comment]
Unfortunately - that's the whole log file, no lines removed.

The previous archived file (in it's entirety): https://gist.github.com/anonymous/bef72ee168af73bce6a30ab6e5a88b32

**Comment by infomaniac50** [comment]
Just my two cents.

> No connection could be made because the target machine actively refused it 127.0.0.1:8585

8585 is not the standard port number. My systems all use 8384. Is Synthing started by something other than SyncTrayzor?

> The remote name could not be resolved: 'synctrayzor.antonymale.co.uk'

This makes me think the network is not ready yet. WiFi may have not had time to reconnect. I'm not sure how Windows handles stale TCP connections. Coming out of sleep will for sure make any existing connections invalid. A server will RST reset and close the connection if it doesn't get a response for more than ~60 seconds.

Windows does have messaging for system events like Sleep and Shutdown. You can listen for these events and do any cleanup.
