### ISSUE TITLE
SyncTrazor 1.1.18; Syncthing 0.14.45-rc2; failure to sync with Syncthing 0.14.44 and earlier

### ISSUE THREAD

**Issue by zz0rk** [canton7/SyncTrayzor#436]
My portable version of SyncTrayzor upgraded to Syncthing 0.14.45-rc2 this morning. Since then sync seems to be failing / or it doesn't see devices that run earlier version of Syncthing (0.14.44 and 0.14.43). I've included some screenshots. I am happy to post excerpts from the Syncthing and SyncTrayzor log files. Please let me know what would be useful.

Both devices that run the earlier Syncthing versions communicating just fine.

Thanks

EDIT:
Syncthing stopped; I've attached the SyncTrazer console output (see new 1.txt).

![2018-02-13 09_38_56-synctrayzor](https://user-images.githubusercontent.com/18619265/36165450-771b9d22-10a4-11e8-8a13-e96358d56c9e.png)
![2018-02-13 09_44_01-synctrayzor](https://user-images.githubusercontent.com/18619265/36165453-7733e440-10a4-11e8-84c3-fb95a9c01cc8.png)
[new 1.txt](https://github.com/canton7/SyncTrayzor/files/1721093/new.1.txt)

**Comment by canton7** [comment]
Please open a thread on the [Syncthing forum](https://forum.syncthing.net), as this is almost certainly a Syncthing issue. Thanks!
