### ISSUE TITLE
Update 1.1.20 Error message Syncthing.exe application error  "The application failed to start properly".

### ISSUE THREAD

**Issue by sergueikp** [canton7/SyncTrayzor#438]
SyncTrayzor version: 1.1.20
Syncthing version: 0.14.44
Windows 7. 

Hello after update SyncTrayzor to 1.1.20 there is an error message when shutting down windows 7.
I see the windows error message : 
Syncthing.exe application error 
"The application failed to start properly". 

Is it problem of SyncTrayzor or Syncthing?

Best regards. 

![error_message](https://user-images.githubusercontent.com/9844780/36939909-4f39ea54-1f39-11e8-8926-37ae804dd284.JPG)

**Comment by canton7** [comment]
Never seen that one before - that's Windows showing that dialog. 

Post your logs (File -> Settings -> Logging), see if there's something interesting in there?

**Comment by sergueikp** [comment]
[CS3J7] 23:30:41 INFO: syncthing v0.14.44 "Dysprosium Dragonfly" (go1.9.2 windows-amd64) teamcity@build.syncthing.net 2018-01-19 06:21:05 UTC
[CS3J7] 23:30:41 INFO: My ID: CS3J7QK
[CS3J7] 23:30:42 INFO: Single thread SHA256 performance is 200 MB/s using minio/sha256-simd (148 MB/s using crypto/sha256).
[CS3J7] 23:30:42 INFO: Hashing performance with weak hash is 178.33 MB/s
[CS3J7] 23:30:43 INFO: Hashing performance without weak hash is 198.66 MB/s
[CS3J7] 23:30:43 INFO: Weak hash enabled, as it has an acceptable performance impact.
[CS3J7] 23:30:43 INFO: Ready to synchronize "Carnet_synchronisé" (5xyha-qlm7e) (readwrite)
[CS3J7] 23:30:43 INFO: Ready to synchronize "Informatique" (5mkzf-khtgj) (readwrite)
[CS3J7] 23:30:43 INFO: Ready to synchronize "Informatique_configuration" (7dwvf-ift7m) (readwrite)
[CS3J7] 23:30:43 INFO: Ready to synchronize "Aramis_gestion" (ryfqd-v2dvu) (readwrite)
[CS3J7] 23:30:43 INFO: Send rate is unlimited, receive rate is unlimited
[CS3J7] 23:30:43 INFO: Rate limits do not apply to LAN connections
[CS3J7] 23:30:43 INFO: Using discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX
[CS3J7] 23:30:43 INFO: Using discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX
[CS3J7] 23:30:43 INFO: Using discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX
[CS3J7] 23:30:43 INFO: TCP listener ([::]:22000) starting
[CS3J7] 23:30:43 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[CS3J7] 23:30:43 INFO: KCP listener (0.0.0.0:22020) starting
[CS3J7] 23:30:43 INFO: Device J55F3HZ is "Serguei-Win7-64" at [dynamic]
[CS3J7] 23:30:43 INFO: Device NLX5SQE is "Serguei-PC-Vaio-Old" at [dynamic]
[CS3J7] 23:30:43 INFO: Device XF6GPEW is "Vaio-Serguei-petit" at [dynamic]
[CS3J7] 23:30:43 INFO: Device 5MOAHNR is "Viktor-PC-Win7" at [dynamic]
[CS3J7] 23:30:43 INFO: Device 7FQTP45 is "sergeipcwin7-32bits" at [dynamic]
[CS3J7] 23:30:43 INFO: Device CS3J7QK is "Serguei-Win7-64" at [dynamic]
[CS3J7] 23:30:43 INFO: Completed initial scan of readwrite folder "Carnet_synchronisé" (5xyha-qlm7e)
[CS3J7] 23:30:43 INFO: GUI and API listening on 127.0.0.1:8384
[CS3J7] 23:30:43 INFO: Access the GUI via the following URL: http://localhost:8384/
[CS3J7] 23:30:43 INFO: Completed initial scan of readwrite folder "Aramis_gestion" (ryfqd-v2dvu)
[CS3J7] 23:30:43 INFO: Completed initial scan of readwrite folder "Informatique_configuration" (7dwvf-ift7m)
[CS3J7] 23:30:43 INFO: Completed initial scan of readwrite folder "Informatique" (5mkzf-khtgj)
[CS3J7] 23:30:52 INFO: kcp://0.0.0.0:22020 detected NAT type: Symmetric NAT
[CS3J7] 23:30:53 INFO: New NAT port mapping: external TCP address 84.101.85.35:51813 to local address 0.0.0.0:22000.
[CS3J7] 23:30:53 INFO: Detected 1 NAT service
[CS3J7] 23:30:57 INFO: Joined relay relay://79.137.32.223:22067

**Comment by canton7** [comment]
Does that log show the point in time where the error was shown?

**Comment by sergueikp** [comment]
Error happens when I shut down windows at the last moment when everything is closed.

**Comment by canton7** [comment]
The log files are kept when the system reboots.

**Comment by sergueikp** [comment]
Give me the path to the log file on widnows 7

**Comment by canton7** [comment]
See my first message in this thread.

**Comment by sergueikp** [comment]
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/1777962/syncthing.log)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/1777963/SyncTrayzor.log)

**Comment by canton7** [comment]
What time did you see the error?

**Comment by sergueikp** [comment]
just after I click on shut down button of my windows 7, I've tested it several times all my three machines

**Comment by canton7** [comment]
Tell me time that your clock showed when the error occurred.

**Comment by canton7** [comment]
(This is really hard work. I'm going to bed now. I'll try and come back to this at some point tomorrow)

**Comment by sergueikp** [comment]
All log files are from my desktop computer.
But If I shut down my laptop computer it will be the time of the shut down, for instance right now I'm shutting down my laptop and it is showing 23:45, which is Paris time.

**Comment by canton7** [comment]
This is really simple. I need to know when the error happened so I can find the right time in the log. The log needs to be from the same computer that the error happened on. If the error happened on your desktop at 12:00, then I need the log files from your desktop, I need you to send me the log files *after* 12:00, and I need you to tell me that the error happened at 12:00.

Telling me that the error happened on your laptop when the log files are from your desktop is a waste of time. Telling me that the error happened at 23:45 when you sent me the log files *before* 23:45 is a waste of time.

Again. Make the error happen. Look at the clock when it happens. Then get the log files from the SAME computer that the error happened on, and tell me what time the clock showed when the error happened.

**Comment by sergueikp** [comment]
Here are logs from the laptop with shut down time at 23:45
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/1777980/syncthing.log)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/1777982/SyncTrayzor.log)

**Comment by canton7** [comment]
Thanks. I have a suspicion, I'll try and investigate tomorrow.

**Comment by sergueikp** [comment]
One  more time, to be sure,  logs of shutting down at 23:56
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/1777994/syncthing.log)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/1777995/SyncTrayzor.log)

**Comment by Hard-Wired** [comment]
Holding off on updating until I see how some of this stuff plays out.
