### ISSUE TITLE
SyncTrayzor seems to monitor an other Syncthing 

### ISSUE THREAD

**Issue by rich7** [canton7/SyncTrayzor#44]
a few weeks ago I tried to look at syncthing and so the first thing I did is install synctrazor
But due a wrong setting in my modem it didn't work (I didn't knew the modemsetting was wrong at that time).
Then I install the original Syncthing and this is working now for me.
But I liked synctrazor so I started this again, but it seems to sync something else (another process? or something) then Syncthing itself.

How can I make Synctrazor to start with the same syncthing as when I just start syncthing from commandline

**Comment by rich7** [comment]
I notice now the ID syncthing is giving me, is a different one then SyncTrazor is giving me.

**Comment by canton7** [comment]
It sounds like when you run `syncthing.exe` yourself it's using one config directory, whereas when SyncTrayzor runs `syncthing.exe`, it's using another.

Did you download the portable version of SyncTrayzor? If you did, it will tell syncthing to use the `data\syncthing` directory within the portable folder. `syncthing.exe` will, by default, use `%LOCALAPPDATA%\Syncthing`. 

Either tell SyncTrayzor to use `%LOCALAPPDATA%\Syncthing` by going to Settings -> Syncthing -> Advanced, and unchecking "Use custom home directory for Syncthing", or if you want to keep everything self-contained, copy the contents of `%LOCALAPPDATA%\Syncthing` into `data\syncthing`.

**Comment by canton7** [comment]
@rich7 any response? Or shall I close off the issue?

**Comment by rich7** [comment]
Hi,
Settings -> Syncthing -> Advanced, and unchecking "Use custom home directory for Syncthing",
is doing the job.
it works perfect now :)

**Comment by canton7** [comment]
Cool! Thanks for letting me know :)
