### ISSUE TITLE
CEF: Device's "Folders" field tooltip don't wrap into multiple lines properly

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#442]
1. Open SyncTrayzor 
2. Expand info for a remote device that shares a lot of folders 
3. Hover above "folders" field of this device's info
4. Tool-tip appears listing all the folders shared with this device

Actual result: with many shared folders this tool-tip just lists everything in one line of monitor's width (and it's still not enough to list all folders)

Expected result: the tool-tip should be limited in width and break into multi-line if above curtain line length.

The tool-tip is underlined with red:
![image](https://user-images.githubusercontent.com/11633330/37215438-9a4d3b0a-23c0-11e8-9039-beb5f147d3c9.png)

The wrapping seem to work fine if UI is accessed from Firefox or "normal" Chrome (https://github.com/syncthing/syncthing/issues/4797#issuecomment-371850294), so probably the embedded browser could use an update.
### Version Information

Syncthing Version: v0.14.45
SyncTrayzor v1.1.21
OS Version: Windows 10x64

**Comment by canton7** [comment]
The embedded browser is now at the latest version. Please reopen if you can still reproduce this. Thanks!
