### ISSUE TITLE
Feature Request: Choose Installation Folder

### ISSUE THREAD

**Issue by tbhova** [canton7/SyncTrayzor#444]
Specifically, I'd like the functionality to install to a drive other than C:\
This seems to have been removed in a recent version, as I have an older version install on D:\

Additionally, it would be great if automatic updates were applied over the custom installation folder instead of the default location.

Thanks!

**Comment by canton7** [comment]
None if this has changed. You can select any folder on installation, and auto upgrades will use that same folder.

**Comment by tbhova** [comment]
Using the newest v1.1.21 "SyncTrayzorSetup-x64.exe" I don't see how to select a folder.

**Comment by canton7** [comment]
![image](https://user-images.githubusercontent.com/568104/37873611-140006a4-3018-11e8-854b-e3c96e37075e.png)

Of course, if it's already installed and you run the installer again, it's going to modify the existing installation, and so it won't let you select a different installation folder.

**Comment by a-raccoon** [comment]
I would like to see the Installer allow you to specify the separate and distinct folder that SyncThing proper is already installed to, instead of mashing Trayzor and a new SyncThing together as one.  This was a serious matter of confusion without any obvious clarity.  Windows users are familiar with front-end addon software for open source projects, where the two softwares are independent and symbiotic.

**Comment by canton7** [comment]
Syncthing is a single executable: does it really matter much where it goes (other than it has to be somewhere the user had wrote access to)?

**Comment by canton7** [comment]
Please don't piggyback on existing unrelated issues: open a new issue.

I need two copies of Syncthing, and you'll realise why if you think about it (consider a machine with multiple users)

**Comment by a-raccoon** [comment]
I didn't say it *was ridiculous*, just ridiculously confusing.  C:\Portable\SyncThing\syncthing.exe (proper), C:\Portable\SyncTrayzor\syncthing.exe, C:\Users\Smith\AppData\Roaming\SyncTrayzor\syncthing.exe

They're everywhere

**Comment by canton7** [comment]
Please open a new issue, as I asked.

**Comment by canton7** [comment]
Closing as no response
