### ISSUE TITLE
Odd Notifications

### ISSUE THREAD

**Issue by Hard-Wired** [canton7/SyncTrayzor#447]
A few of my machines acquired this "Microsoft.Explorer.Notification / {...}" quirk after the Win 10 (1709) upgraded installed... 

![synctrayzor_1 1 18_win10fcu_upgrade_bug](https://user-images.githubusercontent.com/33186956/38721788-78d29a00-3ec9-11e8-940c-5b691426a822.jpg)

I was hoping that SyncTrayzor/Syncthing updates would resolve it, but so far no luck.

**Comment by canton7** [comment]
Windows started doing that to me too, but not just for SyncTrayzor. It happens after a previous Windows update as well for a bit, then stopped. I wouldn't be surprised if a future Windows patch fixes it.

**Comment by canton7** [comment]
See for example https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings-winpc/what-are-these-app-notifications/b3561de4-d462-42d8-a15d-190ff198b291

**Comment by Hard-Wired** [comment]
Ah, that follows. While my "Notification & actions" settings don't show that same {...} issue, the icon for SyncTrayzor is missing on the machines that have the problem. Registry issue?

**Comment by Hard-Wired** [comment]
The problem was temporarily fixed (no odd IDs in notifications and the icon came back in settings) when I used [this Microsoft tool](https://www.google.com/url?q=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Fhelp%2F17588%2Ffix-problems-that-block-programs-from-being-installed-or-removed&sa=D&sntz=1&usg=AFQjCNFY962_E4FZf6nyv38KmP7pQo53lQ) to uninstall a misbehaving app. Note that one of the things the tool fixes is registry issues.

This lasted for a few days until the 2018-04 cumulative update installed and the problem has returned. I'll see if I can reproduce this on other machines.

**Comment by canton7** [comment]
Closing as this is old. I'm fairly sure this is a Windows oddity, and there's nothing I can do about it. Please reopen if you think differently. Thanks!
