### ISSUE TITLE
Quickly replicate configuration to peers

### ISSUE THREAD

**Issue by locksmithone** [canton7/SyncTrayzor#448]
I have 30+ directories (with their own tree of subdirectories) being synced. I have individually configured each one of them in each peer on my SyncTrayzor/thing syncing network. (It is not the case wherein I can simply put all of them under one root directory and sync the root directory.)

Now I am doing a system-wide overhaul and the directory structure will change significantly. I want to try and avoid configuring the new structure in each of my peers; perhaps configure the syncing structure in one peer (the master peer), and replicate the configuration to the other peers. Which is the best way to do it? Is it safe to copy the config.xml files (from Syncthing and Synctrayzor) to the other peers?

**Comment by canton7** [comment]
You can copy SyncTrayzor's XML file, although it doesn't contain much (just the stuff in File -> Settings). For Syncthing's ask [on the forum](https://forum.syncthing.net)
