### ISSUE TITLE
Portable x64 release problem 1.0.12

### ISSUE THREAD

**Issue by xl4m3rx** [canton7/SyncTrayzor#45]
When the application start give a runtime error because the wrong configuration folder is already present.
Fix: remove syncthing folder on data folder.

**Comment by canton7** [comment]
Could you expand on exactly what you mean by "the wrong configuration folder is already present"? What is the exact error message? It should have given you a nice stack trace you can post here.

**Comment by xl4m3rx** [comment]
2015-04-13 16:33:44.0362 [Error] SyncTrayzor.Bootstrapper: An unhandled exception occurred System.NullReferenceException Riferimento a un oggetto non impostato su un'istanza di oggetto. Stylet.ScreenState get_State()    in SyncTrayzor.Services.ApplicationWindowState.get_State() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\ApplicationWindowState.cs:riga 65
   in SyncTrayzor.NotifyIcon.NotifyIconManager.set_ShowOnlyOnClose(Boolean value) in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\NotifyIcon\NotifyIconManager.cs:riga 51
   in SyncTrayzor.Services.ConfigurationApplicator.ApplyNewConfiguration(Configuration configuration) in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\ConfigurationApplicator.cs:riga 65
   in SyncTrayzor.Bootstrapper.Configure() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Bootstrapper.cs:riga 105
   in Stylet.BootstrapperBase.Start(String[] args)
   in System.Windows.Application.<.ctor>b__1(Object unused)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler) System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in SyncTrayzor.Services.ApplicationWindowState.get_State() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\ApplicationWindowState.cs:riga 65
   in SyncTrayzor.NotifyIcon.NotifyIconManager.set_ShowOnlyOnClose(Boolean value) in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\NotifyIcon\NotifyIconManager.cs:riga 51
   in SyncTrayzor.Services.ConfigurationApplicator.ApplyNewConfiguration(Configuration configuration) in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\ConfigurationApplicator.cs:riga 65
   in SyncTrayzor.Bootstrapper.Configure() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Bootstrapper.cs:riga 105
   in Stylet.BootstrapperBase.Start(String[] args)
   in System.Windows.Application.<.ctor>b__1(Object unused)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Bear in mind that Syncthing has a `config.xml` (in `data\syncthing\config.xml`), which is *different* to my `config.xml` (in `data\config.xml`).

The problem you've identified will always occur when 'Show tray icon only on close' is checked. I'll get that fixed up
