### ISSUE TITLE
UI glitch after manual Syncthing start

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#452]
What happened:
1. open SyncTrayzor
2. after a while, shutdown syncthing (using WebUI's Actions->Shutdown)
3. put PC to sleep, move to another location with another WLAN, wake PC
4. click "Start Syncthing" in SyncTrayzor's window

* Result: UI is all screwed up, seems like SyncTrayzor can't connect to the syncthing instance.

SyncTrayzor's log (ST was started at 13:07):
https://privatebin.net/?5f3706e317f2ea94#Y8Ubp19695nJjdzGls4DkhEY7KiI2cJt5RwjOA3zEv0=
Syncthing's log is normal, and the program itself is functioning.

Restarting Syncthing again via Menu->Syncthing->Restart fixes the glitch and brings the UI back in normal state.

Screenshots:
![image](https://user-images.githubusercontent.com/11633330/39300903-f91f4ec4-4955-11e8-95ef-cd5ddf5825d8.png)
![image](https://user-images.githubusercontent.com/11633330/39300921-10502da2-4956-11e8-88ad-99f295ae9b02.png)
![image](https://user-images.githubusercontent.com/11633330/39300932-1bf16cf2-4956-11e8-913b-cd1f905de9a2.png)

**Comment by canton7** [comment]
That's a problem with Syncthing's javascript not running. Is this reproducible at all? Syncthing -> Refresh browser, or just F5, should fix it as well.

**Comment by canton7** [comment]
If it isn't reproducible, I don't think there's a lot we can do to investigate
