### ISSUE TITLE
Feature request: Show "Folder Label" in tray icon's tooltips

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#457]
Current behavior:
1. clink on the tray icon, latest synchronized items list will show up
2. hover over any of the items, "Folder" and "Full Path" are shown in a tooltip
 * The "Folder" there, always shows `Folder ID`

Now, it is fine for legacy folders, which have meaningful ID, but for newer ones, with random string ID and a meaningful `Folder Label`, it is quite useless.

Expected behavior:
* "Folder" shows `Folder Label` by default, falling back to show `Folder ID` in case `Folder Label` is empty.

ST v0.14.47
SyncTrayzor v1.1.21

**Comment by canton7** [comment]
Mind giving this a try? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.21.520/artifacts

**Comment by scienmind** [comment]
Yes, from a brief check, it looks like it does the label vs ID thing correctly 👍

**Comment by canton7** [comment]
Thanks!
