### ISSUE TITLE
Fxed position of select button in conflict dialog

### ISSUE THREAD

**Issue by Kirill** [canton7/SyncTrayzor#458]
When too much files in conflict dialog I can't select all new (for example). Ok I can mouse click much time for select new files, but button jump from left to right and back with different length of file name.
Can you position select button to right border?
![2018-05-28 09_55_43](https://user-images.githubusercontent.com/302940/40603794-5091d4a4-625d-11e8-8931-7302fddad2d3.png)
![2018-05-28 09_56_02](https://user-images.githubusercontent.com/302940/40603814-5d285198-625d-11e8-808c-0ceb30d97aaa.png)
![2018-05-28 09_57_28](https://user-images.githubusercontent.com/302940/40603889-8f5e8286-625d-11e8-9e27-db387c07ccec.png)

**Comment by canton7** [comment]
You know you can select multiple items using shift/control, or select all with ctrl-A?

**Comment by Kirill** [comment]
> You know you can select multiple items using shift/control, or select all with ctrl-A?
No. I don't know before. :)

**Comment by canton7** [comment]
There is a bit of text telling you this at the bottom of the list of items.

**Comment by Kirill** [comment]
For now I can't see. I test it for next time

**Comment by canton7** [comment]
You might be using an old version then - that was introduced a while back.

**Comment by Kirill** [comment]
> You might be using an old version then - that was introduced a while back.

No. I have last version 1.1.21

**Comment by canton7** [comment]
Closing, as there are better ways to resolve multiple files
