### ISSUE TITLE
On startup: No module named traceback

### ISSUE THREAD

**Issue by mattpalermo** [canton7/SyncTrayzor#461]
I am shown this message every time I boot up and log in but not when I exit SyncTrayzor and start it again. I am using SyncTrayzor version 1.1.21. I have enabled the options: start on startup and start minimized.
![screenshot 20](https://user-images.githubusercontent.com/16647352/41453183-0ef19340-70b8-11e8-9327-caf58363a764.png)

**Comment by canton7** [comment]
Are you sure the message is related to SyncTrayzor?

**Comment by mattpalermo** [comment]
Ah, yes you're right, it was actually SyncthingGTK trying to start. I thought I had uninstalled that! The Syncthing icon in the taskbar made me think it was SyncTrayzor. Thank you.
