### ISSUE TITLE
https://github.com/canton7/SyncTrayzor/releases/latest/SyncTrayzorSetup-x64.exe

### ISSUE THREAD

**Issue by nrbray** [canton7/SyncTrayzor#462]
A redirect link to download the latest version of Synctrayzor would be most useful.

It would allow some simpler install instructions to be written for users that trust their admin and get started quickly:

Example instructions to a user:

This view is available on a Syncthing share:

1. Download SyncTrayzorSetup-x64.exe (https://github.com/canton7/SyncTrayzor/releases/latest/SyncTrayzorSetup-x64.exe) and run it.
2. <+ Add Remote Device> with <Device ID> **9K3CYNS-S4VDAXN-LCOHVOO-3Z26H4T-79U294D-FZ1GCFF-TNUXVRW-BZ51QQH**
3. <+ Add Folder> with <Folder ID> **w66r5-kalv2**

**Comment by canton7** [comment]
I'm afraid I don't understand the request. What do you mean by a redirect link? If you're using SyncTrayzor, why are you concerned with downloading Syncthing directly? Why would a link to download the latest version of Syncthing be part of the SyncTrayzor repo, not the Synching repo?

**Comment by nrbray** [comment]
Hi,

I am attempting to give less sophisticated users one less 'click' in their
steps to install.

Sorry, I was only concerned with giving users one direct link to the latest
version of SyncTrazor (knowing they are on Windows 64 bit machines).  I
only describe to users that we are using "Syncthing" as the general name
but in fact the application I ask them to download is SyncTrazor.

BR/ Nigel

+44 7795047872

**Comment by Hard-Wired** [comment]
In reading this, it occurred to me that it would be awesome to be able to include remote device ids and the folder ids in the command line during installation. I read up on [Notes for System Administrators](https://github.com/canton7/SyncTrayzor#notes-for-system-administrators), but I did not see any provision for this. I didn't see anything in Syncthing documentation like this either, but I'll take another look later.

**Comment by canton7** [comment]
@Hard-Wired, please don't jump on top of unrelated issues. Let's try and keep things focussed, please.

**Comment by canton7** [comment]
@nrbray Right, GitHub doesn't support that unfortunately.

**Comment by Hard-Wired** [comment]
Sorry, seemed relative.

**Comment by er1z** [comment]
It's better to promote Chocolatey/Nuget package: https://chocolatey.org/packages/synctrayzor

Or, at least, pay attention to keep this thing fresh by authors themselves instead of third-party maintainer.

**Comment by canton7** [comment]
Closing as not possible
