### ISSUE TITLE
Can't start SyncTrayzor

### ISSUE THREAD

**Issue by victorjagu** [canton7/SyncTrayzor#467]
Good evening,
I'm installing (and also try by executing the portable version with the same result) the lastest version of SyncTryzor on my W7 Home Basic and I get the following message: "No se encuentra el punto de entrada del procedimiento nextafterf en la biblioteca de vínculos dinámicos MSVCR120_CLR0400.dll"
I've already installed:
*Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.23026
*Program Name: Microsoft .NET Framework 4.5.2 (ESN)
*Program Name: Microsoft .NET Framework 4.7.1
Do I need sth else to run your program?
I have it in another computer (running W10) and it works like a charm!
Thank you very much in advace.
Best regards,
Víctor

**Comment by canton7** [comment]
Strange, I've never seen that one before. Can you check whether `"C:\Windows\System32\msvcr120_clr0400.dll"` exists?

**Comment by canton7** [comment]
The versions you installed should have worked. What version fixed it in the end?

**Comment by victorjagu** [comment]
The same one, but without the "ESN". I don't know what does it mean, but I installed it again and it works


En 22 de julio de 2018 23:44:00 Antony Male <notifications@github.com> escribió:

The versions you installed should have worked. What version fixed it in the end?
