### ISSUE TITLE
GUI Theme change not initially visible in SyncTrayzor Browser

### ISSUE THREAD

**Issue by Hard-Wired** [canton7/SyncTrayzor#472]
SyncTrayzor 1.1.21, Syncthing v0.14.48 (auto-upgraded) on Windows 10 (Home/Pro) 1803 with 2018-07 Cumulative Update.

When setting Syncthing's GUI Theme (Black, Dark, Default), the change does not initially appear in SyncTrayzor's browser until after using SyncTrayzor's menu Syncthing / Refresh browser function at least 2-3 times.

**Comment by canton7** [comment]
I think it' something to do with caching, but I can't figure out what: whether it's Syncthing returning 304 when it shouldn't, or the client not sending no-cache when it should. That seems to be involved with the refreshes not working anyway. Something else seems to be going on when you save the config though - this should trigger a reload, but that request to syncthingController.js gets aborted.

**Comment by Hard-Wired** [comment]
It isn't critical, since I would think most people only set this once, but it is annoying. I thought something had broken during a new installation, but realized it was happening on each of my systems.

**Comment by DrSchnagels** [comment]
Just delete the "cef" folder under data in the synctrayzor directoy. after that it worked again for me.

**Comment by canton7** [comment]
Right, think I've got something which more or less works. Some of the other things to try will require upgrading CefSharp, and that's going to be a fairly major undertaking.
