### ISSUE TITLE
ArgumentNullException in CreateDirectory from ConfigurationEditor.

### ISSUE THREAD

**Issue by lyh404** [canton7/SyncTrayzor#477]
Version: 1.1.21.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.ArgumentNullException: 值不能为 null。
参数名: path
   在 Pri.LongPath.Path.NormalizeLongPath(String path, String parameterName)
   在 Pri.LongPath.Directory.CreateDirectory(String path)
   在 SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) 位置 C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:行号 134
   在 SyncTrayzor.Bootstrapper.Configure() 位置 C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:行号 144
   在 Stylet.BootstrapperBase.Start(String[] args) 位置 c:\projects\stylet\Stylet\BootstrapperBase.cs:行号 81
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
If you can still reproduce this, could you please post a section of your log file which contains this crash, and some of the lines before it?

Go to File -> Settings -> Logging -> Show SyncTrayzor Log File.

**Comment by canton7** [comment]
Closing as no response
