### ISSUE TITLE
GUI Crash when Remotedesktopconnectionwindow is resized

### ISSUE THREAD

**Issue by DrSchnagels** [canton7/SyncTrayzor#478]
Synctrayzor crashes with the GUI when i remote into another PC and the Remotedesktopwindow is resized.
They GUI then becames just like a picture. Resizing the Synctrayzor menu doesnt help.

Anyone got an idea to fix this? Thanks! :)

**Comment by canton7** [comment]
> They GUI then becames just like a picture

What does this mean? Is it something you can take a screenshot of?

**Comment by DrSchnagels** [comment]
![4r4r2tt4r34r 2](https://user-images.githubusercontent.com/20019440/44973880-3c677580-af5e-11e8-81ed-1ab260bfef87.jpg)
![4r4r2tt4r34r 1](https://user-images.githubusercontent.com/20019440/44973881-3c677580-af5e-11e8-9144-a214c527249d.jpg)

1) Syncthing running on the other machine
2) log in to the machine via remotedesktopconnection on Windows (to the other windows machine)
3) Synctrayzor GUI crashes, like shown, syncthing running further. 

Interestingly it does only happen to my notebooks not my windows server 2016.

**Comment by canton7** [comment]
Interesting. Have you tried disabling hardware rendering, in File -> Settings?

**Comment by DrSchnagels** [comment]
![fghtrtrfgchstrvgc 1](https://user-images.githubusercontent.com/20019440/44977746-1dbaac00-af69-11e8-8df7-1961192352e1.jpg)
![fghtrtrfgchstrvgc 2](https://user-images.githubusercontent.com/20019440/44977748-1e534280-af69-11e8-93cc-1df039be37cf.jpg)
![fghtrtrfgchstrvgc 3](https://user-images.githubusercontent.com/20019440/44977750-1e534280-af69-11e8-994a-4541d1ea7fd9.jpg)

I now have disabled hardware rendering. Same result. After logging into the remote session the Synctrayzor window is white. Resizing kinda crashes the GUI. As you can see it does not do the adjustments for a small window (like mobile phone websites) and with making the window bigger the new space is white as background.

**Comment by DrSchnagels** [comment]
The GUI does not respond to clicks anymore. And F5 does not work either.

**Comment by canton7** [comment]
I'm afraid I have no idea - it's some strange interaction between Remote Desktop and the .NET Framework.

**Comment by canton7** [comment]
Version 1.1.26 includes the latest version of the embedded browser. Please re-open if you can reproduce the issue with that version. Thanks!

**Comment by DrSchnagels** [comment]
> 
> 
> Version 1.1.26 includes the latest version of the embedded browser. Please re-open if you can reproduce the issue with that version. Thanks!

Problem has been solved since the embedded browser update. Works flawlessly since then!
Thanks a lot!!!!

**Comment by canton7** [comment]
Good to hear, thanks for letting me know.
