### ISSUE TITLE
Decoding posted config: “undefined”: device ID invalid: incorrect length

### ISSUE THREAD

**Issue by RaviAgrawal** [canton7/SyncTrayzor#480]
I am getting following error when I am trying to add folder from connected device.
Connection error: Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart syncthing if the problem exists.
Please any one help me with that

![Attached issue screenshot](https://user-images.githubusercontent.com/6408314/45803682-d73eae80-bcd7-11e8-820f-1576b0c2750a.png)

**Comment by canton7** [comment]
This is a Syncthing issue, please open it in https://github.com/syncthing/syncthing
