### ISSUE TITLE
Auto update notification do not move around when screen resolution changed to lower

### ISSUE THREAD

**Issue by msg7086** [canton7/SyncTrayzor#481]
When a new version is found, synctrayzor pops a notification allowing user to choose between 3 buttons whether to upgrade.

If the screen resolution was higher when the pop up appeared, and later goes down (for example, due to a remote desktop session being established), the buttons could stay out of the screen. As a workaround, user can bring up the main UI to make the choice there, but this is confusing though.

Expecting the notification box to move back when detecting a resolution change, or founding itself out of the screen area.

**Comment by canton7** [comment]
I don't think there's much I can do here I'm afraid: Windows is responsible for placing windows.
