### ISSUE TITLE
Installed version can`t start even with admin permissions! There's my log attached

### ISSUE THREAD

**Issue by xoxefdp** [canton7/SyncTrayzor#482]
Hi, i installed synctrazor and for some reason i can't launch it, attached there is the synctrazor error log link. Hope it can be solved.
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/2158181/SyncTrayzor.log)

**Comment by canton7** [comment]
It seems that the user doesn't have permission to copy syncthing.exe to `C:\Users\usuario\AppData\Roaming\SyncTrayzor\syncthing.exe`.

**Comment by canton7** [comment]
Closing as no response
