### ISSUE TITLE
GUI disappears on selecting title device name and pressing backspace

### ISSUE THREAD

**Issue by GlitchedPolygons** [canton7/SyncTrayzor#483]
Doesn't happen all the time, around once every 5 tries.

Affected version: [v1.1.22](https://github.com/canton7/SyncTrayzor/releases/tag/v1.1.22) - b287efc (SyncTrazorPortable-x64)

Repro: 
* Quit synctrazor.exe if it's running
* Open up synctrazor.exe 
* Select 3 or 4 chars of the title bar (the grey device name, e.g. DESKTOP-DJ495).
* Press backspace
* See the GUI disappear

This is very minor, as the GUI loads normally if you just restart SyncTrazor.

The synced files and folders are NOT affected negatively by this bug.

**Comment by canton7** [comment]
Have you got a screenshot?

**Comment by GlitchedPolygons** [comment]
Sure, I was actually going to create a GIF, but I had a terribly busy day today. Expect something from me tomorrow evening (Swiss local time).

**Comment by GlitchedPolygons** [comment]
> 
> 
> Have you got a screenshot?

Alright, I managed to create a video of the phenomenon: [check it out here on imgur](https://imgur.com/a/yPZKNlH

As you can see, it's not terrible, just weird. The GUI just disappears when I press backspace there
)

**Comment by canton7** [comment]
Thanks for the video!

The backspace is a navigation event, which takes the browser back to its initial empty start page. Weirdly, none of the navigation-related callbacks I get are triggered by this case, so unfortunately I don't think there's anything I can do.
