### ISSUE TITLE
Folder watching / polling

### ISSUE THREAD

**Issue by josephernest** [canton7/SyncTrayzor#488]
Hello,
I'm using SyncTrayzor succesfully since days, congratulations for this awesome project!
I'd just like to have more precisions about the README:

> Can watch your folders for changes, so you don't have to poll them frequently:
> * Syncthing on its own has to poll your folders, in order to see if any files have changed.
> * SyncTrayzor will watch your folders for changes, and alert Syncthing the second anything changes.
> * This means you can increase the polling interval in Syncthing, avoiding the resource usage of high-frequency polling, but still have any changes propagated straight away.

How does this work?

I have looked at Syncthing's `config.xml` and there is:

    rescanIntervalS="3600" fsWatcherEnabled="true" fsWatcherDelayS="10"

I moved 10 to 2 seconds, and it's even better.

Question: isn't this `fsWatcherDelayS` filesystem watcher *already included in Syncthing*?

Where exactly is the improvement that synctrayzor adds to the already-existing watcher?

When you speak about polling interval, do you mean the `rescanIntervalS="3600"` or the `fsWatcherDelayS="10"`?

Thanks in advance.

**Comment by canton7** [comment]
> Good call, those were all unchecked. Why is that?

When a new folder is added, notifications are enabled if any of the previous folders had notifications enabled. Now there might be an edge case if you delete all folders... I'll take this issue as a reminder to check that.

> Also, all my folder connection have "Watch for Changes" turned on. Is that a problem in this case (tryna getting notifications)?

No, unrelated. If you're using a vaguely new Syncthing version, you probably want to enable folder watching in Syncthing instead.
