### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by trymeouteh** [canton7/SyncTrayzor#489]
From what I understand SyncTrayzor is just an Electron based program. And Syncthing client is a web based client. Would it be possible to make SyncTrayzor for Linux users?

**Comment by canton7** [comment]
It's WPF, not Electron, so it's never going to work on Linux I'm afraid. There are other applications which do the same thing though, see the [community contributions page in the docs](https://docs.syncthing.net/users/contrib.html).
