### ISSUE TITLE
Feature Req: Please add the "Device names" where conflict file are located in "Conflict Resolver"

### ISSUE THREAD

**Issue by sandipkc7** [canton7/SyncTrayzor#492]

**Comment by canton7** [comment]
I'm not sure what you mean. All conflict files are on your local device, because that's how conflict files work. Can you clarify, please?

**Comment by sandipkc7** [comment]
Here, in my case usually conflict resolver appears for case like this
There are 2 devices "Dell" & "Lenovo". Both have admin privilege to folder name "Abc" in syncthing app. Dell opens an excel file  xyz.xls located at "Abc" folder, Dell device creates temporary file "~$xyz.xls" on shared folder and same is shared with "Lenovo" Device. 
Now the Lenovo device is switched off. And user at Dell device finishes working on excel which automatically removes ~$xyz.xls after closing file. 
Tomorrow when both devices come online, the "Conflict Resolver" shows the conflict. While it is easy to identify last updated file version by looking at timestamp of conflict files. But there are more than 4 devices with a common folder it would be easier to identify if the last activity on file is caused by which Device on such conflict files.

**Comment by canton7** [comment]
Syncthing creates conflict files, as [described here](https://docs.syncthing.net/users/faq.html?#what-if-there-is-a-conflict). The Conflict Resolver tool looks for files whose names match that pattern, and displays them. The only information it has to work with is the information in the file name.

There was some work done on Syncthing a while back to add the device ID of the device which created the conflict to the file name, but IIRC it started getting hard in some edge cases, and I don't think it was ever merged.

I suggest adding ignore rules which ignore the temporary `~$xyz.xls` files, as they're not the sorts of things you generally want to sync.

**Comment by sandipkc7** [comment]
Thank you for replying and I am happy to know someone out there also wanted device ID to be shown on conflict files.  My conflicts are on original files not temporary files. I can manage conflicted files based on timestamp for now.
Also temporary files notifies application that would lock it for being currently used across all systems, I have no problem with temporary files.

**Comment by fdutheil** [comment]
If I'm correct, device ID is now visible, right? 
It would be a great addition to the conflict resolver to have a method to chose by Source = Device ID additionnally to the timestamps method.

Is it possible to reopen this issue?
