### ISSUE TITLE
Crash when clicking any link

### ISSUE THREAD

**Issue by benshep** [canton7/SyncTrayzor#497]
If I click any link (Home page | Documentation | Support | ...), or click "Open in folder" in the conflict resolver, SyncTrayzor crashes:

> ---------------------------
> Visual Studio Just-In-Time Debugger
> ---------------------------
> An unhandled Microsoft .NET Framework exception occurred in SyncTrayzor.exe [12976]. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.
> 
> Check the documentation index for 'Just-in-time debugging, errors' for more information.

Syncthing seems to stay open.

Running SyncTrayzor 1.1.22, Syncthing 1.0.1-rc.2 on Windows 7 64-bit.

**Comment by canton7** [comment]
Can you post your log file? File -> Settings -> Logging -> Show SyncTrayzor Log File?

**Comment by canton7** [comment]
Can you just check whether `C:\Program Files\SyncTrayzor\ProcessRunner.exe` exists?

**Comment by benshep** [comment]
No, it doesn't. I've got `ProcessRunner.pdb` but not the `.exe`.

**Comment by canton7** [comment]
Something deleted it then (Antivirus?). You probably need to reinstall SyncTrayzor, and teach your AV not to meddle with SyncTrayzor's files

**Comment by benshep** [comment]
OK, thanks - I will. That's very odd - I'm sure I would have got a notification if the AV had deleted it.
