### ISSUE TITLE
Synctrazor shows "downloading" a large file that it is not downloading

### ISSUE THREAD

**Issue by jonathanmc** [canton7/SyncTrayzor#500]
Getting SyncTrazor showing as downloading (single click notification icon) a large file that Syncthing is definitely not downloading.  Tried restarting, and rebooting, and still shows.

**Comment by canton7** [comment]
If you can still reproduce this, please go to File -> Settings -> Logging and change Log level to Debug, then reproduce the issue and send me the log file (see the "Show SyncTrayzor log file" button on that page)

**Comment by jonathanmc** [comment]
Will do. Not sure what I did (nothing in particular after the above rebooting/restarting) but it has since disappeared.  I had restarted each side of the connection, too. If I can reproduce, I will, and post.

**Comment by canton7** [comment]
Thanks!

**Comment by jonathanmc** [comment]
I checked for logs but they have been overwritten while I had to focus on other things. If the issue happens again I'll preserve them.
