### ISSUE TITLE
Any chance for native Windows ARM version?

### ISSUE THREAD

**Issue by starscollide5** [canton7/SyncTrayzor#501]
Now that there is a number of WoA tablets, and Raspberry Pi 3 running Windows 10, it would be fantastic to have a native Windows on ARM version.

**Comment by canton7** [comment]
I'm afraid the embedded browser we use doesn't have an arm build, so you're out of luck.

**Comment by rubin55** [comment]
@canton7 It's a few years later (almost exactly 2!) Do you think you can revisit this? Is the embedded browser still not supported (which is it by the way?)? It would be quite great to have native support for SyncTrayzor on Windows on ARM.

I've filed https://github.com/syncthing/syncthing/issues/7445 for the syncthing binaries.

**Comment by canton7** [comment]
A quick Google suggests someone's working on it, on and off. There's no WPF support for arm either though
