### ISSUE TITLE
Problem closing popup

### ISSUE THREAD

**Issue by nanaya** [canton7/SyncTrayzor#505]
Clicking on the tray icon takes a while before the popup shows. Clicking on anything else during the delay causes the popup to stay open and can't be easily closed.

1. click on tray icon
2. click something else (e.g. empty area of taskbar)
3. wait until the popup shows
4. try closing it
5. give up, click on the tray icon, now wait until it pops up again after it is briefly hid before clicking on something else to finally close it

Would be nice if:
- doing number 2 above doesn't break trigger for closing popup
- clicking tray icon toggles the popup instead of just showing it (after confusingly hid it for a brief moment if it's already shown)

Version: 1.1.22
OS: Windows 8.1

**Comment by canton7** [comment]
I'm afraid the tray icon functionality is provided by a third-party package, and I don't have any control over its behaviour in cases like this.
