### ISSUE TITLE
getfileinformationbyhandle Problem

### ISSUE THREAD

**Issue by Duveru** [canton7/SyncTrayzor#508]
i have a problem since a few days... suddenly i get the errors

GetFileInformationByHandle \\?\E:: Unzulässige Funktion
GetFileInformationByHandle \\?\D:: Unzulässige Funktion

on my root-files since i using .stignore files... 

These are my two local HDD which will be synced on my server.

this is the config of .stignore placed in the root-directory in every drive. i'm using windows 10 pro x64.

this is the content of .stignore:

(?d)System Volume Information
(?d)$RECYCLE.BIN
(?d)desktop.ini
(?d)Thumbs.db

But Syntrayzor is synching every new file without some problems.

How can i fixed it?

**Comment by canton7** [comment]
Check the forum - there are several posts on this. This is a Syncthing issue anyway, not a SyncTrayzor one.
