### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Xeenych** [canton7/SyncTrayzor#509]
I've recently installed SyncTrayzorSetup-x64.exe
v 1.1.22
It crashes at startup

Сигнатура проблемы:
  Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	SyncTrayzor.exe
  Сигнатура проблемы 02:	1.1.22.0
  Сигнатура проблемы 03:	5bb73a08
  Сигнатура проблемы 04:	CefSharp.Core
  Сигнатура проблемы 05:	49.0.0.0
  Сигнатура проблемы 06:	57287dc9
  Сигнатура проблемы 07:	4e4
  Сигнатура проблемы 08:	101
  Сигнатура проблемы 09:	System.BadImageFormatException
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	7fa4
  Дополнительные сведения 2:	7fa46d44230fcd071385a4f63d7416c6
  Дополнительные сведения 3:	e73d
  Дополнительные сведения 4:	e73d1f3fbca3175e0c514b425bae8731

**Comment by canton7** [comment]
Is it the portable or installed version?

Where did you get that error information from? Does it show the "Something went badly wrong" window?

**Comment by Xeenych** [comment]
It is installed version from SyncTrayzorSetup-x64.exe

The window shown is the windows crash handler

**Comment by canton7** [comment]
Can you look in the SyncTrayzor log file? You'll find it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs`

**Comment by antoniocarloss** [comment]
I was having the same problem. It was a permission problem in the applicaion´s directory. Mine is portable 64 bits version.

**Comment by canton7** [comment]
@antoniocarloss I don't think yours will have been the same problem. A permission issue won't cause a `System.BadImageFormatException`

**Comment by canton7** [comment]
Closing as no response
