### ISSUE TITLE
Installed portable version in Program Files, but cannot start (UnauthorizedAccessException)

### ISSUE THREAD

**Issue by StephanRoessler** [canton7/SyncTrayzor#510]
Version: 1.1.22.0; Variant: Portable; Arch: Amd64
Path: C:\Program Files\SyncTrayzorPortable-x64\SyncTrayzor.exe
System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Program Files\SyncTrayzorPortable-x64\data\config.xml.tmp" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei SyncTrayzor.Utils.AtomicFileStream..ctor(String path, String tempPath) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:Zeile 20.
   bei SyncTrayzor.Services.FilesystemProvider.CreateAtomic(String path) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:Zeile 47.
   bei SyncTrayzor.Services.Config.ConfigurationProvider.SaveToFile(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:Zeile 421.
   bei SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration, Boolean& hadToCreate) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:Zeile 191.
   bei SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:Zeile 99.
   bei SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:Zeile 144.
   bei Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:Zeile 81.
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
You've running the Portable version, but you've put it in Program Files. The portable version writes data to the "data" folder inside the portable directory, and so the user who runs SyncTrayzor must have permission to write to the portable directory. This will not be the case if you've put it inside Program Files!

Either use the Installed version (which installs into Program Files, but stores its data in AppData), or put the portable version somewhere your user can write to.
