### ISSUE TITLE
Add SEPA (IBAN & BIC) donation

### ISSUE THREAD

**Issue by beerisgood** [canton7/SyncTrayzor#511]
If you can add this, i would donate.

Using https://www.justgiving.com/fundraising/SyncTrayzor-MSF isn't a option for me.
I like privacy

**Comment by canton7** [comment]
I'm afraid the donations don't go to me, they go direct to charity. If you can find a charity which takes IBAN / BIC, sure.

**Comment by beerisgood** [comment]
Maybe then add a LiberaPay account like Syncthing does?:
https://de.liberapay.com/Nextcloud/
