### ISSUE TITLE
TLS handshake error from 127.0.0.1:XXXX no cipher suite supported by both client and server

### ISSUE THREAD

**Issue by aniro** [canton7/SyncTrayzor#512]
GUI cant connect to syncthing daemon due to issues with TLS.
![image](https://user-images.githubusercontent.com/6030583/56022894-f735ce00-5d0c-11e9-874e-26d45a296448.png)

![image](https://user-images.githubusercontent.com/6030583/56022909-fef57280-5d0c-11e9-8ad9-a5f750fca546.png)

Web access to daemon works well:
![image](https://user-images.githubusercontent.com/6030583/56023042-5267c080-5d0d-11e9-8958-e4d0b0f7ecf0.png)

**Comment by canton7** [comment]
Which Syncthing version, and what Windows version?

**Comment by aniro** [comment]
@canton7 syncthing version is on the screenshot - 1.1.1 
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17763 Build 17763

**Comment by canton7** [comment]
Your browser is using http. Can you try `https://localhost:8384`?

**Comment by aniro** [comment]
Works fine, but certificate is invalid:
![image](https://user-images.githubusercontent.com/6030583/56028259-0a9a6680-5d18-11e9-9684-d7c80505ea75.png)
CN=hostname != localhost

**Comment by aniro** [comment]
Works fine but certificate is invalid:
![image](https://user-images.githubusercontent.com/6030583/56028503-8d232600-5d18-11e9-8296-808a6c7bfe6b.png)
cn=hostname != localhost

**Comment by canton7** [comment]
It's expected that it's untrusted - it's self-signed. I notice you switched from Chrome to Firefox - does it also work in Chrome? That does imply that Windows has the right cipher suites. Are you running the portable or installed version of SyncTrayzor?

**Comment by aniro** [comment]
It is installed.
Works in chrome as well, I just wanted to show that TLS1.2 is used if FF, did not know where to check that in chrome (figured it out now):
![image](https://user-images.githubusercontent.com/6030583/56029176-1e46cc80-5d1a-11e9-83dd-ae1191213089.png)

**Comment by canton7** [comment]
Can you post your log file? File -> Settings -> Logging -> Show SyncTrayzor log file.

**Comment by aniro** [comment]
```2019-04-12 12:01:27.5203 #16720 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.23.0 (Amd64) started at C:\Program Files\SyncTrayzor\SyncTrayzor.exe (.NET version: Unknown (461814)) 
2019-04-12 12:01:27.5472 #16720 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\<username>\AppData\Roaming\SyncTrayzor\logs 
2019-04-12 12:01:27.5492 #16720 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\Program Files\SyncTrayzor\syncthing.exe 
2019-04-12 12:01:27.5492 #16720 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\<username>\AppData\Roaming\SyncTrayzor\config.xml 
2019-04-12 12:01:27.5492 #16720 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\<username>\AppData\Roaming\SyncTrayzor\config-backups 
2019-04-12 12:01:27.5492 #16720 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\<username>\AppData\Local\SyncTrayzor\cef\cache 
2019-04-12 12:01:27.5492 #16720 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\Users\<username>\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-04-12 12:01:27.5492 #16720 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath:  
2019-04-12 12:01:27.5492 #16720 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2019-04-12 12:01:27.5492 #16720 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Did not find any other processes, or they all responded with an error 
2019-04-12 12:01:27.5772 #16720 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowDeviceConnectivityBalloons=True ShowDeviceOrFolderRejectedBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingCommandLineFlags=[] SyncthingEnvironmentalVariables=[] SyncthingDenyUpgrade=False SyncthingPriorityLevel=Normal Folders=[] NotifyOfNewVersions=True LatestNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingCustomPath= SyncthingCustomHomePath= ShowSynchronizedBalloonEvenIfNothingDownloaded=False DisableHardwareRendering=False EnableFailedTransferAlerts=True EnableConflictFileMonitoring=True ConflictResolverDeletesToRecycleBin=True PauseDevicesOnMeteredNetworks=True HaveDonated=False IconAnimationMode=DataTransferring OpenFolderCommand=explorer.exe "{0}" ShowFileInFolderCommand=explorer.exe /select, "{0}"LogLevel=Info> 
2019-04-12 12:01:27.5842 #16720 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\Users\<username>\AppData\Roaming\SyncTrayzor\config.xml 
2019-04-12 12:01:27.6290 #16720 [Debug] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2019-04-12 12:01:28.5875 #16720 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2019-04-12 12:01:29.0480 #16720 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\<username>\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-04-12 12:01:29.3377 #16720 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
```

**Comment by aniro** [comment]
oh.. accidentally closed it(

**Comment by canton7** [comment]
There should be a line just above the bit you pasted, which starts "SyncTrayzor.Bootstrapper: SyncTrazor version". Can you post that too?

**Comment by aniro** [comment]
fixed logs snippet, markdown ate 1st line as a code block language.

**Comment by canton7** [comment]
So you're using .NET 4.7.2, which should be absolutely fine.

Can you leave it until SyncTrayzor posts a dialog saying that it couldn't connect to Syncthing (might take quite a long time iirc), then post the updated log?

**Comment by canton7** [comment]
Oh, before you do that, turn the log level up to Debug in File -> Settings -> Logging.

**Comment by aniro** [comment]
here you go
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/3073083/SyncTrayzor.log)

**Comment by canton7** [comment]
Thanks. 

So it's definitely the cipher suite negotiation that's failing. Which is odd, as Windows and Syncthing definitely have cipher suites in common.

Is your machine on a domain? Presumably, if it's Windows 10 Enterprise. My guess is that a group policy has overridden the default cipher suites in Schannel, such that it has nothing in common with Syncthing (Syncthing's suites are [listed here](https://github.com/syncthing/syncthing/blob/f24676ba5ab294d3bd250479718564eb404b93b6/lib/tlsutil/tlsutil.go#L31)). I'm guessing that Chrome and Firefox don't use Schannel.

Can you run `(Get-TlsCipherSuite).Name` in powershell, and post the result?

**Comment by aniro** [comment]
Yes, machine is a member of domain so there might be some weird policies applied. 
output of (Get-TlsCipherSuite).Name
```
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P521
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P521
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P521
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P521
TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384
```

There are number of suites in common (if I understand correctly elliptic curve specs PXXX from the output above can be neglected):
```
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA                          <
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256                       <
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256                       <
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA                          <
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384                       <
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305                        <
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                              TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256                           TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256                         <
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                              TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384                         | TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305                          | TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA                                    TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA256                                 TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_GCM_SHA256                                 TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA                                    TLS_RSA_WITH_AES_256_CBC_SHA
                                                              > TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384                                 TLS_RSA_WITH_AES_256_GCM_SHA384
```

Tested WebUI in IE and Edge: it opens without any issues in both.

**Comment by canton7** [comment]
Even if you ignore the primes, they've still both got TLS_RSA_WITH_AES_256_GCM_SHA384 in common.

Can you just try editing `SyncTrayzor.exe.config`, and inside `<startup>`, add `<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />` (just after the existing `<supportedRuntime` element). Just in case it's a difference between .NET versions...

**Comment by aniro** [comment]
Added this line to c:\Program Files\SyncTrayzor\SyncTrayzor.exe.config but nothing changed. Is there any way to confirm that .net version change did anything?

**Comment by canton7** [comment]
Just to make sure: you restarted SyncTrayzor after making that change?

OK, that was only a shot in the dark. I'm running out of ideas I'm afraid. Perhaps looking at what cipher suites are being offered by Syncthing in practice is the next step? e.g. from [here](https://superuser.com/questions/109213/how-do-i-list-the-ssl-tls-cipher-suites-a-particular-website-offers).

**Comment by aniro** [comment]
This is what I got from the sslscan utility suggested in the thread you have mentioned above:
```
sslscan.exe  127.0.0.1:8384
Version: 1.11.11 Windows 64-bit (Mingw)
OpenSSL 1.0.2-chacha (1.0.2g-dev)

Connected to 127.0.0.1

Testing SSL server 127.0.0.1 on port 8384 using SNI name 127.0.0.1

  TLS Fallback SCSV:
Server does not support TLS Fallback SCSV

  TLS renegotiation:
Session renegotiation not supported

  TLS Compression:
Compression disabled

  Heartbleed:
TLS 1.2 not vulnerable to heartbleed
TLS 1.1 not vulnerable to heartbleed
TLS 1.0 not vulnerable to heartbleed

  Supported Server Cipher(s):
Preferred TLSv1.2  256 bits  ECDHE-ECDSA-AES256-GCM-SHA384 Curve P-521 DHE 521
Accepted  TLSv1.2  128 bits  ECDHE-ECDSA-AES128-GCM-SHA256 Curve P-521 DHE 521
Accepted  TLSv1.2  128 bits  ECDHE-ECDSA-AES128-SHA256     Curve P-521 DHE 521
Accepted  TLSv1.2  128 bits  ECDHE-ECDSA-AES128-SHA        Curve P-521 DHE 521
Accepted  TLSv1.2  256 bits  ECDHE-ECDSA-AES256-SHA        Curve P-521 DHE 521
```
It looks like server does not support any of the suites from (Get-TlsCipherSuite).Name

**Comment by GermanCoding** [comment]
I can shed a minor bit of light on this, because I know TLS a little:

Syncthing generates a certificate for https on first run. Syncthing versions older than v0.14.53 generate a RSA certificate (for the browser) whilst v0.14.53 and newer generate an ECDSA certificate.

When an ECDSA certificate is used, ECDSA must be used for the handshake (signing). So **EVERY** ciphersuite containing the word "RSA" cannot be used. The user who opened this issue **only** supported RSA ciphers, so it's impossible to work with fresh syncthing certificates.

I've no idea why, but it seems because some administrator configured this really weirdly- the choice of cipher suites is "not useful", to formulate it friendly. This is definetly not a default setting in any Windows operating system that I know of.

> 
> 
> Yes, machine is a member of domain so there might be some weird policies applied.
> output of (Get-TlsCipherSuite).Name
> 
> ```
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P384
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P521
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P256
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P384
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P521
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P521
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P521
> TLS_RSA_WITH_3DES_EDE_CBC_SHA
> TLS_RSA_WITH_AES_128_CBC_SHA
> TLS_RSA_WITH_AES_128_CBC_SHA256
> TLS_RSA_WITH_AES_128_GCM_SHA256
> TLS_RSA_WITH_AES_256_CBC_SHA
> TLS_RSA_WITH_AES_256_CBC_SHA256
> TLS_RSA_WITH_AES_256_GCM_SHA384

There are two possible fixes for this issue:

1. The sensible way, somehow configure the policy to allow modern, rational ciphers. This means including ECDSA for the handshake (there are FIPS-compliant modes for this, for companies who need FIPS). Mozilla lists a [reasonable config](https://wiki.mozilla.org/Security/Server_Side_TLS).

2. The hacky way, replace syncthing's https-cert.pem (and https-key) files with a X.509 certificate that uses RSA.

Disabling TLS for local communication entirely would work too, I guess, but I don't know if that's possible in SyncTrayzor. Using TLS is the better choice anyway.

**Comment by canton7** [comment]
Thanks for your input @GermanCoding!

Unfortunately I don't think there's anything I can do here. Closing.
