### ISSUE TITLE
Transifex subscription expired

### ISSUE THREAD

**Issue by CornyjK** [canton7/SyncTrayzor#515]
![image](https://user-images.githubusercontent.com/9021297/58644727-2971ae00-8302-11e9-9cf5-008a0a6af72e.png)

I get this when I try to join a team.

**Comment by canton7** [comment]
Strange - I don't see anything when I log in. Can you try again please?

**Comment by CornyjK** [comment]
Strange, it works now.

**Comment by canton7** [comment]
Maybe me signing in was enough to get it working again
