### ISSUE TITLE
Config file version is newer than support version

### ISSUE THREAD

**Issue by BinaryAura** [canton7/SyncTrayzor#517]
I've been attempting to get syncTrayzor to work on my machine but Syncting refuses to start. Attached are the syncthing, and syncTrayzor (Trace) logs.
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/3377496/syncthing.log)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/3377497/SyncTrayzor.log)

**Comment by canton7** [comment]
Looks like you ran a newer version of Syncthing, then installed SyncTrayzor? It looks like the version of Syncthing bundled with SyncTrayzor is older than the one which wrote your Syncthing config file.

The easiest way to solve this is going to be to download the latest Syncthing.exe, and put it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor`

**Comment by Mazo** [comment]
Have just had this issue myself - installed syncthing via chocolatey, then uninstalled and installed synctrayzor through chocolatey.

Synctrayzor on chocolatey is currently version 1.1.23, not 1.2.0. Unfortunately it doesn't seem to auto update when this issue happens.

**Comment by ggraubins** [comment]
FYI... I had this issue, too. I overwrote the syncthing.exe with the latest version obtained from the standalone SyncThing and it's working now. Thanks for the fix!

**Comment by ITRabbitx** [comment]
I tried the above fix to solve this issue, but in my case this did not help. 

I still get the same warning message as before:
```
WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
```

I downloaded Syncthing version 1.4.7 and placed syncthing.exe into c:\program files\synctrayzor directory. I asked synctrayzor to kill all syncthing instances and start again. To my suprise i saw in the logs that: 
```
INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
```

**Comment by Rallandlr** [comment]
> I tried the above fix to solve this issue, but in my case this did not help.
> 
> I still get the same warning message as before:
> 
> ```
> WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
> ```
> 
> I downloaded Syncthing version 1.4.7 and placed syncthing.exe into c:\program files\synctrayzor directory. I asked synctrayzor to kill all syncthing instances and start again. To my suprise i saw in the logs that:
> 
> ```
> INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
> ```
> 
> Any help would very much be appreciated. Thank you.

You have to update syncthing.exe in the following address:

C:\Users\<You>\AppData\Roaming\SyncTrayzor

You changed it in program files, its different.
As said before, paste the latest syncthing.exe there, and try again.
It fixed it for me.

**Comment by santilococo** [comment]
> Looks like you ran a newer version of Syncthing, then installed SyncTrayzor? It looks like the version of Syncthing bundled with SyncTrayzor is older than the one which wrote your Syncthing config file.
> 
> The easiest way to solve this is going to be to download the latest Syncthing.exe, and put it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor`

Thanks a lot. That solved my issue.

**Comment by Asinin3** [comment]
I had this issue on a fresh Windows 10 Install only a few hours prior. I fixed it by uninstalling syncthing, cleaning out program files syncthing folder, and the folder in appdata. I think I ran a syncthing.exe accidentally before i realized I actually needed to grab synctrayzor.

**Comment by sm5050** [comment]
> Looks like you ran a newer version of Syncthing, then installed SyncTrayzor? It looks like the version of Syncthing bundled with SyncTrayzor is older than the one which wrote your Syncthing config file.
> 
> The easiest way to solve this is going to be to download the latest Syncthing.exe, and put it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor`

Hi, Thanks for the help.

**Comment by D-Code** [comment]
In my case, I got this issue when trying to migrate from Syncthing-GTK to SyncTrayzor.

Noticed you can override some settings via _File -> Settings -> Syncthing_ and then under the expanded _Advanced_ rolldown.

I set the _Syncthing Custom Path_ to `C:\Users\<USER>\AppData\Local\syncthing\syncthing.exe` and _Syncthing Custom Home Path_ to `C:\Users\<USER>\AppData\Local\syncthing`.

After restarting SyncTrayzor, everything worked smoothly. I could also update Syncthing to the latest version via the SyncTrayzor UI.

**Comment by minusmagis** [comment]
> FYI... I had this issue, too. I overwrote the syncthing.exe with the latest version obtained from the standalone SyncThing and it's working now. Thanks for the fix!

This Fixed the same issue on a windows machine. The syncthing.exe file seems to not be up to date on SyncTrayzor's side.

Thanks for the help 👍

**Comment by canton7** [comment]
Version 1.1.26 ships the latest Syncthing

**Comment by bartonzzx** [comment]
Maybe you had used the Syncthing web version before you use SyncTrayor.
That can explains why you have a newer config file because you config it before
Go to your C:\users\<your computer name>\AppData\Local\Syncthing.
And in this folder,delete config.xml.
If it isn`t work,go to C:\Users\<your computer name>\AppData\Roaming\SyncTrayzor, and in this folder,delete config.xml.
