### ISSUE TITLE
"Open Folder" doesn't (opens wrong location)

### ISSUE THREAD

**Issue by calmh** [canton7/SyncTrayzor#519]
Possibly related to the use of tilde and/or forward slashes in the folder location:

<img width="567" alt="Screen Shot 2019-07-25 at 10 56 47" src="https://user-images.githubusercontent.com/125426/61860834-eb8ca280-aeca-11e9-902f-7e7d2f4ab24f.png">

Clicking the button opens `C:\Users\Jakob Borg\Documents` whereas it *should* open `C:\Users\Jakob Borg\dossiers\2019\201900497`.

(Tilde expansion according to add-folder dialog below)

<img width="914" alt="Screen Shot 2019-07-25 at 10 59 08" src="https://user-images.githubusercontent.com/125426/61861010-44f4d180-aecb-11e9-91de-3d9d03089ee5.png">

**Comment by canton7** [comment]
Weird, I can't reproduce this, even after manually editing Syncthing's config.xml to get a tilde into the folder path (the UI doesn't let you).

Can you grab the Debug logs? See File -> Settings -> Logging. You're looking for a line containiner `[Debug] ProcessStartProvider Starting`.

**Comment by canton7** [comment]
Ah no, seems this was the same root cause as #520, and I fixed this en route.

**Comment by canton7** [comment]
(It'll be the forward slashes, rather than the tilde)

**Comment by calmh** [comment]
Sweet, thanks.
