### ISSUE TITLE
Zoom in built-in browser

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#52]
Hi,
Great peace of work, installer for v0.11 works like a charm...

My "issue":
I'm using web-gui in both external browser an in built-in one. In external (mostly chrome, sometimes firefox) I have set up zoom level (75%) because I have more shared folder then fits on screen and I don't want to scroll down. Font in web-gui is "ugly" big anyway so this suits me just fine. But I can't do it in built-in browser. I went through couple forum post on how to set zoom level in cefsharp but I didn't even find any config file in synctrayzor folder which I could modify. Can you add "zoom level" to settings? Or could you implement it to native UI you mentioned some time before (if it is still actual)?

Thanks

**Comment by canton7** [comment]
This shouldn't be too hard. The native UI is still a work-in-progress (fixing things is taking priority)
