### ISSUE TITLE
Malware on connected IPs

### ISSUE THREAD

**Issue by celeroll** [canton7/SyncTrayzor#522]
Hello, 
I have been forced to remove the software from my computer by our company admin, because it is establishing connections with multiple IPs and some of them are connected with   recent malicious activity.

IP mentioned is 86.125.249.64 "Tor endpoint".

What is the real situation?

**Comment by canton7** [comment]
This will be related to Syncthing, rather than SyncTrayzor, so [the forum](https://forum.syncthing.net) is the place for this. Its probably a relay.

**Comment by celeroll** [comment]
You are right. I'll close the issue :)
