### ISSUE TITLE
Scans are not staggered

### ISSUE THREAD

**Issue by uok** [canton7/SyncTrayzor#523]
Thanks for this great software!

I noticed today that during startup (and also with click on "rescan all") SyncTrayzor scans all folders simultaneously. A plain Syncthing (same version) installation scans one folder at a time while the rest has status "waiting to scan"

Why is this different?

**Comment by canton7** [comment]
SyncTrayzor does not get involved in the scans at all. When you press Rescan All I'm Syncthing's web interface, SyncTrayzor is not even aware that you've pressed it. Whatever the difference you're seeing is, it's not related to SyncTrayzor I'm afraid.

**Comment by uok** [comment]
Ok, thanks for commenting, I thought so too. I will compare several config.xml and report back
