### ISSUE TITLE
"folder path missing" on login when using relative paths

### ISSUE THREAD

**Issue by tomasz1986** [canton7/SyncTrayzor#524]
I am using the portable version of SyncTrayzor. When using relative paths for folders, such as "..\XXX", the folders are not detected when SyncTrayzor is set to "Automatically start on login".

The log file states as follows (I have obscured some data).

```
0000-00-00 00:00:00.0000 #6608 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [XXXXX] 00:00:00 WARNING: Error on folder "XXX" (xxxxx-xxxxx): folder path missing
0000-00-00 00:00:00.0000 #6608 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [XXXXX] 00:00:00 INFO: Failed initial scan of sendreceive folder "XXX" (xxxxx-xxxxx)
```

and the Syncthing GUI looks like this.

![image](https://user-images.githubusercontent.com/5626656/62344383-c3372080-b528-11e9-90e4-e4077ee3aba0.png)

Now, as soon as I change the path to a non-relative one in the advanced settings, the folder is suddenly detected correctly, and it starts syncing.

![image](https://user-images.githubusercontent.com/5626656/62344405-d5b15a00-b528-11e9-95f9-2a71f2b3a035.png)

However, if I change the paths to the relative ones once more, the folders become missing again.

What I have observed is:

1. If you close SyncTrayzor and reopen it manually, the folders suddenly become accessible (without even touching the path settings).
2. The problem does not occur if the folder paths are set to non-relative.
3. The problem occurs on two desktop PCs, one running Windows 7 and one running Windows 10.

I am not sure whether this is caused by SyncTrayzor specifically or by Syncthing itself, but it seems that relative folder paths are not detected properly. The funny thing is that this happens only when SyncTrayzor is set to start on login. Everything works correctly if SyncTrayzor has been started manually. The folders themselves in both cases are local (not network), and are located on a different partition of the same physical disk.

Do you have any idea why this can be happening?

Thank you very much for help in advance.

**Edit:**

The problem is that enabling "Automatically start on login" simply adds `D:\SyncTrayzor\SyncTrayzor.exe" -minimized` to `HKCU\Software\Microsoft\Windows\CurrentVersion\Run`. This makes it start from a different folder, thus the relative paths do not match. When using the shortcut on the other hand, SyncTrayzor.exe is started from its own folder, and the relative paths match there.

I have overcome the issue by using a simple batch script.

```
cd /d "d:\synctrayzor"
start "" "d:\synctrayzor\synctrayzor.exe" -minimized
```

To really solve the problem though, I would humbly like to suggest using the Task Scheduler instead of the Registry to start SyncTrayzor on boot. It is because in the Task Scheduler it is possible to add the starting path in addition to the program path like this.

![image](https://user-images.githubusercontent.com/5626656/62345973-51aea080-b52f-11e9-9fd9-2a31420f63e9.png)

This would make it consistent with the shortcut (or with just running SyncTrayzor.exe manually from its folder, which is usually the case with the portable version), which already uses the SyncTrayzor folder as the starting path for all the relative paths set in the Syncthing GUI.

**Comment by canton7** [comment]
I can control the CWD that Syncthing sees when it starts - it's probably worth setting this to the directory containing SyncTrayzor.exe.
