### ISSUE TITLE
Start syncthing before logging in

### ISSUE THREAD

**Issue by hp48gx** [canton7/SyncTrayzor#528]
Hello,
sorry for the possibly dumb question. 
1) is there an option in synctrayzor to start syncthing as a service, without logging in, so that it's still "compatible" with synctrayzor (e.g. start/stop/restart still work)?
2) assuming the answer is no... there's a procedure on the syncthing website suggesting to use task scheduler and create a task. however, I see that synctrayzor creates a copy of syncthing.exe and starts up the copy. so I'm not completely sure of what would be the best way to do it

thanks in advance

**Comment by canton7** [comment]
SyncTrayzor cannot run Syncthing as a service.

Running Syncthing as a service is not recommended for most users. Services run with elevated permissions by default, and running Syncthing with elevated permissions is a bad idea. If you change this to run Syncthing as a specific user, then you need to run a separate service for each user.

If you start Syncthing as a service, you cannot use SyncTrayzor. SyncTrayzor needs to be the thing that starts Syncthing, so that it can set up the API key it needs to be able to securely communicate with Syncthing.

**Comment by hp48gx** [comment]
> change this to run Syncthing as a specific user

generally you don't run services with admin permissions, but you create a brand new user and run the service under these credentials.


> If you start Syncthing as a service, you cannot use SyncTrayzor. 

please, note that my goal is more general than "running a service", it's actually "running before logging in".

suppose I use the task scheduler to start an instance of syncthing.exe under my own user credentials: maybe there is a command line which allows SyncTrayzor to control this instance anyway?

**Comment by canton7** [comment]
> generally you don't run services with admin permissions, but you create a brand new user with limited/tailored privileges and run the service under these credentials.

The point of Syncthing is to sync a user's files. Your brand new user typically won't have permission to your user's files.

I mean yes it *can* be done, and it *can* be made secure if you're careful, but this isn't the direction we want to push normal users in.

> suppose I use the task scheduler to start an instance of syncthing.exe under my own user credentials: maybe there is a command line which allows SyncTrayzor to control this instance anyway?

There is not. SyncTrayzor needs to be the parent process of Syncthing.

**Comment by hp48gx** [comment]
> There is not. SyncTrayzor needs to be the parent process of Syncthing.

ok, thanks for the clarification. 
p.s.: just curious: what's the rationale for starting a copy of syncthing.exe?

**Comment by canton7** [comment]
Syncthing needs to auto-upgrade, so we need to put it somewhere user-writable (i.e. not Program Files). AppData is a good place for this. If the version in AppData doesn't exist for some reason (mainly user who's never run SyncTrayzor before), we use out backup version from Program Files.

Also it's important that we never downgrade Syncthing, as older versions of Syncthing sometimes can't read newer versions' config files. The user might upgrade Syncthing to the latest version, then upgrade SyncTrayzor to a version which does not have the latest Syncthing -- in that case, we need to keep using the user's latest version.

Also, different users might be using different versions of Syncthing (if one user upgraded Syncthing and another didn't). We need to make sure we use each user's version of Syncthing for that user.

**Comment by SKJoy** [comment]
I think you can create a Task with Task scheduler, assuming you are on Windows, that runs under the specific User at system start up. That should do it.
