### ISSUE TITLE
"The Syncthing admin interface is configured to allow remote access without a password" has started popping up

### ISSUE THREAD

**Issue by davehampson** [canton7/SyncTrayzor#530]
A workaround is to change the startup from localhost to 127.0.0.1

![image](https://user-images.githubusercontent.com/8753766/66037259-1a487a00-e507-11e9-8e54-547649e9b900.png)

there must be a simple string compare going on in Symcthing that doesn't realise that localhost and 127.0.0.1 is the same

**Comment by zzjjbb** [comment]
Thanks! The warning disappear now. (I even spend some time to see if it really open a port on the public network)

**Comment by GermanCoding** [comment]
Yes, this is caused by this: https://github.com/syncthing/syncthing/issues/6049

**Comment by canton7** [comment]
I think this is now fixed on Syncthing's side
