### ISSUE TITLE
Crash when clicking on tray icon or any UI dropdown menu

### ISSUE THREAD

**Issue by cryptikon** [canton7/SyncTrayzor#531]
My SyncTrayzor crashes without any error pop up whenever I click on the tray icon (both left and right click). 

It also crashes when I have the window open and click on any drop-down element of the menu bar. If I click on the settings button on the lower right part of the window I can access the settings but the program crashes again, the moment I click on any drop down menu (**edit:** and any text field)  in the settings window. 

syncthing.exe remains open as a zombie process and the Syncthing gui itself works without issues.

**Synctrayzor versions tested:** 1.1.24; 1.1.22; 1.1.16

I already tried re-installing, deleting the syncthing/synctrayzor config folders and using the portable version.

Anyone have an idea what's causing this?

**Comment by canton7** [comment]
Please post your log file: File -> Settings -> Logging -> Show SyncTrayzor log file

**Comment by canton7** [comment]
Closing as no response
