### ISSUE TITLE
Update to latest syncthing version

### ISSUE THREAD

**Issue by erotavlasme** [canton7/SyncTrayzor#535]
Hi,
thank you for your great project. It helps a lot on windows system. Are you still developing it? Are you planning to update syncTrayzor to latest syncthing version?
Thank you

**Comment by canton7** [comment]
I'm fixing problems (although I've been busy recently). Syncthing will auto-update as soon as it's run, so I don't update SyncTrayzor just to bump the Syncthing version.

**Comment by alfredonodo** [comment]
Hi, any ETA for the update?
Thank you

**Comment by canton7** [comment]
Are you waiting for a particular fix, or is this a general "when is the next version out?" query?

**Comment by alfredonodo** [comment]
I waiting for v1.3 of synctrazor

**Comment by erotavlas-turbo** [comment]
Is the project actively maintained?

**Comment by canton7** [comment]
I'm keeping an eye on it, and I'll fix anything serious, but I don't have time for new features at the moment.

**Comment by erotavlas-turbo** [comment]
I'm personally waiting an update to have security fixes and new features.

**Comment by canton7** [comment]
There are no known security issues with SyncTrayzor, and hence no security fixes. If you want new features, you're welcome to contribute them :)

**Comment by erotavlas-turbo** [comment]
As far I know, if I use the current version of syncTrayzor I'm not using the latest version of syncthing. According to the [release note](https://github.com/syncthing/syncthing/releases) there are a lot of bug and several security fixes.

**Comment by canton7** [comment]
Syncthing auto-updates. Unless you've done something to stop it auto-updating, you should always be running the latest version of Syncthing.

**Comment by erotavlas-turbo** [comment]
Well this is an excellent new. So are the differences just on GUI?

**Comment by canton7** [comment]
Go to Syncthing -> Open in browser (or whatever the option's called). That's Syncthing's UI. Everything else you see in SyncTrayzor is SyncTrayzor (the menu at the top, console at the bottom, tray icon, etc)

**Comment by erotavlas-turbo** [comment]
I know about this. I'm using syncTrayzor on windows since it auto starts at boot and it has a nice UI.

**Comment by canton7** [comment]
I misunderstood what you meant by "So are the differences just on GUI?", then

**Comment by erotavlas-turbo** [comment]
I was asking about the differences between syncthing and syncTrayzor since I discovered that even an old version of syncTrayzor uses the latest version of syncthing.

**Comment by canton7** [comment]
Right, that's the question I tried to answer above.

**Comment by canton7** [comment]
Version 1.1.26 ships the latest Syncthing
