### ISSUE TITLE
Disabling "Watch for Changes" not respected

### ISSUE THREAD

**Issue by tristanbrown** [canton7/SyncTrayzor#538]
SyncTrayzor folder-watching is on by default, until it is manually disabled from the File>Settings menu. Disabling "Watch for Changes" in the "Edit Folder" dialogue only disables Syncthing folder-watching, and then SyncTrayzor folder-watching takes over. To disable ALL folder-watching, you additionally need to disable SyncTrayzor folder-watching in the File>Settings menu.

This behavior is very unintuitive, and not indicated in any way by the GUI. What should happen is if I disable "Watch for Changes" in the "Edit Folder" dialogue, ALL folder watching should then be disabled. I'm not sure what the use-case is for SyncTrayzor folder watching instead of Syncthing folder-watching, but it shouldn't be enabled by default if the "Watch for Changes" check box on each folder doesn't control it. Also the "eyeball" watched/not-watched" graphic should refer to all forms of watching, not just Syncthing watching.

**Comment by canton7** [comment]
SyncTrayzor's folder watching predates Syncthing's by a long way, and disables itself when Syncthing's is enabled to allow a smooth transition from old (SyncTrayzor's) to new (Syncthing's).

Given that Syncthing's folder watching has been in place for a while now, it's probably time to remove SyncTrayzor's for good.

**Comment by canton7** [comment]
The previous logic was that if any folders had SyncTrayzor's watching enabled, then new folders would too (fine). However it also assumed that watching should be enabled if there were no previous folders, and a folder was added.

Removed that last bit, which should solve your issue.

Stripping out watching altogether is a bigger task
