### ISSUE TITLE
GUI: In the settings, the text is cut off in the German language version

### ISSUE THREAD

**Issue by shanks1337** [canton7/SyncTrayzor#540]
1. right click tray icon
2. choose settings

actual:
The text is incomplete for the option "Benachrichtigung, wenn eine neue Version von SyncTrayzor verfügbar i"

![SyncTrayzor settings](https://user-images.githubusercontent.com/8984284/71529042-0f716b80-28e3-11ea-8acc-21efd4e307f1.png)

expected: 
wrapped into next line "Benachrichtigung, wenn eine neue Version von SyncTrayzor verfügbar 
ist"
OR
mouse hover shows tooltip with whole sentence
OR 
unlock resizing of the window

Version SyncTrayzor: 1.1.24
Version Syncthing: v1.3.2
Version OS: Windows 8.1 Pro N

**Comment by canton7** [comment]
Thanks!

**Comment by shanks1337** [comment]
One line does still not wrap

![syncthing options](https://user-images.githubusercontent.com/8984284/103421889-0757a600-4b9f-11eb-8793-28b77f67979c.png)

Also: I don't understand why width of the window is fixed but height is not. I'd expect that height should at least be limited to maximum text.
