### ISSUE TITLE
GUI: Multiple instances when selecting settings

### ISSUE THREAD

**Issue by shanks1337** [canton7/SyncTrayzor#541]
1. Right click on try icon
2. Chose settings
3. Repeat 1&2 

actual:
If you open settings several times, you get several identical settings instances, but only the most recent setting instance is interactable until closed.
![SyncTrayzor serveral instances settings](https://user-images.githubusercontent.com/8984284/71529992-f323fd80-28e7-11ea-848f-65a3fa4160b5.png)

expected:
There is always just one instance of settings and previous instance gets focused as active window when user choses 'settings' at the tray icon. 

Version SyncTrayzor: 1.1.24
Version Syncthing: v1.3.2
Version OS: Windows 8.1 Pro N

**Comment by canton7** [comment]
Thanks!
