### ISSUE TITLE
GUI: Change of language in Syncthing doesn't extent to SyncTrayzor

### ISSUE THREAD

**Issue by shanks1337** [canton7/SyncTrayzor#542]
1. Open SyncTrayzor
2. Change displayed language setting

actual:
Console and menu points of SyncTrayzor stay in default (system?) language.
![SyncTrayzor language issue](https://user-images.githubusercontent.com/8984284/71530464-31bab780-28ea-11ea-8a8a-9e2fc6dfca33.png)

expected: 
Syncthing language setting also changes SyncTrayzor's language.

Version SyncTrayzor: 1.1.24
Version Syncthing: v1.3.2
Version OS: Windows 8.1 Pro N

**Comment by canton7** [comment]
Not possible I'm afraid. SyncTrayzor's language is affected by your Windows language setting. There's a checkbox in the settings which will make SyncTrayzor ask Syncthing to use the language that it's using.
