### ISSUE TITLE
Recently Updated Files not showing

### ISSUE THREAD

**Issue by robonxt** [canton7/SyncTrayzor#543]
In the taskbar, SyncTrayzor doesn't show any of the recently updated files, even though I have edited files and moved folders around. In the image below, there is some transfer activity going on a few minutes before I screenshotted this, but nothing is listed.
![2019-12-28](https://user-images.githubusercontent.com/8854735/71551270-02fb1a80-2998-11ea-8a7c-60288f388696.png)

**Comment by canton7** [comment]
That only shows downloads - I should change the wording

**Comment by robonxt** [comment]
ah ok. Is it possible to add in recent activity like how OneDrive, Google Drive, DropBox, etc does?

**Comment by canton7** [comment]
You mean, uploads?

Syncthing itself has a "Recent Changes" button, but that is not what the tray item is showing. I can't show uploads, because Syncthing doesn't have a concept of "uploading a file"

**Comment by mmedic** [comment]
I am seeing the same issue. The graphs are not showing any activity when Syncthing is obviously synchronizing.

![image](https://user-images.githubusercontent.com/5660492/74608003-863d1080-50ab-11ea-9ac4-25667d854c5e.png)

**Comment by canton7** [comment]
Closing: text changed to "Downloads" in 1.1.26
