### ISSUE TITLE
How well does synching perform on a multi-folder scenario?

### ISSUE THREAD

**Issue by gpr-indevelopment** [canton7/SyncTrayzor#546]
I am considering using SyncTrayzor for a project that I need to syncronize CAD files between 6 different machines. I have done some testing with the software, and it seems to work just fine and suit my needs.

But, I have one question: If I have a syncronized folder with 5000 files, of 10 Mb each, and one new file is added, will SyncTrayzor move every single file across the network to syncronize the folder, or will it just move that single file that was added? Does the same apply to nested files?

**Comment by GermanCoding** [comment]
SyncTrayzor is a wrapper around the main program, syncthing. General questions or support topics can be made on [the official forum](https://forum.syncthing.net/).

**Comment by canton7** [comment]
Syncthing will just move what has changed. Please see the Syncthign docs and forum for more details -- this GitHub project is about SyncTrayzor specifically.
