### ISSUE TITLE
Error message on startup - "Folder is not running"

### ISSUE THREAD

**Issue by GermanCoding** [canton7/SyncTrayzor#547]
I've installed SyncTrayzor for years now and it has always been running fine. Recently I started getting errors messages on boot, even though everything seems to run fine afterwards. This is what is says:

![synctrayzor_error](https://user-images.githubusercontent.com/4279661/72205577-02c54980-3485-11ea-93f2-463d13d0db91.PNG)

The mssage is partly localized (german), translated to english would be roughly this:

> Syncthing was not started correctly
> Syncthing could not be started. RestEase Error. StatusCode: NotFound. Content: folder is not running. Reason: Not Found. Please note hints in syncthing's console.

Some facts on when this happens:

- I've set SyncTrayzor to start on boot and this message appears immediatly after I have logged on. It seems to never appear if I exit and start SyncTrayzor manually.
- It only happens on **some** boots, so I can't reproduce it reliably. It also never showed up before some recent date (may be related to syncthing 1.3.3 update, but not sure).
- I've seen the message now on two different computers, both running Windows 10 1903 (more version info below).
- The message seems to appear very early in the startup, long before syncthing has had time to fully initialize.

**After I've clicked on "OK", SyncTrayzor starts up normally**. I can access the GUI, everything is running fine. It's just the nagging message I have to click first. There are no abnormal messages in syncthing's log.

When the message appeared and syncthing has started, if I enter SyncTrayzors settings (File -> SyncTrayzor -> Directories), it says "Directory not available. Please start syncthing!".

I've disabled watching & notifications for all folders in SyncTrayzor, seems to have no effect on the error.

**Version info:**
All affected computers are running Windows 10 1903, SyncTrayzor 1.1.23.0 and 1.1.24.0 (Amd64) and (as of now) Syncthing 1.3.3

SyncTrayzor's log file is attached below (from a startup where the message appeared - again, it appears infrequently). The log appears to contain some relevant lines about the issue.

[SyncTrayzor_error.log.txt](https://github.com/canton7/SyncTrayzor/files/4049420/SyncTrayzor_error.log.txt)

**Comment by canton7** [comment]
Interesting. Sounds like Syncthing's behaviour on startup if a folder hasn't yet loaded has changed. I'll take a look.

**Comment by rubin55** [comment]
I noticed the same behaviour, with the same error message today for the first time, on two boxes.

**Comment by GermanCoding** [comment]
This was identified to be an unintended behavior change in syncthing and was just fixed in master:

https://github.com/syncthing/syncthing/pull/6272

I will close this when the (verified) fix lands in a stable release.

**Comment by GermanCoding** [comment]
Totally forgot this. This is now fixed in newer syncthing releases (1.4.0 and up).
