### ISSUE TITLE
Include binaries in chocolatey package

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [canton7/SyncTrayzor#548]
It would be nice if the setup executables where included in the chocolatey nupkg. The total package would be well under the chocolatey.org limit of 200mb.

There are a couple of changes needed to make this happen. 
1. Change the install script  `install-chocolateypackage` to `install-chocolateyinstallpackage`
2. Change the install script `url` and `url64` to `file` and `file64` respectively, and point toward the included binaries. 
3. Copy the installers during the build to the chocolatey/tools directory. I think this would be added in the rakefile. 

Also, Rawgit is shutting down, so the CDN url for the icon should be changed to an alternative service.

**Comment by canton7** [comment]
Good point re rawgit. For the other stuff, contributions welcome!

**Comment by TheCakeIsNaOH** [comment]
Pr #550 opened.

**Comment by TheCakeIsNaOH** [comment]
Closed via #550 

Thanks

**Comment by canton7** [comment]
Re-opening: it seems this isn't allowed. I got this email:

User tunisiano <helpdesk.choc@gmail.com> sends the following message to the maintainers of Package 'synctrayzor'.

Hello,
can you update this package ?
The package sent contains the installers, it shouldn't.

Have a nice day.

**Comment by TheCakeIsNaOH** [comment]
@canton7 See https://github.com/canton7/SyncTrayzor/pull/550#issuecomment-754108474

**Comment by TheCakeIsNaOH** [comment]
Fixed by #598
