### ISSUE TITLE
Syncthing failes to start with: WARNING: Database schema: folder db index missing

### ISSUE THREAD

**Issue by nokarukuta** [canton7/SyncTrayzor#554]
The log says:
```
15:45:03 INFO: Migrating database to schema version 9...
15:45:03 WARNING: Database schema: folder db index missing
```

Seems to be similar to [this](https://github.com/canton7/SyncTrayzor/issues/493) issue, but using an older binary like 1.3.4 doesn't work because the config files are different:
`WARNING: Failed to initialize config: config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.`

**Comment by canton7** [comment]
I think this looks like a Syncthing question?

**Comment by nokarukuta** [comment]
The only similar problem I found was here that's why I posted. Any ideas how to fix it?

**Comment by hwdsl2** [comment]
https://github.com/syncthing/syncthing/issues/6415
