### ISSUE TITLE
Syncing Thumbs.db:encryptable results in errors.

### ISSUE THREAD

**Issue by jtagcat** [canton7/SyncTrayzor#555]
`v1.4.0`
Linux and Android devices have no problems, SyncTrayzor (and maybe all Windows devices) fail to sync `Thumbs.db:encryptable` files and result in a failure state even after the file has been removed on all other devices and folder has been re-added.

**Comment by canton7** [comment]
Nothing to do with SyncTrayzor, this is a Syncthing issue. And it will be caused by the fact that `:` is an illegal character in Windows file paths.

**Comment by jtagcat** [comment]
https://github.com/syncthing/syncthing/issues/1734
