### ISSUE TITLE
Malware detected in SyncTrayzorSetup-x64.exe

### ISSUE THREAD

**Issue by jlagermann** [canton7/SyncTrayzor#557]
I downloaded SyncTrayzorSetup-x64.exe and my security software detected the presence of malware.  If this is a False Positive, there is a link on f-secure's site linked below.

https://www.f-secure.com/v-descs/heuristic.shtml

**Comment by ProactiveServices** [comment]
If you downloaded from the releases page here, then it is a false positive. Please report these to your software vendor.

**Comment by FibreFoX** [comment]
@jlagermann you might want to update your software and to rescan your system, according to virus total there is no infection found from the installer provided by github-releases
https://www.virustotal.com/gui/url/6872ecfbe56eaedd1e4d50edebe208f43962e9c642a2b604736ad03fb21ce7ec/detection

But it could be that your file in fact got corrupted/infected.

**Comment by Alex-0293** [comment]
1.26 release detected again.
https://www.virustotal.com/gui/file/1a6a6f7f1ee5793ff6b7745c50314151d505c4368bf8e093124b64bc0341824c/details
May be the cause is signature verification - "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider."

**Comment by canton7** [comment]
I can't control AV I'm afraid: there's nothing I can do.

**Comment by Alex-0293** [comment]
I think, this because something wrong with installation file signature. Windows 10 defender also alert when trying to install.

**Comment by canton7** [comment]
It's self-signed, as older versions of the SyncTrayzor update mechanism required this.

Windows Defender will always moan about newly-published files downloaded from the internet. The only way around this is to spend in the order of €60/year on a certificate, which I'm not going to do. The warning disappears after a day or so, as users are auto-updated to the new version and Defender learns that it is safe.

**Comment by canton7** [comment]
It's also worth noting that when you renew the cert, you lost your reputation (unless you get an EV, but individuals can't get those). I'm doing maybe ~1 release/year, and typical code signing certificates last for a year, so there's basically zero benefit.
