### ISSUE TITLE
error starting synctrayzor

### ISSUE THREAD

**Issue by mocavo67** [canton7/SyncTrayzor#558]
everything was working great but i dont know what this error means as the program wont start anymore.

i have the current version of synctrayzor and 1.4 of syncthing

thanks!

![image](https://user-images.githubusercontent.com/41093174/78198206-7310b500-744d-11ea-9a06-dff460b10912.png)

**Comment by Woren** [comment]
Can this thing be related to this?
https://github.com/canton7/SyncTrayzor/issues/517

**Comment by mocavo67** [comment]
Yes that fixed it thanks!

Get Outlook for Android

________________________________

**Comment by mocavo67** [comment]
Thanks Woren, copying the newer .exe fixed it right up using the method in that thread #517
