### ISSUE TITLE
Trayicon on highdpi is ugly

### ISSUE THREAD

**Issue by rutkas** [canton7/SyncTrayzor#559]
When dpi > 100% in Windows 10 is set for high resolution screens then sync-trayzor's tray icon looks ugly. For example one of my system has 125% DPI setting and tray icon is very blurred. I have tried different DPI scaling app settings for binary and it did not solve the problem.

![image](https://user-images.githubusercontent.com/14265370/78644121-10d90980-78be-11ea-869e-d8080cc29b9e.png)

**Comment by henriklb** [comment]
Also, I'd love an monochrome option if it isn't too much trouble

**Comment by tomasz1986** [comment]
I have just tested the newest version, and I would like to add that not only is the icon blurry, but the overall SyncTrayzor window itself is blurry too.

How to reproduce:

1. Set DPI to 125% when the system default is 100%.
2. Start SyncTrayzor.
3. The overall GUI, including the browser, is blurry.

The problem is limited to Windows 10, because the scaling method has changed in the OS. Windows 7 and 8 do not have this problem, even when using non-standard DPI.

**Comment by rutkas** [comment]
> 3. The overall GUI, including the browser, is blurry.

High DPI is a pain, this is related to many programs, to fix it just right click on the icon or binary file, go to properties -> Compatibility -> Change settings for all users -> Change high DPI settings and set Ovverdie high DPI scaling behaviour to Application. Restart app and check results. You can also play with high settings 
settings there to get better results.

But tray icon blur problem can not be fixed by this method, icon resolution should be fixed in the code.

**Comment by tomasz1986** [comment]
Have you tried this actually in SyncTrayzor? I have, and there is no difference. The built-in browser is still blurry.

**Comment by rutkas** [comment]
I have 125% DPI, here is how SyncTrayzor looks on my system. Maybe browser a little blurry but not critical. And actually I have no difference between "Application" selected and notging selected. But choosing "System" makes everyting blurry.

Have you also tried zoom in and zoom out of browser in synctrayzor in menu?

![2021-01-02 (4)](https://user-images.githubusercontent.com/14265370/103456036-ff147d80-4cfa-11eb-931b-30e14ef49cfe.png)

**Comment by canton7** [comment]
Can you try this build please https://ci.appveyor.com/project/canton7/synctrayzor/builds/37076296/artifacts ?

It contains some switches which should make the embedded browser non-blurry (but I can't reproduce the blurriness myself, so I can't check...).

The tray icon only contains up to 32x32 -- I'm in the process of adding the new resolutions

**Comment by rutkas** [comment]
> Can you try this build please https://ci.appveyor.com/project/canton7/synctrayzor/builds/37076296/artifacts ?

Yes, I cant notice difference between previous release, here is the screenshot from the build you provided:

![2021-01-02 (5)](https://user-images.githubusercontent.com/14265370/103456704-603f4f80-4d01-11eb-8cbc-4876ae78c0ec.png)

**Comment by tomasz1986** [comment]
> Maybe browser a little blurry but not critical.

Yeah, it is not unusable, but definitely blurry when compared side by side with an actual Chromium browser

> Can you try this build please [ci.appveyor.com/project/canton7/synctrayzor/builds/37076296/artifacts](https://ci.appveyor.com/project/canton7/synctrayzor/builds/37076296/artifacts) ?

I have just checked it, but there does not seem to be any different.

By the way, what do you use to change the system DPI? You may need to use "custom scaling", not the Windows 10 slider with pre-defined levels. Can you try reproducing with something like DPI set to 130%?

**Comment by canton7** [comment]
No luck I'm afraid -- still crisp

**Comment by canton7** [comment]
Out of curiosity, can you try File -> Settings -> Disable hardware rendering?

**Comment by rutkas** [comment]
Can you send desktop screenshot with SyncTrayzor opened ?

**Comment by tomasz1986** [comment]
> Out of curiosity, can you try File -> Settings -> Disable hardware rendering?

No difference. I have a feeling that this is related to the blurry icon though, regardless of the size. I use some other older software here, and their tray icons may look pixelated, but not blurry. Only the SyncTrayzor icon has this blurriness.

**Comment by canton7** [comment]
We're talking at cross purposes -- this is why it's a bad idea to mix two different problems into the same issue!

I haven't touched the tray icons yet -- all of the discussion so far as been about the blurry embedded browser.

**Comment by canton7** [comment]
For the blurry embedded browser, can you try this build? https://ci.appveyor.com/project/canton7/synctrayzor/builds/37076655/artifacts

**Comment by tomasz1986** [comment]
I am sorry for the mix. I hope that it is fine to continue with the browser blurriness here?

I have tried the newest build, but to no avail.

This is how the Syncthing GUI looks right now. Everything is a little blurry.

![image](https://user-images.githubusercontent.com/5626656/103457235-abc51e00-4d40-11eb-8117-90f64c291e87.png)

And this is how it looks when opened in the actual Chromium browser. The browser uses 100% default settings, including zoom, etc.

![image](https://user-images.githubusercontent.com/5626656/103457246-bed7ee00-4d40-11eb-8943-7c62c7d9ba82.png)

**Comment by canton7** [comment]
and you can only repro that with a custom scaling, not one of the standard scalings?

**Comment by tomasz1986** [comment]
Actually, no. I had originally thought so, but I have tested the pre-defined 125% scaling right now, and the GUI is still blurry.

**Comment by canton7** [comment]
For the blurry tray icons, can you try this build please https://ci.appveyor.com/project/canton7/synctrayzor/builds/37076901/artifacts ?

Those tray icons contain: 16, 32, 20, 40, 24, 48, 32, 64.

**Comment by tomasz1986** [comment]
The new icon looks much better now. Windows 10 @ 127% DPI.

![image](https://user-images.githubusercontent.com/5626656/103457688-b08bd100-4d44-11eb-91e3-7a9f019a751d.png)

**Comment by canton7** [comment]
It won't be perfect at non-standard scalings, as Windows will be doing its own scaling of the icon, but it has more to work with than it did before

**Comment by canton7** [comment]
For the blurry embedded browser, it looks like things are offset by 0.5px -- see the top and bottom of that folder icon.

Can you try this build? https://ci.appveyor.com/project/canton7/synctrayzor/builds/37076940/artifacts

**Comment by tomasz1986** [comment]
I think that you have nailed it :clap:. The GUI in the new build seems to look exactly as in the Chromium browser.

**Comment by canton7** [comment]
Good to hear! Just for fun, can you try this one? I changed two things last time, and it would be good to know which affected it: https://ci.appveyor.com/project/canton7/synctrayzor/builds/37077030/artifacts . Thanks!

**Comment by tomasz1986** [comment]
Unfortunately, the last one is blurry again. The working one is https://ci.appveyor.com/project/canton7/synctrayzor/builds/37076940/artifacts.

**Comment by canton7** [comment]
OK, good to know what it was, thanks

**Comment by rutkas** [comment]
I have cheked version with new icons and it's great, tray icon is not blurry now, I think you can add them to release 👍

**Comment by canton7** [comment]
This is the comination of fixes that I'm planning to release: https://ci.appveyor.com/project/canton7/synctrayzor/builds/37077130/artifacts . Icons up to 300%, just the fix for your blurriness (and not the other unrelated things I tried at the same time). Mind giving it a sanity-check? Thanks!

**Comment by rutkas** [comment]
Sure, thanks, please write me if you need some help in testing

**Comment by rutkas** [comment]
By the way. what VS version are you using to build the project?

**Comment by tomasz1986** [comment]
I have tested the final build. No blurriness in the GUI and the icon anymore 👍.

**Comment by canton7** [comment]
Thanks!

> By the way. what VS version are you using to build the project?

VS2019
