### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Chensmeat** [canton7/SyncTrayzor#561]
Anyone please take a look at following error showed in my log.

"Failed to initialize config: Config file version (30) is newer than supported version (29)"

In this case I am unable to start syncing, please help, appreciated!
![image](https://user-images.githubusercontent.com/65338744/81916759-d3774280-9606-11ea-8cb5-0f15fe126da3.png)

**Comment by TheValDo** [comment]
Your Syncthing version is outdated and can fix your issue by manually downloading the latest syncthing.exe (not synctrayzor) and replacing it in your %APPDATA%/synctrayzor folder, it did worked for me.

**Comment by Chensmeat** [comment]
> Your Syncthing version is outdated and can fix your issue by manually downloading the latest syncthing.exe (not synctrayzor) and replacing it in your %APPDATA%/synctrayzor folder, it did worked for me.
> Check this thread for more details : #517

Thank you for your help but unfortunately this won't work for me. :(

**Comment by Rallandlr** [comment]
Have you tried also replacing the file in the \program files\synctrayzor folder?

**Comment by dgasaway** [comment]
Here is how I ended up in this situation:
choco install syncthing
choco install synctrayzor

**Comment by canton7** [comment]
Version 1.1.26 ships the latest Syncthing
