### ISSUE TITLE
this filename causes "filename is invalid" error

### ISSUE THREAD

**Issue by huang-junwei** [canton7/SyncTrayzor#563]
the filename "rclone-mount-rclone:_(v1.52.0)_mod:_(v1.11)(111).zip" seem to be causing some invalid filename error in current synthing version

**Comment by canton7** [comment]
This is a Syncthing question, not a SyncTrayzor question.

Colons are not valid in Windows filenames. You will have to rename the file to remove the colons in order to be able to create it on Windows.

**Comment by huang-junwei** [comment]
Ah, I see. Thanks :D
