### ISSUE TITLE
Bad zoom level after reboot

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#57]
When started after log in (after reboot or log out) browser displays default zoom level. But after changing zoom level (ctrl++ or ctrl +-) it change it to +1 or -1 from position last used before reboot, so it remembers, but have trouble reuse it somehow.

Example:
Hit ctrl+0, zoom level default. Hit 10x ctrl+-, zoom -10. Log out. Log in. Open browser, zoom level default. Hit ctrl++, zoom level way to - values. After hitting ctrl++ 9 more times, zoom level return to default (checked by ctrl+0, zoom without change), so it remembers exact zoom level, only fails to use it.

**Comment by canton7** [comment]
Interesting - I'll try and repro. Thanks.

**Comment by canton7** [comment]
Turned out to be a CefSharp issue: https://github.com/cefsharp/CefSharp/issues/738#issuecomment-91099199

I've got a workaround in place.
