### ISSUE TITLE
Error while starting for the first time

### ISSUE THREAD

**Issue by noxer** [canton7/SyncTrayzor#570]
When I try to start SyncTrayzor on a Windows machine for the first time, I keep getting the following error message:
![grafik](https://user-images.githubusercontent.com/566185/86395763-136eb380-bca1-11ea-9070-e72165918c9d.png)

The log prints the following error:
`[XXXXX] 20:17:12 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.`

This happens on versions 1.1.24 and 1.1.23.

**Comment by cheesyfries7** [comment]
Hey there, I followed the suggestion of another poster: 
https://github.com/canton7/SyncTrayzor/issues/572#issuecomment-667250814

And after my application worked.

**Comment by canton7** [comment]
Version 1.1.26 ships the latest Syncthing
