### ISSUE TITLE
WARNING: Database schema: Syncthing v1.7.0 required

### ISSUE THREAD

**Issue by rammco** [canton7/SyncTrayzor#572]
I downloaded and got Syncthing v1.7.1 running. Then I installed SyncTrazor. Ran it and it told me to start Syncthing with "-allow-newer-config". I did that. Now SyncTrazor tells me:

WARNING: Database schema: Syncthing v1.7.0 required

I have no idea how to get v1.7.0. The only thing I can find on the https://syncthing.net/ for Windows is 1.7.1. So I'm stuck.

For what it's worth here is everything from the Syncthing Console from last attempt to start Syncthing from SyncTrazor:

[TARF5] 11:30:39 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[TARF5] 11:30:39 INFO: My ID: TARF5XO
[TARF5] 11:30:40 INFO: Single thread SHA256 performance is 186 MB/s using minio/sha256-simd (153 MB/s using crypto/sha256).
[TARF5] 11:30:40 INFO: Archiving a copy of old config file format at: C:\Users\administrator\AppData\Local\Syncthing\config.xml.v31
[TARF5] 11:30:40 INFO: Hashing performance is 157.89 MB/s
[TARF5] 11:30:40 WARNING: Database schema: Syncthing v1.7.0 required
[TARF5] 11:30:40 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[TARF5] 11:30:40 INFO: My ID: TARF5XO
[TARF5] 11:30:41 INFO: Single thread SHA256 performance is 187 MB/s using minio/sha256-simd (153 MB/s using crypto/sha256).
[TARF5] 11:30:41 INFO: Archiving a copy of old config file format at: C:\Users\administrator\AppData\Local\Syncthing\config.xml.v31
[TARF5] 11:30:42 INFO: Hashing performance is 161.49 MB/s
[TARF5] 11:30:42 WARNING: Database schema: Syncthing v1.7.0 required
[TARF5] 11:30:42 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[TARF5] 11:30:42 INFO: My ID: TARF5XO
[TARF5] 11:30:43 INFO: Single thread SHA256 performance is 186 MB/s using minio/sha256-simd (153 MB/s using crypto/sha256).
[TARF5] 11:30:43 INFO: Archiving a copy of old config file format at: C:\Users\administrator\AppData\Local\Syncthing\config.xml.v31
[TARF5] 11:30:43 INFO: Hashing performance is 159.99 MB/s
[TARF5] 11:30:43 WARNING: Database schema: Syncthing v1.7.0 required
[TARF5] 11:30:43 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[TARF5] 11:30:43 INFO: My ID: TARF5XO
[TARF5] 11:30:44 INFO: Single thread SHA256 performance is 186 MB/s using minio/sha256-simd (151 MB/s using crypto/sha256).
[TARF5] 11:30:44 INFO: Archiving a copy of old config file format at: C:\Users\administrator\AppData\Local\Syncthing\config.xml.v31
[TARF5] 11:30:45 INFO: Hashing performance is 160.49 MB/s
[TARF5] 11:30:45 WARNING: Database schema: Syncthing v1.7.0 required

Here are entries in SyncTrazor log for the same attempt to start Syncthing:

2020-07-21 11:57:55.0962 #1068 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\administrator\AppData\Roaming\SyncTrayzor\syncthing.exe 
2020-07-21 11:57:56.6412 #1068 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2020-07-21 11:57:56.6412 #1068 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\administrator\AppData\Roaming\SyncTrayzor\syncthing.exe 
2020-07-21 11:57:58.1904 #1068 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2020-07-21 11:57:58.1904 #1068 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\administrator\AppData\Roaming\SyncTrayzor\syncthing.exe 
2020-07-21 11:57:59.7368 #1068 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2020-07-21 11:57:59.7368 #1068 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\administrator\AppData\Roaming\SyncTrayzor\syncthing.exe 
2020-07-21 11:58:01.2661 #1068 [Warn] SyncTrayzor.Syncthing.SyncthingProcessRunner: 4 restarts in less than 00:01:00: not restarting again

**Comment by trajanmcgill** [comment]
I suspect rather than using -allow-newer-config you need to use the instructions in the readme for manually using a newer version of Syncthing (it's talking about using a beta version, but would seem to apply to a newer release version as well). Assuming you're using the installed rather than the portable version of SyncTrayzor, that means copying the syncthing.exe file from wherever you have Syncthing installed (that is, the 1.7.1 version) into `%UserProfile%\AppData\Roaming\SyncTrayzor` replacing the 1.2.0 version of the .exe that is installed with SyncTrayzor.

Doing that got SyncTrayzor up and running with Syncthing 1.7.1 for me.

**Comment by cheesyfries7** [comment]
> 
> 
> I suspect rather than using `-allow-newer-config` you need to use the instructions in the readme for manually using a newer version of Syncthing (it's talking about using a beta version, but would seem to apply to a newer release version as well). Assuming you're using the installed rather than the portable version of SyncTrayzor, that means copying the syncthing.exe file from wherever you have Syncthing installed (that is, the 1.7.1 version) into `%UserProfile%\AppData\Roaming\SyncTrayzor` replacing the 1.2.0 version of the .exe that is installed with SyncTrayzor.
> 
> Doing that got SyncTrayzor up and running with Syncthing 1.7.1 for me.

Hi there, just wanted to say I did this and I got SyncTrayzor up and running as well on my end. Many thanks!

**Comment by canton7** [comment]
Version 1.1.26 ships the latest Syncthing
