### ISSUE TITLE
installation fail server 2016-2019

### ISSUE THREAD

**Issue by migueladp** [canton7/SyncTrayzor#573]
when The installation finished i receive this message:

Version: 1.1.24.0; Variant: Installed; Arch: X86
Path: C:\Program Files (x86)\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Intento de realizar una operación no válida.
   en Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   en Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   en Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   en SyncTrayzor.Services.AutostartProvider.SetAutoStart(AutostartConfiguration config) en C:\projects\synctrayzor\src\SyncTrayzor\Services\AutostartProvider.cs:línea 222
   en SyncTrayzor.Bootstrapper.Configure() en C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:línea 169
   en Stylet.BootstrapperBase.Start(String[] args) en c:\projects\stylet\Stylet\BootstrapperBase.cs:línea 80
   en Stylet.BootstrapperBase.<Setup>b__0(Object o, StartupEventArgs e) en c:\projects\stylet\Stylet\BootstrapperBase.cs:línea 48
   en System.Windows.Application.OnStartup(StartupEventArgs e)
   en System.Windows.Application.<.ctor>b__1_0(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

somebody know what i have to do?

**Comment by canton7** [comment]
Looks like the user running SyncTrayzor can open the registry key `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` with write permissions, but can't actually write anything. Maybe this is some sort of antivirus getting in the way?

**Comment by canton7** [comment]
Closing as no response
