### ISSUE TITLE
Duplicate (but case-different) proxy environment variable causes crash

### ISSUE THREAD

**Issue by daniele-athome** [canton7/SyncTrayzor#577]
I run in a mixed environment where I have Linux tools and mixed environment variables. For proxy variables (http_proxy, https_proxy, no_proxy) I have applications that use uppercase variables and other that use lowercase variables, so I have to define them both. However, SyncTrayzor crashes because of NO_PROXY and no_proxy both existing among the environment variables.

```
2020-09-17 09:59:08.5162 #16720 [Error] SyncTrayzor.Bootstrapper: An unhandled AppDomain exception occurred. Terminating: True System.ArgumentException L'elemento è già stato aggiunto. Chiave nel dizionario: 'NO_PROXY'. Chiave aggiunta: 'no_proxy' Void Insert(System.Object, System.Object, Boolean)    in System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   in System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
   in SyncTrayzor.Syncthing.SyncthingProcessRunner.StartInternal(Boolean isRestart) in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingProcessRunner.cs:riga 130
   in SyncTrayzor.Syncthing.SyncthingManager.<StartAsync>d__118.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:riga 192
```

(sorry for the Italian exception message, basically it says "duplicate key in hash table")

The issue can be worked around by removing the uppercase variables. I created a wrapper script to do that, but I thought this would be worth a bug report.

I'm not an expert on Windows systems, but if you need more information, just ask.

**Comment by canton7** [comment]
Thanks!

**Comment by canton7** [comment]
Unfortunately it looks like this is an issue with the .NET Framework -- this happens when fetching the set of environmental variables. I'm afraid I don't think there's anything I can do, sorry!

**Comment by daniele-athome** [comment]
I actually expierenced this with other .NET applications too, that's unbelievable!
Thank you for trying.
