### ISSUE TITLE
GUI displays text (key value pairs?) at the bottom after conflict is detected

### ISSUE THREAD

**Issue by shanks1337** [canton7/SyncTrayzor#579]
Version Syncthing: v1.9.0, Windows (64 bit)
Version SyncTrayzor: 1.1.24
Version OS: Windows 8.1 Pro N

GUI displays text (key value pairs?) at the bottom after conflict is detected that isn't supposed to be there.

![syncthing visual bug 1](https://user-images.githubusercontent.com/8984284/94147338-72ddf900-fe75-11ea-8d3e-973b48bf0e9a.png)
![syncthing visual bug 2](https://user-images.githubusercontent.com/8984284/94147343-740f2600-fe75-11ea-9f0b-543f8523dd78.png)

This is how the bug is reliable reproducible for me:
1. trigger conflict: change text in new.txt on device A and new.txt on device B before it's been synced
2. then go "actions" -> "restart" and wait untill window is reinitialized
3. close syncthing window [X] and open it again via double click from tray

**Comment by canton7** [comment]
I don't think this is anything to do with conflicts -- this is inside the embedded browser, and the conflict stuff happens outside.

My guess is that this is a Syncthing bug, or some weird interaction with the embedded browser. Can you reproduce it using a normal web browser?

**Comment by canton7** [comment]
Version 1.1.26 ships a new version of the embedded browser. Please re-open if you still see issues with that. Thanks!

**Comment by shanks1337** [comment]
The patch worked, I can't reproduce this behaviour anymore. Sorry for the delay.
