### ISSUE TITLE
Bad format of folder ID in tray menu

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#58]
Because of rule of one string for folder ID, I'm using underscore sing (_) between words. But underscore sign is also used in text string for that "press alt and then you can navigate in menu by letter keys and arrows" function (don't know what its called nor real purpose, something to do with using computer without a mouse maybe?). In result it eats first underscore in folder ID and displays it only as part of that function after alt press. But since I don't know how to use it, I cant even test if this is normal part of other tray icon menus or not in which case I would say lets disable it for tray (if it is even possible).

Can it be disabled for part of menu that concerns folders? Or can it be changed so it didn't chunk that first underscore?

**Comment by canton7** [comment]
Fair point!

**Comment by chucic** [comment]
Just discovered same behaviour in settings.

**Comment by canton7** [comment]
Yeah they'll be checkboxes... I'll fix those too thanks!

**Comment by canton7** [comment]
Righty, got those too. Thanks!
