### ISSUE TITLE
Donation link gets "404 Not Found"

### ISSUE THREAD

**Issue by shanks1337** [canton7/SyncTrayzor#580]
Version Syncthing: v1.9.0, Windows (64 bit)
Version SyncTrayzor: 1.1.24
Version OS: Windows 8.1 Pro N

Following the link at the top: help -> info -> donate, leads to https://synctrayzor.antonymale.co.uk/donate which returns "404 Not Found" in browser.

(this also apply to the documentation: https://github.com/canton7/SyncTrayzor#find-synctrayzor-useful-please-donate )

**Comment by canton7** [comment]
Weird, it doesn't for me, trying it just now. Is it https://synctrayzor.antonymale.co.uk/donate itself which 404's, or the redirected URL? Can you screenshot it please?

**Comment by shanks1337** [comment]
Sorry! It seems like it's an local issue. When I access https://synctrayzor.antonymale.co.uk/donate with firefox / chromium / vivaldi on desktop I get 404'ed.

![donation](https://user-images.githubusercontent.com/8984284/94258891-e2afba80-ff2d-11ea-999d-30b83ccb7140.png)

However when I use mobile firefox on my smartphone with disabled W-Lan so mobile data is used, the redirect to https://www.justgiving.com/fundraising/SyncTrayzor-MSF seems working. So I guess the issue is somewhere on my side in my local lan setup.

**Comment by canton7** [comment]
Chasing the logs, I suspect the 404 is happening when the request is made over IPv6... I'll dig into this, thanks!

**Comment by canton7** [comment]
That should be working now. Would you mind trying it on your desktop again please?

**Comment by shanks1337** [comment]
It does work now for desktop as well.

And your guess was correct, I have IPv6 on LAN and IPv4 on Mobile.

**Comment by canton7** [comment]
Thanks for checking!
