### ISSUE TITLE
Synctrayzor displays "Syncthing starting" with white screen

### ISSUE THREAD

**Issue by 93-infinity** [canton7/SyncTrayzor#581]
Synctrayzor version: 1.1.24
Syncthing version: v1.10.0, Windows (64 bit) "Fermium Flea"
Windows version: Windows 10 x64 Version 2004 Build 19041.508
Sidenote: I don't recall Windows, Synctrayzor, Syncthing, to have been updated recently, everything was normal this morning, and after a reboot, this problem appeared. I haven't changed any folder settings recently either.

1. Open Synctrayzor
2. Synctrayzor starts, displays "Syncthing starting" and stays like this for 10 minutes or so until error (below)
3. In the meantime, all menu bar items under "Syncthing" are greyed out except "Kill all syncthing processes" 
4. Tray icon: Grey, tasks relating to syncthing greyed out
5. Check syncthing is running normally: Change GUI listen address to 0.0.0.0:8384 from default localhost:8384 (File/Settings/Syncthing), syncthing now accessible in browser and appears to be running normally (I don't know why localhost doesn't work and 0.0.0.0 does)
6. After a while Synctrayzor opens error message "Unable to start Syncthing: Unexpected exception while starting Syncthing: Syncthing didn't connect after 00:10:00. Please see Syncthing's console output for clues. (This doesn't always appear after 10 minutes, sometimes it doesn't appear)

```
[monitor] 19:21:28 INFO: Log output saved to file "C:\Users\**\AppData\Local\Syncthing\syncthing.log"
[start] 19:21:28 INFO: syncthing v1.10.0 "Fermium Flea" (go1.15.2 windows-amd64) teamcity@build.syncthing.net 2020-09-15 17:38:23 UTC
[start] 19:21:28 INFO: Using large-database tuning
[**] 19:21:28 INFO: My ID: **
[**] 19:21:29 INFO: Single thread SHA256 performance is 1695 MB/s using minio/sha256-simd (404 MB/s using crypto/sha256).
[**] 19:21:29 INFO: Hashing performance is 986.66 MB/s
[**] 19:21:29 INFO: Overall send rate is unlimited, receive rate is unlimited
[**] 19:21:29 INFO: Using discovery mechanism: global discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX
[**] 19:21:29 INFO: Using discovery mechanism: global discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX
[**] 19:21:29 INFO: Using discovery mechanism: global discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX
[**] 19:21:29 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[**] 19:21:29 INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
[**] 19:21:29 INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
[**] 19:21:29 INFO: Ready to synchronize "**"
[**] 19:21:29 INFO: Ready to synchronize "**"
[**] 19:21:29 INFO: GUI and API listening on [::]:8384
[**] 19:21:29 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[**] 19:21:29 INFO: My name is "**"
[**] 19:21:29 INFO: Device ** is "**" at [dynamic]
[**] 19:21:29 INFO: Device ** is "**" at [dynamic]
[**] 19:21:29 INFO: Device ** is "**" at [dynamic]
[**] 19:21:29 INFO: QUIC listener ([::]:22000) starting
[**] 19:21:29 INFO: TCP listener ([::]:22000) starting
[**] 19:21:37 INFO: Completed initial scan of sendreceive folder "**"
[**] 19:21:40 INFO: New NAT port mapping: external TCP address ** to local address 0.0.0.0:22000.
[**] 19:21:40 INFO: New NAT port mapping: external TCP address ** to local address 0.0.0.0:22000.
[**] 19:21:40 INFO: New NAT port mapping: external TCP address ** to local address 0.0.0.0:22000.
[**] 19:21:40 INFO: Detected 3 NAT services
[**] 19:21:42 INFO: Completed initial scan of sendreceive folder "**"
[**] 19:21:44 INFO: Established secure connection to ** at **/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256
[**] 19:21:44 INFO: Device ** client is "syncthing v1.10.0" named "**" at **/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256
[**] 19:21:49 INFO: quic://0.0.0.0:22000 detected NAT type: Port restricted NAT
[**] 19:21:49 INFO: quic://0.0.0.0:22000 resolved external address quic://** (via stun.syncthing.net:3478)
[**] 19:22:02 INFO: Established secure connection to ** at **/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256
[**] 19:22:02 INFO: Device ** client is "syncthing v1.10.0" named "**" at **/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256
[**] 19:23:24 INFO: Joined relay relay://218.72.124.179:22067
[**] 19:44:19 INFO: Connection to ** at **/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256 closed: reading length: EOF

```

Let me know what more information I need to provide to contribute

**Comment by 93-infinity** [comment]
![error](https://user-images.githubusercontent.com/16083086/95744790-83400180-0cc6-11eb-8e0e-e799c9d31d56.png)
![gui](https://user-images.githubusercontent.com/16083086/95744800-85a25b80-0cc6-11eb-8e49-e57f13f74052.jpg)
![tray](https://user-images.githubusercontent.com/16083086/95744825-90f58700-0cc6-11eb-8c76-401baa5006c4.png)

**Comment by canton7** [comment]
Please provide the SyncTrayzor log file? You'll find a button to show it until File -> Settings -> Logging (IIRC)

**Comment by 93-infinity** [comment]
Here is the log:

[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/5370835/SyncTrayzor.log)

**Comment by 93-infinity** [comment]
Here is the log: 

[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/5370846/SyncTrayzor.log)

**Comment by canton7** [comment]
That log file seems to show a different problem, with Syncthing exiting immediately whenever we try to start it

**Comment by 93-infinity** [comment]
And it's working again.

**Comment by WurstCommander** [comment]
Hi.

I got a similar issue, 

Synctrayzor version: 1.1.23
Syncthing version: v1.10.0, Windows (64 bit) "Fermium Flea"
Windows version: Windows 10 x64

Syncthing updated and after that I get the white screen with "Syncthing started"

Here is the debug level log:
[
[synctray.log](https://github.com/canton7/SyncTrayzor/files/5395254/synctray.log)
](url)

**Comment by WurstCommander** [comment]
I "fixed" it bei deleting the data folder and starting with a new config / syncthing install.

**Comment by canton7** [comment]
Note the timestamps in those two logs don't line up: the Syncthing log starts at 11:17, while the SyncTrayzor one ends at 11:05.

Either way, Syncthing logs the following messages when it's started enough to be accessed over its web interface or API:

```
INFO: TCP listener ([::]:22000) starting
INFO: GUI and API listening on 127.0.0.1:8384
INFO: Access the GUI via the following URL: http://localhost:8384/
INFO: My name is "XXX"
```

Those don't appear in either of the logs, which means Syncthing simply hadn't started enough for SyncTrayzor to access its API. This is supported by the fact that SyncTrayzor is unable to connect to its API.

I've just tried 1.11.0-rc.1, and everything seems fine, so I don't think there's anything fundamentally wrong with that version.

Sometimes Syncthing wants to do a database upgrade or something between versions and that takes a while, during which time SyncTrayzor can't connect.

**Comment by canton7** [comment]
Closing as explained
