### ISSUE TITLE
SyncTrazor crashes

### ISSUE THREAD

**Issue by mmendivelsov** [canton7/SyncTrayzor#582]
I can't initialize SyncTrazor. The program crashes with every single try to run.

I obtained this in my last run:

Version: 1.1.24.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Acceso denegado.

   en Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   en SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to) en C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:línea 51
   en SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) en C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:línea 137
   en SyncTrayzor.Bootstrapper.Configure() en C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:línea 144
   en Stylet.BootstrapperBase.Start(String[] args) en c:\projects\stylet\Stylet\BootstrapperBase.cs:línea 81
   en System.Windows.Application.OnStartup(StartupEventArgs e)
   en System.Windows.Application.<.ctor>b__1_0(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Looks like the user that SyncTrayzor is running as doesn't have permission to write to `C:\Users\<You>\AppData\Roaming\SyncTrayzor`?

**Comment by canton7** [comment]
Closing as no response
