### ISSUE TITLE
SyncTrayzor still appears in Task-Manager Autostart after uninstall 

### ISSUE THREAD

**Issue by shanks1337** [canton7/SyncTrayzor#586]
Version SyncTrayzor: 1.1.24
Version Syncthing: v1.11.1
OS: Windows 10 Pro 
Version OS : 10.0.19042 Build 19042

When using the unins000.exe to execute the deinstall process, it won't remove the SyncTrayzor entry in the Autostart tab in the Task-Manager. After installing and uninstalling SyncTrayzor a few times I've had serveral inactive instances of SyncTrayzor.

**Comment by canton7** [comment]
This is impossible to do in the general case (autostart registry keys are per-user, but the installer runs as a single particular user).

I've updated the installer to make a best-effort attempt to clean these up: it will work provided that the user who runs the uninstaller is the same user who ran SyncTrayzor, and you didn't need to elevate to a different user.
