### ISSUE TITLE
Start minimized after automatic upgrade

### ISSUE THREAD

**Issue by jkaberg** [canton7/SyncTrayzor#59]
Would be cool if it could stay in tray even after update installation etc ;)

**Comment by canton7** [comment]
I'm in two minds about this... I'm worried that, if we do an update but restart in the tray, the user will go "Huh? What happened? Did it crash? Did it complete?"

**Comment by jkaberg** [comment]
How about an optional setting, in settings? And an balon text saying "SyncTrayzor updated successfully!" when it did

**Comment by canton7** [comment]
Yeah a balloon might be a half-decent way of doing it.

**Comment by chucic** [comment]
Maybe not even in settings, but do it always when "start minimised" is checked? Or is it a bad idea to have balloon which user can't forbid in config?

**Comment by canton7** [comment]
I'd probably:

 - Look at whether the current instance was started minimized or not, and copy that
 - Make the balloon look like the 'upgrade available' one, rather than the 'XXX connected' ones

**Comment by jkaberg** [comment]
Sounds good to me!

**Comment by canton7** [comment]
Actually, no. We want to restore the UI to the state that it was in prior to the upgrade being triggered methinks (which is slightly easier to determine!)

**Comment by canton7** [comment]
This isn't going to make 1.0.16 I'm afraid, but I'll hopefully get it in before 1.0.17

**Comment by canton7** [comment]
Should now be fixed, but needs testing
