### ISSUE TITLE
WARNING: Failed to initialize config: Config file version (32) is newer than supported version (29). If this is expected, use -allow-newer-config to override.

### ISSUE THREAD

**Issue by copenhagen72** [canton7/SyncTrayzor#590]
Just downloaded and installed latest SyncTrayzor Version 1.1.24.
GUI starts, but Syncthing cannot be ran.

What I have in log:

> [54WQS] 13:17:26 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
> [54WQS] 13:17:26 INFO: My ID: 54WQSKB
> [54WQS] 13:17:27 INFO: Single thread SHA256 performance is 415 MB/s using minio/sha256-simd (363 MB/s using crypto/sha256).
> [54WQS] 13:17:27 WARNING: Failed to initialize config: Config file version (32) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
> [54WQS] 13:17:27 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
> [54WQS] 13:17:27 INFO: My ID: 54WQSKB
> [54WQS] 13:17:28 INFO: Single thread SHA256 performance is 499 MB/s using minio/sha256-simd (423 MB/s using crypto/sha256).
> [54WQS] 13:17:28 WARNING: Failed to initialize config: Config file version (32) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
> [54WQS] 13:17:28 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
> [54WQS] 13:17:28 INFO: My ID: 54WQSKB
> [54WQS] 13:17:29 INFO: Single thread SHA256 performance is 502 MB/s using minio/sha256-simd (423 MB/s using crypto/sha256).
> [54WQS] 13:17:29 WARNING: Failed to initialize config: Config file version (32) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
> [54WQS] 13:17:29 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
> [54WQS] 13:17:29 INFO: My ID: 54WQSKB
> [54WQS] 13:17:30 INFO: Single thread SHA256 performance is 503 MB/s using minio/sha256-simd (422 MB/s using crypto/sha256).
> [54WQS] 13:17:30 **WARNING: Failed to initialize config: Config file version (32) is newer than supported version (29). If this is expected, use -allow-newer-config to override.

By the way SyncTrayzor is much outdated: Version 1.1.24 released on 27 Jul 2019, more than 1 year ago. 
It uses syncthing v1.2.0 when v1.12.0 is released.

**Comment by ignaciobe** [comment]
I got the same issue. I tried the same version but portable and it is working, seems to be an issue with the installer.

**Comment by mort3za** [comment]
I runned syncthing manually by running **syncthing.exe** and SyncTrazor automatically started working itself.

**Comment by the-solo-king** [comment]
I tried the suggestion in these[https://github.com/canton7/SyncTrayzor/issues/517](url) and got it work.

**Comment by PearseT** [comment]
I replaced the syncthings.exe in C:\Users\YOURUERNAME\AppData\Roaming\SyncTrayzor
as this is where the config file lives.

I ran the .exe file on its own and then quit Ctrl+C in the terminal. 

Then ran StncTrayzor and it worked fine.

**Comment by canton7** [comment]
Version 1.1.26 ships the latest Syncthing

**Comment by natrius** [comment]
The same problem is currently happening with 1.1.29

**Comment by stevetb777** [comment]
Same problem with 1.1.29, your solution worked for me.  Thanks!!

> The same problem is currently happening with 1.1.29
> 
> Switched the synctrhing exe in `%AppData%\SyncTrayzor` to the newer one i downloaded and it works :)

**Comment by diorcula** [comment]
> The same problem is currently happening with 1.1.29
> 
> Switched the synctrhing exe in `%AppData%\SyncTrayzor` to the newer one i downloaded and it works :)

This worked for me as well :)
