### ISSUE TITLE
Add "register as service"

### ISSUE THREAD

**Issue by mammutserver** [canton7/SyncTrayzor#591]
Add a button or shortcut to install SyncTrayzor as a service in Windows.

**Comment by canton7** [comment]
This is not supported I'm afraid: SyncTrayzor needs to be the parent process if Syncthing. There are other issues on the topic of services.

**Comment by lostmsu** [comment]
@canton7 I also want the feature of starting as a service, or at least like a service (e.g. on boot, without login). Can you clarify what is it that SyncTrayzor does that requires it to be the parent process of Syncthing?

**Comment by ProactiveServices** [comment]
[Starting syncthing automatically on Windows](https://docs.syncthing.net/users/autostart.html#windows).

**Comment by canton7** [comment]
#528, #143

**Comment by lostmsu** [comment]
@canton7 so the only requirement is the API key?
I just realized SyncTrayzor could also be the process to be started at boot. If the tray part is the problem, just have two separate processes, one to babysit Syncthing, and the other one to show the tray icon and other UI. Surely there's a way to store API key securely between the two.

**Comment by canton7** [comment]
That's also been discussed. Possible, but a lot of work, and not the direction I wanted to take this project in. There are plenty of other alternatives out there these days if synctrayzor doesn't suit your needs

**Comment by lostmsu** [comment]
I started working on it.

After initial review of code my idea is to simply replace or augment `SyncthingProcessRunner` with an implementation based on [Task Scheduler](https://github.com/dahall/TaskScheduler).

Should take a day or two max.

**Comment by canton7** [comment]
Feel free to create your own fork, but I won't be accepting a PR here I'm afraid.

**Comment by lostmsu** [comment]
Huh? It is going to be pretty trivial.
