### ISSUE TITLE
Conflict of different files in different directories

### ISSUE THREAD

**Issue by Revertron** [canton7/SyncTrayzor#593]
Syncthing 1.12.0 in SyncTrayzor on Windows.

Different files in different directories are considered by Syncthing/SyncTrayzor as conflict. See screenshot:
![hRuSZG](https://user-images.githubusercontent.com/105154/103154323-0be31f80-4797-11eb-9b71-d01d560cf1ea.png)

I've filed [an issue](https://github.com/syncthing/syncthing/issues/7233) to Syncthing, but they say that it is a SyncTrayzor issue.

**Comment by canton7** [comment]
Is there an issue here? There are two files which have conflicts. You've selected the first one, and it's showing you the two conflicting versions. 

The thing that's confusing you I think is that you've for two files which have conflicts, and both files have the same name.

**Comment by Revertron** [comment]
Yes, I see that now. I've thought that I didn't sync that directory before, and didn't expect sync-conflicts in the first place.
My apologies!

**Comment by canton7** [comment]
No worries!
