### ISSUE TITLE
localhost GUI no longer visible

### ISSUE THREAD

**Issue by stevegee58** [canton7/SyncTrayzor#595]
After today's upgrade the GUI is blank.

**Comment by canton7** [comment]
What Windows version are you using? Can you post your log file (File -> Settings -> Logging -> Show SyncTrayzor log file)

**Comment by stevegee58** [comment]
Windows 7.  I've attached the log file.
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/5747990/SyncTrayzor.log)

**Comment by canton7** [comment]
Syncthing -> Refresh browser?

**Comment by stevegee58** [comment]
Refresh has no effect.

**Comment by stevegee58** [comment]
I tried open in external browser and it asked me for a username and password.  I don't ever having to do this.

**Comment by stevegee58** [comment]
Is the username/password a syncthing thing or SyncTrayzor?

**Comment by canton7** [comment]
A syncthing thing. If you're using a normal web browser, SyncTrayzor isn't involved

**Comment by slubman** [comment]
Same issue here, with the synctrayzor window staying blank. Refreshing the browser does not change a thing.

```
Edition	Windows 10 Home
Version	20H2
OS build	19042.685
```
Opening the interface in a browser does work fine, and syncthting itself is working fine.

**Comment by canton7** [comment]
Try stopping SyncTrayzor, delete %LOCALAPPDATA%\SyncTrayzor\cef\cache, and start it again?

**Comment by stevegee58** [comment]
I just tried deleting cache and restarting but still blank.

**Comment by canton7** [comment]
No idea then I'm afraid -- the embedded browser is a third-party component, and there's a history of random white screens. Please downgrade to 1.1.24.

**Comment by stevegee58** [comment]
Downgraded to 1.1.24 and the GUI is restored now.

I feel your pain, Antony.  Supporting multiple platforms is a royal PITA!

**Comment by canton7** [comment]
When you launch synctrayzor, does it start in the background and then you use the tray icon to bring it to the foreground, or does it start in the foreground?

**Comment by canton7** [comment]
Can you try:

- Download https://cef-builds.spotifycdn.com/cef_binary_86.0.24%2Bg85e79d4%2Bchromium-86.0.4240.198_windows64_client.tar.bz
- Extract and run cefclient.exe with:
```
cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --no-sandbox --disable-site-isolation-trials
```
That should help narrow down whether it's a problem with the embedded browser itself, or something else.

**Comment by canton7** [comment]
Also, does everyone with this issue have a username/password set on Syncthing's Web interface?

**Comment by slubman** [comment]
> 
> 
> Can you try:
> 
>     * Download https://cef-builds.spotifycdn.com/cef_binary_86.0.24%2Bg85e79d4%2Bchromium-86.0.4240.198_windows64_client.tar.bz
> 
>     * Extract and run cefclient.exe with:
> 
> 
> ```
> cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --no-sandbox --disable-site-isolation-trials
> ```
> 
> That should help narrow down whether it's a problem with the embedded browser itself, or something else.

Found something with this browser test.
If I disable « use HTTPS for GUI » from the syncthing setting, I can have the interface to load from within the cefclient **and** synctrayzor.

If I enable « use HTTPS for GUI » from the syncthing setting, now I can’t get the interface to show in synctrayzor and I get the following error in cefclient:
![image](https://user-images.githubusercontent.com/23456/103249318-e3ae1900-496e-11eb-80a2-3dce988b8200.png)

--- 

> 
> 
> Also, does everyone with this issue have a username/password set on Syncthing's Web interface?

I do not have username/password set in the Syncthing web interface.

**Comment by canton7** [comment]
Ah, interesting thanks. I'll see if I can repro that way.

**Comment by skst** [comment]
FWIW, same problem with 1.1.25 portable on Windows 10 Pro 20H2 (19042.685). No credentials set on the syncthing Web UI.

[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/5749189/SyncTrayzor.log)

**Comment by canton7** [comment]
Can you try this build, and confirm whether it fixes your issue, please? https://ci.appveyor.com/project/canton7/synctrayzor/builds/37033863/artifacts 

Thanks!

**Comment by skst** [comment]
> Can you try this build, and confirm whether it fixes your issue, please?

I unzipped it over my portable 1.1.24 installation, and yes, the UI is back. 👍

**Comment by slubman** [comment]
> 
> 
> Can you try this build, and confirm whether it fixes your issue, please? https://ci.appveyor.com/project/canton7/synctrayzor/builds/37033863/artifacts
> 
> Thanks!

I can also confirm the UI is also loading inside the synctrayzor window with this build.

**Comment by canton7** [comment]
Thanks all! I'll get that out soonish
