### ISSUE TITLE
Mistakenly committed option "WOo yay this is a really long string and it isn't wrapping nooo make it even longer go on I dare you"?

### ISSUE THREAD

**Issue by nanaya** [canton7/SyncTrayzor#597]
I'm rather sure this isn't supposed to be actually committed :wink: 

https://github.com/canton7/SyncTrayzor/blob/55e739e0199bf04de433dc69569fd23cff5b404f/src/SyncTrayzor/Pages/Settings/SettingsView.xaml#L55

**Comment by canton7** [comment]
D'oh. Thanks. Fixed (and I had to pull the release for other reasons)
