### ISSUE TITLE
Syncing folder/usb device

### ISSUE THREAD

**Issue by jkaberg** [canton7/SyncTrayzor#6]
When you sync (in my case) a folder on a USB HDD and then unplug it SyncTrayzor will become very unfriendly and crash ;-)

**Comment by canton7** [comment]
That will be the directory watcher falling over, I assume? I'll get that fixed, thanks.

**Comment by jkaberg** [comment]
Yeah I assume so :-)

**Comment by canton7** [comment]
Righty, I can reproduce this if I configure Syncthing with a folder on an external drive, unplug the external drive, then restart Syncthing / SyncTrayzor. The message is "The directory name <folder path> is invalid". Is that what you're seeing?

**Comment by jkaberg** [comment]
Yeah, it is :-)

**Comment by canton7** [comment]
Should be fixed in 1.0.3

**Comment by jkaberg** [comment]
Thanks! :)
