### ISSUE TITLE
Missing string in transifex

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#60]
1) In advanced settings is changed line saying "Syncthing Environmental Variables" but in Resources.resx in Transifex is still old one "Syncthing Trace Variables".

Btw, new one is way better, finally I can translate it reasonably without declining from your meaning.

2) For future: Is this even a bug? Should I raise issue next time I see something like this? I don't know your system of writing code, if you for example waiting for more strings to accumulate and then you change Resources.resx or if you just forgot this one...

3) One more thing: Searching for some other missing string I found out that in "Components" window there is "Description" and "Notes" line for each component which could be translated too. I can imagine that licence text can use only some authorised translation, but these two maybe don't?

**Comment by canton7** [comment]
Pushed the source again - sorry about that.

The process is documented here: https://github.com/canton7/SyncTrayzor/wiki/Localization. Anything which is in the `develop` branch should also be on Transifex. 

I wasn't going to bother with the third-party components stuff - it's mainly for legal reasons, and I didn't see the point in bothering the translators with it. I can if you want :smile:

**Comment by chucic** [comment]
No need. If you think it's not necessary... When I think about it, with high probability for someone who is interested about components and licence and stuff English probably isn't any problem.

**Comment by chucic** [comment]
There is a typo in "Must be in the format 'VAR=value VAR2="val1 vla2"'" string.

**Comment by canton7** [comment]
So there is :) thanks

**Comment by canton7** [comment]
Fixed
