### ISSUE TITLE
Request to post an issue appeared  - see below

### ISSUE THREAD

**Issue by greg4b** [canton7/SyncTrayzor#600]
Version: 1.1.25.0; Variant: Portable; Arch: Amd64
Path: C:\common\prog\SyncTrayzorPortable-x64\SyncTrayzor.exe
SmartFormat.Core.Formatting.FormattingException: Error parsing format string: No suitable Formatter could be found at 141
{0:p:Der folgende Ordner beinhaltet einen fehlgeschlagenen Kopiervorgang|Die folgenden Ordner beinhalten fehlschlagende Kopiervorgänge} {0:l:{}l, }
---------------------------------------------------------------------------------------------------------------------------------------------^
   bei SmartFormat.SmartFormatter.FormatError(FormatItem errorItem, Exception innerException, Int32 startIndex, FormattingInfo formattingInfo) in /_/src/SmartFormat/SmartFormatter.cs:Zeile 276.
   bei SmartFormat.SmartFormatter.Format(FormattingInfo formattingInfo) in /_/src/SmartFormat/SmartFormatter.cs:Zeile 260.
   bei SmartFormat.SmartFormatter.Format(IFormatProvider provider, String format, Object[] args) in /_/src/SmartFormat/SmartFormatter.cs:Zeile 154.
   bei System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.Activate(Object item)
   bei System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   bei System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   bei MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   bei MS.Internal.Data.DataBindEngine.Run(Object arg)
   bei System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   bei System.Windows.ContextLayoutManager.UpdateLayout()
   bei System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Thanks for reporting. This is a known issue in 1.1.25, which was fixed in 1.1.26.
