### ISSUE TITLE
Freeze interface in built-in browser

### ISSUE THREAD

**Issue by pinkkoff** [canton7/SyncTrayzor#606]
Hi!

Sorry for my English
When i start Synctrayzor, interface is freeze and i can't push any buttons. When i launch syncthing in external browser - all is ok (except my antivirus, he said that connection is not secure)
I try to reinstall all, change users (admins and users) and nothing help me. I clean program files, appdata files and try to reinstall - nothing. 

[monitor] 16:45:59 INFO: Log output saved to file "C:\Users\Vladimir\AppData\Local\Syncthing\syncthing.log"
[monitor] 16:45:59 INFO: Default folder created and/or linked to new config
[start] 16:45:59 INFO: syncthing v1.12.0 "Fermium Flea" (go1.15.5 windows-amd64) teamcity@build.syncthing.net 2020-11-27 13:33:58 UTC
[start] 16:45:59 INFO: Generating ECDSA key and certificate for syncthing...
[start] 16:45:59 INFO: Default folder created and/or linked to new config
[start] 16:45:59 INFO: Default config saved. Edit C:\Users\Vladimir\AppData\Local\Syncthing\config.xml to taste (with Syncthing stopped) or use the GUI
[start] 16:45:59 INFO: Archiving a copy of old config file format at: C:\Users\Vladimir\AppData\Local\Syncthing\config.xml.v0
[S4PW6] 16:46:00 INFO: My ID: S4PW6TV
[S4PW6] 16:46:01 INFO: Single thread SHA256 performance is 1866 MB/s using minio/sha256-simd (450 MB/s using crypto/sha256).
[S4PW6] 16:46:01 INFO: Hashing performance is 1041.78 MB/s
[S4PW6] 16:46:01 INFO: Running database migration 1...
[S4PW6] 16:46:01 INFO: Running database migration 2...
[S4PW6] 16:46:01 INFO: Running database migration 3...
[S4PW6] 16:46:01 INFO: Running database migration 5...
[S4PW6] 16:46:01 INFO: Running database migration 6...
[S4PW6] 16:46:01 INFO: Running database migration 7...
[S4PW6] 16:46:01 INFO: Running database migration 9...
[S4PW6] 16:46:01 INFO: Running database migration 10...
[S4PW6] 16:46:01 INFO: Running database migration 11...
[S4PW6] 16:46:01 INFO: Running database migration 13...
[S4PW6] 16:46:01 INFO: Running database migration 14...
[S4PW6] 16:46:01 INFO: Running database migration 15...
[S4PW6] 16:46:01 INFO: Compacting database after migration...
[S4PW6] 16:46:01 INFO: Overall send rate is unlimited, receive rate is unlimited
[S4PW6] 16:46:01 INFO: No stored folder metadata for "default"; recalculating
[S4PW6] 16:46:01 INFO: Using discovery mechanism: global discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX
[S4PW6] 16:46:01 INFO: Using discovery mechanism: global discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX
[S4PW6] 16:46:01 INFO: Using discovery mechanism: global discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX
[S4PW6] 16:46:01 INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
[S4PW6] 16:46:01 INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
[S4PW6] 16:46:01 INFO: Ready to synchronize "Default Folder" (default) (sendreceive)
[S4PW6] 16:46:01 INFO: Loading HTTPS certificate: open C:\Users\Vladimir\AppData\Local\Syncthing\https-cert.pem: The system cannot find the file specified.
[S4PW6] 16:46:01 INFO: Creating new HTTPS certificate
[S4PW6] 16:46:01 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[S4PW6] 16:46:01 INFO: TCP listener ([::]:22000) starting
[S4PW6] 16:46:01 INFO: QUIC listener ([::]:22000) starting
[S4PW6] 16:46:01 INFO: Completed initial scan of sendreceive folder "Default Folder" (default)
[S4PW6] 16:46:01 INFO: GUI and API listening on 127.0.0.1:8384
[S4PW6] 16:46:01 INFO: Access the GUI via the following URL: http://localhost:8384/
[S4PW6] 16:46:01 INFO: My name is "UltraMaster"
[S4PW6] 16:46:02 INFO: Failed to exchange Hello messages with 5YU5KLO at 192.168.1.225:22000-195.209.48.25:47449/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: write tcp 192.168.1.225:22000->195.209.48.25:47449: wsasend: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:46:03 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:45546: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:46:11 INFO: New NAT port mapping: external TCP address 10.17.18.7:53608 to local address 0.0.0.0:22000.
[S4PW6] 16:46:11 INFO: New NAT port mapping: external TCP address 10.17.18.7:62636 to local address 0.0.0.0:22000.
[S4PW6] 16:46:11 INFO: Detected 2 NAT services
[S4PW6] 16:46:20 INFO: quic://0.0.0.0:22000 detected NAT type: Port restricted NAT
[S4PW6] 16:46:20 INFO: quic://0.0.0.0:22000 resolved external address quic://195.209.48.25:37750 (via stun.syncthing.net:3478)
[S4PW6] 16:46:21 INFO: Sent usage report (version 3)
[S4PW6] 16:46:40 INFO: Joined relay relay://46.188.59.8:22067
[S4PW6] 16:46:42 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.50:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:46:42 INFO: Failed to exchange Hello messages with SFR6HTJ at 192.168.1.225:22000-195.209.48.25:1052/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: read tcp 192.168.1.225:22000->195.209.48.25:1052: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:46:42 INFO: Failed to exchange Hello messages with SFR6HTJ at 192.168.1.225:22000-195.209.48.25:22000/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: write tcp 192.168.1.225:22000->195.209.48.25:22000: wsasend: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:47:17 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.75:43850: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:47:18 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:47459: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:47:18 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:45552: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:48:02 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.50:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:48:02 INFO: Failed to exchange Hello messages with SFR6HTJ at 192.168.1.225:22000-195.209.48.25:22000/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: read tcp 192.168.1.225:22000->195.209.48.25:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:48:02 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:1052: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:48:38 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.75:43861: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:48:39 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:47472: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:48:39 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:45561: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:49:02 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.50:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:49:02 INFO: Failed to exchange Hello messages with SFR6HTJ at 192.168.1.225:22000-195.209.48.25:1052/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: write tcp 192.168.1.225:22000->195.209.48.25:1052: wsasend: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:49:03 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:49:39 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.75:43877: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:49:40 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:45580: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:49:40 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:47484: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:50:23 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.50:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:50:23 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:50:23 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:1052: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:51:00 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.75:43897: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:51:01 INFO: Failed to exchange Hello messages with 5YU5KLO at 192.168.1.225:22000-195.209.48.25:47505/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: write tcp 192.168.1.225:22000->195.209.48.25:47505: wsasend: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:51:01 INFO: Failed to exchange Hello messages with 5YU5KLO at 192.168.1.225:22000-195.209.48.25:45600/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: write tcp 192.168.1.225:22000->195.209.48.25:45600: wsasend: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:51:43 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.50:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:51:43 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:51:43 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:1052: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:52:21 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.75:43907: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:52:22 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:45614: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:52:22 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:47520: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:53:03 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.50:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:53:03 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:53:03 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:1052: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:53:42 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.75:43919: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:53:43 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:45624: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:53:44 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:47523: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:54:24 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.50:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:54:24 INFO: Failed to exchange Hello messages with SFR6HTJ at 192.168.1.225:22000-195.209.48.25:1052/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: write tcp 192.168.1.225:22000->195.209.48.25:1052: wsasend: An existing connection was forcibly closed by the remote host
[S4PW6] 16:54:24 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:22000: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:55:04 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->192.168.1.75:43931: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:55:05 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:47539: wsarecv: An existing connection was forcibly closed by the remote host.
[S4PW6] 16:55:05 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.1.225:22000->195.209.48.25:45634: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by pinkkoff** [comment]
in synctrazor logs no errors

**Comment by canton7** [comment]
Does this affect the buttons in the menu bar ("File", etc), or just the Syncthing interface?

Can you try File -> Settings -> check "Disable hardware rendering"?

**Comment by pinkkoff** [comment]
> Does this affect the buttons in the menu bar ("File", etc), or just the Syncthing interface?
> 
> Can you try File -> Settings -> check "Disable hardware rendering"?

Only syncthing interface, Synctrazor works well

check "Disable hardware rendering", nothing change

**Comment by canton7** [comment]
Please download https://cef-builds.spotifycdn.com/cef_binary_86.0.24%2Bg85e79d4%2Bchromium-86.0.4240.198_windows64_client.tar.bz2, launch it with:

```
cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --no-sandbox --disable-site-isolation-trials
```

and see whether that has the same problem?

**Comment by pinkkoff** [comment]
May be some problems with antivirus. When i start synctrayzor, my kaspersky antivirus said that connection is not secure, because of self-signed cert. When i say "continue using non-secure connections" interface of syncthing is appear in synctrayzor. But it freeze, i can not do anything. 
I tried to close antivirus, but nothing changed. And i have the same installation on desktop, with the same antivirus and version of synctayzor, it works fine

**Comment by canton7** [comment]
Try disabling https for Syncthing (Actions -> Settings -> GUI, uncheck "Use HTTPS for GUI")

**Comment by pinkkoff** [comment]
> Please download https://cef-builds.spotifycdn.com/cef_binary_86.0.24%2Bg85e79d4%2Bchromium-86.0.4240.198_windows64_client.tar.bz2, launch it with:
> 
> ```
> cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --no-sandbox --disable-site-isolation-trials
> ```
> 
> and see whether that has the same problem?

i launched it and put localhost:8384 in adress bar and all works fine

**Comment by pinkkoff** [comment]
> Try disabling https for Syncthing (Actions -> Settings -> GUI, uncheck "Use HTTPS for GUI")

it is unchecked now. i try to check and uncheck, nothing

**Comment by canton7** [comment]
What if you check it?

**Comment by pinkkoff** [comment]
all the same. 
May be synctraysor always use https instead of http?
upgrading now to xx.27 version, nothing changed

**Comment by pinkkoff** [comment]
![screenshot](https://user-images.githubusercontent.com/11784294/103459569-8aa10500-4d21-11eb-8d67-ae5adda6e276.PNG)
but with your browser some problems. try http and https - not working with https enabled

**Comment by canton7** [comment]
No idea then I'm afraid. Sorry!

**Comment by pinkkoff** [comment]
may be i should full uninstall synctrayzor? 
What I need to delete all Syncthing and Synctrayzor files? Which directories?
What files i need to backup for recover all my syncs? (i don't want to loss my files and sync folders)

**Comment by slgray** [comment]
Same problem here.
Hi @pinkkoff , what's your GPU/CPU model, I wonder if it is related to the new `Iris® Xe graphics `.

**Comment by slgray** [comment]
Add reference to similar issue with [CefSharp](https://github.com/cefsharp/CefSharp/issues/3280#issue-742243962)

**Comment by canton7** [comment]
Interesting, good find! https://github.com/dotnet/wpf/issues/3817 is also relevant.

Would you mind trying [this build](https://ci.appveyor.com/project/canton7/synctrayzor/builds/38029853/artifacts) please? You'll need to select the "Disable Hardware Rendering" checkbox under File -> Settings.

**Comment by slgray** [comment]
Tried force software rendering with this [modification](https://github.com/slgray/SyncTrayzor/commit/bfb9af781415cae270c160b668c3e280809393f6), it fix the problem.
I don't have the laptop around now, I will try you build later.

**Comment by canton7** [comment]
Yeah, I figured I'd try [this comment](https://github.com/cefsharp/CefSharp/issues/3337#issuecomment-757409384) first, since it's less disriptive to disable GPU rendering for just the browser thanf or the whole of WPF. If that doesn't work, I'll fall back to using `ProcessRenderMode`

**Comment by slgray** [comment]
I tried your build, the browser UI is blank. I'm afraid we have to using `ProcessRenderMode` to workaround this issue.
![Snipaste_2021-03-03_23-03-52](https://user-images.githubusercontent.com/1411489/109825474-d36b3080-7c74-11eb-9cb5-3922369b2e80.png)

**Comment by canton7** [comment]
Cool, I'll get that wired in

**Comment by canton7** [comment]
Can you try [this build](https://ci.appveyor.com/project/canton7/synctrayzor/builds/38049984/artifacts)?

You should also see this blue bar at the top of the page (unless you've already disabled hardware rendering). Can you just check it appears for you please?

![image](https://user-images.githubusercontent.com/568104/109872500-69e32600-7c64-11eb-9cb0-c07e68e0815f.png)

**Comment by slgray** [comment]
Great, it works now. Hope this workaround will released soon.
Thank you for your great working and hope you have a great day.

![Snipaste_2021-03-04_20-33-21](https://user-images.githubusercontent.com/1411489/109966188-eb04f080-7d2a-11eb-82cf-66acd2bdbb58.png)
![Snipaste_2021-03-04_20-34-12](https://user-images.githubusercontent.com/1411489/109966189-eb04f080-7d2a-11eb-9d13-9f940f460cc8.png)

**Comment by canton7** [comment]
Thanks for testing!

**Comment by canton7** [comment]
Version 1.1.28 is out, containing this workaround.

**Comment by pinkkoff** [comment]
Thank you!! Now all is working fine!
