### ISSUE TITLE
Avast detects a virus in CefSharp.BrowserSubProcess.exe

### ISSUE THREAD

**Issue by vdeconinck** [canton7/SyncTrayzor#609]
Hi,
I've just received and accepted the auto-update notice for SyncTrayzor 1.1.27, and right after that, Avast popped up the following window:
![image](https://user-images.githubusercontent.com/4469945/103477372-a0183c80-4dbe-11eb-93c0-ff41e2ae0a37.png)
It's in French, sorry, but basically it says "Blocked threat - we have blocked CefSharp.BrowserSubProcess.exe because it is infected by IDP.Generic". I chose to add it as an exception because I guess it's a false positive, but I think it might be worth checking if there is an updated CefSharp version or something.
FWIW a bit of Google search showed that Avast also detected it wrongly in other products - e.g. https://community.articulate.com/discussions/articulate-storyline/avast-anti-virus-threat-idp-generic-in-cefsharp-browsersubprocess-exe
Keep on the good work.
Vincent

**Comment by canton7** [comment]
This is the most recent version of CefSharp -- the main point of this release was to update it. It's more likely that a newer version will trigger AV I think, as the AV won't have had as much time to learn that it's safe.

I'm afraid I can't support the behaviour of AV applications, sorry! Any given release will cause false positives on someone's machine.

**Comment by vdeconinck** [comment]
OK, makes sense. Thanks for explaining.
