### ISSUE TITLE
Version 1.1.27 being identified as infected by a virus.

### ISSUE THREAD

**Issue by rebelgtp** [canton7/SyncTrayzor#610]
Attempted to upgrade today after CefSharp.BrowserSubprocess.exe from a previous install was identified as being infected by Avast.
At this point, Windows Smartscreen notified me that the installer was not able to be identified. I selected "Run Anyway" and eventually SyncTrayzorSetup-x64.tmp was identified as being infected.

I will be uninstalling for the time being.

**Comment by canton7** [comment]
AV does have a habit of flagging the embedded browser as a false positive. This is a problem with your AV I'm afraid: ask them for support.
