### ISSUE TITLE
Support .NET 4.6.2?

### ISSUE THREAD

**Issue by foxdotcom** [canton7/SyncTrayzor#611]
Operation System: Windows server 2016
SyncTrayzor version: 1.1.27 (can not work),   v1.1.24 (can work well)
Syncthing version : 1.12.

Phenomenon  description:
SyncTrayzor portable version v1.1.27 cannot run normally, and a prompt box pop up: This application requires .Net framework 4.7.2;

Original version v1.1.24  worked well.
But when I download new version 1.1.27, and unzip it, then run it.
It pop up a error message, see below screenshot.  It said that this application can not be started, this application requires .Net Framework 4.7.2;
![snap-(2021-01-04)(09-33-49)-01879](https://user-images.githubusercontent.com/76934815/103507400-09b94900-4e9a-11eb-81e7-80f5b23e5904.jpg)

However, I run SyncTrayzor on a windows server 2016 system. I am not the administrator of this server.  My role is only "USER".   So I only have the permission to run application, and not have the permission to install some application.

If the SyncTrayzor portable version include some runtime .Net framework files which are needed by SyncTrayzor, this error can be avoid.

**Comment by canton7** [comment]
> If the SyncTrayzor portable version include some runtime .Net framework files which are needed by SyncTrayzor, this error can be avoid.

I can't do that I'm afraid.

I might be able to target .nET 4.6.2 (which I think you should have pre-installed) in the next version, whenever that is. For now, using an older version of SyncTrayzor is probably your best option, or asking your administrator nicely 🙂
