### ISSUE TITLE
.Net install is not silent

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [canton7/SyncTrayzor#614]
So the [version 1.1.27 chocolatey package](https://chocolatey.org/packages/synctrayzor/1.1.27#versionhistory) is failing verification testing ([log](https://gist.github.com/7b0a8688c66912126aded74c347421bb)) because the dotnet installer hangs waiting for the finish button to be clicked, which means that the synctrazyor installer never completes and thus times out the test.

There are two major options that I see:
1. Fix the dotnet installer so it does not show the installation is complete screen.
2. Take a chocolatey dependency on dotnet via the [dotnetfx package](https://chocolatey.org/packages/dotnetfx), so the synctrayzor installer does not need to install dotnet.

Option one is not ideal, as changing the arguments for the dotnet installer inside the synctrazyor installer might make for a worse experience for normal users, because a completely quiet install does not show the close apps warning for example. Additionally, the Chocolatey mods probably prefer that the dotnet be a dependency.

Option two does not work %100 currently. The problem is that if you install dotnet, the registry key with the current installed version does not get updated until after a reboot. So even if a dependency is taken on `dotnetfx`, synctrazyor will still re-install it, and then hang on the finish screen. This could be fixed at least two ways. The first would be to add an argument the synctrazyor installer to completely skip the .Net install. The second would be to find a way to detect if a high enough dotnet version is installed, even if the registry has not been updated.

**Comment by canton7** [comment]
Sorry, its been a busy week: this is on my backlog.

**Comment by canton7** [comment]
I'd probably prefer putting the dependency in the nuspec, and passing a flag to the synctrayzor installer telling it not to try to install net. Thoughts?

**Comment by TheCakeIsNaOH** [comment]
> Sorry, its been a busy week: this is on my backlog.

No problem, sorry again about not putting enough testing into my previous PRs.

> I'd probably prefer putting the dependency in the nuspec, and passing a flag to the synctrayzor installer telling it not to try to install net. Thoughts?

That's my preferred option as well,

**Comment by canton7** [comment]
That's OK! You saw how many people I broke with the last few releases...

**Comment by canton7** [comment]
Version 1.1.28, which should fix this. Let's see how the moderation process goes....

**Comment by Ivoz** [comment]
Synctrayzor updated automatically for me on 1.1.28 with choco
