### ISSUE TITLE
Tray Icon not removed on exit.

### ISSUE THREAD

**Issue by code-daemon** [canton7/SyncTrayzor#619]
When you quit the app the SysTray icon is not removed, and it only disappears when you hover over it as Windows does it purge of the un-owned icon.

**Comment by canton7** [comment]
Works here: how are you closing it?

**Comment by canton7** [comment]
Closing as no response

**Comment by code-daemon** [comment]
Sorry I some how missed the email from Jan, and only saw the one from this being closed. I was closing it via the right click menu on the icon. But it seems to be fixed in the new release.

**Comment by canton7** [comment]
Nothing changed there in any recent releases, so I think it must have been a transient Windows-related issue of some sort!
