### ISSUE TITLE
Bad characters in Console View

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#62]
Console of Syncthing shows: Stávající připojení bylo vynuceně ukončeno vzdáleným hostitelem.
![syncthing_console_text](https://cloud.githubusercontent.com/assets/10828858/7249144/6e898bf4-e818-11e4-803f-bfd917b64908.JPG)

Whereas Console View of SyncTrayzor shows: StĂˇvajĂ­cĂ­ pĹ™ipojenĂ­ bylo vynucenÄ› ukonÄŤeno vzdĂˇlenĂ˝m hostitelem.
![synctrayzor_console_text](https://cloud.githubusercontent.com/assets/10828858/7249155/7f6848b6-e818-11e4-9fd2-f230aff6e1dc.JPG)

Translation: A existing connection was forcibly closed by the remote host.

Something to do with character encoding maybe?

**Comment by canton7** [comment]
Yep, that's almost certainly a character encoding issue.

**Comment by canton7** [comment]
So, C# will be reading Syncthing's stdout in whatever encoding is used by the console by default, but Syncthing (via go) is likely setting some other encoding then using that. Google seems helpless to tell me *what* it will be using though... Trial and error's probably the most sensible way, but trying to figure out if there's a way to control what locale I get error messages in so I can do the 'trial' bit locally.

**Comment by AudriusButkevicius** [comment]
Go uses the OS locale AFAIK

**Comment by canton7** [comment]
OK thanks. I *think* that means I can't trial locally using Windows 7 professional (not ultimate). 

I don't suppose you'd happen to know what encoding Go uses to write to the console?

**Comment by canton7** [comment]
@chucic I think what might be most efficient, if you're willing, is for me to post a series of intermediate builds using likely encodings (there's a high change it's UTF-8 in which case it'll work first time), and you tell me whether they still mess up?

Living in the UK is a huge disadvantage for making international apps. We speak English, so don't see problems with language, encodings, etc. We're on GMT+0, so don't see issues to do with timezones. Etc...

**Comment by chucic** [comment]
Of course, fire away.

And I always forget: Windows 7 Ultimate 64bit

Yea, English + GTM+0 vs. encodings + timezones is uncomfortable from development point of view I suppose.

**Comment by canton7** [comment]
Thanks!

UTF-8 attempt: https://s3-eu-west-1.amazonaws.com/canton7/SyncTrayzorSetup-x64-issue-62-ee086e.exe

**Comment by chucic** [comment]
Sorry it took so long, many scenarios to test.

Text is ok now:
![synctrayzor_console_text_take1](https://cloud.githubusercontent.com/assets/10828858/7250915/85f9f50e-e826-11e4-8bf7-4d72419c5452.JPG)

Some other things happened:
I didn't close SyncTrayzor manually before install (like I usually do), I let installer do it this time. I also checked "Launch SyncTrayzor".
After start, GUI showed me ugly those generated icons for devices. Also syncthing didn't choose Czech himself this time.
![synctrayzor_gui_icons_take1](https://cloud.githubusercontent.com/assets/10828858/7251569/daf4d6b8-e82c-11e4-8006-f90dad512933.JPG)

I tried to find right action that would always lead to this bug, but without success.
From here on I'm working with assumption I got from #59 that SyncTrayzor installer should close SyncTrayzor gracefully during installation. Feel free to correct me.

So, after some trial and error:
Icons of devices are big SOMETIMES if SyncTrayzor is closed by installer and not manually during installation. After closing it manually before installation icons of devices are always fine. Also if they are big, language is always English, there are no spaces between folder icons and folder IDs and names of info lines about devices are bold, but not info data itself.
Icons of folders are SOMETIMES represented only by a rectangle, this happens no matter how I close SyncTrayzor (manually or not) nor it's started manually or by installer. Language is SOMETIMES English (no connection found).
![synctrayzor_gui_icons2_take1](https://cloud.githubusercontent.com/assets/10828858/7251920/0d881150-e830-11e4-92ec-db76cbae9567.JPG)
Also SOMETIMES (no connection found, have no idea how to reproduce) is browser after launch blank, although Console View shows GUI is running. This happened to me few times before.

After refreshing browser ALL of this is ok (no blank browser, both sets of icons are fine and language is Czech).

All of these glitches (except blank browser) are new to me and I have never noticed any of them before. Language always changed from English to Czech within first 3 seconds after GUI showed. Hope it helps. Need another info?

**Comment by canton7** [comment]
Thanks for testing.

I saw the icons issue once, but wasn't able to reproduce it. I think they're related to some changes that were made to set the browser's zoom level on start - I'll have a play around that area, and see if I can reproduce anything sensible. Thanks for the pointer on the restarting: I hadn't considered that as a trigger.

If you end up with a blank browser window, can you try Syncthing -> Refresh Browser? See if that helps...

**Comment by chucic** [comment]
Yes, Syncthing -> Refresh Browser always helps. I wrote it in previous text too :wink:

**Comment by canton7** [comment]
Aha so you did! My bad

**Comment by canton7** [comment]
Right, think I've solved it. Can you try this for me? https://s3-eu-west-1.amazonaws.com/canton7/SyncTrayzorSetup-x64-issue-62-5f61361.exe

See https://github.com/canton7/SyncTrayzor/commit/5f613618d6f06795fe2c41121271b3492cc0ab1b#diff-2bf6356a5cce43ba4d7293154f5efefaR98 if you're interested.

**Comment by chucic** [comment]
Every time I let installer close and open SyncTrayzor.

First attempt:
Blank browser.
After refresh all good, except... see fifth.

Second:
![synctrayzor_gui_icons2_take2](https://cloud.githubusercontent.com/assets/10828858/7253260/951444e4-e83b-11e4-86fb-c2cbfead848d.JPG)
After refresh all good, except... see fifth.

Third:
Blank browser.
After refresh:
![synctrayzor_gui_icons2_take2_2](https://cloud.githubusercontent.com/assets/10828858/7253300/e64eea3a-e83b-11e4-917c-eb3258c9af2c.JPG)
After another refresh all good, except... see fifth.

Four:
All good, except English was there.
After refresh all good, except... see fifth.

Fifth:
All good, except one folder remain in "Unknown" state although Console says it passed initial scan and all indexes was exchanged.
![synctrayzor_gui_icons2_take2_3](https://cloud.githubusercontent.com/assets/10828858/7253380/9d26104e-e83c-11e4-9715-2873e11c0e50.JPG)
In general, after every refresh it take really long time to all folders to show "Up to date". Most of the time some of them just wont, even after few minutes. In those cases (although I haven't tried this every time) browser don't react to manual language change.
GUI in external browser loads always under 10s.

**Comment by AudriusButkevicius** [comment]
Unknown is a valid state after startup, while syncthing is recalculating stuff.

**Comment by canton7** [comment]
OK, so you're still seeing blank browsers after an install? Hmm, I can't reproduce those. Ideally we don't want to ever have to click on 'Refresh browser' - stuff should work first time. 

My suspicion is that we're trying to connect to Syncthing too early in its startup process. We don't kick off the browser until we've established communications over the REST API, but that may still be too early.

If Syncthing's loaded some folders but not others, I don't think there's a lot I can do - javascript's obviously running, since other folders have loaded, but I have no idea why that one particular one hasn't loaded. Can you reproduce that using a native browser (Syncthing -> Open in external browser)?

**Comment by chucic** [comment]
@AudriusButkevicius Yes, but in those cases syncthing has scanned all folders and received all indexes from connected devices. I can see all folders "Up to date" in external browser, but it almost never gets to all folders "Up to date" in built-in.

**Comment by canton7** [comment]
What Syncthing version are you using, actually? Maybe that's relevant...

**Comment by chucic** [comment]
@canton7 Yes, after an install I'm still seeing blank browser in about half of the times. But when I just restart SyncTrayzor it's fine, no blanks anymore.

When I'm using external browser (chrome), whether through Syncthing -> Open in external browser or just switch to chrome and type 127.0.0.1:8384, whole GUI with "Up to date" on every folder loads under 10 seconds. Also changing folder states from "Unknown" to "Up to date" happens alphabetically from top to bottom whereas in built-in it happens very much randomly and almost every time it "hangs". When I click Refresh, process starts again. Now it even switched to English after Refreshing although before there was Czech and after another Refresh it switched back to Czech.

I'm using syncthing v0.11.0-rc1 on this machine.

One other thing, which may have nothing to do with SyncTrayzor itself because I saw it before in chrome but maybe because of weird/slow behaving of built-in happens more often now is that sometimes after start (not after refresh though) some folders change their status from "Unknown" to "blank" (nothing, no text) and after a while to "Scanning" or "Up to date" but some others go without "blank" state.
![synctrayzor_gui_states_take2_5](https://cloud.githubusercontent.com/assets/10828858/7254742/335542ee-e845-11e4-9ed1-c64f6a4cf58e.JPG)

**Comment by canton7** [comment]
Hrm, I can also reproduce the switching language thing. Every time I refresh, I switch from English to Czech, then back again. I'm sending the same Accept-Language headers to Syncthing each time, so I'm not sure what this could be.

**Comment by canton7** [comment]
Something else is going on too. I've enabled http tracing in Syncthing, and opening Settings -> 'Show ID' displays a broken image....

I added some logging from CEF's console, and get some interesting things...

This is a one-off where the page failed to load at all (only a few angular placeholders were visible)
```
[F3HZW] 2015/04/21 16:14:53.968774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/core/directives/validDeviceidDirective.js": status 200, 344 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.969774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/core/directives/popoverDirective.js": status 200, 173 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.970774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/core/filters/alwaysNumberFilter.js": status 200, 158 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.971774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/core/filters/basenameFilter.js": status 200, 212 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.972774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/core/filters/binaryFilter.js": status 200, 238 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.973774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/core/filters/durationFilter.js": status 200, 539 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.974774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/core/filters/naturalFilter.js": status 200, 146 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.975774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/core/services/localeService.js": status 200, 3035 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.975774 gui.go:238: DEBUG: http: GET "/assets/lang/valid-langs.js": status 200, 139 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:53.976774 gui.go:238: DEBUG: http: GET "/scripts/syncthing/app.js": status 200, 1446 bytes in 0.00 ms
Error: [ng:areq] http://errors.angularjs.org/1.2.7/ng/areq?p0=SyncthingController&p1=not%20a%20function%2C%20got%20undefined
    at Error (native)
    at https://localhost:8384/vendor/angular/angular.min.js:6:449
    at tb (https://localhost:8384/vendor/angular/angular.min.js:18:360)
    at Oa (https://localhost:8384/vendor/angular/angular.min.js:18:447)
    at https://localhost:8384/vendor/angular/angular.min.js:61:470
    at https://localhost:8384/vendor/angular/angular.min.js:49:14
    at q (https://localhost:8384/vendor/angular/angular.min.js:7:380)
    at E (https://localhost:8384/vendor/angular/angular.min.js:48:382)
    at f (https://localhost:8384/vendor/angular/angular.min.js:42:399)
    at https://localhost:8384/vendor/angular/angular.min.js:42:67 (https://localhost:8384/vendor/angular/angular.min.js:84)
[F3HZW] 2015/04/21 16:14:54.185795 gui.go:238: DEBUG: http: GET "/modal.html": status 200, 537 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:54.191796 gui.go:238: DEBUG: http: GET "/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff": status 200, 23156 bytes in 2.00 ms
[F3HZW] 2015/04/21 16:14:57.358113 gui.go:238: DEBUG: http: GET "/rest/system/connections": status 200, 136 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:58.388216 gui.go:238: DEBUG: http: GET "/rest/system/status": status 200, 310 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:58.389216 gui.go:238: DEBUG: http: GET "/rest/system/connections": status 200, 137 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:14:58.424219 gui.go:238: DEBUG: http: GET "/rest/system/error": status 200, 14 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:15:02.366613 gui.go:238: DEBUG: http: GET "/rest/system/connections": status 200, 137 bytes in 0.00 ms
```

This one is more typical: See the 'HTTPError' every so often:
```[F3HZW] 2015/04/21 16:15:35.548931 main.go:587: INFO: Device F3HZWRO is "UKHARPORT059" at [dynamic]
[F3HZW] 2015/04/21 16:15:35.548931 main.go:625: INFO: No automatic upgrades; v0.11.0-rc1 is not a release version.
[F3HZW] 2015/04/21 16:15:35.549931 gui.go:238: DEBUG: http: GET "/rest/events?since=4": status 200, 91 bytes in 1065.11 ms
[F3HZW] 2015/04/21 16:15:35.549931 gui.go:238: DEBUG: http: GET "/rest/events?since=4": status 200, 91 bytes in 507.05 ms
[F3HZW] 2015/04/21 16:15:35.560932 rwfolder.go:258: INFO: Completed initial scan (rw) of folder foo_bar
HTTPError (https://localhost:8384/scripts/syncthing/core/controllers/syncthingController.js:119)
[F3HZW] 2015/04/21 16:15:35.572934 rwfolder.go:258: INFO: Completed initial scan (rw) of folder default
[F3HZW] 2015/04/21 16:15:35.576934 gui.go:238: DEBUG: http: GET "/rest/events?since=5": status 200, 572 bytes in 1.00 ms
[F3HZW] 2015/04/21 16:15:36.010977 gui.go:238: DEBUG: http: GET "/rest/svc/report": status 200, 338 bytes in 644.06 ms
UIOnline (https://localhost:8384/scripts/syncthing/core/controllers/syncthingController.js:70)
[F3HZW] 2015/04/21 16:15:36.013978 gui.go:238: DEBUG: http: GET "/rest/events?since=4": status 200, 661 bytes in 0.00 ms
refreshSystem (https://localhost:8384/scripts/syncthing/core/controllers/syncthingController.js:334)
[F3HZW] 2015/04/21 16:15:36.034980 gui.go:238: DEBUG: http: GET "/rest/system/status": status 200, 309 bytes in 3.00 ms
refreshConfig (https://localhost:8384/scripts/syncthing/core/controllers/syncthingController.js:409)
[F3HZW] 2015/04/21 16:15:36.035980 gui.go:238: DEBUG: http: GET "/rest/system/config": status 200, 1948 bytes in 1.00 ms
refreshConnections (https://localhost:8384/scripts/syncthing/core/controllers/syncthingController.js:395)
[F3HZW] 2015/04/21 16:15:36.037980 gui.go:238: DEBUG: http: GET "/rest/system/config/insync": status 200, 22 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:15:36.038980 gui.go:238: DEBUG: http: GET "/rest/system/connections": status 200, 137 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:15:36.038980 gui.go:238: DEBUG: http: GET "/rest/system/version": status 200, 177 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:15:36.172994 gui.go:238: DEBUG: http: GET "/rest/events?since=5": status 200, 572 bytes in 0.00 ms
HTTPError (https://localhost:8384/scripts/syncthing/core/controllers/syncthingController.js:119)
[F3HZW] 2015/04/21 16:15:36.681044 gui.go:238: DEBUG: http: GET "/rest/svc/report": status 200, 338 bytes in 641.06 ms
[F3HZW] 2015/04/21 16:15:38.401216 gui.go:238: DEBUG: http: GET "/rest/system/status": status 200, 309 bytes in 1.00 ms
[F3HZW] 2015/04/21 16:15:38.402217 gui.go:238: DEBUG: http: GET "/rest/system/connections": status 200, 136 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:15:38.413218 gui.go:238: DEBUG: http: GET "/rest/system/error": status 200, 14 bytes in 0.00 ms
[F3HZW] 2015/04/21 16:15:38.676244 gui.go:238: DEBUG: http: GET "/rest/system/connections": status 200, 137 bytes in 1.00 ms
```

@AudriusButkevicius any idea what might be causing these?

**Comment by chucic** [comment]
Btw, I looked at  [5f61361](https://github.com/canton7/SyncTrayzor/commit/5f613618d6f06795fe2c41121271b3492cc0ab1b#diff-2bf6356a5cce43ba4d7293154f5efefaR98) and I only understand that CefSharp hits some threading issue (which is causing most if not all of troubles we experiencing) after trying to set zoom through some startEvent (and some complicated events after that) because of a bug it prevails from doing it "some other way". Trying to bypass it leads to loosing some properties of function responsible for proper call which is causing setting improper zoom level. So "solution" is to call it on both/more places, which sets zoom level right but causes more troubles. But I bet I misunderstood something, this is really far beyond me.

Btw, what is current status of #10?

**Comment by canton7** [comment]
I took out the zoom stuff as part of my testing here, and still hit the issues I described above, as well as the language toggling every time Syncthing is restarted. I think that was responsible for the really weird image rendering / spacing issues, but nothing else.

The state on #10 is basically "Yeah, we want to bring everything under one umbrella. SyncTrayzor should get a better name (which I'm fine with), but I'm not sure what...". There was also a hold-up while I changed up auto-update system to handle moving the repository, which is now done.

**Comment by canton7** [comment]
Hrm, it seems to be related to the upgrade to CefSharp 39

**Comment by canton7** [comment]
@chucic mind trying this build? I downgraded CefSharp to what it was previously, and put some hacks in place to still do the zoom stuff I need to do...

https://s3-eu-west-1.amazonaws.com/canton7/SyncTrayzorSetup-x64-issue-62-b74f8b0.exe

**Comment by AudriusButkevicius** [comment]
So it seems there is some JS error in CefSharp, unless you can add some breakpoints in the JS engine to workout where it's happening, there is a little we can do, as angular errors are completely useless.

**Comment by canton7** [comment]
I don't it's that advanced :smile: I want to get as little involved with CefSharp as possible - that way lies pain. The old version seemed to work, and I'm happy to leave it at that.

One thing I did notice though: my experience says that 'console.log' doesn't take multiple arguments, but https://github.com/syncthing/syncthing/blob/master/gui/scripts/syncthing/core/controllers/syncthingController.js#L119 uses it as such (so you don't actually get `arg` logged) - but I could be wrong.

**Comment by AudriusButkevicius** [comment]
Yeah, it seems you are right, but I am more worried about the angular error.

**Comment by canton7** [comment]
It's a pity I didn't catch more context around that error. I'm willing to bet that `syncthingController.js` was never fetched. I never saw the symptoms of that with the older Cef version, so I'm willing to bet it was a Cef screw-up.

One other thing: on startup, Syncthing 0.11 requests `/qr/?text={{myID}}`. Interpolation failure?

**Comment by AudriusButkevicius** [comment]
Well it should expand that, but if it doesn't raise an issue.

**Comment by canton7** [comment]
See syncthing/syncthing#1679

**Comment by chucic** [comment]
Works. Tried multiple times.
Zoom level correct, no blank browser, Czech set (mostly immediately, sometimes it takes few seconds), "Up to date" next to folders shows immediately after it shows "Initial scan completed" in Console View, after initial scan of all folders Refreshing takes under 10 seconds to complete page (quick as chrome), Czech text in Console View is ok, everything in place and working. Is this all or did I miss something?

Thank you, it's awesome again :smiley: 

Only thing that stays is "blank" state:
![synctrayzor_gui_states_take3_1](https://cloud.githubusercontent.com/assets/10828858/7257383/9563af56-e855-11e4-9553-0138688f9211.JPG)
On one start it occur on all folder states, but I missed it an now only a few of them turns "blank"  and they turn "Scanning" or "Up to date" fast. This only happens on SyncTrayzor start, could it be

    trying to connect to Syncthing too early in its startup process. ?

**Comment by AudriusButkevicius** [comment]
The blankness I think is also a syncthing bug due to the way we work this data out, but it's a temporary thing, hence not sure if it's a bug.

**Comment by canton7** [comment]
Fantastic, thank you so much for your help!

**Comment by canton7** [comment]
v1.0.16 is out!

**Comment by chucic** [comment]
Great news, thanks!

**Comment by canton7** [comment]
And thank **you** for all of your testing! With issues I can't reproduce locally, I'm completely dependent on helpful people like you to track down and test things like this :smiley:
