### ISSUE TITLE
Update Chocolatey package

### ISSUE THREAD

**Issue by SlugFiller** [canton7/SyncTrayzor#621]
Ever since version 1.1.27 has been released, SyncTrayzor has been complaining that it needs to update, but the package in Chocolatey remains on version 1.1.24.

In general, Chocolatey packages should be configured to have any internal auto-update disabled, and only update through Chocolatey. This is particularly important for allowing Chocolatey's "pin version" feature.

**Comment by canton7** [comment]
See the chocolatey page comments for details on the lack of release.

@TheCakeIsNaOH Do we need to disable auto upgrades?

**Comment by TheCakeIsNaOH** [comment]
> Do we need to disable auto upgrades?

That would be ideal. 

Although, I thought that it just only notified, and does not update automatically unless the user clicks the ok. So it is an annoyance on the user end, not something that breaks the pin feature. For example, both Chrome and Firefox auto-update without any user intervention at all, whereas SyncTrayzor only checks then alerts and gives the option to update.

**Comment by canton7** [comment]
> Although, I thought that it just only notified, and does not update automatically unless the user clicks the ok

Yep, that's right. There is a way of disabling it by editing SyncTrayzor.exe.config (`<NotifyOfNewVersions>`), but since the complaint rate here is less than 0.01% I'm be tempted to leave it as-is unless more people chip in. Remember that it also ships Syncthing, which *is* set up to auto-upgrade without any prompts.

Copy/paste of the message from the Chocolatey page:

> The newer SyncTrayzor installers require a newer .NET Framework version. It turns out that this isn't present in the test environment used for moderation (although it is present on all modern PCs), so the installer had to trigger installation itself. This upset the chocolatey moderation process, so we needed to change the package to specify the .NET Framework as a dependency, and update the installer to not try to install the .NET Framework if called from chocolatey (as the official way of detecting the installed .NET Framework version only works after a reboot).
>
> This update was made post-1.1.27 and will not be available until 1.1.28. Changing the entire package release process and handing control to a stranger will not fix this: there is already an automated process for updating and releasing the chocolatey package. The issue is with the SyncTrayzor installer, which will be fixed in 1.1.28.

**Comment by canton7** [comment]
Version 1.1.28 is out, and is going through the moderation process.
