### ISSUE TITLE
Conflict resolver: choose for all, hotkey or fixed position buttons

### ISSUE THREAD

**Issue by Eenpersoonscommissie** [canton7/SyncTrayzor#623]
Hi, I have some work folders which are quite large and often have conflicting files. In Conflict resolver I have to manually choose sometimes more than 300 conflicts. In most cases the choice which file should stay would be the same for the complete list. But I have to click 300+ times the right button for each conflict. On top of that the layout is responsive and the position of the choose button depends upon the length of the name of the file. So you can't just click on the same spot, but have to aim constantly. 

- Best option would be something like a choose for all (selected), where the same source will be used for everything (selected). 
- Another option would be to add hotkeys for the different choice buttons (a simple 1,2,3 would do). 
- Or (maybe as quick fix) make the filename length fixed (width adjustible with mouse, like for example in Excel) forcing the buttons to stay on the same position.
- 
This is really the only annoyance I have had with Synctrayzor, Great little program (next to Syncthing itself off course) ehich I use daily.
Kind regards, Epco

**Comment by canton7** [comment]
I mis-remembered: no right-click, but ctrl-A does work.

![image](https://user-images.githubusercontent.com/568104/108973211-01041880-767c-11eb-8d2b-d194ced8a940.png)

**Comment by Eenpersoonscommissie** [comment]
Ah, my bad. Overlooked that tip! Thanks for the heads up!
