### ISSUE TITLE
Synctrayzor doesn't show GUI or GUI issues but GUI works fine in browser

### ISSUE THREAD

**Issue by coolVariable** [canton7/SyncTrayzor#624]
Love this program which is, without any peers, the best file sync tool today.
Just got a new device (Win10 PC) and I am having a weird issue though.
Syncthing works but Synctrayzor does not show the GUI when I open it, or it only comes up with issues (blank screen with GUI elements becoming visible by mousing over them, and they do not respond).
Tried different installs as well as the portable version, and it stubbornly refuses to work normally.

Going to the GUI via the browser works without any problems.

**Comment by canton7** [comment]
Intel Xe graphics card, by any chance?

**Comment by coolVariable** [comment]
Yes. New Surface with Intel Xe graphics.
I feel like the plot is thickening.

**Comment by canton7** [comment]
Yep, Intel graphics / driver issue. #606. Hopefully have a workaround out in a few days.
