### ISSUE TITLE
Edit Folder Defaults dialogue opening instead of Folder Specific after opening Defaults. 

### ISSUE THREAD

**Issue by sembeeuk** [canton7/SyncTrayzor#629]
Title doesn't really explain it. 
If I open Actions, Settings, and then under Default Configuration, select Edit Folder Defaults, then close it, then go to one of the specific synchronised folders and choose Edit, the same windows comes up - just with the paths changed to match the folder I am editing. Therefore missing the tabs for Ignore Patterns, and the Folder ID etc. 

![SyncTrazor1](https://user-images.githubusercontent.com/25618369/111194213-dc33fe80-85b2-11eb-9c43-d4bebdf44545.PNG)

If I restart SyncThing from the menu, then it comes back as expected - and that is the only way I have found to reset it. 

![SyncTrazor2](https://user-images.githubusercontent.com/25618369/111194901-91ff4d00-85b3-11eb-8345-447c8c1b09b2.PNG)

It is like it is remembering the wrong window. 

Versions 
SyncThing: 1.14.0
SyncTrayzor: 1.1.28

**Comment by canton7** [comment]
This is a question about the Syncthing UI. Please open a thread on the [Syncthing forum](https://forum.syncthing.net). Thanks!
