### ISSUE TITLE
Enhancement: Add Right-click "Pause Syncthing for 30 Minutes"

### ISSUE THREAD

**Issue by kleinfelter** [canton7/SyncTrayzor#635]
On slow devices, a Syncthing scan can consume so much resources that the machine is unusable.  Sometimes, you really need to *use* a computer *now*.  It would be really nice if SyncTrayzor offered a right-click option to "Pause Syncthing for 30 minutes" (or an hour or some other chunk of time).  

Yes, right now we can right-click and "Stop Syncthing", but wonderful people like my wife will forget to re-start Syncthing, and then sync doesn't happen for a long time.

**Comment by canton7** [comment]
#369?

**Comment by kleinfelter** [comment]
Thank you. I saw that one, but I thought maybe it was specific to detecting the connection state.  If that one will include the ability for the user to tell it to pause, I'm certainly content to close this request.
