### ISSUE TITLE
Documentation for Choco: Syncthing vs SyncTrayzor

### ISSUE THREAD

**Issue by BrandonKMLee** [canton7/SyncTrayzor#639]
Here are some questions that have to be addressed:
1. Does one need to install Syncthing in order to use SyncTrayzor?
2. How are they different? Would there be missing features?
3. Can this be a replacement for Resilio Sync?
4. What is with the Scan Testing Resulted in the https://community.chocolatey.org/packages/synctrayzor page?

**Comment by canton7** [comment]
1. No. Synctrayzor bundles a copy of Syncthing
2. Syncthing's UI is browser-based: you need to open a web browser to use it. Synctrayzor makes it behave as a normal desktop application (and also adds some other features, such as tray notifications). Synctrayzor doesn't replace Syncthing 
3. Syncthing does much the same thing as Resilio sync, yes
4. Not sure what you mean. As that page explains, VirusTotal integration into Chocolatey is very new, and the last version of SyncTrayzor was published before that happened

**Comment by BrandonKMLee** [comment]
Thanks for the replies, hope that 4th can be resolved soon.

**Comment by canton7** [comment]
What do you mean? There's nothing to resolve.

**Comment by BrandonKMLee** [comment]
> VirusTotal integration into Chocolatey is very new

if the test can be cleared then it would be good.

**Comment by canton7** [comment]
There is nothing I *can* do until a new version of SyncTrayzor is released, which will go through the new Chocolatey process.

**Comment by canton7** [comment]
It's also worth noting that this application gets fairly frequent false positives (see the closed issue list)
