### ISSUE TITLE
"oops something went terribly wrong" even after reinstall

### ISSUE THREAD

**Issue by DanBaur** [canton7/SyncTrayzor#640]
I have synctrazor installed on a laptop running the latest stable build of windows 10. Whenever I run synctrazor it crashes and tells me "oops something went terribly wrong". This problem still persists even after multiple reinstalls (done using BCUninstaller to make sure nothing is left behind in appdata, registry and the like). I also ran the windows integrity checker sfc /scannow for good measure but the problem still persists. The log file and a text file containing some more messages the app outputted have been attached.
[out.txt](https://github.com/canton7/SyncTrayzor/files/6502549/out.txt)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/6502551/SyncTrayzor.log)

I haven't had this problem on any of my other windows machines by the way, they are all running the latest version of synctrazor

**Comment by DanBaur** [comment]
this problem only started happening recently on my laptop, it used to work perfectly before on the laptop.

**Comment by canton7** [comment]
See #626 -- there's a fix linked there
