### ISSUE TITLE
Is there a lightweight client for windows

### ISSUE THREAD

**Issue by huyifanstar** [canton7/SyncTrayzor#641]
I plan to use Syncthing, but I don’t need web management ui on windows, I have ubuntu as the server side

I prefer configuration files and executable programs to complete the startup, but SyncTrayzor has too many functions

Plan to use exe file and Windows service to start automatically to use Syncthing Windows client

**Comment by canton7** [comment]
https://docs.syncthing.net/users/autostart.html#windows
