### ISSUE TITLE
Conflict Resolution Notification

### ISSUE THREAD

**Issue by Joshuao95** [canton7/SyncTrayzor#650]
Hi,

I am not actually a Windows user, but your program looks great!

I was wondering however, how are you detecting conflicts exactly, is it through scanning synced directories for files matching the sync conflict filename, or is there some syncthing API to plug into?

Asking because I'd like to create a small tool for dealing with Syncthing conflicts for Linux for myself.

Thanks!
I did try to read it from the code myself,  but I'll admit to being OOP-illiterate >_>

**Comment by canton7** [comment]
It's what you suspected: scanning through files looking for matching filenames.

I do have filesystem notifications set up though, so I'm not constantly doing large expensive scans: I'll get a notification when a new file is created in one of Syncthing's folders.

- [ConflictFileWatcher](https://github.com/canton7/SyncTrayzor/blob/master/src/SyncTrayzor/Services/Conflicts/ConflictFileWatcher.cs)
- [ConflictFileManager](https://github.com/canton7/SyncTrayzor/blob/master/src/SyncTrayzor/Services/Conflicts/ConflictFileManager.cs)

**Comment by Joshuao95** [comment]
Excellent, thanks a lot @canton7 !
