### ISSUE TITLE
SyncTrayzor not opening on Start Up and not opening from Start Menu

### ISSUE THREAD

**Issue by catvix** [canton7/SyncTrayzor#654]
Hello,

I noticed that SyncTrayzor wasn't open, so I went to open it from the Start Menu. I got the below error.

![Error ST2 2607](https://user-images.githubusercontent.com/87963052/126936692-04da68ef-5287-410b-a401-203f37c67079.png)

Is there anything you can do to help with this, please?

Thank you.

**Comment by canton7** [comment]
This happened quite a lot many years ago, and the nearest we got was that windows update was corrupting SyncTrayzor's configuration file, which lead to those instructions being added at the bottom of the dialog. You're best off deleting the file it names, which will lose your SyncTrayzor (*not* Syncthing) settings.
