### ISSUE TITLE
Displays blank screen after opening tray icon for 1st time.

### ISSUE THREAD

**Issue by smipx** [canton7/SyncTrayzor#658]
Hi,  A little issue I am having.  I have Synctrayzor set to run on startup minimized.  The icon appears but when I double click on it the first time after a boot in Windows 10 (fast startup is disabled) I get a blank screen with only the syncthing log displaying:

![image](https://user-images.githubusercontent.com/56273763/128501806-bd71a7e9-a6f5-40df-9ac3-243eed5085ca.png)

I have to close the window (back to the minimised tray icon) and then the 2nd time I double click the tray icon everyting is displayed as it should be. It is only a very minor issue but I thought you would want to know.:

![image](https://user-images.githubusercontent.com/56273763/128501852-bf5b33c7-00e3-4dc7-8d63-9022b8fa8844.png)

thanks
Paul

**Comment by canton7** [comment]
Have you tried disabling hardware rendering under File -> Settings?

**Comment by smipx** [comment]
I've done that and so far it's loding each time as expected so I guess it was that.  thanks for the tip :-)
Paul
