### ISSUE TITLE
How to gracefully exit SyncTrayzor through command line?

### ISSUE THREAD

**Issue by qcksilver** [canton7/SyncTrayzor#660]
This isn't a bug or feature request, sorry if this isn't the right place to ask this question. I tried to find a SyntTrayzor user forum or someplace where it would make more sense to post about this but couldn't find anything. Is there a better place to ask this?

**Does anyone know if it is possible to gracefully exit SyncTrayzor through command line on Windows 10?**

I have a batch script that closes a lot of background programs that I usually have running and I'd like to add SyncTrayzor to it.

I tried `taskkill /im synctrayzor.exe` and I get this response:
`SUCCESS: Sent termination signal to the process "SyncTrayzor.exe" with PID 8784.`
but synctrayzor doesn't actually exit.

I know I can add `/f` to force close synctrayzor, but if I do that then synctrayzor will exit but syncthing will still be running of course.  And I don't want to `/f` syncthing because I don't want to risk corrupting syncthing's database.

I want to close syntrayzor to properly shutdown as if I right clicked on the icon and selected "exit," which will also properly shutdown syncthing.

Thanks!

**Comment by canton7** [comment]
In the next version, you'll be able to run `SyncTrayzor.exe --shutdown`. I'll try and get that version out soon.
