### ISSUE TITLE
The Yes/No buttons on "The allow anonymous usage reporting" do not work 

### ISSUE THREAD

**Issue by Piratealgeria** [canton7/SyncTrayzor#661]
The Yes/No buttons on "The allow anonymous usage reporting" do not work 
![image](https://user-images.githubusercontent.com/45120897/128753795-7679a73e-fafd-4dbc-a6a8-3edfcc3aad00.png)

I kept clicking and nothing I can't get rid of it it's blocking my way preventing me from doing anything

hope it gets fixed, it's my first time using this project and I'm having a problem already

**Comment by canton7** [comment]
This is a question for Syncthing - try the forum.
