### ISSUE TITLE
Position in Console View after opening from tray

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#67]
After opening from tray, Console View is set to show log from beginning, so I have to scroll down every time I it open to see what was Syncthing doing recently. Could it be otherwise, that Console View would show end of log?

**Comment by canton7** [comment]
Ah, yeah, it might. It should scroll down every time a new message is received, but probably not when its size is changed (which is likely what's causing this).

**Comment by chucic** [comment]
Yes, when new message is received it does scroll down.

**Comment by canton7** [comment]
Should be a 3-line fix

**Comment by Thumbsy** [comment]
Fantastic, I noticed this behaviour as well and would prefer for it to show the end of the log just like chucic described. Good to hear it's an easy fix!
