### ISSUE TITLE
F-secure malware protection going bonkers over Synctrayzor upgrade v.1.18.5 

### ISSUE THREAD

**Issue by Megantonneke** [canton7/SyncTrayzor#673]
F-secures DeepGuard which is running on my system, blocks Syncthing v.1.18.5 (it attempted an automatic update yesterday). Is this a false positive or is Syncthing compromised?

**Comment by RdivineNW** [comment]
Malware bytes has blocked Syncthing from accessing an IP that resolves to Russia on my computer: 193.201.9.71

**Comment by canton7** [comment]
This is the SyncTrayzor issue tracker, and you're talking about Syncthing. Try https://forum.syncthing.net
