### ISSUE TITLE
Support `ignoreDelete` setting

### ISSUE THREAD

**Issue by h-h-h-h** [canton7/SyncTrayzor#676]
Syncthing documentation page: https://docs.syncthing.net/advanced/folder-ignoredelete.html

I couldn't find this option in SyncTrayzor. I need a folder with one device as the master source, where file *edits* are bidirectionally synced, but without the danger of losing files when they are accidentally or illegitimately deleted on the non-master device. This would be possible if SyncTrayzor on the master device could be configured to ignore deletes.

**Comment by canton7** [comment]
Set it in Syncthing's settings. Synctrayzor does not replicate Syncthing's menus or UI.

**Comment by h-h-h-h** [comment]
Sorry, I confused Syncthing's with SyncTrayzor's interface. And the Syncthing people don't seem to want to expose the setting in the UI. So, one *has* to edit Syncthing's `config.xml` in `%LOCALAPPDATA%\Syncthing` and restart SyncTrayzor.

**Comment by canton7** [comment]
It's in the advanced settings.

**Comment by h-h-h-h** [comment]
That sounds like "[Folder] > Edit > Advanced", and it's not there. But, now, I've found out what you mean: "[Syncthing UI's top bar] > Actions > Advanced > Folders > [Folder]" (just for documentation purposes).
