### ISSUE TITLE
Position of splitter between Console and Viewer is lost after hiding and showing Console

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#68]
When I hide Console and then show it again, position of splitter is lost and returned to default.

Now I'm thinking, maybe it's by design? Anyway, really minor one...

**Comment by AudriusButkevicius** [comment]
I feel this was recently closed, but perhaps not yet released. Look for closed issues.

**Comment by chucic** [comment]
If you mean #56 than it concerns remembering position after closing to tray and opening again.

**Comment by canton7** [comment]
Yeah, the console being hidden is counted as having a height of 0. I did it that way because it simplified things slightly and I honestly didn't think anyone would care :smiley:

If it bothers you, it shouldn't be too hard to put in.

**Comment by chucic** [comment]
It doesn't bother me too much, only that I really like this app and trying to contribute to it the way I can, which sadly seems to be only issues raising. But since this is really something that nobody will notice/care about, don't waste your time on it. I will think more about importance of things I discover before I click that green button here next time :wink:

**Comment by canton7** [comment]
Fair enough! I appreciate the helpful attitude :smile:

**Comment by canton7** [comment]
I think this is wontfix
