### ISSUE TITLE
Allow for disabling notifications of successful syncs!

### ISSUE THREAD

**Issue by iMartyn** [canton7/SyncTrayzor#683]
I use Syncthing to keep machines in sync, and quite often the thing I want to do immediately after switching machines is do something in the system tray.

Because I switch machines, the machine wakes and suddenly I have to wait for tonnes of notifications that I really don't care about and they interfere with any interaction in the system tray.

Please allow for turning successful sync messages off!

**Comment by canton7** [comment]
You can disable them under the settings. Check the Folders tab as well
