### ISSUE TITLE
Version 1.1.29.0 crashing on Windows 10

### ISSUE THREAD

**Issue by Miq1** [canton7/SyncTrayzor#688]
I am not able any more to run Synctrayzor on my Windows 10 pro box, I always will get this error message (sorry, screen shot only, I could not copy the message text):
![2022-02-22 16_52_27-Window](https://user-images.githubusercontent.com/25884124/155169221-9f6ff69d-1416-4402-b79a-a89ecfa1a13a.png)

What am I doing wrong?

**Comment by hobbsecky** [comment]
You need the installer not the portable version. Download and install the Windows version.

**Comment by Miq1** [comment]
Well, no, I have the installer. The issue seems to have dissolved after a few reboots, though, I am afraid it might have been caused by a Windows problem after the recent bulk update MS seems to have made.
Thank you anyway!
