### ISSUE TITLE
SyncTrayzor won't start

### ISSUE THREAD

**Issue by SamGreenwood1** [canton7/SyncTrayzor#695]
SyncTrayzor doesn't open at boot (even though it's configured to) and when I try to open it I get the following error:
![image](https://user-images.githubusercontent.com/20076209/164293890-1ac59406-7a46-46b9-a76f-85bea0d647e1.png)

**Comment by SamGreenwood1** [comment]
Still waiting for a response.

**Comment by canton7** [comment]
Dup of #471
