### ISSUE TITLE
1.1.29 - VirusTotal detects Trojan.Sdum in SyncTrayzorSetup-x64.exe (Not detected for 1.1.28)

### ISSUE THREAD

**Issue by gnat** [canton7/SyncTrayzor#697]
:warning: Virus Total Results for [v1.1.29/SyncTrayzorSetup-x64.exe]( https://www.virustotal.com/gui/file/bd9631c18b6b0bede73fdb80481784d2e21820e9dbb1d3d7f1b98b5d89745209)

:heavy_check_mark: Virus Total Results for [v1.1.28/SyncTrayzorSetup-x64.exe](https://www.virustotal.com/gui/file/bbaab4c9fdddad1a777eb8aa113b45351064e0dfd1c974ff069f8e4a746878dc)

Might be an issue, since it occurred between the last two point releases. Thanks.

**Comment by canton7** [comment]
Not much I can do about that: complain to your virus scanner vendor
