### ISSUE TITLE
Automatic Conflict Resolver?

### ISSUE THREAD

**Issue by DocMAX** [canton7/SyncTrayzor#699]
Hi,
i always get conflicts and i always select "take newest file". Can this be automated?
No matter which machine i changed my file, i want Syncthing/SyncTrayzor to always let newest file "win".
One host of all my hosts is running 24/7. So there is theoretically always this host, which holds the latest file, even when the modifiying host is offline.

Hope you understand what i mean, thanks.

**Comment by laurinkeithdavis** [comment]
I second and third that! Seriously, this drives me crazy having to constantly pick these, even though I always pick the same one (newest).

**Comment by jabacz** [comment]
This request should go to Syncthing engine. Synctrayzor is just an installer and wrapper for Windows.

**Comment by DocMAX** [comment]
Yes you are right and i think i found it: In advanced options set on every folder "Max Conflicts = 0". No more conflict files are appearing so far. Great!

**Comment by canton7** [comment]
Do bear in mind that Syncthing creates conflict files because there is no way to automatically resolve them without throwing away your work. So any setting which does this necessarily results in automatic data loss.

**Comment by DocMAX** [comment]
Yes i have this in mind, thank you.
With this setting i assume that Syncthing always keeps the newer file and deletes the old ones, which is exactly what i want. Correct me if i am wrong.

**Comment by canton7** [comment]
I'm not sure what the setting does exactly, but my guess is that it will just stop syncthing creating the conflict file at all, so whatever file was originally on the device gets kept, and the incoming file is rejected. So the one that is kept depends solely on whether device A fetches device B's changes first, or the other way around

**Comment by DocMAX** [comment]
1. I put host A, B, C offline (disabled syncthing).
2. I edited all files at different times. Host C last.
3. I enabled syncthing on all hosts.
4. Works exactly as expected: All 3 hosts synced to newest file of host C
5. Great!

**Comment by canton7** [comment]
I'd still say that's probably due to timing during synchronisation. Try editing the file last on A and B, B keep everything else the same. Even then, I'd be cautious. Make sure you're keeping good backups!

**Comment by DocMAX** [comment]
Edited host A last. Turned on A, B, C and guess what? All synced to file of host A. :-)

**Comment by canton7** [comment]
Cool, glad it's working for you! Make sure you re-enabled Syncthing in the same order both times.

**Comment by canton7** [comment]
Looks like it is based on mtime: https://docs.syncthing.net/users/syncing.html#conflicting-changes

**Comment by DocMAX** [comment]
I will test, if i was wrong with something i will report this here. Fingers crossed.

**Comment by DocMAX** [comment]
Yes, it's mtime based and that doesn't change if Syncthing copies files from A to B.
