### ISSUE TITLE
Crash on startup issue

### ISSUE THREAD

**Issue by azerby** [canton7/SyncTrayzor#701]
Synctrayzor immediately gives an error window on attempting to run it, which said to open an issue at this link.
Haven't tried any of the usual troubleshooting steps yet but will try to update as I go, starting with re-installing SyncTrayzor.
Device specs below under error info/logs.

Text from the error window:
> Version: 1.1.28.0; Variant: Installed; Arch: X86
> Path: C:\Program Files (x86)\SyncTrayzor\SyncTrayzor.exe
> System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
> File name: 'C:\Program Files (x86)\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
>    at CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
>    at CefSharp.Cef.Initialize(CefSettingsBase cefSettings)
>    at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
>    at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
>    at Stylet.Screen.SetState(ScreenState newState, Action\`2 changedHandler)
>    at Stylet.Screen.Stylet.IScreenState.Activate()
>    at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
>    at System.EventHandler\`1.Invoke(Object sender, TEventArgs e)
>    at Stylet.Screen.<>c__DisplayClass35_0.<Stylet.IScreenState.Activate>b__1()
>    at Stylet.Execute.OnUIThread(Action action)
>    at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
>    at Stylet.Screen.SetState(ScreenState newState, Action\`2 changedHandler)
>    at Stylet.Screen.Stylet.IScreenState.Activate()
>    at Stylet.ScreenExtensions.TryActivate(Object screen)
>    at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
>    at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
>    at Stylet.WindowManager.ShowWindow(Object viewModel)
>    at Stylet.BootstrapperBase.DisplayRootView(Object rootViewModel)
>    at Stylet.Bootstrapper\`1.Launch()
>    at SyncTrayzor.Bootstrapper.Launch()
>    at Stylet.BootstrapperBase.Start(String[] args)
>    at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
>    at System.Windows.Application.OnStartup(StartupEventArgs e)
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 

Log files:
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/8645781/syncthing.log)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/8645782/SyncTrayzor.log)

Device I'm experiencing these issues on is my wife's laptop, a Lenovo Yoga running Win10 Home (Currently at version: 10.0.19043 Build 19043)

Here's some device specs that are hopefully useful:
| Item                 | Value |
| -----------------|-------|
|System Model | 81TD |
| System Type | x64-based PC |
| System SKU | LENOVO_MT_81TD_BU_idea_FM_Yoga C740-15IML |
| Processor | Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, 2304 Mhz, 4 Core(s), 8 Logical Processor(s) |
| BIOS Version/Date | LENOVO BNCN38WW, 7/15/2020 |
| Installed Physical Memory (RAM) | 16.0 GB |

**Comment by azerby** [comment]
Uninstalled SyncTrayzor, grabbed the latest release from GitHub to install and I'm now realizing I didn't have the latest release.
After installing the latest it seems to be opening just fine now, that was most likely my issue. Will go ahead an close now.

**Comment by canton7** [comment]
Looks like your anti virus probably took a dislike to one of its files - there's a file missing from the Program Files folder. Reinstalling put it back.
