### ISSUE TITLE
Better text options in icon menu

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#71]
In tray icon menu there are lines like "Stop", "Restart" and "Exit", but there is no clear determination whether it will stop, restart or exit SyncTrayzor or Syncthing. I know that it is logical and from menu in window one can determine that (because there are SyncTrayzor stuff and ST stuff under separate sections), but it can be confusing for "average Windows user". Furthermore, in some languages (like Czech) is better to use same expression to both Stop and Exit (at least in case of an app) although there are two separate expressions. So user will basically see "Exit", "Restart" and "Exit". Could it be for example "Start Syncthing", "Stop Syncthing" and "Restart Syncthing" instead for tray icon menu options? Maybe even "SyncTrayzor settings" and "Exit SyncTrayzor" although it is probably unnecessary. Or two separate sections with Syncthing and SyncTrayzor in headers?

**Comment by canton7** [comment]
Probably fair - I'll look at this thanks
