### ISSUE TITLE
Files deleted while I am using them

### ISSUE THREAD

**Issue by janaxhell** [canton7/SyncTrayzor#711]
In the past 2 days SyncTrazor erased from existence 2 files I was working on and there was no way to save them as the app expected them to be somewhere, while they weren't anymore. Tried an aggressive tool like DiskDrill to recover them, but they were completely wiped. The app I was using is WhereIsIt for Windows, it scans folders/disks and archives the contents in a database. When I tried to save and close the file I was using, it gave an error, so since I barely modified it, I decided to close&reopen the app only to find out the file was no more. SyncTrayzor showed it as an error like "the file has changed hash" and decided to kill it on all synced devices. I manually rebuilt the lost file scanning data for hours, so nothing's lost, but this makes SyncTrayzor unreliable, I cannot trust it. It's like working with a time bomb under the chair. I made a manual copy of all the files, tried again to use WhereIsIt normally and again, after a random number of usages SyncTrayzor erased the file I was working on, but this time I had a manual copy outside synced folders. For context, I have SyncThing on a OMV server in a Docker container and SyncTrayzor on Windows to backup stuff on the server.

**Comment by canton7** [comment]
Sounds like a Syncthing question/problem. Synctrayzor just the wrapper which turns it into a nice-looking Windows application: it doesn't create/delete any files. Please use the forum: https://forum.syncthing.net. Thanks!
