### ISSUE TITLE
Syncthing on windows doesn't start

### ISSUE THREAD

**Issue by jkpieters** [canton7/SyncTrayzor#714]
![image](https://user-images.githubusercontent.com/60701434/177706566-76f42ab0-938e-4e28-9691-1d272d91d623.png)
I keep getting a Failed to start pop-up message. Did what was suggested in the message box, but to no avail.

**Comment by canton7** [comment]
What text is in the log window at the bottom of the screen?

**Comment by jkpieters** [comment]
[start] 2022/07/07 08:36:16 WARNING: Error opening database: The process cannot access the file because it is being used by another process. (is another instance of Syncthing running?)

No other process for syncthing is running.

**Comment by canton7** [comment]
This is a Syncthing issue I'm afraid - ask in the forum: https://forum.syncthing.net. Thanks!
