### ISSUE TITLE
Connected device Addresses set on "dynamic" almost never works

### ISSUE THREAD

**Issue by nevaran** [canton7/SyncTrayzor#718]
I have a connection between a Windows Server 2019 laptop acting as the backup machine connected on the **ethernet**, and a Windows 10 machine that uses the **WiFi** network. Both machines are on the latest versions on SyncTrayzor and Windows updates.

The connections seem to not be able to find the device in the local network, they will often go through a relay if the option is enabled.
Setting the address from **dynamic** to the statically assigned ones on the devices works pretty much 100%, but it is not an option since if the W10 machine switches from **WiFi** to **ethernet**, the IP changes, whilst using a relay destroys the purpose of having a local-only syncing.

In "**dynamic**" mode, the program yells about "NAT type: Port restricted NAT" and refuses to connect locally.

Enabled settings: **Enable NAT traversal, Local Discovery**
Version on all devices: **1.20.3**

**Comment by canton7** [comment]
This is a Syncthing issue. Please use https://forum.syncthing.net. Thanks!
