### ISSUE TITLE
System tray Tooltip at wrong place

### ISSUE THREAD

**Issue by JoAllg** [canton7/SyncTrayzor#719]
Wiindows 10, SyncTrazor v1.1.29

The tooltip, that pops up when hovering on the SyncTrazor icon in the system tray, very often hangs on the left upermost corner of the screen:
![grafik](https://user-images.githubusercontent.com/57436524/180165245-f9561af7-5635-43d6-8ef7-5a507d4fc778.png)
Getting rid of it is only possible by hovering the cursor on the SyncTrazor icon on purpose.
I could reproduce this by hovering on the icon and then moving the cursor away in exact the moment the tooltip would pop up (after the tooltip delay). I am not sure if this is the only cause, it happens very frequently.

I also noticed that the tooltip delay is significantly higher then the delay of other apps/icons. The implementation seems to be different?

**Comment by canton7** [comment]
Duplicate of #398?

**Comment by JoAllg** [comment]
You are right, thank you :-)
