### ISSUE TITLE
Avast block us again v1.1.92

### ISSUE THREAD

**Issue by Harvie** [canton7/SyncTrayzor#725]
Avast blocks us again claiming IDP.Generic infection in trayzor v1.1.92 based on behavioral filter:

![image](https://user-images.githubusercontent.com/276504/190705299-48f5fff7-eb4b-430f-9f2a-47797ae05346.png)

**Comment by canton7** [comment]
There's nothing I can do about Avast I'm afraid. Open the issue with them.
