### ISSUE TITLE
Show In & Out bandwidth in the tooltip on hover

### ISSUE THREAD

**Issue by VsevolodGolovanov** [canton7/SyncTrayzor#732]
Like e.g. qBittorrent does:
![image](https://user-images.githubusercontent.com/8070317/196927892-414da1a1-fc80-4861-bff7-a5da25ab7bc4.png)

**Comment by canton7** [comment]
You can click the tray icon to see this

**Comment by VsevolodGolovanov** [comment]
I'm aware. I wish this info would be shown on hover though.
