### ISSUE TITLE
Doesn't work on first boot

### ISSUE THREAD

**Issue by 0uros** [canton7/SyncTrayzor#739]
It is the first time that I start it, but it gives an error as if there was another process running, which is not the case, and even closing that process, it keeps happening

![image](https://user-images.githubusercontent.com/67289586/202264617-042f14e5-7e02-4940-bb9e-4f6ad134489f.png)

All this using the latest version available (1.1.29)

**Comment by canton7** [comment]
What does the console window at the bottom say?

**Comment by 0uros** [comment]
in the console? that:

`
[monitor] 17:27:59 INFO: Log output saved to file "C:\Users\Ouros\AppData\Local\Syncthing\syncthing.log"
[start] 17:27:59 INFO: syncthing v1.18.1 "Fermium Flea" (go1.16.6 windows-amd64) teamcity@build.syncthing.net 2021-07-30 12:41:57 UTC
[start] 17:27:59 WARNING: Failed to initialize config: config file version (37) is newer than supported version (35). If this is expected, use -allow-newer-config to override.
`

^ This is repeated several times in the console, but it is the only thing that appears.

There's also this log file, I hadn't noticed before: [syncthing.log](https://github.com/canton7/SyncTrayzor/files/10025463/syncthing.log)

What I wanted to do I could do with Syncthing without many problems, but well, I don't know what would have to be configured in Synctrayzor to make it work

**Comment by canton7** [comment]
Aha, you've hit #723 (and similar)

**Comment by 0uros** [comment]
Oh great, I followed the advice given there to use the command `./syncthing.exe -allow-newer-config` in powershell, and it worked without any problems.

Thanks for mentioning it

**Comment by canton7** [comment]
Great!
