### ISSUE TITLE
Web display unresponsive in latest versions on HP laptop with Pentium Gold 7505 processor

### ISSUE THREAD

**Issue by billthefarmer** [canton7/SyncTrayzor#742]
I installed version 1.1.24 on a HP Laptop 15s-fq2024na, which appeared to work OK, and upgraded itself to 1.1.29, which then became unresponsive in that the main web view is blank unless the window is resized. Once resized the display does not respond to user clicks or scrolling. The top menu works, and the log view at the bottom works normally. Using Syncthing->Open in external browser works and the display in the default browser works OK. Syncthing->Refresh browser does nothing.

**Comment by canton7** [comment]
Tried disabling hardware rendering in the settings?

**Comment by billthefarmer** [comment]
Yes, that fixes it, didn't notice that.
