### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Drendx** [canton7/SyncTrayzor#744]
Hi,
I started using SyncTrayzor a month ago.  When i tried today to open it dropped this error.
Thanks for the help

Version: 1.1.29.0; Variant: Installed; Arch: Amd64
Path: D:\programitas\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
Nombre de archivo: 'D:\programitas\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
   en CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   en SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   en Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   en Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   en Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   en Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   en Stylet.ScreenExtensions.TryActivate(Object screen)
   en Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   en Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   en Stylet.WindowManager.ShowWindow(Object viewModel)
   en Stylet.BootstrapperBase.Start(String[] args)
   en System.Windows.Application.OnStartup(StartupEventArgs e)
   en System.Windows.Application.<.ctor>b__1_0(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
My guess is your antivirus deleted the file D:\programitas\SyncTrayzor\CefSharp.BrowserSubprocess.exe ?

**Comment by Drendx** [comment]
Hi!
Thanks for helping.
It looks like! 
Is there a way to recover that file or should i reinstall SyncTrayzor?
If i have to reinstall it, do i have to reconfig it?

**Comment by canton7** [comment]
Normally AV quarantined files, so you can ask it to put the file back and leave it alone in future. If that doesn't work, reinstalling will be fine and won't remove your config

**Comment by Drendx** [comment]
Much appreciate it!
Everything is working now! I've reinstalled it because i couldn't restore the file.
Thanks for your support :) 
Wish you a nice day!

**Comment by canton7** [comment]
Great!
