### ISSUE TITLE
List platform compatibility

### ISSUE THREAD

**Issue by endolith** [canton7/SyncTrayzor#75]
I tried to install on Windows XP but it needs .NET 4.5, which is not available on XP.  Please list in the readme which OSes it's compatible with.

**Comment by canton7** [comment]
Fair request. Didn't think anyone still used XP :smile:

**Comment by endolith** [comment]
It's required to interface with old hardware, and IT doesn't allow it on the company network, so I'm using Syncthing over the internet to transfer files easily. :)

**Comment by canton7** [comment]
Fair enough!

Unfortunately .net 4.5 adds some rather useful stuff which I do rely on, so I'm afraid XP support isn't a possibility. Sorry!

**Comment by endolith** [comment]
That's fine; it would just be good to mention

**Comment by hrj** [comment]
I am not very familiar with the .net ecosystem. Does SyncTrayzor work with mono? mono is apparently supported on Windows XP.

**Comment by canton7** [comment]
No, only Microsoft .NET. Mono does not support the GUI framework I use.
