### ISSUE TITLE
Synctrayzor settings too tall when lots of folders

### ISSUE THREAD

**Issue by jaredthirsk** [canton7/SyncTrayzor#76]
My poor old laptop has only a height of 768, and I have about 20 folders being synced.  The File -> Settings window fills my screen from top to bottom with a list of checkboxes for each of my folders.  If I expand advanced settings, the window is too tall for the screen.

Maybe put these in a ListView/ListBox?

**Comment by canton7** [comment]
Sure, I can make those scrollable.
