### ISSUE TITLE
Synctrazor leaving small open window on windows 11 desktop 

### ISSUE THREAD

**Issue by thrive12** [canton7/SyncTrayzor#762]
This artifact inerferes with other open apps because it overlays the upper left corner of whatever other app is open.  I am closing Synctrazor to the taskbar but this little window remains until I reopen Synctrazor.  Then it disappears temporarily but then always comes back. The window contains the work Synctrazor.

**Comment by thrive12** [comment]
I updated to v1.23.3 and it appears to have addressed the problem

**Comment by thrive12** [comment]
Spoke too early.  Problems still exists on v1.23.3

**Comment by abcdehc** [comment]
https://github.com/canton7/SyncTrayzor/issues/760#issuecomment-1484068251

**Comment by thrive12** [comment]
Closing as duplicate of #760
