### ISSUE TITLE
"Cannot open database"

### ISSUE THREAD

**Issue by emresaracoglu** [canton7/SyncTrayzor#781]
Hello, 

I am installing it for the first time and got this error.

![SyncthingError](https://github.com/canton7/SyncTrayzor/assets/297968/6292d3bc-1872-4c31-b6ce-ecf10c696382)

I did a reinstall but same error.

**Comment by Mr-Developer-X** [comment]
For anyone still waiting for an answer try replacing the ```syncthing.exe``` in ```C:\Users\<You>\AppData\Roaming\SyncTrayzor``` with the ```syncthing.exe``` that you may have installed already from the SyncThing website or Github, which you probably have in your download (hopefully not) or Program File folder in C drive

**Comment by emresaracoglu** [comment]
Hi @Mr-Developer-X 
I solved the problem, thanks for your interest
