### ISSUE TITLE
sync in same device

### ISSUE THREAD

**Issue by EHMilon** [canton7/SyncTrayzor#798]
Synching offer peer-to-peer file synchronization and directories across different devices on a local network or over the internet. It does not support cloud storage integration. Is it possible to add third party cloud storage integration such as Google Drive, One Drive, Drop Box etc. It will be helpful because in peer to peer synchronization, tow device need to connect a same network in same time, some time it not possible to do.
If cloud storage integration is not possible, then add sync data in the same device different directory. If I need to back up data on my external drive, suppose pen drive when I plug it to my machine it will automatically sync data to my pen drive. In this way, we can solve Cloud Storage hosting. It will help us proven loss data and make our work easier.

**Comment by canton7** [comment]
This is a Syncthing topic, not SyncTrayzor. https://forum.syncthing.net
