### ISSUE TITLE
Browser respects proxy settings, even for localhost - causes blank screen

### ISSUE THREAD

**Issue by dorsey** [canton7/SyncTrayzor#80]
Don't know if this is something you can fix (or even need to fix) but I figure it's something you need to know about.

I was getting a blank screen in the SyncTrayzor browser.  "Refresh browser" didn't fix the issue.  I tried accessing http://localhost:8384 in a separate browser and got a proxy error, which reminded me to modify my proxy autoconfig script (lots of weird SSH tunneling in my environment) to ignore the 127.0.0.0/8 network.  After I did that, the issue was fixed and Syncthing displayed correctly in the SyncTrayzor browser.

Is it possible to set the internal browser to either
1) ignore all system proxy settings, or 
2) ensure that localhost is never proxied?

**Comment by canton7** [comment]
Oh, fun! Let me look into this, thanks.

**Comment by dorsey** [comment]
No problem, let me know if I can provide any more info.

**Comment by canton7** [comment]
Turned out to be easy :)

Until this is released, the workaround you described should be fine.

**Comment by dorsey** [comment]
Sweet, I love easy fixes.

I'll test next release by removing my workaround and making sure the browser still works.

**Comment by canton7** [comment]
Cool, thanks. Unless something major crops up, we're probably looking at a week or two until the next release - I'm trying to not bug people too frequently :stuck_out_tongue_closed_eyes:
