### ISSUE TITLE
Better update experience for portable users

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#82]
See https://github.com/canton7/SyncTrayzor/issues/39#issuecomment-100138538

**Comment by berrnd** [comment]
Hi, I'm using SyncTrayzor on all my machines as a "portable" installation.

Updating SyncTrayzor is always the same task: Download the new release, copy away the data directory, empty the application directory, unzip the new release, restore the data directory...

To have something like a one click update mechanism would be great.
In the meantime, I have created a little PowerShell script to accomplish this. :)

&rarr; https://gist.github.com/berrnd/b88820ce10d97b52257e

**Comment by canton7** [comment]
Looking good!

Just a heads-up: I'll likely combine both installed and portable versions into a single installer as part of the solution to this issue, which will cause this script to fail.

**Comment by canton7** [comment]
#110 means that we now have a way of validating downloaded zips, which was the main blocker
