### ISSUE TITLE
Move syncthing-specific settings from SyncTrazor.exe.config to config.xml

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#86]
I'm using PortableApps.com Platform on my flash drive. I used syncthing in SyncthingPortable folder launched from .bat file. Later I set up SyncTrayzor in SyncTrayzorPortable as well. I wanted to keep using syncthing binary from SyncthingPortable with index in SyncthingPortable/syncthing_data. To do that, I had to modify SyncTrazor.exe.config. But when upgrading, this file is overwritten. I could set up some other .bat file to perform upgrade in way that SyncTrazor.exe.config will be kept, but I could broke SyncTrayzor or at least miss some (possibly important) changes when they come.

So, could
````
<SyncthingCustomHomePath>%EXEPATH%\data\syncthing</SyncthingCustomHomePath>
<SyncthingPath>%EXEPATH%\syncthing.exe</SyncthingPath>
````
be moved to config.xml file so that they're not lost after upgrade?

I can imagine that 
````
<LogFilePath>%EXEPATH%\logs</LogFilePath>
````
would be difficult to move (and counter-productive as we would lost some error logs) and that
````
<ConfigurationFilePath>%EXEPATH%\data\config.xml</ConfigurationFilePath>
<ConfigurationFileBackupPath>%EXEPATH%\data\config-backups</ConfigurationFileBackupPath>
````
cannot be moved, but I think that syncthing-specific lines should be in config.xml.

I realise that this probably concerns very few people, but it limits SyncTrayzor adaptability quite a lot I think.

**Comment by canton7** [comment]
I'll have a think, sure

**Comment by canton7** [comment]
In theory this is fine: in practice there are a few wrinkles I need to think my way through....
