### ISSUE TITLE
Language Selection for Syncthing

### ISSUE THREAD

**Issue by Rewt0r** [canton7/SyncTrayzor#87]
There's a new language selection in v0.11.x of Syncthing within the WebGUI, this is stored using localStorage which isn't saved upon restarting SyncTrayzor

**Comment by canton7** [comment]
The best we can do is to set the on-disk location for all of Cef's caches - it doesn't let us break out the local storage location. 

I've put this in `%LOCALAPPDATA%` for the installed version, and `data` for the portable one.
