### ISSUE TITLE
Set polling via API to higher value by default

### ISSUE THREAD

**Issue by jkaberg** [canton7/SyncTrayzor#9]
As you already assume the user wants to use SyncTrayzors built-in file watcher, how about setting the polling in Syncthing to every 30m or 60m instead (by default) when adding new directorys instead of every 60s like now?

Just because I'm lazy :^)

(dont know if the Syncthing API allows this)

**Comment by canton7** [comment]
I don't think I can affect the default presented by the Syncthing UI unfortunately. 

What I *could* do is notice whenever the user's configuration changes, read it in, increase the polling interval if it's the default, save it, and restart Syncthing again.

However, the thought of doing that makes me a bit uncomfortable. A certain amount of magic is acceptable, but changing random bits of the user's configuration without their consent crosses a line for me, particularly as they OK'd the default value when setting up the folder!

I guess what I could do is display a little message saying something like "You've got this polling interval set really rather low, and you've got the filewatcher enabled, you might want to increase it" in the settings, next to each affected folder.

On the flip side, there's no real harm in frequent polls. Syncthing can churn through 7000 files in less than half a second on my box. I think the people who would benefit from increasing the polling interval probably know what they're doing anyway...  

What do you think?

**Comment by jkaberg** [comment]
Yeah, might have been a bit fast on hitting the issue button pressing

I agreed with you (crossing line), perhaps an advanced option "Increase default polling rate" or something that power users can use? Disabled by default :-)

**Comment by canton7** [comment]
Just to be clear on the terminology: I can edit the settings, but I can't edit the default polling interval (to my knowledge).

Let me mull this one over for a few days. There might be a neat solution we haven't thought of yet,

**Comment by canton7** [comment]
I think this will come in after the native UI

**Comment by Zillode** [comment]
This can be resolved using a new API call: https://github.com/syncthing/syncthing/commit/fe34b08ece37707f80febf7b0267b199a5abe16d (https://github.com/syncthing/syncthing/issues/1591)

**Comment by canton7** [comment]
See also #83

**Comment by canton7** [comment]
Closing, as duped by #83
