### ISSUE TITLE
Updates to file transfer progress

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#98]
From https://forum.syncthing.net/t/synctrayzor-windows-host-for-syncthing-installer-auto-start-built-in-browser-tray-icon-folder-watcher-and-more/2011/159m @Rewt0r

    You show the folder directory

I couldn't find a nice place to fit that in! I don't want to take up too much vertical height with each item, and an item's name might be very long so I don't want to add anything to that row...

    Highlight items on hover with the native Windows colour

Yep, worth doing I think.

    Grey out deleted items

Now that's a good idea.

    When hovering over the time show the actual time/date in a tooltip or always show it next to the human time

Yep, nice idea.

    Possibly change the title of the popup to Sync Overview?

Maybe

    Hover over the tray icon to show a tooltip of the current transfer speeds

Heh sure. This tray icon is fast becoming extremely multifunctional (different things done on single click, double click, right click, hover, etc). Not sure how much more I want to cram in...

    The transfer notification balloon to show the file that's just transferred

Now that I can't do. The balloon notifications show when a folder has finished syncing: that is, Syncthing has told us that it was in the Syncing state (blue on the GUI), and is now in a different state.

This means that the balloon is shown when we've finished uploading our index to another device, which means it catches the case where we want to know when a file has uploaded (ish).

Syncthing only tells us the names of files that it downloads. We get these names through a different mechanism, which gives us all the info we need to display the new 'transfers' window.

Now I could change the balloon to only show downloads (and never indicate a potential upload), but that doesn't feel right.

Also, if I display every file that's downloaded in a balloon, the user is going to be swamped with balloons if they're synchronizing a lot of stuff, which I'd rather avoid if possible...

**Comment by canton7** [comment]
Coloured highlights on hover, and the tooltip showing the actual date, are in.

I might replace the current right-click context menu with this, in the same way that Dropbox does, so I don't want to call it something too specific like "Sync Overview"

**Comment by canton7** [comment]
Right, so Dropbox: if one file was transferred, the balloon says 'File so-and-so was downloaded; if more than one, 'x file(s) downloaded'

**Comment by Rewt0r** [comment]
That'd be nice on the notifications @canton7, I think if you're going to replace the context menu for the icon, you will need a menu within the "Sync Overview" that replicates the context menu behaviour. So as not to upset people that rely on some of the options currently there.

I don't use them myself.

**Comment by canton7** [comment]
Of course - that's a given.

**Comment by canton7** [comment]
Pretty much done: closing off
