### ISSUE TITLE
Sync Notifications per Folder

### ISSUE THREAD

**Issue by fti7** [canton7/SyncTrayzor#99]
Hi,

i've enabled the Sync Notifications Option (which i really like)
But i have one Folder where Files are being updated very often. (And there its a little bit frustrating to see Notifications each time)
Would be nice if you could do the Sync Notifications Option configurable per Folder

Best Regards,
Frank

**Comment by canton7** [comment]
Yeah, fair request. I'll have to have a think about how best to display that in the GUI! Maybe combine it with the filesystem watcher settings, so we don't have two (potentially) large lists of folders...

**Comment by canton7** [comment]
Right, that's in! There will be a build available at https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.25.91/artifacts in about 20 mins if you want to have a play.

**Comment by fti7** [comment]
Awesome :-) Thx

**Comment by canton7** [comment]
(This is also in v1.0.26)
